== To the Reader

Be serious when you take in hand to read this treatise,
and have a single regard to the state of your immortal soul;
and let your spirit bow down to "`the measure of
the Spirit of God given you to profit withal,`"^
footnote:[1 Corinthians 12:7]
that by it the eye of your understanding may be opened to see the things herein contained,
which concern your own eternal welfare.
And let not your own thoughts and imaginations,
in the wisdom from below (which is sensual and earthly) be judge therein;
but stand still, out of your own comprehendings;
and let a true and diligent regard be given to the Word in your heart and mouth,
placed there that you may obey it and do it.
So will your heart be truly opened to read with delight
the things opened by the Spirit of Truth,
who searches all things, yes, even the deep things of God; and the travail in spirit,
which is for opening the eyes of the blind, and unstopping the ears of the deaf,
will be answered; and the Lord God Almighty will have His honor from His own workmanship,
and you will have the benefit; which is the desire and longing of him,
who is a laborer for Zion`'s perfect deliverance.

Charles Marshall

Bristol, the 2nd of the Seventh month, in the year 1673
