== Man`'s Happy State Before the Fall

In the beginning God created the heaven and the earth;
and after He had made all things on the earth, He made man in His own image,
formed him of the dust of the ground, and breathed into him the breath of life,
and man became a living soul.
And the Lord planted a garden in Eden, and there He placed the man whom He had formed;
and out of the ground the Lord God made every tree
to grow which was pleasant to the sight,
and good for food; the tree of life was also in the midst of the garden,
and the tree of knowledge of good and evil.
And He that made man in this state, gave him a law to preserve him therein,
as the Scriptures of Truth witness, saying, "`And the Lord God commanded the man, saying,
'`Of every tree in the garden you may freely eat;
but of the tree of knowledge of good and evil, you may not eat;
for in the day you eat thereof, you shall surely die.`'`"^
footnote:[Genesis 2:16-17]
Now God saw everything that He had made, and behold it was very good;
the tree of knowledge of good and evil was good, but not for food.

Man was endued with Divine wisdom,
so that when the Lord God brought every beast of the field and fowl of the air to Adam,
he gave names unto them; and whatsoever Adam called every living creature,
that was its name.
Man`'s station was in the image of God, a living soul, a noble plant,
wholly a right seed, filled with Divine wisdom and virtue,
clothed with innocency and glory, adorned with celestial beauty,
in the continual enjoyment of the love and favor of God,
having his daily communion with Him that made him.
There was no death, no darkness, no sorrow, no occasion of tears, no transgression,
no knowledge of evil, for he dwelt in the innocent life itself,
and was placed in the garden, into which came the river out of Eden that watered it.
Oh blessed state!
Oh happy condition!
Oh inexpressible enjoyment, beauty and glory!
It is beyond the tongue of man to declare fully that blessed, happy state of joy, peace,
holiness, righteousness and fruition of life,
which man was in before he transgressed the royal law of God.
