[#sect-three, short="The Way of Restoration Out of the Fall"]
== The Way of Restoration Out of the Fall, Into the Image of God, In Which Man was Before the Fall.

But how salvation comes to be wrought by Him,
and how mankind may be brought again into Him, who is the Way, the Truth, and the Life,
and brought out from under the power and dominion of the seed of
the serpent (in which by nature all have been the children of wrath),
this indeed is the thing that lies on my spirit weightily to demonstrate,
having obtained mercy to see this way of life and salvation revealed and opened.
And not only so, but a necessity is laid upon me to preach the Gospel of Christ Jesus,
and to declare the way of life and salvation to my
countrymen through this island of England;
and now a necessity is also upon my spirit to leave a testimony of the same on record.

This is generally confessed, that in the first Adam all died,
and in the second Adam (Christ the Lord) all come to be made alive again.
But _how_ mankind comes out of this state of death in the first Adam,
into this state of life in the second Adam,
is that which the wisdom of this world never knew nor comprehended rightly.
Man by that wisdom has only imagined and conceived something
in the carnal mind concerning this great mystery,
and therein has set up many inventions of the way of life and salvation.
And into these many ways of man`'s invention and imagination,
set up in the fallen wisdom of man, there have been the several calls, "`Lo here,
lo there;`"^
footnote:[Luke 17:21]
but the day has dawned,
and is now breaking forth more and more (magnified and praised
be the name of Almighty God) wherein all invented ways,
set up in the will and wisdom of man (which is earthly,
sensual and devilish) shall come to an end.
And now, in the name of the mighty God, all the graven images, the work of men`'s hands,
and earthly wisdom shall be broken to pieces and ground to powder;
the mouth of the Lord of hosts has spoken it,
who will perform it by the might of His arm.

Therefore, tremble all you image-makers of all sorts,
who have been making likenesses of the way of life
and salvation in your fallen wisdom and corrupt wills,
and have made gods thereof, and have bowed down to and worshipped them;
so that it may be said of Christendom (so called) as it was once said of Israel,
"`According to the number of your cities, so are your gods, O Judah!`"^
footnote:[Jeremiah 2:28, 11:13]

But now is the fulness of time coming,
wherein the ancient way of holiness (in which the righteous walked
through all ages and generations) is cast up and being made manifest;
which way is Christ Jesus,
the gift of the Father`'s love unto the sons and daughters of men,
who has (as before-mentioned) been declared by His
prophets and apostles under several names or appellations,
according as He was pleased to manifest Himself to them,
and as His Spirit gave them utterance.
Amongst many other appellations,
He has been declared a Priest forever after the order of Melchizedek,
the Rock that followed Israel who was in the church in the wilderness, a King,
a Lawgiver, Wonderful, Counsellor, Prince of peace, a Branch,
a Light to lighten the Gentiles, the Arm of God`'s salvation, a Covenant, Messiah,
a Leader, a Commander, a Captain, the Horn of God`'s anointed, a Stone of stumbling,
a Foundation laid in Zion, the Cornerstone; the Word of God,
the Word that was in the beginning,
the True Light that enlightens every man that comes into the world, the Way, the Truth,
and the Life, King of kings, Lord of lords, Christ; Emmanuel, Jesus,
the Beginning of the creation of God, the Firstborn of every creature,
the First-begotten from the dead, the Faithful Witness, Alpha and Omega,
Bright and Morning-star, the Image of the invisible God, the Offspring of David.
He has been spoken of under these and other names,
and yet has a name that no man knows but Himself,
who is that one Eternal Fountain of blessedness, and the one precious Savior;
and there is no other besides Him.

And now, by the power of the holy, everlasting God,
He is preached under the name of _Light,_ in this island of the Gentiles,
according as it was prophesied of old by Isaiah, who said,
"`Is it a light thing that You should be My Servant, to raise up the tribes of Jacob,
and to restore the preserved of Israel?
I will also give You for a light to the Gentiles,
that You may be My salvation unto the ends of the earth.`"^
footnote:[Isaiah 49:6]
And this is one with the testimony of John, who said, "`In the beginning was the Word,
and the Word was with God; and the Word was God; the same was in the beginning with God;
all things were made by Him, and without Him was not anything made that was made.
In Him was life, and _the life was the light of men,_ and the light shines in darkness,
and the darkness comprehends it not.`"
"`There was a man sent from God, whose name was John; the same came for a witness,
to bear witness of the light, that all through Him might believe.
He was not that light, but was sent to bear witness of that light:
that was the true light, which enlightens every man that comes into the world.`"
And with this agrees the testimony of just Simeon,
who came by the Spirit into the temple, and took the child Jesus in his arms, and said,
"`Lord, now let Your servant depart in peace according to Your word;
for my eyes have seen Your salvation,
which you have prepared before the face of all people, a light to enlighten the Gentiles,
and the glory of Your people Israel.`"^
footnote:[Luke 2:29-32]
This is He of whom we testify, _whose light is the way to life:_
"`And this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil.
_For everyone that does evil hates the light,_ neither comes to the light,
lest his deeds should be reproved; but he that does Truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`"^
footnote:[John 3:19-21]

Now this light, which the servants of the Most High testified of,
is that which has been spoken of under several names.
For this manifestation of God in man is sometimes called the Word, the Spirit, the Law,
the Grace of God; and the Word, Light, Grace, Law and Spirit are all one in nature,
although diversely named.
Moses called it the Word, and directed men to this Word in the heart and in the mouth.
And Paul, that illuminated man, referring to this says, "`Say not in your heart,
who shall ascend into heaven, that is to bring Christ down from above,
or who shall descend into the deep, that is, to bring Christ up from the dead.`"
But what does it say?
"`The Word is near you, even in your mouth, and in your heart; that is,
the Word of faith that we preach.`"^
footnote:[Romans 10:6-8]
This is the sure word of prophecy unto which Peter directs us to take heed,
as unto a light that shines in a dark place, until the day dawns,
and the daystar arises in the heart.

This light is the law of the Spirit of life, with which Paul was acquainted,
that warred against the law of sin and death in his members.
It is the law in the heart, and the Spirit in the inward parts,
the new covenant of God Almighty.
This is the law that converts the soul,
which law Paul delighted in according to the inward man,
of which the Scriptures of Truth plentifully testify.
This is that grace which Paul declared "`brings salvation,`" which has
in different measures "`appeared to all men`" as God`'s talent or mina,
teaching all that are led and guided by it "`to deny all ungodliness and worldly lusts;
and to live soberly, godly and righteously in this present world.`"^
footnote:[Titus 2:11-12]
This is that grace which the Lord (the giver thereof) told Paul
was sufficient for him to deliver him from his temptation,
the thorn in the flesh.
The same apostle said unto the Ephesians, "`By grace you are saved,`" etc.
And this is the "`manifestation of the Spirit which
is given to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]
This is that good Spirit of the Lord given to Israel, "`who rebelled against it,`"^
footnote:[Psalm 106:33, Isaiah 63:10]
as the old world did, unto whom the Lord said,
"`My Spirit shall not always strive with man.`"^
footnote:[Genesis 6:3]
This Spirit (Light, Word,
or Grace) is given to mankind to be their leader and guide out of sin, death,
and darkness, into which man fell through disobeying the righteous law of God,
as the holy Scriptures give clear and full testimony.

But now, an objection is ready to arise in some whose understandings are not yet opened,
and whose comprehension of salvation stands in that wisdom which is from below,
and in the will and reason of men who are degenerated from the life of God.
Some of these have questioned whether the preaching of this Spirit and grace of God
manifest within has a tendency to make Christ Jesus`' appearance in the flesh,
His sufferings, death, resurrection and ascension, to be invalid?
Unto this I answer: No;
for no one has ever truly discerned or enjoyed the
benefit of Christ Jesus`' manifestation in the flesh,
except as their hearts were opened,
and their understandings were illuminated by the light;
which is a measure of the Divine fulness that dwelt in Him.
And this light is communicated to the immortal soul as the universal love
of God (extended in the Son of His love) to all the families of the earth,
as the revealer and discoverer of the will of Him from whose Divine fulness it comes.
For the Scriptures thus witness,
that "`no one knows the things of a man except the spirit of the man which is in him.
Even so no one knows the things of God except the Spirit of God.`"^
footnote:[1 Corinthians 2:11]

The hearts of the Jews, not being seasoned with this grace of God,
and ignorant of the gift of God (which is eternal life), neither discerned,
loved or received Christ Jesus when He was manifest in that outward bodily appearance.
Though they professed to honor and regard the prophets,
and lived in expectation of the fulfilling of many
prophecies concerning the coming of the Messiah,
when in due time He came, they did not receive Him,
but instead set themselves against Him, taking counsel how they might slay Him,
though in words they professed to be earnestly waiting for Him.
So it is now.
For there are many at this day who, by their words,
profess to believe in His coming in the flesh and His sufferings, death,
resurrection and ascension; yet having a faith that consists in outward notions,
and no inward experience of the purpose of His coming,
nor of the virtue of His sufferings, death, resurrection, etc.,
they remain enemies in their minds to His second appearance and coming,
"`without sin unto salvation.`"^
footnote:[Hebrews 9:28]

So then, there is a necessity for all men to come to and obey this divine spiritual Seed,
which is placed in their consciences by the living God,
that thereby the spiritual eye may be opened,
which through disobedience has been blinded by the god of the world.
For, until this is in some measure effected,
the mystery of godliness (which is great) can neither be seen nor understood.
For this reason,
finding the woman of Samaria ignorant of Himself (who was and is
that great mystery and the gift of the Father`'s love),
Christ said, "`If you knew the gift of God, and who it is that says unto you,
give Me to drink, you would have asked of Him,
and He would have given you living water.`"^
footnote:[John 4:10]

The travail in spirit of the messengers and servants of the Most High in ages past,
was the same as it is now, namely: "`To turn people from darkness to light,
and from the power of Satan to the power of the living God.`"^
footnote:[Acts 26:18]
This in no way invalidates Christ`'s manifestation in that bodily appearance,
nor His sufferings, death, resurrection or ascension; but rather,
it brings all people to that which will open the eyes of their understandings,
so as to see and know their benefit by the outward appearance of the Savior of the world.
For this we testify, that by that one offering all are perfected who are sanctified.^
footnote:[Hebrews 10:14]

But here arises another objection by some,
who may come so far as to acknowledge and confess that there
is a Seed or light in man that discovers sin,
and teaches man to do justly and equally (which some call morality).
For lack of understanding,
many of these deny that this light or Seed in man is of a saving property,
of the nature and quality of the Divine Being, and so they become opposers of Truth,
and stumble over that Cornerstone which in all generations
has been a stone of stumbling and a rock of offense.
Yes, many who are accounted as wise master-builders, professors of God and Christ,
giving themselves up to be guided by their own wisdom and prudence,
yet being ignorant of the root and offspring of David, reject this Cornerstone.

Now, for the sake of all who desire the true and saving knowledge of Christ Jesus,
it is on my spirit yet further to open the nature and property of this Seed and light;
whose fountain is the Eternal Being and everlasting ocean of Divine fulness,
and whose nature and quality is one with the Fountain from which it comes.
John testified, "`In the beginning was the Word, and the Word was with God,`" etc.
"`In Him was life, and the life was the light of men.`"
He also testified that John the Baptist was not that light, but came for a witness,
to bear witness that the true light was that which
enlightens every man that comes into the world.
So the origin of this light is Christ Jesus, the Word.
But some may ask: Is Christ the light in every man?

To this I answer: Christ does appear by His light in every man;
and the light which comes from Christ is in every man,
as is clearly demonstrated in the Scriptures of Truth.^
footnote:[John 1:9, Romans 1:19, Titus 2:11, John 16:8]
And, though I account it unnecessary to answer the curious inquiries of such,
who seeking to know much, do not walk according to what they already know;
yet for the sake of those whose understandings are not opened,
and are inquiring about the way to Zion, I will offer this similitude:
The natural sun is placed by the Creator to enlighten the outward world,
and manifests out from itself a measure of its light and natural property,
shining on the just and the unjust,
and so giving forth of that virtue which is inherent in itself.
When the sun shines upon any object whatsoever, we sometimes say,
"`The sun appears there;`" and other times we say,
"`There is the sun;`" the propriety of either of these expressions,
I suppose none will question.
For in that appearance light is seen and virtue is felt,
penetrating to the refreshment of our natural bodies,
and this light and heat are inseparable from the fulness.
And although the sun does daily shine and display its virtuous
life into and over all the earth and its inhabitants,
yet its body is not in any way exhausted or altered through ages and generations.
In a similar way, I say, Christ (the universal fountain of life,
the Sun of righteousness, the ocean and fulness of spiritual light, life and virtue,
from whom is communicated a measure of His nature,
property and quality) is given of the Father to enlighten
all the sons and daughters of men,
who accordingly are all enlightened with His spiritual appearance.
And though this inward appearance cannot be called the fulness,
yet being a measure of that fulness, it is one in nature and property with,
and inseparable from the fulness.
And though through its virtue, life is daily communicated unto the sons of men,
who wait for its appearance as for the morning light,
and cannot live unto God without it, yet the Fountain knows no lessening or change,
but all the fulness of Divine light, life and glory, does and shall,
through every age and generation, remain with Him.

Now, because the veil of darkness has overshadowed the hearts of men,
when we give testimony to the universal appearance of the Sun of
righteousness in the hearts of all the sons and daughters of men,
some are ready to say that such a testimony leads to the diminishing
of that glory and honor which belongs unto Him as He is the fulness,
and sits at the right hand of the Father;
inferring that while we testify to His appearance in our hearts,
we exclude His presence elsewhere.
Yet this inference is as irrational as it would be for any to conclude
that because we say concerning the shining and appearance of the sun,
"`There is the sun,`" or "`The sun appears there,`"
we therefore exclude the existence of the sun elsewhere.
For we know that its virtue is communicated to our natural bodies,
everyone having in measure some enjoyment of the virtue or light of the natural sun,
which is light to the eye of the natural body.
In a similar way,
those whose spiritual senses are quickened by the virtue which proceeds
from the eternal Sun of righteousness do thereby discern spiritual things
according to the clear manifestation of Truth in their inward parts.
And from a sense of this, these can give certain testimony that Christ, the Lord,
by His holy life-giving Spirit, has appeared in them to quicken their immortal souls;
and they also bear witness that by believing in the light, and obeying His appearance,
they have come out of that state which is reprobated by the Lord,
and can with certain experiential knowledge say, "`Christ is in us, the hope of glory.`"^
footnote:[Colossians 1:27]

And so, when we direct people to this Word, Seed, Light, Law, Grace and Spirit,
we do not thereby intend to suggest that Christ Jesus (the light
of the world and the gift of God) is not the true Savior,
Redeemer and Reconciler of mankind unto God.

Now this light and Spirit leads the soul of all who obey it up to God,
the fountain from whom it comes; and no man can see its nature,
but those who are led by it.
For it is only in the light of the Lord that man comes to see light,
and to have true understanding.
And before this can be fully seen or understood, the mind of man must be brought down,
out of all its own willing and running, comprehending and searching, unto this light,
therein to experience a death to his own will, and be comprehended in this light.
Thus man comes to have "`an understanding to know Him that is true,
and to be in Him that is true.`"^
footnote:[1 John 5:20]

Now, as any are convinced and converted by this heavenly Seed,
which is placed in the conscience to be a guide and leader to mankind,
they are led out of darkness where they have been.
For the light shines in the darkness, but while he abides in the darkness,
man cannot comprehend this light or heavenly grace.
The light sometimes moves through the darkness on man`'s understanding,
reproving and discovering the darkness, and causing him to hear its still, small voice.
Indeed, it daily reproves man while he remains in rebellion and disobedience,
all the time of his visitation,
and also approves and gives peace to man when he is obedient.

Although a man may turn and go from it, and rebel against it,
and thereby become like those of whom Job speaks, who "`rebel against the light,
and thereby know not the way of it,`"^
footnote:[Job 24:13]
giving way to the working of the god of the world to be drawn out into fading,
perishing things; even so, the light remains immutable in itself,
being of and from the unchangeable Being,
and it remains with man until it is taken from him, and he is cast into utter darkness.

Jesus compared this gift of the Father to a grain of mustard seed,
and to a little leaven which a woman took and hid in three measures of meal,
until the whole came to be leavened.
The first operation of this heavenly light in those who are convinced by it,
and turned to it, _is to show man his true inward state and condition._
Thus, the first step in the way of life is to be turned to this holy Seed,
which teaches the obedient to know God savingly.
And when a man comes to have a true sense of his fallen state,
and sees how he has transgressed against that eternal Being who gave him life and breath,
and who waits long to be gracious, and knocks at the door of the heart,
and strives with him by His Divine light, the sense of this will break the heart,
and tenderize the spirit before the Lord.
And under the weight of the great burden of sin and iniquity, there will be a crying out,
"`My sins are too heavy for me to bear,
and my iniquities have gone over my head!`"^
footnote:[Psalm 38:4]
Saying, as Paul did, "`Oh wretched man that I am!
Who shall deliver me from the body of this death?`"^
footnote:[Romans 7:24]
Here the eye comes to be opened that sees Him,
whom man in his disobedience has pierced again and put to open shame;
and then there will be days of mourning and wailing because of Him;
and truly this is "`the day of Jacob`'s trouble.`"^
footnote:[Jeremiah 30:7]

In the sense of this deplorable fallen state, and the long-suffering of the Lord,
and the long-striving of His Spirit, you will see that in the justice of God,
eternal death could be your portion.
But that which brings you into this sense also begets
a secret cry in the soul for a Deliverer and Savior,
and will also give a true sight that there is no way for your soul to be ransomed,
but in and through the tender mercies of the Lord Jesus Christ;
_which you will see can be effectually begun in you in no
other way than in the way of the judgments of the Lord,_
for "`it is through judgment that Zion is redeemed,
and her converts with righteousness.`"^
footnote:[Isaiah 1:27]
And here also you will see that the measure of the sufferings
of Christ that are lacking must be filled up in you;
for there is no other way that a man may pass unto life, peace and joy,
with the Father of spirits, but the way the Captain of salvation has passed,
which was through death; and here you will begin to "`arm yourself with the same mind.`"^
footnote:[1 Peter 4:1]
For no one ceases from sin any further than they suffer
in the flesh the crucifying of its affections and lusts.^
footnote:[1 Peter 4:1-2]
And here the end of the Gospel`'s preaching comes to be known and witnessed, which is,
__that all might be "`judged according to men in the flesh,
but live according to God in the spirit.`"__^
footnote:[1 Peter 4:6]
And in this inward exercise, the Lord God Almighty will bow down His ear,
and answer the cries of your awakened soul, and manifest His Word of power,
which all who are in this state will know to be sharper than any two-edged sword,
piercing even to the dividing asunder of your immortal soul from
the spirit and nature of transgression and its daily working,
as subjection and obedience are yielded unto it,
making a separation between joints and marrow,
and giving you a discerning of the thoughts and intents of your heart.^
footnote:[Hebrews 4:12]

And unto all who feel true longings, living breathings,
and ardent desires in their souls, to know this blessed work, I say,
bow down in tenderness of spirit and sincerity of heart to this Seed of the kingdom,
though it be but as a grain of mustard seed.
Be low within, and love that light which discovers the seed of the serpent;
love its workings and moving in the heart.
Suffer with it, sorrow and mourn with it,
and give up not only to the discoveries of the Seed of the kingdom,
but also to the judgment it brings,
that the nature and works of the seed of the serpent may be destroyed.
For the soul can never come to be one with the incorruptible Seed,
nor be born of it (in which the promises are all yes and amen) but through the wasting,
working under, and destroying of the nature and work of the seed of the serpent,
which hath been as a separation or partition-wall between the soul and Christ Jesus.
So through becoming passive and subject to the power of God,
and the working of His incorruptible Seed in its least and lowest appearance,
it will bring everyone that is acquainted with it into a very low and tender spirit,
and will fill the heart and soul with the fear, dread and awe of the Most High.
And these will become truly careful, and will be diligent to heed,
and cautious of neglecting, its secret motions, and its sweet,
powerful workings in the soul.
And if you will diligently and constantly cleave with your souls unto it,
you will feel and see (as your faith stands in it) the working of it to be as leaven,
to leaven you into the divine nature.

So be not weary of bearing the cross of Christ,
nor of mourning here in these deep exercises of spirit;
but persevere daily in the love of this immortal Seed; for then,
coming to be born again and brought forth by the power of its workings in the soul,
you will be tenderly nursed up by that which is of the same nature, namely,
the pure milk of that Word which lives and abides forever, of which you were begotten.
And thereby you will grow up to the day of espousal
in the marriage-chamber of divine love and life,
where the soul is safe in the enjoyment of the unutterable
joy of the Lord God and the Lamb forever.

So then, as the soul gives up in love to God,
freely to follow Him in the way of His judgments,
and gives up to the sword of the Lord that which is for the sword,
and gives up to destruction that which is for destruction,
so the precious work of the Lord will prosper.
And although this may be a time of sorrow, of trouble and anguish, yet it is a good day.
Therefore strive not to get out from under it, neither to make haste;
for the true godly sorrow works the true repentance, which is never to be regretted.
After the true repentance, follows the true knowledge of remission and forgiveness;
and so your iniquities come to be blotted out by the judgments of the Lord,
and then times of refreshment come from the presence of the Lord,
and from the glory of His power.

Therefore, in the name of Him who lives forever, I say unto you everywhere,
be _inward, inward, inward._
Hasten inward to the divine nature,
which alone will be a safe abiding place in the dreadful
pleading day of Almighty God that comes quickly.
And in His name I warn all who have gone out from
the obedience to the daily cross of Christ Jesus,
and abide not in the daily, holy watch (and thereby have got into a false liberty,
in their ways, words, conduct, food, drink and apparel), to return speedily inward,
under the operation of the spiritual circumcising-knife; that all which offends the Lord,
and grieves His good Spirit may be effectually cut off and removed,
and you may be brought into fear, dread, awe,
and holy watchfulness in the light of the Lamb.
Bear the yoke of the Lord Jesus, and love His heavenly cross,
which crosses all your inclinations to vanity and vain pleasures.
Let nothing come between it and you;
so your growth will be daily from one degree of strength and stature to another.
And in the light, you will behold the snares and temptations of the enemy,
and abide in a living inward diligence,
out of the foolish virgins`' state (where spiritual idleness brings spiritual slumber,
to the losing of the oil, and so the lamp goes out).
But abiding in a daily subjection to the heavenly cross, in the holy watch,
you will grow up to the young man`'s state, wherein you become strong,
and the Word of God abides in you; and abiding in it, you will overcome the wicked one,
and escape the highway, stony and thorny ground.

For as there is a faithful abiding in inward watchfulness,
and a continual obedience to this heavenly light
(in which the beginning of the work of God is known),
there will be a going on from step to step in the footsteps of the flock of Christ Jesus,
and a growing from strength to strength, over sin and the nature thereof,
and from one degree of grace to another.
So the eye of the understanding will be single,
and here everything which does hinder will be seen,
and the soul will not be moved away from an inward travail,
until that which hinders is taken out of the way,
and until all the rule and authority of the enemy
is subdued under the feet of the Lord`'s anointed,
and the government in the soul is upon His shoulders,
whose right it is to reign over all.

And here salvation, redemption and restoration are effectually enjoyed,
through faith and the effectual working of the Almighty power of God,
unto whom be the glory of His own work forever.
Here will be a growing and increasing,
until there is a coming into that precious state
and image which man was in before he fell.
