[#sect-four, short="The Snares of the Enemy Discovered"]
== The By-paths, Crooked Ways, Wiles and Snares of the Enemy Discovered

Now when the mind is turned to this Divine heavenly Seed,
and the work of the Lord has begun,
the same destroyer that brought man into bondage at first, and has kept him in bondage,
will begin to work cunningly,
and endeavor to destroy the work which God has begun in the soul.
And that he may accomplish his end, he will go about every way, seeking an entrance,
and will lay his temptations suitable to the propensity or inclinations of each person.

If the heart is bowed under a weighty sense of iniquity and many transgressions,
through which sorrow and bitterness has become great,
then the enemy will work in his "`transformings`"^
footnote:[2 Corinthians 11:13-15]
in an appearance like light, though in nature he is contrary thereto.
For, though the true light gives a certain understanding of the inward state,
and brings sorrow because of sin, and reveals the mountain of iniquity,
yet it also begets a secret hope of overcoming by the Lord`'s strength.
But when the enemy sees the soul bowed down,
he often afflicts and brings it into unbelief of ever overcoming,
thereby endeavoring to sink it into despair; knowing that if he overcomes,
he still keeps the soul under his power.
But if all who are in this exercise will but wait upon the Lord with a single heart,
and with the mind stayed in the light, they will discover this snare.
For, as I said,
although the true appearance of God`'s heavenly light
and grace does bring a day of trouble,
sorrow and anguish, yet this sorrow is not a sorrow without hope.
But the enemy`'s working is to bring the soul into a sorrow without hope,
and to drag down the spirit into the chambers of darkness.

When this snare is discovered,
and the soul (through the love and power of God) is comforted and refreshed,
and raised up in a measure of living hope,
then the enemy endeavors to lead away from the inward daily travail,
so that judgment will not be brought forth into victory;^
footnote:[Matthew 12:20]
and so he draws the mind into a false persuasion of obedience and diligence when
there is not a real abiding in that light which gives a true sense of its state.
And as he before desired to destroy the hope which is a sure and steadfast anchor,
so now he seeks to beget a false hope and confidence,
and lead the soul out from under the daily cross,
by which the nature that is alienated from God should be destroyed.

If the enemy is seen and overcome in both these snares,
and the inward work prospers until much has been subjected,
and through daily obedience to the heavenly power much has been slain,
and the heart comes in good measure to be cleansed,
and a good progress is made through the administration
of condemnation (that is glorious in its time),
and something of pure peace and heavenly joy arises in the
heart--here again the enemy will be subtly at work to betray,
by persuading the soul to sit down now as if all were done,
and so lead it away from feeding on the tree of life,
to feed on the tree of knowledge of good and evil,
and to break the commandment of the Lord.
At first he subtly draws the mind out to take a little liberty,
away from that diligent watchfulness and fear it was in before.
And if he prevails in this, he will lead further out of the innocent life,
and by degrees open an eye that sees something attractive
in outward things that affects the mind.
And as he prevails gradually and hiddenly,
the true eye that was opened comes again (through
disobedience) to be in some measure blinded;
and here loss is sustained, even before the unwatchful is aware.
So the work of the enemy is first to cause these
to make shipwreck of faith in a little measure,
no longer having their daily belief stand in the power.
And as the daily enjoyment of this is lost by degrees,
there will then be a turning away from the power of godliness into the mere form.
And although at times the power of the Lord may still be felt in this state,
yet because there is not a continual feeling after
and enjoying it as true refreshment and consolation,
so a false image rises up in its place.
Then the enemy presents some objects to take up the mind,
so that by degrees he may enter in and defile it, and draw it from its true Guide,
so as to make shipwreck of a good conscience.

If the enemy is discovered here before he can so effect
his work and bring death and darkness over the soul again,
and the power of the Lord breaks his snares, and gives a true sense thereof,
through which trouble and anguish of spirit comes--here
he will again transform and work as he did in the beginning,
appearing like the condemning power of the Lord.
Thus he endeavors to lead the mind into despair of ever recovering its former condition,
and also to draw it to look at the one who has stung him,
so that the remedy (i.e. the soul-ransoming power
of the Lord) may not be felt after or looked for.
But if there is a true regard unto the Lord,
and a "`waiting upon Him in the way of His judgments,`"^
footnote:[Isaiah 26:8]
desiring that all faith and confidence stand in His power,
then the backsliding will be healed.^
footnote:[Jeremiah 3:22]
And so, returning and diligently keeping in the light,
the power of the Lord God will overcome that which
has endeavored like a roaring lion to destroy,
and so lead the soul on in the way again.

But when deliverance is known from this deadly snare,
and the work goes on prosperously until the house is swept and put in order,
and there is a passing from death unto life;
and when the soul has gone through the ministration of condemnation,
and the spirit that ruled in the disobedient state has been cast out,
and the administration of the Spirit (which does exceed in glory) is known--then
the enemy will again transform himself as an angel of light,
and with all his power and strength,
work by temptation on the right hand and on the left.
For when there are openings in the understanding, and prophecies,
and when through the working of the eternal power joy springs in the heart,
then the enemy will work secretly to draw the mind out of the valley of humility.
And if he prevails in this, he will endeavor to lead into extremes,
and so bewilder the mind and hurry it into imaginary notions,
in order to dishonor the name of the living God and to lay waste His work.
Thus he seeks to destroy the true birth,
which through sorrow and travail has been brought forth.

If the enemy cannot prevail here, but the light of the Lord discovers him,
then he will work to draw the mind out from watchfulness and daily fear,
and from the liberty of the sons of God, which liberty is only to serve the Lord.
For when dominion is felt in some measure, comfort and consolation are enjoyed,
and praises arise in the heart to the One who has visited and redeemed,
then the enemy will be ready to draw the mind out of the
steady state of meek and constant watchfulness in the light,
thereby causing the soul to spend his portion (like the prodigal),
and to squander his enjoyment by running before the leadings and
movings of the power of the Lord--speaking much of the enjoyment,
the prophecies and openings,
but not being led thereto by that power that first opened the heart.
Here an untimely birth is brought forth, that will wither and come to nothing.

Where the enemy cannot prevail by these snares and temptations, he will not cease,
but "`goes about as a roaring lion, seeking whom he may devour`"^
footnote:[1 Peter 5:8]
and how he may again get entrance; but he lays his temptations according to the spirit,
growth, capacities and inclinations of every individual.
After the good work of God has begun,
and the arm of His salvation has been wonderfully
revealed to bring out of Egypt`'s spiritual darkness,
and He has given many eminent deliverances from the destroying enemy,
and has often fed the soul with the heavenly food,
and caused the rock to yield water for the thirsty;
and after many bypaths and backslidings in the wilderness
have been seen and discovered by the eternal power,
and there is a passing through the river of judgment,
and the mighty power of God drives out the enemy that has
inhabited the land where only Abraham`'s Seed is to inhabit,
and the war in great measure ceases, and part of the good land is possessed and enjoyed,
even the land that flows with spiritual milk and honey--here also will the crooked,
subtle enemy be working, as he did with outward Israel, causing "`Jeshurun to grow fat,
and then kick`"^
footnote:[Deuteronomy 32:15]
against the power.
For in the case of those who have come thus far,
the serpent seeks to lead the mind out through the
enjoyment of that which is good in its place,
into a state of ease,
to lightly esteem the Rock of their salvation and so forget the
Lord that formed man and brought him into the land of rest.
Thus he leads out from the inward enjoyment of virtue, to set up idols in the heart,
so that men serve gods of their own creation,
having a profession of truth without the possession of life.

Into this condition the old enemy has prevailed to lead many a people,
who in different ages have seen the mighty works of the Lord,
and His arm stretched out and magnified in the sight of their enemies; nevertheless,
they departed from the Lord, and from the inward sense of His power.
And then, the spirit that was formerly cast out, and wandered in dry places,
takes with it seven worse spirits and returns, tempts, prevails and enters,
and the latter end is worse than the beginning.
For in the beginning, although the enemy had his power and rule,
yet there was a sense of this, and the heart was humbled, made tender,
and brought into true poverty,
and there was a mourning before the Lord for lack of dominion.
And in this state of humiliation and brokenness of heart (in which the Lord takes delight)
He visited the soul in His boundless lovingkindness and caused His redeeming,
saving power to be revealed.
But now, in this other state, the mind is lofty, the heart is fat, full, at ease,
and has gone into the love of the world and the things thereof,
through which it has become unmindful of the Lord,
who in the beginning was sought after every day, and diligently waited for.
Thus the Rock, the power of God, is lightly esteemed;
for the esteem is set upon another thing.
And here two great evils have been committed at once, namely:
They have forsaken the Fountain of living mercies,
and they have hewn for themselves broken cisterns^
footnote:[Jeremiah 2:13]--that is, a Christian profession that will hold no water,
no durable refreshment, no durable joy, no durable peace or consolation.

Thus the enemy has prevailed through many ages, through his gradual working and subtlety,
to bring thousands away from their enjoyment of God in a pure, tender and upright spirit.
_And his first step thereto is always to bring the mind out of the constant,
daily watchfulness (almost imperceptibly),_
causing a little liberty to be taken for the carnal mind,
with a certain enjoyment or sweetness therein,
whereby a darkening comes over the sight of the mind,
and the soul is allured into more liberty.
Sometimes he begins by drawing out of obedience to those
things that were required in "`the day of small things;`"^
footnote:[Zechariah 4:10]
perhaps into the use of many words,
no longer to be a "`door-keeper in the house of the Lord.`"^
footnote:[Psalm 84:10]
The enemy works to cause such things to seem small and indifferent,
thereby causing the offense of the cross to cease.
Then the mind runs forth "`to make provision for the flesh to fulfill its lust,`"^
footnote:[Romans 13:14]
either in food, drink, apparel,
or any such thing which the Truth in time past had made manifest,
and the power of God (the cross of Christ) had judged down, and in measure led out of,
into watchfulness and pure fear,
not making provision for the flesh in any respect to fulfill its lusts.
For the Truth draws the heart (both in practice as well as in principle) into plainness,
and out of all superfluities, allowing the creature to refresh his natural needs,
but not to feed his lusts.

But yet the enemy works by degrees,
subtly and covertly to lead out of the liberty of the cross
of Christ Jesus (which is the power of God unto salvation),
into the liberty of the flesh.
Hereby he gets a further entrance, gradually working to draw the mind into many words,
either in business or discourse, or into the love of the world, etc.
And though many times the power of God here may be
felt in some measure to draw out of the snare,
yet because the god of this world has already much blinded the eye,
and darkened the understanding,
there is not a clear sense of the power of the Lord in His workings,
nor the subtlety of the enemy.
For though a man may in great measure keep to his religious profession and outward conformity,
yet under all this the enemy may work undiscovered by the unwatchful,
and so (step by step) lead out of the power of godliness,
until he has slain the birth which was begotten in the first days of tender visitation.
And then there will be a growing proud,
and such as these will call the operation of God`'s power "`extremes`" and "`imaginations,`"
and will kick (like Jeshurun) and turn against the power of God;
for these are best contented with a likeness and image.
Such love to hear smooth things from the wisdom of gifted men,
who have lost their way by turning from the power
and not waiting on all occasions to be guided thereby.
And here we find the "`itching ear,`" and the "`heaping up of teachers to please themselves`"^
footnote:[2 timothy 4:3]
And here Jezebel is upheld, which error crept into the church of Thyatira,
and has continued in all ages wherever men have gone out from the broken, tender state,
and allowed and nurtured this Jezebel, who must be "`cast on the bed of torments,
and all her children killed with death.`"^
footnote:[Revelation 2:20-23]

All the workings of the enemy, under every disguise,
are to slay that which was made alive,
and to bring the soul into contentment with an outside
profession of the way of the truth,
light and life of Christ Jesus (the power of God unto salvation),
while the heart has gone from the Lord and embraced other lovers.
Where the enemy thus prevails, in the process of time he leads all back into the world,
from where the arm of the Lord had gathered them,
and the latter end of such is worse than the beginning.
For having made shipwreck of faith and of a good conscience,
the second death comes over them, and these become twice dead,
and are as salt which has lost its savor,
being good for nothing but to be cast forth and trodden under foot of men.
The preservation out of all these by-paths, crooked ways, wiles,
snares and temptations of the enemy,
is only _in the true waiting and sincere abiding in the light, gift and grace of God,
in which the daily revelations and manifestations of God`'s eternal power are known._
For in the daily acquaintance and experience of this,
the heart is preserved low and tender,
and inward breathing and panting arises after the daily enjoyment of life, power,
and refreshing virtue, which alone renews and increases the strength of the inward man.
May God Almighty preserve all of Zion`'s travelers in this way unto the end.
