== A Call in the Love of God, to All the Scattered Sheep.

Now hearken and give ear,
you scattered ones upon the barren mountains of religious profession,
who having lost the living sense that was on many of your spirits years ago,
are now seeking the living amongst dead professions,
and looking for bread in desolate places.
Remember the years past; call to mind the days of your tenderness,
when the light of God so shined upon your tabernacle
that by it you saw yourselves to be in darkness,
and in separation from the enjoyment of your Creator.
This sense brought a day of mourning and bitter lamentation upon you,
and was the cause of your fasting, praying,
and earnest seeking after the Lord with sighs and tears.
This caused some of you to set times to meet together to pour forth your
souls in seeking the living God for His breaking forth among you,
and for the revealing of His arm of salvation.
In that day,
how did many of you retire into your closets and secret places to mourn before the Lord!
How were your cries and pantings after the Lord more than those who watch for the morning!
And in that day, was it not the substance itself that you sought after,
even the revealing of the Son of God`'s love in your souls?

Let me expostulate with you in the name of the mighty God,
even with those among all religious professions who have any tenderness
or breathings after the Lord remaining in you.
What was it that stirred up your hearts, many years ago, to thus seek after the Lord?
What gave you the sense of your own inward conditions,
and made sin appear exceedingly sinful?
What was it that you felt in your minds that warred
against the law of sin and death in your members,
and in some measure opened the eye of your understanding to see idolatry and superstition?
What was it that drew your hearts out of the world,
and made those things of little esteem in comparison
with that which your awakened souls sought after?
What was it that inwardly upheld you in sufferings
when the wicked raged as the waves of the sea,
and when you were mocked for the plainness of your
appearance or the strictness of your families?
Remember your many eminent deliverances.
How did the Lord answer you in the day of your tenderness?
What was it that exercised your hearts, and moved on your spirits for a true reformation?
Was it not the free grace of God?
Was it not that light which shined in your tabernacle?
Did it not shine in your hearts, and move your spirits Godwards,
and begin the work of the Lord in you?
Why did you turn aside from following on to know the Lord in the way of His judgments,
when a little prosperity attended you?
Why did you seek to get out from under His judgment,
before it was brought forth into victory?
Be awakened, and come back, you who have thus turned aside for empty words,
and wandered from one mountain of profession and imagination to another,
until you have spent all your portion and (in nature) have returned to Babylon,
the city of confusion, out of which the Lord thus calls you; "`Hasten,
hasten to come forth, and partake no longer with her in her sins,
lest you partake with her in her plagues, which are hastening to come upon her,
and upon all that shall be found within her borders.`"

Open your eyes, and behold where it was that you turned aside,
and why your foolish hearts have been darkened.
For the enemy that "`goes about as a roaring lion, seeking whom he may devour,`"^
footnote:[1 Peter 5:8]
wrought in you to turn you from this Divine Seed that had awakened you,
and begun to work the work of God in you,
to a profession of the words and conditions which the saints wrote of in the Scriptures.
But the saints had attained these things by passing from death to life in obedience
to the grace of God which "`is given to every man to profit withal.`"^
footnote:[1 Corinthians 12:7]
They knew the holy war, and fought the good fight, and so obtained the victory.
Through the effectual workings of grace they obtained it,
and not through mere notions concerning the words of their brethren the prophets.
Thus they were made partakers of the promises through faith and obedience unto, and in,
the eternal Spirit of holiness.
In this way they came to put off the old man, which is indeed a real work,
and to put on the new man which is a real change and translation out of Satan`'s kingdom,
out from under his power, into the kingdom of the dear Son of the living God,
so to be under His power.

But the enemy of your souls turned you from this free grace of God (which wrought in
you in your day of tenderness) by drawing your minds into an airy notional grace,
professing that by it you were saved;
not considering that the immortal souls of such as these continue to lie in bondage,
for their faith stands in notions, and not in the power of God.
This faith is nothing more than a belief in what has been done for them outwardly,
but not a coming experientially to know the work of God inwardly,
nor the obedience of faith which purifies the conscience and makes alive unto God.
And such has been the soaring imagination of some who are called ministers,
that they have presumed to teach and hold forth a free grace that
allows liberty to the fleshly nature and avoids the cross of Christ,
which teaching is contrary to that holy liberty which
is known by the operation of the true grace of God.
For though it is true, as the apostle says, that "`by grace we are saved;`"^
footnote:[Ephesians 2:5, 8]
yet whoever holds forth this grace,
so as to raise a belief in any that they are saved by it from condemnation
while they are found transgressors against the righteous law of God;
these, I say, "`do not rightly divide the word of truth,`"^
footnote:[2 Timothy 2:15]
but teach for doctrine the conceptions of their own brain.
For it is not a bare belief or assent of the mind to the power
of grace that can give satisfaction to the immortal soul,
or a true assurance of eternal peace with God;
but there must be also a conformity in the inward man to its power,
so that man comes to be created anew in Christ Jesus unto good works,
and to be sanctified throughout, in body, soul and spirit.

And I have found, that instead of preaching a conformity to the power of the grace,
men have preached a sort of free grace (which, in itself,
is indeed a proper enough expression,
for the grace of God is freely extended unto all) which justifies
sinful and unsanctified persons by an imputed righteousness;
even in such a manner as has led many to conclude themselves to be in
a state of salvation while sin continues its reign in their mortal bodies.
This, I cannot help but testify, is as great an error,
and as contrary to the Gospel ministration and to the end for which Christ
was manifest in the flesh (which was to save people _from_ their sins,
so as no longer to live therein), as the error of the scribes and pharisees,
who sought and believed in justification by the works of the law,
without the righteousness of faith.

Thus has it been that many have turned the grace of God into fleshly license,
or turned from the grace of God into indulgence;
so that many professors of Christianity have grown light and vain,
and run with the profane "`into the same flood of dissipation,`"^
footnote:[1 Peter 4:4]
and being lifted up in the flesh, they became much in show,
but were little and light in the true balance.
And here,
all you professors of Christianity who have gone out from
the spiritual appearance of Christ Jesus within,
into a profession of the saints`' conditions and performances,
without the leadings of the same Spirit and power--here, I say, you have lost your way,
and gone out from your Guide who would have led you up to the substance, Christ Jesus.
Thousands of ignorant people have been led, through the cunning craftiness of men,
into an empty profession of words.
And when the manifestation of the Spirit of God (which
is given to every man for their profit^
footnote:[1 Corinthians 12:7]) has stirred in the heart to draw the mind out of the ways,
spirit and nature of the world,
then the transforming enemy has lain near to deceive and betray,
directing people into one profession of religion or another,
or encouraging them to take up this outward performance or the other shadow,
under the plausible pretense of being the ordinances of God and Christ.
Hereby the subtle enemy (who will gladly allow men
to be in the practice of outward things,
while he can retain his throne in the heart) has
led thousands aside out of the straight way of salvation,
by drawing them away from the true inward Guide,
from "`the grace of God that brings salvation, that has appeared unto all men,`"^
footnote:[Titus 2:11]
into outward observations.
And here "`the fear towards God, is taught by the precepts of men,`"^
footnote:[Isaiah 29:13]
who know not the leadings of the Spirit and power of God;
and so "`they have healed the hurt of My people slightly, saying, '`Peace,
peace!`' when there is no peace,`"^
footnote:[Jeremiah 6:14, 8:11]
and have "`plastered with the untempered mortar.`"^
footnote:[Ezekiel 13:10]

And now, all you scattered ones upon the barren mountains,
hear the counsel and call of the Lord: Turn, you prodigals,
who have spent your portions and lost much of your sincerity and tenderness,
and that inward enjoyment of the Lord that you had years ago.
Oh turn, you who for a long season have endeavored to fill yourselves with husks,
and with a profession in words of what the former saints enjoyed.
My heart yearns towards you,
and my soul is often bowed down in the sense of your condition.
My heart is pained within me when I behold you wandering up and down,
seeking rest and finding none, except what is polluted,
so that your souls are lean for lack of the fullness
of God`'s house and the enjoyment of it.
My soul cries unto Him night and day, to visit you with His outstretched arm.
Return, return unto that light which will show you all you ever have done,
and will lead you to the Father`'s house where your bread will be sure.
Spend no more money,
precious time or labor for that which is only a profession or talk of bread,
and which cannot truly satisfy your soul.

Therefore, everyone gather inward, into a feeling of, a continuing with,
and a being subject to, the glorious, precious, ancient, living and mighty power of God.
Let all diligently attend its teachings, leadings, openings and operations,
that by its light a search may go forth through all hearts, all families and assemblies;
and that all that grieves His Holy Spirit, and is offensive in the pure eye of the Lord,
may be discovered, and every garden viewed to see what grows there,
so that every plant that is not of the Lord`'s planting may be discovered and pulled up.
For the Lord is arising to prove, to try, to fan, to purge and to refine.
The day comes on that will burn as an oven; but what shall abide?
Who may abide?
Let this be your inquiry; for the lead, the tin, yes, also "`the reprobate silver,`"^
footnote:[Jeremiah 6:30]
will pass away in this refining fire.
And that which may have the likeness of gold, but is not of a pure, enduring nature,
will vanish away, and leave poor and empty all who possess not the true gold.

So dear Friends, everywhere, I say unto you, in the dread, awe, fear,
and name of the Lord, hasten, hasten out of all that is not weighty,
out of that nature which keeps the soul in any bondage and distance from the Lord.
Yes, hasten out of the state of professing the truth in a nature and spirit contrary unto it,
which grieves the Spirit of the Lord God.
Dear Friends, the pure eye of the Lord that runs to and fro,
beholding the evil and the good, sees all states and conditions,
all false ways and false births.
He sees all that run from the daily cross, that lose the sweet lovely image of God,
and are growing up in another image in the house of imagery.
He sees and all that depart out of the sweet, tenderizing, heavenly wisdom,
into that which is earthly and sensual, wherein there is a pride in former experiences,
a sort of knowledge that brings sorrow,
and a growing fat and strong in that which must be fed with judgment; I say, the pure,
immortal eye of the eternal, ever-living God, sees all these states and conditions,
and all the by-paths and crooked ways which the enemy of souls leads into.

Therefore hasten, hasten, to meet the Lord God Almighty in the way of His judgments.
Bow, bow unto the pure power of the Lord;
feel it burning and consuming wherever there is anything that hurts the soul,
brings into bondage, and darkens the understanding.
Let all be brought down under the dominion and reign of this glorious power,
through its consuming,
utter destroying and burning up all that is contrary to the divine nature.
In this immortal power, peace is known with the Lord,
through His blessed work of spiritually slaying the enemy;
and thereby is the reconciliation to God through Christ Jesus our Lord.

And all who are lovers of this sweet, ancient power of the Lord,
having had heavenly tastes of it, and precious, sweet openings by it;
oh dwell with it and in it, and it will give you your soul`'s desire,
crowning you with dominion over the man of sin, both his root and fruit.
And in this power your inward man will walk in spirit with God who is a Spirit,
and obtain that which Enoch obtained, even the testimony that you are pleasing to God.^
footnote:[Hebrews 11:5]
And therefore all friends everywhere,
wait for the fresh springing and glorious arising of this Almighty power of the Lord,
that it may manifest itself everywhere, rending all veils, breaking all bonds,
opening all graves, raising up all souls into life itself.
Then, in all your assemblies and meetings everywhere, you will have this testimony:
that "`life and immortality have been brought to light,`"^
footnote:[2 Timothy 1:10]
and in it you will rejoice with joy unspeakable and full of glory,
because this immortal power reigns over all, glows over all, waters all, melts down all,
fills all, and sweetens all.
And in the enjoyment of its spiritual filling, holy high praises will arise,
and thanksgiving (in the sweet,
spiritual melody of eternal life) will spring and
be offered up in the sweet overcoming of His love,
who is the mighty power of God unto salvation.
And so all that is false and wrong, all that grieves the good Spirit of the Lord,
may be driven and carried away before the mighty stream and the strong
flowing of the immortal power of the Being of all beings.

But, to all who have lost your way, I sound the trumpet of the Lord in your ears:
Prepare, prepare, to meet the Lord Jehovah "`in the valley of decision.`"^
footnote:[Joel 3:14]
And to all who have any tenderness in your hearts,
and breathings after the Lord amongst all Christian professions, I say: Come out,
come out of Babylon, and be separate; touch no unclean thing,
that the Lord may receive you.
For He stands ready to receive all that come to Him in Truth and righteousness,
and will mark all who mourn because of the sins of the people, which are great.
Therefore flee for your lives out of Sodom`'s nature,
and do not stick in a mere profession of words which does not spring from the
immediate work of God and the daily operation of His eternal power in your heart.
Rather, come down into obedience to the pure, still, voice of the Spirit,
the gift of God in your own heart,
which will (as your inward ear is attentive) direct you in the narrow way of life eternal.
Here you will come to what perhaps moved your heart toward God many years ago,
and wrought you into a tender frame.
Now walk in this and be faithful,
and it will lead to the Fountain of blessedness from which it came,
and unto the horn of God`'s anointed; and so to Shiloh^
footnote:[Genesis 49:10, i.e. the Messiah]
shall be the gathering of thousands throughout the nations, tongues and people;
and the mountain of the Lord`'s house shall be exalted above all the mountains,
through this great day of trial, tribulation and anguish.

May the Lord God Almighty reach all hearts that have any longing desires after Him,
amongst people all religious professions,
drawing many to Himself as brands plucked from the fire.
So breathes my soul,
who am a travailer for the universal visitation and deliverance of the seed of Jacob.

Charles Marshall
