== To The Reader.

BE serious when thou takest in hand to read this following treatise,
and have a single regard unto the inward estate of thy immortal soul;
and let thy spirit bow down to the measure of the
Spirit of God given thee to profit withal,
that by it the eye of thy understanding may be opened;
so wilt thou see the things herein contained, which concern thy own eternal welfare:
and let not thy own thoughts and imaginations, in the wisdom from below,
which is sensual and earthly, be judge therein; but stand still,
out of thy own comprehendings, ascendings and descendings;
and let a true and diligent regard be had to the word in thy heart and mouth,
there placed, that thou mayst obey it and do it;
so will thy heart be truly opened to read with delight
the things herein opened by the Spirit of Truth,
which searches all things, yea, the deep things of God; and the travail in Spirit,
which is for opening the eyes of the blind, and unstopping of the ears of the deaf,
will be answered,
and the Lord God Almighty will have his honour from his own workmanship,
and thou the benefit; which is the desire, travail and breathings of him,
who is a traveller for Zions perfect deliverance.

C+++.+++ M.

Bristol, the 2nd of the Seventh Month, in the year 1673.
