[.style-blurb]
== Section 2. Man`'s Miserable Estate In the Fall.

But now he, who kept not his first habitation, neither abode in the truth,
envied mans happiness in the truth, and therefore, as a serpent,
more subtle than any beast of the field, which the Lord God had made, came to the woman,
who out of the man was made, and said, Yea, hath God said,
ye shall not eat of every tree of the garden?
The woman said, We may eat of the fruit of the trees of the garden;
but of the fruit of the tree which is in the midst of the garden, God hath said,
Ye shall not eat of it, neither shall ye touch it, lest ye die.
And the serpent said unto the woman, Ye shall not surely die; for God doth know,
that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods,
knowing good and evil.
And here the serpent got an entrance.
And when the woman, saw that the tree was good for food,
and that it was pleasant to the eyes, and a tree to be desired to make one wise,
she took of the fruit, and did eat, and gave also to her husband with her,
and he did eat, and the eyes, of them both were opened:
here the god of the world prevailed, so as to open an eye that saw evil pleasant,
and to blind the eye in these children of disobedience,
that they should no longer behold the glory of God, etc.
And here they became naked,
having lost the robe of righteousness and garment of innocency,
and then made aprons of fig-leaves to cover their nakedness;
and they heard the voice of the Lord God walking in the cool of the day,
and Adam and his wife hid themselves from the presence of the Lord God;
and the Lord God called unto Adam, saying, Where art thou?
And he said, I heard thy voice in the garden, and I was afraid, because I was naked;
and I hid myself: and he said, who told thee that thou wast naked?
Hast thou eaten of the tree whereof I commanded thee that thou shouldest not eat?
Then Adam began to excuse himself, saying, The woman whom thou gavest to be with me,
she gave me of the tree, and I did eat.
And the Lord God said unto the woman, What is this that thou hast done?
And the woman said, The serpent beguiled me, and I did eat.
And the Lord God said unto the serpent, Because thou hast done this,
thou art cursed above all cattle, and above every beast of the field;
upon thy belly shalt thou go, and dust shalt thou eat, etc.
And I will put enmity between thee and the woman, and between thy seed and her seed;
it shall bruise thy head, and thou shalt bruise his heel.
So the Lord sent Adam forth from the garden to till the ground, etc.,
and placed at the east of the garden of Eden cherubims,
and a flaming sword which turned every way, to keep the way of the tree of life.

O miserable change!
O deplorable alteration!
O lamentable state! undeclarable, undone condition! inexpressible fall!
What!
He that was in the image of the incorruptible Being,
a living soul inhabiting in the garden of the Lord, where the tree of life was,
and the splendour of the glory of the Divine Being was known and enjoyed,
driven from all into the earth; and not only so,
but the cherubims and flaming sword that turneth every way,
placed to keep the way of the tree of life!
Be astonished, O heavens! at this, and be horribly afraid, O earth!
The Lord God brought up children, and they rebelled against him.

Now what was the cause and ground,
O ye sons and daughters of Adam! that brought this wonderful change,
that brought man into this deplorable state and condition?
Was it not disobedience to the righteous law of God?
Did not sin enter into the world through disobedience, and death by sin?
And is not sin continued in the world through disobedience?
Is there any other way by which sin enters now, than it did then, and death by sin,
which has reigned over all, and reigns over all who are in the fallen estate from God,
even over them that have not sinned according to the similitude of Adams transgression?
For all have not sinned according to his similitude,
who was deceived with an expectation of a higher estate
than that in which the Lord God had placed him.
But all iniquity, of what similitude soever, is one in the ground,
and becomes a separator of man from his God.
So the ground of all iniquity and transgression that ever was, is, or shall be,
is mans disobeying the righteous law of God, disobedience whereunto bringeth death.

But what was that which in Adam died?
and what was the death?
seeing that the Lord said, In the day thou eatest of the tree, before mentioned,
thou shalt surely die; and yet, though he did eat thereof, he lived outwardly,
and had children.

It was the inward man that died, which was so made by the living breath of the Almighty;
for man going out of the counsel of the Lord,
by his disobedience came to be alienated from the life of God,
and so became insensible of that primary life in which he was wholly a right seed,
and a noble plant.
In his degeneration he became inwardly dead;
the inward senses of the inward man were lost; the inward ear was stopped;
the inward eye was blinded; the inward sense of tasting how good the Lord is,
the inward feeling after the divine virtue, which is all power, life, love, and joy,
the inward sense of smelling his garments,
that smell of myrrh and of the spikenard spiritually, were all lost; and instead thereof,
an ear opened, that hearkened to the voice of the stranger; and an eye opened,
that saw the forbidden fruit pleasant and desirable; the heavenly clothing of innocency,
meekness, and resignation lost; and thus he came to be without God in the world;
and here, in this estate, man was altogether out of a capacity of abiding in the garden,
or partaking of the heavenly tree of life that was in the midst thereof;
and in this estate are all the unconverted sons and daughters of men,
notwithstanding all fig-leaf coverings of professions.

But as the law of the spirit of life breaketh forth in its manifestation,
and the sons and daughters of men come with it to be awakened,
they will have the sight and true sense of their inward estate and condition,
which will indeed cause a cry to arise in the soul, O wretched estate!
O miserable condition!
And here the entrance of sin come to be seen, which hath brought death;
for the wages of sin is death, which was the death that came over Adam,
and over all since, that have disobeyed the righteous spiritual law of God,
which is just, holy, and good, and was before transgression;
which law bringeth to Christ, the promised seed, the gift of God, which is eternal life.

Now, man being thus departed out of that nature, image and seed,
in which man had his being before transgression,
is become the degenerate plant of a strange vine before the Lord God that made him.
And from the sons and daughters of men,
as they stand joined to this nature and seed of the serpent,
which hath defiled man in soul, body, and spirit,
proceed these branches and fruits of iniquity, to wit; pride, envy, emulation, strife,
variance, debate, hatred, wrath, anger, murder, inordinate affection, concupiscence,
lasciviousness, wantonness, vanity, uncleanness, fornication, adulteries,
love to this world, drunkenness, revelling, idleness, swearing, cursings, cheating,
defrauding, double-dealing, evil-speaking, back-biting, covetousness, idolatry,
witchcraft.

Man being thus fallen from God into this miserable, deplorable state, the Divine Being,
in his endless, boundless, fathomless lovingkindness,
hath opened a way by which mankind might be restored up to himself again;
which way is the promised seed, concerning whom he said to the serpent,
I will put enmity between thee and the woman, and between thy seed and her seed;
it shall bruise thy head, and thou shalt bruise his heel.
So herein was the tender mercy of the everlasting God extended unto mankind,
in giving the seed, to wit, Christ Jesus; else all would have been as Sodom,
and like unto Gomorrah, which God destroyed with fire in his wrath:
so this is that one seed, on which he hath laid help, who is mighty to save,
who is the image of the invisible God, the first-born of every creature;
in which image man was before the transgression,
who was glorified with the Father before the world began.
This is He, of whom in the name of the great Jehovah, I give testimony,
that He is the way of life and salvation;
and that there is no other name by which any man can be saved, than by Him who was,
and is, and is to come; who was from everlasting to everlasting, the Rock of Ages,
which followed Israel, and was in the church in the wilderness,
as Stephen testified before he was stoned to death.
This is He, who is without beginning of days, or end of life;
who in the fulness of time was manifest, taking on Him not the nature of angels,
but the seed of Abraham, for whom there was a body prepared,
in which to do the will of his Father; who, after He had accomplished it,
ascended where He was before, far above all heavens, that He might fill all.
This is the Emmanuel, God with us; Jesus, the Savior; Christ, the Anointed;
who hath been called by several names,
and spoken of under several denominations and appellations,
through the mouths of his servants,
the prophets and apostles in ages and generations by-past.
This is the only Beloved of the ransomed, and this is our Friend.

And now He is arisen and arising, who is the Ancient of days, in the might of his power;
and is revealing himself the good old way, and path of life,
whose out-goings have been from everlasting; in which way Abel, Seth, Enoch, Noah,
Abraham, Isaac, Jacob, and all the servants, prophets, apostles,
and saints of the Most High God walked, through all ages and generations;
which way was before all the invented ways and worships were,
which have been set up in the will and time of man; for all the holy men of God,
and saints of the most high, worshipped God in the spirit of holiness,
in which they were accepted of Him, who is the God of the spirits of all flesh.
And no outward performance whatever, performed by any, through ages and generations,
was any farther acceptable unto the Lord, but as performed in this spirit.
