[#sect-three, short="The Way of Restoration Out of the Fall"]
== Section 3. The Way of Restoration Out of the Fall, Into the Image of God Again, In Which Man Was Before the Fall, etc.

But how salvation comes to be wrought by Him,
and how mankind may be brought again into Him, who is the way, the truth, and the life;
and brought from under the power and dominion of the seed of the serpent,
in which by nature all have been the children of wrath,
is indeed the thing that lieth on my spirit weightily to demonstrate,
having obtained mercy to see this way of life and salvation revealed and opened;
and not only so,
but a necessity hath been and is upon me to preach the gospel of Christ Jesus,
and declare the way of life and salvation to my countrymen,
through this island of England; and now a necessity is also upon my spirit,
to leave a testimony of the same on record.

This is generally confessed, that in the first Adam all die, and in the second man Adam,
Christ the Lord, all shall be made alive.
But how mankind comes out of this state of death, in the first man Adam,
into this state of life in the second Adam,
is that which the wisdom of this world never knew, never saw, never understood,
nor comprehended truly or rightly.
Man, by that wisdom,
hath only imagined and conceived something in the
carnal mind concerning this great mystery,
and therein hath set up many inventions of the way of life and salvation.
And into these many ways of mans inventions and imaginations,
set up in the fallen wisdom of man, there have been the several calls, lo here, lo there;
but the day is dawned, and appearing, and now breaking forth more and more,
(magnified and praised be the name of the infinite,
almighty God,) wherein all invented ways, set up in the will and wisdom of man,
that is earthly, sensual and devilish, shall come to an end.

And now, in the name of the mighty God, all the graven images, the work of mens hands,
and earthly wisdoms shall be broken to pieces and ground to powder;
the mouth of the Lord of Hosts hath spoken it,
who will perform it by the might of his arm, and by the strength of his power.

And therefore, tremble, tremble, all ye image-makers of all sorts,
who have been making and framing likenesses of the way of life and salvation,
in your fallen wisdoms and corrupt wills, and have made gods thereof, and have fallen,
bowed down to, and worshipped them; so that it may be said of christendom, so called,
as it was once said of Judah, according to the number of thy cities are thy gods,
O Judah.

But now is the fulness of time come and coming, wherein the ancient way of holiness,
in which the righteous walked through all ages and generations, is cast up,
manifest and manifesting; which way is Christ Jesus,
the gift of the Fathers love unto the sons and daughters of men,
who hath as before-mentioned, been preached up and declared of by his servants,
messengers, prophets and apostles, under several denominations and appellations,
according as he was pleased to manifest himself in and to them,
and as his Spirit gave them utterance.
Amongst many other appellations, he hath been declared a Priest forever,
after the order of Melchizedec; the Rock that followed Israel,
who was in the church in the wilderness; a King; a Law-giver; Wonderful; Counsellor;
Prince of peace; a Branch; a Light to lighten the Gentiles; the Arm of Gods salvation;
a Covenant; Messiah; a Leader; a Commander; a Captain; the Horn of Gods Anointed;
a Stone of stumbling; a Foundation laid in Zion; the Corner-stone; the Word of God;
the Word that was in the beginning; the True Light,
that lighteth every man that cometh into the world; the Truth, the Way, and the Life;
King of kings; Lord of lords; Christ; Emmanuel; Jesus;
the Beginning of the creation of God; the First-born of every creature;
the First-begotten from the dead; the Faithful Witness; Alpha and Omega;
Bright and Morning star; the Image of the invisible God; the Offspring of David.
Under these, I say, and other names and denominations,
hath he been spoken and declared of, and by;
who still hath a name that no man knoweth but himself,
who is that one Eternal Fountain of blessedness, and the one previous Savior;
and there is no other besides him, although diversely denominated,
according as his Spirit gave utterance,
to demonstrate him to those unto whom his servants spake, prophesied, and wrote.

And now, by the ancient power of the holy everlasting God, is he preached up,
under the denomination of LIGHT, in this island of the Gentiles,
according as was prophesied of old, by Isaiah, chap.
xlix.
6, who said, It is a light thing that thou shouldest be my servant,
to raise up the tribes of Jacob, and to restore the preserved of Israel;
I will also give thee for a light to the Gentiles,
that thou mayest be my salvation unto the end of the earth;
which is one with the testimony of John chapter 1, saying,
In the beginning was the Word, and the Word was with God; and the Word was God.
The same was in the beginning with God.
All things were made by him, and without him was not any thing made that was made.
In him was life, and the life was the light of men.
And the light shineth in darkness, and the darkness comprehendeth it not.
There was a man sent from God, whose name was John.
The same came for a witness to bear witness of the Light,
that all men through him might believe.
He was not that Light, but was sent to bear witness of that Light.
That was the true Light, which lighteth every man that cometh into the world, etc.
And to this agrees the testimony of just Simeon, who came by the Spirit into the temple,
and took the child Jesus into his arms, and said, Lord,
now lettest thou thy servant depart in peace, according to thy word;
for mine eyes have seen thy salvation,
which thou hast prepared before the face of all people, a light to lighten the Gentiles,
and the glory of thy people Israel.
This is he of whom we testify, whose light is the way of life:
And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
For every one (mark) that doeth evil hateth the light, neither cometh to the light,
lest his deeds should be reproved.
But he that doeth truth cometh to the light, that his deeds may be made manifest,
that they are wrought in God.

Now this Light, which the servants of the Most High testified of,
is that which hath been spoken of and denominated under several names:
for this manifestation of God in man, is sometimes called the Word, the Spirit, the Law,
the Grace of God; now the Word, Light, Grace, Law, Spirit, are all one in nature,
although diversely named: Moses called it the Word,
and directed to this Word in the heart and in the mouth; which Paul,
that illuminated man, rehearsing, saith,
Say not in thine heart (mark) who shall ascend into heaven?
(that is, to bring Christ down from above:) or, who shall descend into the deep?
(that is, to bring up Christ again from the dead.) But what saith it?
The word is nigh thee, even in thy mouth and in thy heart; that is,
the word of faith which we preach.
This is the sure word of prophecy, unto which Peter directs to take heed,
as unto a light that shineth in a dark place,
until the day dawn and the day-star arise in the heart.

This Light is the law of the spirit of life, wherewith Paul was acquainted,
that warred in his mind against the law of sin and death, which was in his members:
this Light is the law in the heart and the spirit in the inward parts,
the new covenant of God Almighty; this is that which converts the soul;
which law Paul delighted in according to the inward man: this law is light,
of which the scriptures of truth plentifully testify:
this is that grace that Paul declared, brings salvation, which hath appeared to all men;
which Law, Light, Spirit, Grace, Gift, hath in measures, as Gods talent,
appeared to all men, which teacheth all that are led, taught and guided by it,
to deny all ungodliness and worldly lust; and not only so, but also to live soberly,
righteously and godly in this present world.
This is that grace which the Lord, the giver thereof,
said to Paul was sufficient for him, to deliver him from the temptation,
the thorn in the flesh; of which the same apostle said unto the Ephesians,
By grace ye are saved, etc.
And this is the manifestation of the Spirit spoken of by Paul,
which is given to every man to profit withal.
And this is that good Spirit of the Lord given to Israel, who rebelled against it,
as the old world did, unto whom the Lord said,
My Spirit shall not always strive with man; of which Word, Law, Light, Grace and Spirit,
given to be the Leader and Guide of mankind out of sin, and death, and darkness,
into which man fell through disobeying the righteous law of God, as is afore declared,
the Holy Scriptures give clear and full testimony, as hath been demonstrated.
But now, that which is ready to arise, is an objection in some,
(whose understandings are not opened, whose searchings to comprehend,
and inquiries after the way of mans salvation, stand in that wisdom that is from below,
and in the will and reason of man degenerated from
the life of God,) whether the preaching up this Word,
Light, Law, Spirit and Grace of God manifest within,
hath not a tendency to make Christ Jesus appearance in the flesh, his sufferings, death,
resurrection and ascension to be invalid?
Unto which I answer, nay; forasmuch as no persons ever did, do, or shall truly see,
discern, know,
understand or enjoy the benefit of Christ Jesus manifestation in the flesh,
but as their hearts were, are or shall be opened,
and understanding illuminated by the light;
which is a measure of the Divine fulness that dwelt in him, and is communicated to,
and placed in all immortal souls, as the universal love of God;
extended in the Son of his love to all the families of the earth,
as the revealer and discoverer of the will of Him from whose divine fulness it comes,
and issueth forth itself universally: for the Scripture thus witnesseth,
that no man knoweth the things of a man, save the spirit of man which is in him;
even so the things of God knoweth no man, but the Spirit of God.

The hearts of the Jews not being seasoned with this grace of God,
and ignorant of the gift of God, which is eternal life, they neither discerned,
loved nor received Christ Jesus, when manifested in that outward bodily appearance,
but rejected him; notwithstanding they professed love, honour and regard to the prophets,
and were in expectation of the fulfilling their prophecies of the coming of the Messiah,
who in due time came, and yet they did not receive him; but instead thereof,
set themselves against him, taking counsel from time to time how they might slay him,
though in words they professed an earnest waiting for him: so in this day,
age and generation, there are many,
who by their words do profess they believe his coming in the flesh, and his sufferings,
death, resurrection and ascension;
but yet having their faith consisting in outward notions,
and having no inward experience of the end of his coming,
nor of the virtue of his sufferings, death, resurrection, etc.,
they are enemies in their minds to his second appearance,
and coming without sin unto salvation.
So there is a necessity for all the sons and daughters of men to come to,
and obey this divine, spiritual principle,
which is placed in their consciences by the living eternal God,
that thereby the eye which hath been blinded through disobedience,
by the god of the world, may be opened; for, until this in some measure be effected,
the mystery of godliness, which is great, can neither be seen nor understood;
and therefore Christ said, finding the woman of Samaria ignorant of himself,
who was and is that great mystery, and the gift of the Fathers love,
If thou knewest the gift of God, and who it is that saith to thee, give me to drink,
thou wouldest have asked of him, and he would have given thee living water.

The travail in spirit of the messengers and servants of the Most High in ages past,
was the same as now it is, viz., to turn people from darkness into light,
and from the power of Satan to the power of the living God;
thereby in no wise invalidating Christ Jesus manifestation in that bodily appearance,
neither his sufferings, death, resurrection or ascension;
but bringing all people guided thereby,
unto that which will open the eyes of their understandings,
whereby they all come unto such a condition and spiritual understanding,
as to see and know their benefit by that appearance of the Savior of the world;
for this we testify, all are perfected by that one offering, that are sanctified.
But here ariseth another objection by some, who may come so far as to own and confess,
that there is a principle or light in man, that discovereth sin,
and teacheth man to do justly and equally, which some call morality;
but that this light or principle in man, is of a saving property,
and of the nature and quality of the Divine Being,
many for want of understanding do deny; and so are found opposers of Truth itself,
and stumble at the cornerstone; which indeed in all generations,
hath been to many men a stone of stumbling and rock of offence; which thousands,
giving themselves up to be guided by their own wisdom and prudence, reject; yea,
those accounted the wise master-builders, professors of God and Christ,
being ignorant of the root and offspring of David,
have and yet do reject this corner-stone.

Now, for the sake of all who do or may desire after the
true and saving knowledge of Christ Jesus,
it is on my spirit yet further to open and manifest
the nature and property of this principle and light;
whose fountain is the Eternal Being, and everlasting ocean of Divine fulness,
and its nature and quality is one with this fountain from which it comes.
John testified, In the beginning was the Word, and the Word was with God,
and the Word was God.
In him was life, and the life was the Light of men.
He also testified, that he was not that Light, but came for a witness, to bear witness,
that that was the true Light, which lighteth every man that cometh into the world:
so the original of this light is Christ Jesus, the Word.

But some may query thus, is Christ the Light in every man?

To which I answer; Christ doth appear by his light in every man; and the light,
which comes from Christ, is in every man;
as is clearly demonstrated in the Scriptures of truth: and,
though I account it unnecessary to answer the curious inquiries of such,
who seeking to know much, do not walk answerable to what they know;
yet for the sake of such whose understandings are not opened,
and yet are inquiring the way to Zion, I add this similitude:
the natural sun is placed by the Creator to lighten the outward world,
and doth extend from its body a measure of its light and natural property,
shining on the just and the unjust,
and so doth daily give forth of that virtue which is inherent in itself.
When the sun shineth on any object whatsoever, we sometimes say, the sun there appears;
and other times we say.
There is the sun; the propriety of either of which manner of expression, I suppose,
none will question; for light in that appearance is seen, and virtue is felt,
penetrating to the refreshment of our natural bodies;
and this light and heat is inseparable from the fulness:
and notwithstanding it daily shineth,
and displays its virtuous life into and over all the earth and its inhabitants;
yet its body is not any way exhausted or altered through ages and generations.
And so I say, that Christ, the universal fountain of Life, the Sun of Righteousness,
the ocean and fulness of spiritual light, life and virtue,
from whence is communicated a measure of his nature, property and quality,
is given of the Father to enlighten all the sons and daughters of men;
who accordingly are all enlightened with his spiritual appearance;
and though this appearance cannot be called the fulness,
yet being a measure of that fulness, it is one in nature and property with,
and inseparable from the fulness; and though through its virtue,
life is daily communicated unto the sons of men, who waiting for the appearance thereof,
as for the morning light, cannot live unto God without it,
yet doth he admit of no diminution, alteration or change;
but all fulness of Divine light, life and glory, doth and shall,
through every age and generation, remain with him:
and albeit the veil of darkness hath over-shadowed the hearts of some,
so as when we give testimony unto the universal appearance of the Sun
of Righteousness in the hearts of all the sons and daughters of men,
they are ready to say,
such a testimony leads to the diminishing of that
glory and honour which belongs unto Him,
as He is the fulness, and sitting at the right hand of the Father;
inferring from such our testimony, as if,
whilst we testify to his appearance in our hearts, we exclude his presence elsewhere:
which inference, I say, is as irrational as it would be for any to conclude,
that because we say of the shining and appearance of the sun, there is the sun,
or the sun there appears, therefore we exclude the being of the sun elsewhere:
for its virtue is communicated to our natural bodies,
every one having in measure some enjoyment of the virtue or light of the natural sun;
which is light to the eye, even as the outward eye is light to, or of the natural body;
and whosoever they are,
whose invisible sense are quickened by the influencing
virtue which proceeds from the Eternal Sun of Righteousness,
do thereby see and discern,
that these things are according to the clear manifestation
of Truth in their inward parts;
and from a true sense thereof, can of a truth give this certain testimony,
that Christ the Lord, by his holy quickening Spirit, hath appeared in them,
to the quickening of their immortal souls;
and that through believing in the Light and obedience to his appearance,
being come out of that state which is reprobated by the Lord,
can of certain experimental knowledge say, Christ is in us the hope of glory.

And so, when we direct people to this Word, Light, Law, Grace and Spirit,
we do not thereby intend that Christ Jesus, the Light of the world, and gift of God,
is not the true Savior, Redeemer, and Reconciler of mankind unto God.

Now this Word, Light, Law, Grace and Spirit, which is one in nature,
doth lead and guide the souls and spirits of all such as obey it, up to God,
the fountain from whom it comes; and no man comes to see its nature,
but such who are led by it; for in the light of the Lord alone, man cometh to see light,
and to have an understanding from whence it springs.
Before this be fully seen or understood, the mind of man must be brought down,
out of all its own willings and runnings, comprehendings and searchings,
into the principle of light, therein to see a death to his own will,
and be comprehended into this light;
and so man comes to have an understanding to know Him that is true,
and to be in Him that is true.

Now, as any are convinced of, and converted by this heavenly principle,
(which is placed in the conscience,
there given to be a guide and leader unto mankind,) they are led thereby out of darkness,
wherein they have been, while yet the light shone in darkness;
in which darkness no man ever comprehended this light or heavenly grace,
which sometimes moves through the darkness, on the depth of mans understanding,
reproving and discovering darkness, causing man to hear its small still voice,
moving in man Godwards; and so daily continues without change,
reproving man whilst he remains in rebellion and disobedience,
all the time of his visitation,
and approving and giving peace unto man when he is obedient.

This principle of light remains entire in its own purity;
and although man may change and alter, and go from it, and rebel against it;
and thereby become one of them of whom Job speaks, that rebel against the light,
and thereby know not the way of it; but give way to the working of the god of the world,
to be drawn out into the fading perishing things;
yet this principle remains immutable in itself, being of and from the immutable,
unchangeable Being, and remains with man, until it be taken from him,
and he be cast into utter darkness.

The first operation of this heavenly Light, amongst those who are convinced by,
and turned to it, the gift of the Father (which Christ Jesus, in his parable to the Jews,
compared to a grain of mustard seed; and to a little leaven,
which a woman took and hid in three measures of meal,
until the while came to be leavened,) is, to shew man his inward state and condition;
and the first step in the way of life, is, to be turned to this holy principle,
that teacheth the obedient to know God savingly;
and when by this principle man comes to have a true sight and sense of his fallen estate,
and sees how he hath transgressed against that Eternal
Being that gave him life and breath,
who notwithstanding in his long-suffering, waiteth still to be gracious,
and knocketh at the door of the heart, and hath striven by his Divine light,
the true sight and sense hereof will break the heart,
and tender the spirit before the Lord;
and under the weighty sense of the great burden of sin and iniquity,
there will be a crying out, my sins they are too heavy for me to bear,
and mine iniquities are gone over mine head; as Paul did, saying,
O wretched man that I am! who shall deliver me from the body of this death?
And here comes the eye to be opened that seeth Him, whom man, in is disobedience,
hath pierced afresh and put to open shame;
and then there will be days of mourning and wailing, because of Him;
and this is truly the day of Jacobs trouble.
And in the sense of this deplorable, fallen estate, and the long-suffering of the Lord,
and the long-striving of his Spirit, thou wilt see, that in the justice of God,
eternal death might be thy portion; but that which brings into this sense,
begets a secret cry in the immortal soul, after a deliverer and Savior;
and will also give a true sense and sight,
that there is no way for thy soul to be ransomed,
but in and through the tender mercies of God through Jesus Christ;
which thou wilt see can no other way be effectually begun in thee,
but in the way of the judgments of the Lord; for Zion shall be redeemed with judgment,
and her converts with righteousness.
And here also thou wilt see that the measure of the sufferings of Christ yet behind,
must be filled up in thee; for no other way can any man pass unto life,
peace and joy with the Father of spirits, but the way the Captain of Salvation passed,
which was through death; and here thou wilt begin to arm thyself with the same mind:
for none ceaseth any further from sin,
but as they suffer in the flesh the crucifying of the affections and lusts thereof;
and here the end of the gospels preaching comes to be known and witnessed,
which was and is, that they might be judged according to men in the flesh,
but live according to God in the Spirit.
And in this spiritual inward sense and exercise,
the Lord God Almighty will bow down his ear, and answer the cries of thy awakened soul,
and manifest his word of power;
which all in this state and passage will know to be sharper than any two-edged sword,
piercing,
to the dividing asunder of thy immortal soul from the spirit and nature of transgression,
and its working daily, as subjection and obedience is yielded unto it;
dividing and making a separation between joints and marrow,
giving thee daily a discerning of the thoughts and intents of thy heart.

And as the soul, mind, and heart, gives up in love to God,
freely to follow him in the way of his judgments,
and gives up to the sword of the Lord that which is for the sword;
and that which is for destruction to be destroyed;
thus will the precious work of the Lord prosper.
And although this be a time of sorrow, and a time of trouble, travail and anguish; yet,
notwithstanding, it is a good day: therefore, strive not to get from under it,
neither to make haste; for the true godly sorrow worketh the true repentance,
which is never to be repented of.
And after the true repentance, follows the true knowledge of remission and forgiveness;
and so thy iniquities, by the judgments of the Lord God Almighty, come to be blotted out;
and then the times of refreshment come from the presence of the Lord,
and from the glory of his power.

And as there is a faithful abiding in inward watchfulness,
and continual obedience to this heavenly light,
in which the beginning of the work of God was known,
there will be a going on from step to step in the footsteps of the flock of Christ Jesus,
and a growing from strength to strength over sin and the nature thereof,
and from one degree of grace to another;
and as there is a faithful perseverance in this divine principle,
the eye of the understanding will be single; and here everything which hath or doth let,
will be seen, and the soul never start aside from an inward travail,
until that which hindereth be taken out of the way,
and until thou seest all the rule and authority of the enemy
to be subdued under the feet of the Lords anointed,
and the government in the soul upon his shoulders, whose right it is to reign over all.

And here salvation, redemption, and restoration is effectually enjoyed through faith,
and the effectual working and operating of the almighty power and arm of God Almighty,
unto whom be the glory of his own work forever;
and so here will be a growing and increasing,
until there is a coming into that precious state and image,
in which man was before he fell.
