[.style-blurb, short="The Snares of the Enemy Discovered"]
== Section 4. The By-paths, Crooked-ways, Wiles, and Snares of the Enemy Discovered.

Now when the mind is turned to this divine heavenly principle,
and that therein the work of the Lord is begun, which before is said,
is the bringing man into a real, sensible knowledge of his state and condition,
then will the same destroyer, that brought man into bondage at first,
and hath kept him in bondage, begin to work cunningly,
and ever way endeavour to destroy the work of God begun in the soul;
and that he may accomplish his end, he will go about every way, seeking an entrance,
and will lay his temptations suitable to the propensity or inclinations of the creature.

If the heart and mind be bowed down under the weighty sense of iniquity,
the sins committed coming in order, and the many transgressions in sight,
through which the sorrow and bitterness is great,
here the enemy will work in his transformings, and although in appearance like the light,
yet in nature contrary thereto: for,
albeit the light and appearance of God gives the
certain understanding of the inward state,
and brings sorrow because of sin,
and shews the mountain of iniquity and the exalted hills of transgression,
yet its workings inwardly beget a secret hope of overcoming by the Lords strength;
but then the enemy, when he seeth the soul bowed down, as aforesaid,
oftentimes afflicteth and bringeth down the mind into unbelief of ever overcoming,
thereby endeavouring to sink the soul down into despair; knowing, if he overcomes,
he still keeps under his power, although in another appearance;
but to all that are exercised in this kind, waiting on the Lord singly,
with the mind stayed in the light, this snare will be discovered; for, as I said,
although the true appearance of Gods heavenly light and grace brings a day of trouble,
sorrow and anguish; yet that sorrow is not a sorrow without hope;
but the enemy`'s working is, to bring into a sorrow, trouble and anguish without hope,
and to draw down the spirit into the chambers of darkness, where there is no order.

But now, when the enemy of the souls peace is discovered in this his working,
and the heart and soul, through the love and power of God, is comforted,
encouraged and refreshed, and raised up into a measure of the living hope,
satisfaction and content; then the old, crooked, subtle serpent,
endeavours to lead from off the inward, daily travail,
(that so judgment may not be brought forth unto victory;) and to
draw up the mind into a false persuasion of obedience and diligence,
when as there is not an abiding in that which gives
a true sight and sense of the state and condition.
And as before, he would have destroyed the hope that is an anchor sure and stedfast,
so now on the other hand, he would beget a false hope and confidence,
and so bring out of the daily cross,
through which the nature which hath alienated from God, should be destroyed.

And if the workings of the enemy be seen and overcome in both these wiles and snares,
on the right hand and on the left,
and that the work prospereth even until much be subjected; and that,
through the daily obedience to the heavenly power, much is slain;
and that the heart and mind comes in a good measure to be cleansed;
and that in pure obedience and constant faithfulness, in this light of righteousness,
a good progress is made through the administration of condemnation,
that is glorious in its time;
and that something of pure peace and heavenly joy
springs and arises in the heart and soul;
here again the enemy will be subtly at work, to betray and lead aside,
in persuading to sit down now, as if all were done;
and so lead out from the feeding on the tree of life,
to feed on the tree of knowledge of good and evil,
and into a liberty to break the commandment of the Lord;
and here at first subtly and cunningly draws the
mind out so far as to take a little liberty,
and draws the mind somewhat from that diligent watchfulness, dread,
fear and awe it was in before, in the inward travail of spirit.
And here, if the destroying subtle enemy can but prevail a little,
he will lead out of the innocent harmless life, and so gradually lead a little forth,
and by degrees open an eye that may see something in the outward visible things,
that may somewhat affect the mind; and as here he prevails,
and causeth his work to prosper, which he doth subtly, gradually and hiddenly,
the eye that was opened comes again, through disobedience, to be in some measure blinded;
and here loss is sustained, even before the unwatchful is aware.
And so the working of the enemy first is,
to cause such to make shipwreck of faith in a little measure; that is,
not to have the daily belief stand in the power; the daily enjoyment of which,
coming to be left by degrees, there will then be a turning from the power of godliness,
into the form thereof.
And although at sometimes the eternal power of the Lord God may be felt in this estate,
yet there being not a daily feeling after it, the enjoyment thereof,
as to true refreshment and consolidation, comes to be lost,
and an image comes up in its place;
and the enemy provides and presents some object or objects so to take up the mind,
as that by degrees he may enter in, and defile the mind,
and draw it out from its true guide, so as also to make shipwreck of a good conscience.

And now, if the enemy be discovered in these his workings,
before he can so effect his work, as to bring death and darkness over again;
and that the power of the Lord breaks his snares, and gives a true weighty sense thereof,
through which trouble and anguish of spirit comes; here he will again transform,
and begin to work, as in the beginning of the work,
like the condemning power of the Lord;
endeavouring to lead the mind down into despair of
ever recovering again into the former condition;
and hereby endeavour to draw the mind to look at him that hath stung, that so the remedy,
the soul-ransoming power of the Lord, may not be felt after, nor looked at.
But here, as there is a true regard to the Lord,
and a waiting upon him in the way of his judgments,
having the faith and confidence to stand in his power, the backsliding will be healed;
and returning and diligently keeping in the light,
the power of the Lord God Almighty will work over that which hath hurt,
and endeavoured like a roaring lion to destroy, etc., and so lead on the way again.

But when deliverance is known again from this deadly snare,
and the work again goes on prosperously until the house be swept and garnished,
and there is a passage known and witnessed from death unto life,
and the administration of condemnation being passed through,
and the spirit that ruled in the disobedient estate cast out,
and the openings of that which doth exceed in glory, the administration of the Spirit,
being known, here the enemy will again transform,
and with all his power and strength in the transformation, as an angel of light,
work by his temptation on the right hand and on the left.
For when there are openings to the understanding and prophecies,
and through the working of the Eternal Power, joy springs in the heart,
then will the enemy work secretly and cunningly; and if he prevaileth here,
to draw out of this habitation of safety,
then he will transform to lead the mind out through
the motions of his transforming spirit and power,
into extremes, thereby endeavouring to destroy the true birth, which is bringing forth;
and so bewilder the mind and hurry it forth, through imaginary notions,
to dishonour the name of the living Eternal God, and to destroy his work,
which through sorrow and travail hath been brought forth.

And if he cannot prevail here, but the light of the Lord discovereth him,
and the power of the Lord works over his appearance herein,
then will he be at work to draw the mind out of the watchfulness,
out of the daily awe and fear, and out of the liberty of the sons of God;
which liberty is, only to serve the Lord: for dominion being felt in some measure,
the morning of comfort and consolation enjoyed,
and praises springing in the heart of Him that visited and redeemed,
the enemy will be ready here also to draw the mind out of the valley of humility,
out of the stayed estate of meek and constant watchfulness in the light;
thereby causing the creature prodigally to spend the portion and to lavish out the enjoyment,
by running and climbing up to sacrifice upon the mountains,
and to run before the leadings, guidings and movings of the power of the Lord,
into the speaking forth of the enjoyment, the prophesyings and openings;
not being led thereunto by that Eternal Power that first opened the heart:
and here is the ground of the untimely birth that hath been brought forth,
that +++[+++hath withered; and such]
will wither and come to nothing.

But now, where the enemy is seen and discovered in all the aforesaid workings,
and cannot prevail by these snares, traps, gins and temptations aforesaid,
he will not cease, who goes about as a roaring lion, seeking whom he may devour,
and how he may again get entrance;
so that he lays his temptations according to the spirit, growth,
capacities and inclinations of every one.
Now after the good work of God has been begun prosperously,
and that the right arm of Gods salvation hath been wonderfully revealed,
and signally manifest to bring out of Egypts land of darkness spiritually;
and that the Lord hath magnified his arm spiritually,
in giving many signal deliverances from the destroying enemy;
and has often fed with the heavenly food,
and caused the rock to yield water for the thirsty;
and that the many turnings aside in the passage through the wilderness have been seen,
and the backslidings and going out from a sense of the Eternal Power,
have been discovered; and that there is a coming through the river of judgment;
and the mighty power and arm of the everlasting God drives out the enemy that hath inhabited,
where only Abrahams seed is to inhabit; and that the war in great measure ceaseth,
and part of the good land is possessed and enjoyed,
even the land that floweth with spiritual milk and honey,
and the fruit of the vine drunk of; here also, as in the travails afore-mentioned,
will the old crooked, subtle enemy be working, as he did with outward Israel,
causing Jesurun to wax fat, and then kick against the ancient Power;
leading the mind out, through the enjoyment of that which in its place is good,
into ease; and so to forget the Lord that made and formed man,
and brought him into the land of rest, and lightly to esteem the very rock of salvation;
and so leadeth into an easeful state, in a profession;
and draws away the mind from the inward enjoyment of virtue,
to set up idols in the heart, and to serve other gods, even gods of silver and gold,
and an idol, a profession without life and possession:
and into this state and condition did the old enemy prevail to lead a people,
who in many ages had seen the great and mighty works of the Lord,
who saw from time to time the arm of God Almighty out-stretched
and magnified in the sight of their enemies for them;
howbeit they departed from the Lord, and from the inward sense of his Eternal Power.
Now here the spirit that was cast out, and wandered in dry places,
takes to it seven worse spirits, and returns, tempts, prevails and enters;
and here indeed the latter end is worse than the beginning; for in the beginning,
although the enemy had his power and rule, yet there was a sense thereof,
and the heart and mind was humbled, tender, and brought into the true poverty;
and there was a mourning before the Lord for want of the dominion;
and this state of humiliation, brokenness of heart, and tenderness of spirit, +++[+++is that]
in which the Lord took and taketh delight; and therefore in his endless,
boundless lovingkindness +++[+++hath]
visited and caused his redeeming saving power and arm to be revealed:
but now in this other estate, the mind is high, the heart fat and full, and at ease,
and gotten forth into the love of the world, and the things thereof,
through which there is an unmindfulness of the Lord,
who in the beginning was every day sought after, and diligently waited for;
and here the Rock, the Power, is lightly esteemed of;
for the estimation is of another thing:
and here two great evils are committed even at once,
viz. the fountain of the former living mercies forsaken,
and a hewing out broken cisterns, a profession, that will hold no water,
no durable refreshment, no durable joy, no durable peace nor consolation.
And the enemy hath thus prevailed through many ages,
to bring thousands from their enjoyment of God, in the pure, tender, broken, contrite,
upright-spirited estate, which he doth effect through his workings and subtlety,
and that gradually: his first footsteps hereunto is, to bring out of the constant, daily,
sure watchfulness,
and causing a little liberty to be taken to the carnal
mind and to the flesh and that gradually,
and, as it were unperceivably; causing such to take, as it were, a taste,
a certain enjoyment of sweetness therein, and thereby a little darkening the sight,
and so alluring into a little more liberty:
sometimes his beginnings are to draw out of obedience in
those things that were required in the day of small things;
sometimes into many words, out of watchfulness,
no more to be as a door-keeper in the house of the Lord,
and so the enemy works to cause such-like things to seem small and indifferent things,
thereby to cause the offence of the cross in those things to cease;
and then the heart and mind runs forth to make provision
for the flesh to fulfill the lust thereof,
either in meats, drinks, apparel, or such-like,
which the truth in times past hath discovered and made manifest, and the power of God,
the cross of Christ, hath crossed, and in measure led out of, into watchfulness,
in pure fear and holy awe, not making provision for the flesh, in any respect,
to fulfill the lusts thereof; but drawing the creature in practice,
as well as in principle, into plainness, and out of all superfluities,
admitting of the creature to refresh nature, and not feed the lusts.

But yet the enemy works by degrees, subtly and covertly,
to lead out of the liberty of the cross of Christ Jesus, the power of God unto salvation,
into the liberty of the flesh again, and hereby gets a little further entrance;
and though the enemy be working to draw forth the mind into a wrong liberty,
as into many words in dealings, in commerce, or converse,
and into the love of the world and the things thereof again,
and yet the profession may remain, and the enemy may be contented therewith; yea,
and many times the power of God may be felt in some measure,
which indeed works not in the approvement, but to draw out of the snare;
but the god of the world having by this time much blinded the eye,
and darkened the heart, and deceived the understanding,
there is not a sense nor knowledge of the mind of the power of the Lord in its workings,
nor a real sense of the decay, and gradual, subtle workings of the enemy;
for the outward profession and conformity may be in a great measure kept to,
which is a cover, under which the enemy may work undiscovered by the unwatchful.
And so the enemy many times leads cunningly step by step,
until he hath led out of the power of godliness, and slain the tender birth,
which in the first days of tender visitations was begotten;
and so here will be a growing high, fat and thick; and such +++[+++as are in this state]
will call the operation of Gods dividing power, extremes and imaginations;
and Jesurun-like, will kick and turn against the dividing power of the mighty God;
for all such are best contented with a likeness and image:
for they love the smooth things in the wisdom of the gifted man, that has lost his way,
through erring from the power,
not waiting continually on all occasions to be guided thereby.
So here is the itching ear, and heaping up teachers to please self,
to please that and uphold that; and here Jezebel is suffered and upheld,
which error crept into the church of Thyatira;
and in all ages they that went from the broken, tender estate,
into the conditions before +++[+++described]
did and do both suffer and nurture this Jezebel, who must be cast on the bed of torments,
and all her children must be killed with death; and all the workings of the enemy,
under every disguise, is to slay that which was quickened,
and to bring in a contentedness with an outside profession of the way of Truth,
Light and Life of Christ Jesus, the power of God unto salvation,
whilst the heart is adulterated and gone from the Lord, and has embraced other lovers;
and so in process of time, where the enemy thus prevails, he leads again into the world,
from whence the arm of the Lord gathered;
and the latter end of such is indeed worse than the beginning:
for the enemy having led to make shipwreck of faith and of a good conscience,
the second death comes over, and such become twice dead,
and become as salt which has lost its savour, and are good for nothing,
but to be cast forth and trodden under foot of men.

The preservation out of these by-paths, crooked ways, wiles,
snares and temptations of the enemy,
is only in the true waiting and sincere abiding in the light, gift and grace of God,
in which the daily revelations and manifestations of Gods Eternal Power,
and right arm of salvation and preservation is known,
in the daily acquaintance and experience thereof; which keeps all minds truly low,
and hearts sincerely tender; wherein ariseth an inward travail, longing,
breathing and panting after the daily and continual enjoyment of the life, power,
and blessed refreshing,
the heavenly virtue which alone renews and increases the strength of the inward man;
in which God Almighty preserve all the travellers Zionwards to the end.
