[.style-blurb, short="Section V -- The End of All False Professions"]
== Section V. The Utter End and Final Destruction Prophesied, of All False Professions, Which Have Had Their Rise in the Night of Apostacy

After the glorious breakings forth of the day of God amongst the apostles, etc.,
the enemy wrought mightily against that appearance, both in his instruments,
by and through which he raised up persecution,
and also in those apostates in whom he got an entrance amongst the churches,
and has so prevailed, that great has been that horrible night of darkness and apostacy,
that hath been many centuries in and over the nations of the earth;
in which times the old subtle serpent, in his many transformings and appearances,
has mightily wrought, to alienate man from his God.
O the ways and inventions that have been by him set up,
through his workings in the wisdom which is from below, which is earthly,
sensual and devilish, under pretence of religion, obedience, and worship of God!
What rending, tearing, devouring, murdering and destroying,
has there been for these many hundreds of years about religion?
First, the great red dragon of persecution appeared,
to devour the man-child and destroy the woman, but both were preserved;
then he made war with the remnant of her seed; and after came in another appearance,
which John saw rise as a beast out of the sea, having seven heads and ten horns;
and on his horns, crowns, and upon his heads the name of blasphemy;
and one of his heads had a deadly wound by the sword;
but this deadly wound was again healed; and all the world wondered after the beast,
saying, who is like the beast?
And who is able to make war with him?
And all on the earth do and shall worship the beast,
whose names are not written in the book of life of
the Lamb slain from the foundation of the world.
And after this, a second beast appeared, that came out of the earth;
and this beast had two horns like a lamb, but spake like a dragon;
and John saw he exercised all the power of the first beast,
who received his power and authority from the dragon,
like unto which this second beast spake; and this beast that had horns like a lamb,
caused the earth and them that dwelt therein,
to worship the first beast whose deadly wound was healed; and he caused all,
both small and great, rich and poor, free and bond,
to receive a mark in their right hand or in their foreheads.
And here has been the universal working of the power and spirit of darkness,
that hath exalted himself, sitting in the temple of God as god and ruler.
But, blessed forever be the name of the Almighty God, the great red dragon,
and the beast that arose out of the sea, and the beast that arose out of the earth,
and mystery Babylon, are and shall be manifest.
The wisdom that is pure and peaceable, numbers these appearances.
And the judgment of the great whore is come and coming, who rides upon the first beast;
for now the angel of Gods presence is come down from heaven, having great power,
who lightens the earth with his glory, and the mighty cry is now going over the earth,
uttered with a strong voice, saying, Babylon the great is fallen, is fallen,
and is become the habitation of devils, etc.
All nations have drunk of the wine of the wrath of her fornication,
and the kings of the earth have committed fornication with her,
and the merchants of the earth are waxed rich, through the abundance of her delicacies;
and the voice is now uttering from heaven, Come out of her, my people,
that ye be not partakers of her sins, and that ye receive not of her plagues;
for her sins have reached unto heaven, and God hath remembered her iniquities:
and now is the one day dawning over the earth, wherein her plagues, mourning,
and famine come, and she shall be utterly burned with the fire of Gods jealousy;
for strong is the Lord God who judgeth her.
And now, in the name of the eternal, ever-living, blessed God, the Creator of all things,
I prophesy of the perpetual destruction and utter desolation of the religions,
inventions, ways, worships, prescriptions, orders, decrees and imitations,
that have been setting up these many hundreds of years, and not by the eternal,
living Power of the living God, nor by the directions,
leadings and guidings of his quickening Spirit of life,
that led and guided the Apostles in their day, age and generation: root and branch,
head and tail, and the whole fabric of the Babylonish building shall be utterly consumed,
razed down and confounded forever;
and all the worshippers of the beast and his image
shall drink of the wine of the wrath of God,
which is poured forth, without mixture, into the cup of his indignation;
and these worshippers shall be tormented, and have no rest night nor day,
who worship the beast and his image, and whosoever receive the mark of his name, etc.
