== Section 6. A Call, In the Tender Bowels of the Love of God, Shed Abroad in this Day, Age and Generation, Unto All the Scattered Sheep, etc.

Hearken and give ear, ye scattered ones, upon the barren mountains of profession,
who having lost the living sense that was on many of your spirits years ago,
and are now seeking the living amongst the dead professions,
and your bread in desolate places.
Remember the days, months and years past; call to mind the days of your tenderness,
when the Light of God so shined on your tabernacle,
that by it you saw yourselves in darkness,
and in separation from the enjoyment of your Creator;
which sense brought a day of mourning and bitter lamentation on you,
which was the cause of your fasting, praying, and earnest seeking after the Lord,
with multitude of sighs, groans and tears;
which caused you to put many days and times apart,
to meet together to pour forth your souls in seeking the living God,
for his appearance and breaking forth by his Eternal Power,
and for the revealings of his ancient arm and horn of salvation:
and in that day how did many of you retire yourselves into your closets and secret places,
to mourn before the Lord! and how did your cries, breathings and pantings after the Lord,
prevent the morning-watches!
And in that day was it not substance itself that you sought after,
even the revealings of the Son of Gods love in your souls?
Let me now come near, and expostulate with you in the name of the mighty God;
even with you, amongst all professions,
that have any tenderness or breathings after the Lord remaining in you.
What was it that stirred up your hearts, many years since, thus to seek after the Lord?
What was it that gave you the sense of your own inward conditions?
What was it that made sin appear exceeding sinful?
What was it that you felt in your minds that warred
against the law of sin and death in your members?
What was it that in some measure opened the eye of
your understanding to see idolatry and superstition?
What was it that was drawing your hearts out of the world,
that even made those things of light esteem,
in comparison of that which your awakened souls sought after?
What was it that inwardly upheld you in sufferings?
What was it that you retired your minds unto,
when the wicked raged as the waves of the sea;
when you were mocked for the plainness of your apparel
and for your strictness in your families?
Remember your many signal deliverances:
how did the Lord answer you in the day of your tenderness?
What was it that exercised you inwardly,
moving on every one of your particular souls and spirits for a reformation?
Was it not the free grace of God?
Was it not that Light which shined on your tabernacle?
Did not this shine in your hearts, and move on your spirits godwards,
and began the inward work of the Lord in you?
Why did you start aside from following on toward the Lord in the way of his judgments,
when a little prosperity attended you?
Why did you seek to get from under the judgment, before it was brought forth unto victory?
Be awakened and come back, you professors of all sorts,
that have thus turned aside for a thing of nought,
which has caused you to wander from one mountain of profession to another,
and from one exalted hill of imaginations and conceivings to another,
until you have spent all your portion, and are in nature returned to Babylon,
the city of confusion, out of which the Lord God Almighty thus calls you, hasten,
hasten to come forth, and partake no longer with her in her sins,
lest ye partake with her of her plagues, which are now hastening to come upon her,
and upon all that shall be found within her borders.

Open now your eyes, and behold where you missed and turned aside,
through which your foolish hearts have been and are darkened;
for the enemy that goes about as a roaring lion, seeking whom he may devour,
wrought in you to turn you from this pure, immortal principle of the Divine Being,
(that in the days months and years by past, awakened you,
and began to work the work of God in you,) whereof
the saints wrote and left on record behind them;
who attained thereunto, through passing from death to life,
in obedience to the grace of God that is given to every man to profit withal;
who knew the holy war, and fought the good fight, and so obtained the victory;
through the effectual workings of God they obtained it,
and not through mere notions upon the words of their brethren the prophets;
of which victory through faith and obedience unto, and in the Eternal Spirit of holiness,
they were made partakers.
And thus was it that they came to put off the old man, which indeed is a great work;
and to put on the new man, which is a real change and translation out of Satans kingdom,
and from under his power, into the kingdom of the dear Son of the living God,
and so to be under his power.
But the enemy of your souls turned you from this free grace of God,
(which was that which stirred in you,
and wrought in you in your day of tenderness,) by drawing
your minds up into an airy notional profession of this grace,
and +++[+++into the belief]
that by it you were saved;
not considering that the immortal souls of such lie in bondage,
whose faith stands in notions, and not in the power of God;
or whose faith is no other than a belief of what is done for them without,
not coming experimentally to know the work of God in themselves,
and the obedience of faith which purifies the conscience, and makes alive unto God.
And such was the soaring up into imaginations,
of some called gifted men for the ministry,
that they presumed to teach and hold forth the free grace of God after such a manner,
as that the understandings of many were confounded,
and thereby many were defiled and corrupted,
by admitting a liberty unto the fleshly nature, and avoiding the cross of Christ,
contrary to that holy liberty, which through the operation of the grace of God is known.
For though it is true, that, as the Apostle saith, by grace we are saved;
yet whosoever holds forth this grace, so as to raise a belief in any,
that they are thereby saved from condemnation,
whilst they are found transgressors against the righteous law of God; such, I say,
divide not the word of God aright,
but teach for doctrine the conceptions of their own brains.
For it is not a bare belief or assent of the mind, to the power of the grace,
which can give satisfaction to the immortal soul,
or true assurance of eternal peace with God;
but there must be also a conformity in the inward man, unto the power thereof;
and so man comes to be created in Christ Jesus unto good works,
to be sanctified throughout, both in body, soul and spirit.
And indeed, I have found,
that instead of preaching up conformity to the power of the grace,
they have not only preached up free grace, (which indeed is an expression, in itself,
proper enough to be held forth,
for that the grace of God is freely extended unto all,) but also therewith they have
preached up a justification of sinful and unsanctified persons by imputed righteousness;
even in such a manner,
as many have from thence concluded themselves in a state of salvation,
while sin has had its reign in their mortal bodies; which I cannot but testify,
is as great an error,
and as contrary to the gospel-ministration and the
end for which Christ was manifest in the flesh,
(which was, to save people from their sins,
so as to live no longer therein,) as the error of the Scribes and Pharisees was,
when they were seeking and believing justification by the works of the law,
without the righteousness of faith.

And thus has it been, that many have turned the grace of God into wantonness,
or turned from the grace of God into wantonness; so that in a little time,
how did many professors grow light and vain,
and run with the very profane into the same excess of riot;
and were lifted up in the flesh, and so came to be much in shew,
but little and light in the balance?
and here, you professors of all sorts,
that have gone from the spiritual appearance of Christ Jesus within,
into a profession of the saints conditions and performances,
without the leadings and guidings of the same Spirit and Power, lost your way,
and went out from your Guide, which would have led you up to the substance, Christ Jesus:
and thousands of ignorant people have been led here, through the cunning sleights of men,
into an empty profession; and when the manifestation of the Spirit of God,
which is given unto every man to profit withal,
hath stirred in the heart and soul to draw the mind out of the ways,
spirit and nature of the world,
then the transforming enemy of mankind has lain near to betray and deceive,
by pointing and directing people to run into this profession or the other,
or take up this outward performance or the other shadow,
under the specious pretence of the ordinances of God and Christ:
and hereby the subtle enemy,
that will admit of the peoples being in the outward practice of outward things,
whilst that he can have his place, seat and throne in the heart of mankind,
has led thousands aside out of the strait way of salvation,
through his drawing them from the true inward Guide,
the grace of God that brings salvation, that has appeared unto all men,
into the outward observations: and here the fear of thousands, towards God,
is taught by the precepts of men,
who know not the leadings and guidings of the Spirit and power of God;
and so have healed the hurt of the daughter of Zion deceitfully,
and have daubed with the untempered mortar.

And now, all you scattered ones upon the barren mountains of professions, give ear,
hear the counsel and call of the Lord: turn you, prodigals, who have spent your portions,
and lost much of your sincerity and tenderness,
and that secret enjoyment you had of the Lord inwardly, years ago,
and who for a long season have endeavoured to fill your bellies with husks,
and the profession of the saints enjoyments.
My heart yearns on you, and for you are my bowels turned:
my soul is often bowed down in the sense of your states; yea,
often my heart is pained within me,
when I behold your wanderings up and down from mountain to mountain,
seeking rest and finding none but what is polluted;
and your souls are lean for want of the fatness of Gods house,
and you have not the enjoyment of it.
My soul is even many times distressed for you, God that made heaven and earth,
bears me record, whom my soul cries unto, even night and day,
to visit you with an out-stretched arm.
Return, return, unto that which will shew you all that ever you have done,
and that will hasten you to the Fathers house, where the bread of life is;
and no longer spend your money, precious time, and labour,
for that which is not the bread of life, but a profession, a talk of bread,
which cannot truly satisfy your souls.

And now, in the name and authority, and by the motion of the Spirit of the Eternal God,
behold, I sound the trumpet of the Lord God Almighty in your ears; prepare, prepare,
to meet the Lord Jehovah in the valley of decision;
and all you who have any tenderness in your hearts,
and breathings inwardly after the Lord, amongst all professions,
of what name or denomination soever, come out, come out of Babylon, and be you separate;
touch not any longer the unclean thing, that the Lord may receive you,
who stands ready to receive all that come in truth and righteousness unto him;
who now will mark all that mourn because of the sins of the people, which are great,
and the measure thereof filling up apace; and the day and time is hastening,
of the pouring out of the vials of the unmixt fury and indignation of God,
who lives forever and ever.
And therefore flee, flee for your lives, out of Sodom`'s nature,
and stick not in the profession of things, neither the one nor the other,
whilst the ground of thy profession did not,
or doth not spring from the immediate work of God,
and daily operation of his Eternal Power in thy heart;
but come down into pure obedience to the pure still voice of the Spirit,
and gift of God in thy own heart and soul, which will, as thy inward ears are attentive,
direct thee in the narrow way of life eternal, in which thou shouldest walk;
so coming here, you come to that which moved in the hearts of many, years since,
godwards, which was that which wrought many into the tenderness before spoken of:
herein walk, and be faithful, and it will lead to the fountain of blessedness,
from which it came, and unto the horn of Gods Anointed:
and to Shiloh shall be the gathering of thousands through the nations, tongues,
languages and people; and the mountain of the Lords house shall be exalted,
through this great day of trial, tribulation and anguish,
upon the top of all the mountains.

So the Lord God Almighty, by the arm of strength,
reach all hearts that have any breathing, panting desires after Him,
amongst all professions, and pull many as brands out of the fire.
So breathes my soul,
who am a travailer for the universal visitation and deliverance of the seed of Jacob,
and raised up to prophesy of the things which shall come to pass,
and be fulfilled in their time and season.

Charles Marshall.
