== To the reader.

Be serious when you take in hand to read this treatise,
and have a single regard to the state of your immortal soul;
and let your spirit bow down to the measure of
the Spirit of God given you to profit withal,
that by it the eye of your understanding may be opened,
so will you see the things herein contained, which concern your own eternal welfare.
And let not your own thoughts and imaginations, in the wisdom from below,
which is sensual and earthly, be judge therein; but stand still,
out of your own comprehendings;
and let a true and diligent regard be had to the word in your heart and mouth,
placed there that you may obey it and do it;
so will your heart be truly opened to read with
delight the things opened by the Spirit of Truth,
which searches all things, yes, the deep things of God, and the travail in spirit,
which is for opening the eyes of the blind, and unstopping the ears of the deaf,
will be answered, and the Lord God Almighty will have his honor from his own workmanship,
and you the benefit; which is the desire and breathings of him,
who is a laborer for Zion's perfect deliverance.

[.signed-section-signature]
Charles Marshall

[.signed-section-context-close]
Bristol, the 2nd of the Seventh month, in the year 1673
