== Man`'s happy estate before the fall.

In the beginning God created the heaven and the earth;
and after he had made all things on the earth, he made man in his own image,
formed him of the dust of the ground, and breathed into him the breath of life,
and man became a living soul.
And the Lord planted a garden in Eden, and there he placed the man whom he had formed;
and out of the ground the Lord God made every tree pleasant to the sight,
and good for food, to grow; the tree of life also in the midst of the garden,
and the tree of knowledge of good and evil.
And he that made man in this estate, gave him a law to preserve him therein,
as the Scripture of Truth witnesses, saying, "`And the Lord God commanded the man,
saying, Of every tree in the garden you may freely eat;
but of the tree of knowledge of good and evil, you may not eat;
for in the day you eat thereof, you shall surely die.`"
Now God saw everything that he had made, and behold it was very good;
the tree of knowledge of good and evil was good, but not for food:
and man was endued with that Divine wisdom,
that when the Lord God brought every beast of the field and fowl of the air, to Adam,
he gave names unto them; and whatsoever Adam called every living creature,
that was the name thereof.
Man`'s station was in the image of God, a living soul, a noble plant, wholly a right seed,
filled with Divine wisdom and virtue, clothed with innocency and glory,
adorned with celestial beauty, in the continual enjoyment of the love and favor of God,
having his daily interaction with him that made him; no death, no darkness, no sorrow,
no occasion of tears, no transgression, no knowledge of evil,
dwelling in the innocent life itself, placed in the garden,
into which came the river out of Eden that watered it.
Oh blessed state!
Oh happy condition!
Oh inexpressible enjoyment, beauty and glory!
It is beyond the tongue of man to declare fully that blessed, happy estate of joy, peace,
holiness, righteousness and fruition of life,
which man was in before he transgressed the royal law of God.
