[.style-blurb]
== Man`'s Miserable State in the Fall.

But now he, who kept not his first habitation, neither abode in the Truth,
envied man`'s happiness in the Truth, and therefore, as a serpent,
more subtle than any beast of the field which the Lord God has made,
came to the woman and said, "`Has God said,
you shall not eat of every tree of the garden? The woman said.
We may eat of the fruit of the trees of the garden;
but of the fruit of the tree which is in the midst of the garden, God has said.
You shall not eat, neither shall you touch it, lest you die.`"
And the serpent said to the woman, "`You shall not surely die; for God does know,
that in the day you eat thereof, then your eyes shall be opened,
and you shall be as gods, knowing good and evil:`" and here the serpent got an entrance.
When the woman saw that the tree was good for food, and that it was pleasant to the eyes,
and a tree to be desired to make one wise, she took of the fruit, and did eat,
and gave also to her husband with her, and he did eat,
and the eyes of them both were opened.
Here the God of the world prevailed, so as to open an eye that saw evil pleasant,
and to blind the eye in these children of disobedience,
that they should no longer behold the glory of God.
And here they lost the robe of righteousness and garment of innocency;
and they heard the voice of the Lord God walking in the cool of the day,
and Adam and his wife hid themselves from the presence of the Lord God.
And the Lord God called unto Adam, saying, "`Where are you?`" And the man said,
"`I heard your voice in the garden, and I was afraid, because I was naked;
and I hid myself`" And the Lord God said,
"`Who told you that you were naked? Have you eaten of the tree whereof I
commanded you that you should not eat?`" He began to excuse himself,
saying, "`The woman you gave to be with me, she gave me of the tree, and I did eat.`"
And the Lord God said to the woman,
"`What is this that you have done?`" And the woman said, "`The serpent beguiled me,
and I did eat.`"
And the Lord God said unto the serpent, "`Because you have done this,
cursed are you above all cattle, and above every beast of the field;
on your belly shall you go, and dust shall you eat.
And I will put enmity between you and the woman, and between your seed and her seed;
it shall bruise your head, and you shall bruise his heel.`"
So the Lord sent man forth from the garden to till the ground,
and placed at the east of the garden of Eden, cherubim and a flaming sword,
which turned every way to keep the way of the tree of life.

Oh deplorable change!
Oh lamentable, undone condition, and inexpressible fall!
He that was in the image of the incorruptible Being, a living soul,
inhabiting the garden of the Lord, where the tree of life was,
and the glory of the Divine Being was known and enjoyed, driven from all into the earth,
and not only so but the cherubim and flaming sword, that turns every way,
placed to keep the way of the tree of life!
Be astonished oh heavens at this, and be horribly afraid oh earth!
The Lord God brought up children, and they rebelled against him.

Now, what was the cause and ground of this change,
that brought man into this deplorable state and condition? Was it not disobedience
to the righteous law of God? Did not sin enter into the world through disobedience,
and death by sin? And is not sin continued in the world through
disobedience? Is there any other way by which sin enters now,
than it did then, and death by sin, which has reigned,
and reigns over all who are in the fallen estate from God,
even over them that have not sinned according to the similitude of Adam`'s
transgression? For all have not sinned according to his similitude,
who was deceived with an expectation of a higher estate
than that in which the Lord God had placed him.
But all iniquity, of what kind soever, is one in the ground,
and separates man from his God.
So the ground of all iniquity and transgression,
is man`'s disobeying the righteous law of God, disobedience whereunto brings death.

But what was that which in Adam died? and what was the death; seeing that the Lord said,
"`In the day you eat of the tree, you shall surely die;`" and yet,
though he did eat thereof, he lived outwardly, and had children?

It was the inward man that died, which was so made by the living breath of the Almighty.
For man going out of the counsel of the Lord,
by his disobedience came to be alienated from the life of God,
and so became insensible of that life in which he was wholly a right seed,
and a noble plant.
In his degeneration he became inwardly dead;
the inward senses of the inward man were lost; the inward ear was stopped;
the inward eye was blinded; the inward sense of tasting how good the Lord is;
the inward feeling after his Divine virtue, who is all power, life, love and joy,
the inward sense of smelling, were all lost; and instead thereof, an ear opened,
that hearkened to the voice of the stranger; and an eye opened,
that saw the forbidden fruit pleasant and desirable; the heavenly clothing of innocency,
meekness and resignation was lost; and thus he came to be without God in the world.
In this state man was altogether out of a capacity of abiding in the garden,
or partaking of the heavenly tree of life, that was in the midst thereof;
and in this state are all the unconverted sons and daughters of men,
notwithstanding all fig-leaf coverings of professions.

But as the law of the spirit of life breaks forth in its manifestation,
and the sons and daughters of men come with it to be awakened,
they will have the sight and true sense of their inward state and condition,
which will indeed cause a cry to arise in the soul.
Oh wretched state!
Oh miserable condition!
Here the entrance of sin comes to be seen, which has brought death;
for the wages of sin is death, which was the death that came over Adam,
and over all since that have disobeyed the righteous spiritual law of God, which is just,
holy and good, and was before transgression, which law brings to Christ,
the promised Seed, the gift of God, which is eternal life.

Man being thus departed out of that nature,
image and seed in which he had his being before transgression,
is become the degenerate plant of a strange vine before the Lord God.
And from the sons and daughters of men,
as they stand joined to this nature and seed of the serpent,
which has defiled man in soul, body and spirit,
proceed the branches and fruits of iniquity.

Man having fallen into this miserable deplorable state,
God in his boundless lovingkindness,
has opened a way by which he might be restored up to himself again;
which way is the promised Seed, concerning whom he said to the serpent,
"`I will put enmity between you and the woman, and between your seed and her seed;
it shall bruise your head, and you shall bruise his heel.`"
Herein was the tender mercy of God extended unto mankind, in giving the Seed, that is,
Christ Jesus; else all would have been as Sodom, and like unto Gomorrah,
which God destroyed with fire in his wrath.
This is that one Seed, on whom he has laid help, who is mighty to save,
who is the image of the invisible God, the first-born of every creature,
in which image man was before the transgression,
who was glorified with the Father before the world began.
This is he of whom I give testimony, that he is the way of life and salvation;
and that there is no other name by which any man can be saved, than by him who was,
and is, and is to come; who was from everlasting to everlasting, the Rock of ages,
which followed Israel, and was in the church in the wilderness,
as Stephen testified before he was stoned to death.
This is he, who is without beginning of days, or end of life;
who in the fulness of time was manifest, taking on him not the nature of angels,
but the seed of Abraham, for whom there was a body prepared to do the will of his Father;
who, after he had accomplished it, ascended where he was before, far above all heavens,
that he might fill all.
This is the Emmanuel, God with us; Jesus, the Savior; Christ, the Anointed;
who has been called by several names, and spoken of under several appellations,
through the mouths of his servants the prophets
and apostles in ages and generations past:
this is the only beloved of the ransomed, and this is our friend.

And now he is arisen and arising, who is the Ancient of days, in the might of his power,
and is revealing the good old way and path of life,
whose out-goings have been from everlasting; in which way Abel, Seth, Enoch, Noah,
Abraham, Isaac, Jacob, and all the servants, prophets,
apostles and saints of the Most High God walked, through all ages and generations.
This way was before all the invented ways and worships,
which have been set up in the will and time of man; for all the holy men of God,
and saints of the Most High, worshipped God in the spirit of holiness,
in which they were accepted of him, who is the God of the spirits of all flesh;
and no outward performance was any farther acceptable unto the Lord,
but as performed in this spirit.
