[#restoration, short="The way of restoration"]
== The way of restoration out of the fall, into the image of God, in which man was before the fall.

But how salvation comes to be wrought by him,
and how mankind may be brought again into him, who is the Way, the Truth, and the Life,
and brought from under the power and dominion of the seed of the serpent,
in which by nature all have been the children of wrath,
is indeed the thing that lies on my spirit weightily to demonstrate,
having obtained mercy to see this way of life and salvation revealed and opened;
and not only so, but a necessity is upon me to preach the Gospel of Christ Jesus,
and declare the way of life and salvation to my countrymen,
through this island of England; and now a necessity is also upon my spirit,
to leave a testimony of the same on record.

This is generally confessed, that in the first Adam all died, and in the second Adam,
Christ the Lord, all come to be made alive again.
But how mankind come out of this state of death, in the first Adam,
into this state of life in the second Adam,
is that which the wisdom of this world never knew nor comprehended rightly.
Man by that wisdom has only imagined and conceived something
in the carnal mind concerning this great mystery,
and therein has set up many inventions of the way of life and salvation.
And into these many ways of man's invention and imagination,
set up in the fallen wisdom of man, there have been the several calls, Lo here, lo there;
but the day is dawned, and now breaking forth more and more;
magnified and praised be the name of Almighty God, wherein all invented ways,
set up in the will and wisdom of man, that is earthly, sensual and devilish,
shall come to an end.

And now, in the name of the mighty God, all the graven images, the work of men's hands,
and earthly wisdom shall be broken to pieces and ground to powder;
the mouth of the Lord of hosts has spoken it,
who will perform it by the might of his arm.

And therefore, tremble all you image-makers of all sorts,
who have been making likenesses of the way of life and salvation,
in your fallen wisdom and corrupt wills, and have made gods thereof,
and have bowed down to, and worshipped them; so that it may be said of Christendom,
so called, as it was once said of Israel, "`As are your cities, so are your gods,
O Israel!`"

But now is the fulness of time coming, wherein the ancient way of holiness,
in which the righteous walked, through all ages and generations,
is cast up and manifesting; which way is Christ Jesus,
the gift of the Father's love unto the sons and daughters of men, who has,
as before-mentioned, been declared of by his prophets and apostles,
under several appellations, according as he was pleased to manifest himself to them,
and as his Spirit gave them utterance.
Amongst many other appellations, he has been declared a Priest for ever,
after the order of Melchizedek; the Rock that followed Israel,
who was in the church in the wilderness; a King, a Lawgiver, Wonderful, Counsellor,
Prince of peace, a Branch, a Light to lighten the Gentiles; the Arm of God's salvation;
a Covenant, Messiah, a Leader, a Commander, a Captain; the Horn of God's anointed;
a Stone of stumbling; a Foundation laid in Zion; the Cornerstone; the Word of God;
the Word that was in the beginning; the True Light,
that enlightens every man that comes into the world; the Truth, the Way and the Life;
King of kings; Lord of lords; Christ; Emmanuel; Jesus;
the Beginning of the creation of God; the Firstborn of every creature;
the First-begotten from the dead; the Faithful Witness; Alpha and Omega;
Bright and Morning-star; the Image of the invisible God; the Offspring of David.
Under these and other names has he been spoken of,
who still has a name that no man knows but himself,
who is that one Eternal Fountain of blessedness, and the one precious Savior;
and there is no other besides him.

And now, by the power of the holy, everlasting God,
is he preached under the denomination of Light, in this island of the Gentiles,
according as was prophesied of old, by Isaiah, who said,
"`Is it a light thing that you should be my servant, to raise up the tribes of Jacob,
and to restore the preserved of Israel? I will also give you for a light to the Gentiles,
that you may be my salvation unto the ends of the earth;
`" which is one with the testimony of John,
saying, "`In the beginning was the Word, and the Word was with God; and the Word was God;
the same was in the beginning with God; all things were made by him,
and without him was not any thing made that was made; In him was life,
and the life +++[+++mark]
was the light of men; and the light shines in darkness,
and the darkness comprehends it not.`"
"`There was a man sent from God, whose name was John; the same came for a witness,
to bear witness of the light, that all through him might believe.
He was not that light, but was sent to bear witness of that light:
that was the true light, which enlightens every man that comes into the world.`"
And to this agrees the testimony of just Simeon, who came by the Spirit into the temple,
and took the child Jesus in his arms, and said, "`Lord,
now let your servant depart in peace, according to your word;
for mine eyes have seen your salvation,
which you have prepared before the face of all people, a light to lighten the Gentiles,
and the glory of your people Israel.`"
This is he of whom we testify, whose light is the way to life:
"`And this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil;
for everyone +++[+++mark]
that does evil hates the light, neither comes to the light,
lest his deeds should be reproved; but he that does Truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`"

Now this light, which the servants of the Most High testified of,
is that which has been spoken of under several names.
For this manifestation of God in man is sometimes called the Word, the Spirit, the Law,
the Grace of God; and the Word, Light, Grace, Law, Spirit, are all one in nature,
although diversely named.
Moses called it the Word, and directed to this Word in the heart and in the mouth;
which Paul, that illuminated man, rehearsing, says, "`Say not in your heart +++[+++mark]
who shall ascend into heaven, that is to bring Christ down from above,
or who shall descend into the deep, that is,
to bring Christ up from the dead;`" but what says it? "`The word is nigh you,
even in your mouth, and in your heart; that is, the word of faith that we preach.`"
This is the sure word of prophecy unto which Peter directs to take heed,
as unto a light that shines in a dark place, until the day dawn,
and the day-star arise in the heart.

This light is the law of the Spirit of life, wherewith Paul was acquainted,
that warred against the law of sin and death, which was in his members.
It is the law in the heart, and the spirit in the inward parts,
the new covenant of God Almighty; this is that which converts the soul,
which law Paul delighted in, according to the inward man;
of which the Scriptures of Truth plentifully testify.
This is that grace that Paul declared brings salvation;
which has in measures appeared to all men, as God's talents,
teaching all that are led and guided by it, to deny all ungodliness and worldly lusts;
and to live soberly, godly and righteously in this present world.
This is that grace which the Lord, the giver thereof, said to Paul,
was sufficient for him to deliver him from the temptation, the thorn in the flesh.
The same apostle said unto the Ephesians, "`By grace you are saved,`" etc.
And this is the manifestation of the Spirit, which is given to every man to profit withal.
This is that good Spirit of the Lord given to Israel, who rebelled against it,
as the old world did, unto whom the Lord said,
"`My Spirit shall not always strive with man;`" this is given
to be the leader and guide of mankind out of sin and death,
and darkness, into which man fell through disobeying the righteous law of God,
as the holy Scriptures give clear and full testimony.
But now, that which is ready to arise, as an objection in some,
whose understandings are not opened, and whose searchings to comprehend,
and inquiries after the way of man's salvation stand in that wisdom that is from below,
and in the will and reason of man degenerated from the life of God, is,
whether the preaching up this Spirit and grace of God manifest within,
has not a tendency to make Christ Jesus' appearance in the flesh, his sufferings, death,
resurrection and ascension to be invalid? Unto which I answer, no;
for no persons ever did, or can truly discern,
or enjoy the benefit of Christ Jesus' manifestation in the flesh,
but as their hearts are opened, and their understandings illuminated by the light,
which is a measure of the Divine fulness that dwelt in him,
and is communicated to the immortal soul, as the universal love of God,
extended in the Son of his love to all the families of the earth,
as the revealer and discoverer of the will of him from whose Divine fulness it comes;
for the Scripture thus witnesses, that "`No man knows the things of a man,
save the spirit of a man which is in him;
even so the things of God knows no man but the Spirit of God.`"

The hearts of the Jews not being seasoned with this grace of God,
and ignorant of the gift of God, which is eternal life, they neither discerned,
loved nor received Christ Jesus, when manifested in that outward bodily appearance,
but rejected him; notwithstanding they professed honor and regard to the prophets,
and were in expectation of the fulfilling of
their prophecies of the coming of the Messiah,
who in due time came, and yet they did not receive him,
but instead thereof set themselves against him,
taking counsel from time to time how they might slay him,
though in words they professed an earnest waiting for him.
So in this day, there are many,
who by their words do profess they believe his coming in the flesh and his sufferings,
death, resurrection and ascension; but yet, their faith consisting in outward notions,
and having no inward experience of the end of his coming,
nor of the virtue of his sufferings, death, resurrection, etc.,
they are enemies in their minds to his second appearance and coming,
without sin unto salvation.
So there is a necessity for all men to come to, and obey this Divine spiritual Seed,
which is placed in their consciences by the living God,
that thereby the eye may be opened, which through disobedience,
has been blinded by the god of the world; for, until this in some measure be effected,
the mystery of godliness, which is great, can neither be seen nor understood.
Therefore Christ said, finding the woman of Samaria ignorant of himself,
who was and is that great mystery, and the gift of the Father's love,
"`If you knew the gift of God, and who it is that says unto you, give me to drink,
you would have asked of him, and he would have given you living water.`"

The travail in spirit of the messengers and servants of the Most High in ages past,
was the same as it is now, namely: "`To turn people from darkness to light,
and from the power of satan to the power of the living God;`" thereby in no
wise invalidating Christ Jesus his manifestation in that bodily appearance,
neither his sufferings, death, resurrection nor ascension; but it brings all people,
guided thereby, unto that which will open the eyes of their understandings,
whereby they come to such a condition and spiritual understanding,
as to see and know their benefit by that appearance of the Savior of the world;
for this we testify, by that one Offering all are perfected that are sanctified.
But here arises another objection by some,
who may come so far as to own and confess that there is a Seed or light in man,
that discovers sin, and teaches man to do justly and equally, which some call morality,
but that this light or Seed in man is of a saving property,
and of the nature and quality of the Divine Being,
many for lack of understanding do deny, and so are found opposers of Truth itself,
and stumble at the Corner-stone,
which indeed in ail generations has been to many
men a stone of stumbling and rock of offense,
which thousands, giving themselves up to be guided by their own wisdom and prudence,
reject; yes, those accounted the wise master-builders, professors of God and Christ,
being ignorant of the root and offspring of David, reject this Corner-stone.

Now, for the sake of all who desire the true and saving knowledge of Christ Jesus,
it is on my spirit yet further to open the nature and property of this Seed and light;
whose fountain is the Eternal Being and everlasting ocean of Divine fulness,
and its nature and quality is one with this Fountain from which it comes.
John testified, "`In the beginning was the Word, and the Word was with God,`" etc.
"`In him was life, and the life was the light of men.`"
He also testified, that he was not that light, but came for a witness, to bear witness,
that that was the true light, which enlightens every man that comes into the world:
so the original of this light, is Christ Jesus, the Word.
But some may query thus.
Is Christ the light in every man?

To which I answer, Christ does appear by his light in every man;
and the light which comes from Christ, is in every man:
as is clearly demonstrated from the Scriptures of Truth.
And, though I account it unnecessary to answer the curious inquiries of such,
who seeking to know much, do not walk answerable to what they know;
yet for the sake of such, whose understandings are not opened,
and yet are inquiring the way to Zion, I add this similitude:
The natural sun is placed by the Creator to lighten the outward world,
and does extend from its body a measure of its light and natural property,
shining on the just and the unjust,
and so does daily give forth of that virtue which is inherent in itself.
When the sun shines on any object whatsoever, we sometimes say, the sun there appears;
and other times we say, there is the sun; the propriety of either of which expressions,
I suppose none will question; for light in that appearance is seen, and virtue is felt,
penetrating to the refreshment of our natural bodies;
and this light and heat are inseparable from the fulness;
and notwithstanding it daily shines and displays its virtuous life into,
and over all the earth and its inhabitants;
yet its body is not any way exhausted or altered through ages and generations.
And so, I say, that Christ, the universal fountain of life, the Sun of righteousness,
the ocean and fulness of spiritual light, life and virtue,
from whom is communicated a measure of his nature, property and quality,
is given of the Father, to enlighten all the sons and daughters of men,
who accordingly are all enlightened with his spiritual appearance;
and though this appearance cannot be called the fulness,
yet being a measure of that fulness, it is one in nature and property with,
and inseparable from the fulness.
And though through its virtue, life is daily communicated unto the sons of men,
who wait for the appearance thereof, as for the morning light,
and cannot live unto God without it, yet does he admit of no diminution or change;
but all fulness of Divine light, life and glory, does and shall,
through every age and generation, remain with him.
And although the veil of darkness has overshadowed the hearts of some,
so that when we give testimony to the universal appearance of the Sun
of righteousness in the hearts of all the sons and daughters of men,
they are ready to say,
such a testimony leads to the diminishing of that glory and honor which belongs unto him,
as he is the fulness, and sitting at the right hand of the Father; inferring, as if,
while we testify to his appearance in our hearts, we exclude his presence elsewhere.
Yet this inference is as irrational as it would be for any to conclude,
that because we say of the shining and appearance of the sun, there is the sun;
or the sun there appears; therefore we exclude the being of the sun elsewhere.
For its virtue is communicated to our natural bodies,
everyone having in measure some enjoyment of the virtue or light of the natural sun,
which is light to the eye of the natural body;
and those whose spiritual senses are quickened by the virtue
which proceeds from the eternal Sun of righteousness,
do thereby discern that these things are according to
the clear manifestation of Truth in their inward parts;
and from a sense thereof, can of a truth give this testimony, that Christ, the Lord,
by his holy quickening Spirit, has appeared in them,
to the quickening of their immortal souls; and that through believing in the light,
and obedience to his appearance,
being come out of that state which is reprobated by the Lord,
they can of certain experimental knowledge say, Christ is in us, the hope of glory.

And so, when we direct people to this Word, Light, Law, Grace and Spirit,
we do not thereby intend, that Christ Jesus, the light of the world and gift of God,
is not the true Savior, Redeemer and Reconciler of mankind unto God.

Now this light and spirit, does lead the souls of all such as obey it, up to God,
the fountain, from whom it comes; and no man sees its nature, but they who are led by it;
for in the light of the Lord alone man comes to see light, and to have an understanding.
Before this be fully seen or understood, the mind of man must be brought down,
out of all its own willings and runnings, comprehendings and searchings, to the light,
therein to see a death to his own will, and be comprehended in this light;
and so man comes to have an understanding to know him that is true,
and to be in him that is true.

Now, as any are convinced and converted by this heavenly Seed,
which is placed in the conscience, to be a guide and leader to mankind,
they are led out of darkness, wherein they have been,
while yet the light shone in darkness,
in which darkness no man ever comprehended this light or heavenly grace.
It sometimes moves through the darkness, on man's understanding,
reproving and discovering the darkness, and causing man to hear its small still voice;
and so daily continues reproving man while he remains in rebellion and disobedience,
all the time of his visitation, and approving and giving peace to man,
when he is obedient.

Although man may change and go from it, and rebel against it,
and thereby become one of them of whom Job speaks, that rebel against the light,
and thereby know not the way of it; but give way to the working of the god of the world,
to be drawn out into fading, perishing things; yet it remains immutable in itself,
being of and from the unchangeable Being,
and remains with man until it be taken from him, and he be cast into utter darkness.

The first operation of this heavenly light, in those who are convinced by,
and turned to it, the gift of the Father, which Christ Jesus, in his parable to the Jews,
compared to a grain of mustard-seed, and to a little leaven,
which a woman took and hid in three measures of meal,
until the whole came to be leavened, is to show man his inward state and condition.
The first step in the way of life is, to be turned to this holy Seed,
that teaches the obedient to know God savingly;
and when man comes to have a true sense of his fallen estate,
and sees how he has transgressed against that
eternal Being that gave him life and breath,
who waits long to be gracious, and knocks at the door of the heart,
and has striven by his Divine light, the sense hereof will break the heart,
and tender the spirit before the Lord.
And under the weight of the great burden of sin and iniquity, there will be a crying out,
My sins they are too heavy for me to bear, and mine iniquities are gone over mine head;
saying, as Paul did,
"`Oh wretched man that I am! who shall deliver me from the body of
this death?`" Here the eye comes to be opened that sees him,
whom man in his disobedience has pierced afresh and put to open shame;
and then there will be days of mourning and wailing, because of him;
and this is truly the day of Jacob's trouble.
In the sense of this deplorable fallen estate, and the long-suffering of the Lord,
and the long-striving of his Spirit, you will see, that in the justice of God,
eternal death might be your portion; but that which brings into this sense,
begets a secret cry in the soul, after a Deliverer and Savior,
and will also give a true sight, that there is no way for your soul to be ransomed,
but in and through the tender mercies of the Lord Jesus Christ;
which you will see can no other way be effectually begun in you,
but in the way of the judgments of the Lord;
for it is through judgment that Zion is redeemed, and her converts with righteousness.
And here also you will see that the measure of the sufferings
of Christ yet behind must be filled up in you;
for no other way can any man pass unto life, peace and joy, with the Father of spirits,
but the way the Captain of salvation passed, which was through death;
and here you will begin to arm yourself with the same mind.
For none cease from sin any further than as they suffer in the
flesh the crucifying of the affections and lusts thereof;
and here the end of the Gospel's preaching comes to be known and witnessed, which is,
that all men might be judged as men in the flesh,
that so they might live according to God in the spirit.
And in this inward exercise, the Lord God Almighty will bow down his ear,
and answer the cries of your awakened soul, and manifest his word of power,
which all in this state will know to be sharper than any two-edged sword, piercing,
to the dividing asunder of your immortal soul,
from the spirit and nature of transgression and its daily working,
as subjection and obedience are yielded unto it,
making a separation between joints and marrow,
and giving you a discerning of the thoughts and intents of your heart.

As the soul gives up in love to God, freely to follow him in the way of his judgments,
and gives up to the sword of the Lord, that which is for the sword,
and that which is for destruction, to be destroyed,
the precious work of the Lord will prosper.
And although this be a time of sorrow, of trouble and anguish, yet it is a good day.
Therefore strive not to get from under it, neither to make haste;
for the true godly sorrow works the true repentance, which is never to be repented of.
After the true repentance, follows the true knowledge of remission and forgiveness;
and so your iniquities, by the judgments of the Lord, come to be blotted out;
and then the times of refreshment come from the presence of the Lord,
and from the glory of his power.

As there is a faithful abiding in inward watchfulness,
and continual obedience to this heavenly light,
in which the beginning of the work of God was known,
there will be a going on from step to step in the footsteps of the flock of Christ Jesus,
and a growing from strength to strength, over sin and the nature thereof,
and from one degree of grace to another; and the eye of the understanding will be single;
and here every thing which does let, will be seen,
and the soul will not start aside from an inward travail,
until that which hinders be taken out of the way,
and until all the rule and authority of the enemy be
subdued under the feel of the Lord's anointed,
and the government in the soul be upon his shoulders,
whose right it is to reign over all.

And here salvation, redemption and restoration is effectually enjoyed,
through faith and the effectual working of the Almighty power of God,
unto whom be the glory of his own work for ever;
and here will be a growing and increasing,
until there is a coming into that precious state and image,
in which man was before he fell.
