[#snares, short="The Snares of the Enemy Discovered"]
== The By-paths, Crooked Ways, Wiles and Snares of the Enemy Discovered

Now when the mind is turned to this Divine heavenly Seed,
and the work of the Lord is begun,
the same destroyer that brought man into bondage at first, and has kept him in bondage,
will begin to work cunningly, and endeavor to destroy the work of God begun in the soul;
and that he may accomplish his end, he will go about every way, seeking an entrance,
and will lay his temptations suitable to the propensity or inclinations of the creature.

If the heart be bowed under a weighty sense of iniquity and many transgressions,
through which sorrow and bitterness is great, the enemy will work in his transformings,
and in appearance like the light, yet in nature contrary thereto.
For, though the light gives the certain understanding of the inward state,
and brings sorrow because of sin, and shows the mountain of iniquity,
yet it begets a secret hope of overcoming by the Lord`'s strength.

But when the enemy sees the soul bowed down,
he often afflicts and brings it into unbelief of ever overcoming,
thereby endeavoring to sink it into despair; knowing, if he overcomes,
he still keeps under his power, although in another appearance.
But all who are thus exercised, waiting on the Lord singly,
with the mind stayed in the light, will discover this snare; for, as I said,
although the true appearance of God`'s heavenly light and grace brings a day of trouble,
sorrow and anguish, yet that sorrow is not a sorrow without hope;
but the enemy`'s working is to bring into a sorrow without hope,
and to draw down the spirit into the chambers of darkness.

When the enemy is discovered in this,
and the soul through the love and power of God is comforted and refreshed,
and raised up in a measure of living hope,
then he endeavors to lead from the inward daily travail,
that judgment may not be brought forth into victory;
and so draw the mind into a false persuasion of obedience and diligence,
when there is not an abiding in that which gives a true sense of its state.
And as he would have before destroyed the hope that is an anchor sure and steadfast,
so now he would beget a false hope and confidence, and bring out of the daily cross,
through which the nature that has alienated from God, should be destroyed.

If the enemy be seen and overcome in both these snares,
and the work prospers even until much be subjected,
and through daily obedience to the heavenly power, much is slain,
and the heart comes in good measure to be cleansed,
and a good progress is made through the administration of condemnation,
that is glorious in its time;
and something of pure peace and heavenly joy arises in the heart;
here again the enemy will be subtly at work, to betray, in persuading to sit down now,
as if all were done; and thus lead from feeding on the tree of life,
to feed on the tree of knowledge of good and evil,
and to break the commandment of the Lord.
At first he subtly draws the mind out to take a little liberty,
and from that diligent watchfulness and fear it was in before.
And if he can but prevail he will lead out of the innocent life,
and by degrees open an eye that may see something in
outward things that may affect the mind;
and as he prevails gradually and hiddenly, the eye that was opened comes again,
through disobedience, to be in some measure blinded; and here loss is sustained,
even before the unwatchful is aware.
And the working of the enemy is first,
to cause such to make shipwreck of faith in a little measure;
that is not to have the daily belief to stand in the power; the daily enjoyment of which,
coming to be left by degrees, there will then be a turning from the power of godliness,
into the form thereof.
And although at times the power of the Lord may be felt in this state,
yet there not being a daily feeling after it, the enjoyment thereof,
as to true refreshment and consolation, is lost, and an image comes up in its place;
and the enemy presents some objects to take up the mind,
so that by degrees he may enter and defile it, and draw it from its true guide,
so as to make shipwreck of a good conscience.

If the enemy be discovered before he can so effect his work,
as to bring death and darkness over again, and the power of the Lord breaks his snares,
and gives a true sense thereof, through which trouble and anguish of spirit comes,
here he will again transform and work as in the beginning,
like the condemning power of the Lord,
endeavoring to lead the mind into despair of ever recovering its former condition;
and to draw it to look at him that has stung, that so the remedy,
the soul-ransoming power of the Lord, may not be felt after, nor looked at.
But as there is a true regard to the Lord,
and a waiting upon him in the way of his judgments,
having the faith and confidence to stand in his power, the backsliding will be healed;
and returning and diligently keeping in the light,
the power of the Lord God will work over that which has
endeavored like a roaring lion to destroy,
and so lead on in the way again.

But when deliverance is known from this deadly snare,
and the work again goes on prosperously until the house be swept and garnished,
and there is a passing from death unto life,
and the ministration of condemnation being gone through,
and the spirit that ruled in the disobedient state cast out,
and the openings of that which does exceed in glory, the administration of the Spirit,
is known; the enemy will again transform himself as an angel of light,
and with all his power and strength,
work by temptation on the right hand and on the left.
For when there are openings to the understanding, and prophecies,
and through the working of the eternal power joy springs in the heart,
then the enemy will work secretly, to draw the mind out of the valley of humility;
and if he prevail he will endeavor to lead into extremes,
thereby to destroy the true birth, which is bringing forth, and so bewilder the mind,
and hurry it through imaginary notions, to dishonor the name of the living God,
and to destroy his work, which through sorrow and travail has been brought forth.

If he cannot prevail here, but the light of the Lord discovers him,
then will he be at work, to draw the mind from watchfulness and daily fear,
and the liberty of the sons of God, which liberty is only to serve the Lord.
For dominion being felt in some measure, comfort and consolation enjoyed,
and praises raised in the heart to him that has visited and redeemed,
the enemy will be ready to draw the mind out of the stayed
estate of meek and constant watchfulness in the light,
thereby causing the creature prodigally to spend the portion,
and to lavish out the enjoyment by running before the
leadings and movings of the power of the Lord,
to speak of the enjoyment, the prophecyings and openings,
not being led thereto by that power that first opened the heart;
and here is an untimely birth brought forth, that will wither and come to nothing.

Where the enemy cannot prevail by these snares and temptations, he will not cease,
"`who goes about as a roaring lion,
seeking whom he may devour,`" and how he may again get entrance;
but lays his temptations according to the spirit, growth,
capacities and inclinations of everyone.
After the good work of God has been begun,
and the arm of his salvation has been wonderfully revealed,
to bring out of Egypt`'s darkness spiritually,
and has given many signal deliverances from the destroying enemy,
and has often fed with the heavenly food,
and caused the rock to yield water for the thirsty,
and many turnings aside in the passage through the wilderness have been seen,
the backslidings from a sense of the eternal power, have been discovered,
and that there is a coming through the river of judgment,
and the mighty power of God drives out the enemy that has inhabited,
where only Abraham`'s Seed is to inhabit, and the war in great measure ceases,
and part of the good land is possessed and enjoyed,
even the land that flows with spiritual milk and honey,
and the fruit of the vine drunk of; here also will the crooked, subtle enemy be working,
as he did with outward Israel, causing Jeshurun to wax fat,
and then kick against the power,
leading the mind through the enjoyment of that which in its place is good, into ease,
and to forget the Lord that formed man, and brought him into the land of rest,
and lightly to esteem the Rock of salvation.
Thus he leads the mind into a state of ease, and from the inward enjoyment of virtue,
to set up idols in the heart, and to serve gods of silver and gold,
and a profession without life and possession.
And into this condition the old enemy prevailed to lead a people,
who in many ages had seen the mighty works of the Lord,
and his arm stretched out and magnified in the sight of their enemies for them;
nevertheless, they departed from the Lord, and from the inward sense of his power.
Now the spirit that was cast out, and wandered in dry places,
takes to it seven worse spirits, and returns, tempts, prevails and enters,
and the latter end is worse than the beginning.
For in the beginning, although the enemy had his power and rule,
yet there was a sense thereof, and the heart was humbled, tender,
and brought into true poverty,
and there was a mourning before the Lord for lack of the dominion;
and this state of humiliation and brokenness of heart, in which the Lord takes delight,
in his boundless loving- kindness he visited and caused his redeeming,
saving power to be revealed.
But now in this other estate, the mind is high, the heart fat and full, and at ease,
and gone into the love of the world and the things thereof,
through which there is an unmindfulness of the Lord,
who in the beginning was every day sought after, and diligently waited for; and the Rock,
the Power, is lightly esteemed; for the estimation is of another thing.
Here two great evils are committed at once, namely:
The fountain of living mercies is forsaken, and broken cisterns hewn out,
even a profession, that will hold no water, no durable refreshment, no durable joy,
no durable peace nor consolation.

The enemy has thus prevailed through many ages,
to bring thousands from their enjoyment of God in the pure,
tender and upright-spirited state, which he effects through his workings and subtlety,
and that gradually.
His first step hereunto is, to bring out of the constant, daily watchfulness,
and causing a little liberty to be taken to the carnal mind,
and as it were imperceptibly, a certain enjoyment of sweetness therein,
whereby a darkening of the sight comes over the mind,
and so they are allured into more liberty.
Sometimes his beginnings are to draw out of obedience in those
things that were required in the day of small things;
sometimes into many words,
no more to be as a "`door-keeper in the house of the Lord,`" and so
the enemy works to cause such things to seem small and indifferent,
and thereby cause the offense of the cross to cease.
Then the mind runs forth to make provision for the flesh to fulfill the lust thereof,
either in meats, drinks, apparel, or such like,
which the Truth in time past had made manifest, and the power of God,
the cross of Christ, had crossed, and in measure lead out of,
into watchfulness and pure fear, not making provision for the flesh in any respect,
to fulfill the lusts thereof; but drawing in practice, as well as in principle,
into plainness, and out of all superfluities, admitting the creature to refresh nature,
but not to feed the lusts.

But yet the enemy works by degrees,
subtly and covertly to lead out of the liberty of the cross of Christ Jesus,
the power of God unto salvation, into the liberty of the flesh,
and hereby gets a farther entrance; working to draw the mind into many words in dealing,
in commerce or converse, and into the love of the world,
and though many times the power of God may be felt in some measure,
to draw out of the snare,
yet the god of this world having by this time much blinded the eye,
and darkened the understanding,
there is not a sense of the power of the Lord in its workings,
nor of the subtlety of the enemy.
For the outward profession and conformity may be in a great measure kept to,
under which the enemy may work undiscovered by the unwatchful, and so step by step,
lead out of the power of godliness, until he has slain the birth,
which in the first days of tender visitation was begotten.
Now there will be a growing high,
and such will call the operation of God`'s power extremes and imaginations,
and Jeshurun-like, will kick, and turn against the power of God,
for such are best contented with a likeness and image.
Such love smooth things in the wisdom of the gifted man, that has lost his way,
through erring from the power, not waiting on all occasions to be guided thereby.
So here is the itching ear, and heaping up teachers to please self,
and Jezebel is upheld; which error crept into the church of Thyatira;
and in all ages they that went from the broken, tender estate,
into the conditions before discovered, allowed and nurtured this Jezebel,
who must be cast on the bed of torments, and all her children killed with death.
All the working of the enemy, under every guise, is to slay that which was quickened,
and to bring in a contentedness with an outside profession of the way of the Truth,
light and life of Christ Jesus, the power of God unto salvation,
while the heart has gone from the Lord, and embraced other lovers.
Where the enemy thus prevails, in process of time he leads again into the world,
from where the arm of the Lord gathered;
and the latter end of such is worse than the beginning.
For having made shipwreck of faith and of a good conscience, the second death comes over,
and such become twice dead, and as salt which has lost its savor,
and are good for nothing, but to be cast forth, and trodden under foot of men.
The preservation out of these by-paths, crooked ways, wiles,
snares and temptations of the enemy,
is only in the true waiting and sincere abiding in the light, gift and grace of God,
in which the daily revelations and manifestations of God`'s eternal power are known,
and preservation in the daily acquaintance and experience thereof,
which keep all truly low and tender,
wherein arises an inward breathing and panting after the daily enjoyment of the life,
power, and blessed refreshing virtue,
which alone renew and increase the strength of the inward man;
in which God Almighty preserve all the travelers Zionward to the end.
