[#destruction, short="The destruction of false professions"]
== The utter end, and final destruction of all false professions, which have had their rise in the night of apostasy

After the glorious breaking forth of the day of God amongst the apostles,
the enemy wrought mightily against that appearance, both in his instruments,
by whom he raised up persecution, and by those apostates, in whom he got an entrance,
amongst the churches, and so prevailed,
that a great night of darkness and apostasy has been
some hundred of years over the nations of the earth;
in which the old subtle serpent, in his many transformings, wrought mightily,
to alienate man from God.
Oh! the ways and inventions that have been set up in the wisdom which is from below,
which is earthly, sensual and devilish, under pretense of religion, obedience,
and the worship of God!
What rending, devouring, murdering and destroying,
has there been for many hundred years about religion? First,
the great dragon of persecution appeared to devour the man-child, and destroy the woman,
but both were preserved; then he made war with the remnant of her seed;
and after came in another appearance, which John saw rise as a beast out of the sea,
which had several heads and ten horns; and on his horns, crowns; and upon his heads,
the name of blasphemy; and one of his heads had a deadly wound by the sword,
but this deadly wound was healed; and all the world wondered after the beast, saying.
Who is like the beast? And who is able to make war with
him? And all on the earth worshipped the beast,
whose names are not written in the book of life of the
Lamb slain from the foundation of the world.
And after this, a second beast appeared, that came out of the earth;
and this beast had two horns like a lamb, but spake like a dragon:
And John saw that he exercised all the power of the first beast,
which received his power and authority from the dragon,
like unto which this second beast spake, and caused the earth,
and them that dwelt therein, to worship the first beast, whose deadly wound was healed;
and he caused all, both small and great, rich and poor, free and bond,
to receive a mark in their right hand, or in their foreheads.
And here the power and spirit of darkness has exalted himself,
sitting in the temple of God, as god and ruler.
But, blessed for ever be the name of God,
the great red dragon and the beast that arose out of the sea,
and the beast that arose out of the earth, and Mystery Babylon,
are and shall be manifest.
The wisdom that is pure and peaceable, numbers these appearances;
and judgment is come and coming upon Mystery Babylon;
for now the angel of God`'s presence is come down from heaven, having great power,
who lightens the earth with his glory, and the cry is now going over the earth,
"`Babylon the great is fallen, is fallen, and become the habitation of devils.`"
All nations have drunk of the wine of the wrath of her abominations,
and the merchants of the earth have waxed rich, through the abundance of her delicacies;
"`Come out of her, my people, that you be not partakers of her sins,
and that you partake not of her plagues; for her sins have reached unto heaven,
and God has remembered her iniquities.`"
The day is dawning wherein her plagues, mourning and famine will come,
and she shall be burned with the fire of God`'s jealousy,
for strong is the Lord God who judges her.
And now I- prophesy of the perpetual destruction of the religions, inventions, ways,
worships, prescriptions, orders, decrees and imitations,
that have been setting up these many hundreds of years,
but not by the power of the living God,
nor the directions and leadings of his quickening spirit,
that led and guided the apostles in their day.
The whole fabric of the Babylonish building shall be consumed,
and all the worshippers of the beast and his image,
shall drink of the wine of the wrath of God, which is poured forth, without mixture,
into the cup of his indignation; and these worshippers shall be tormented,
and have no rest night nor day, who worship the beast and his image,
and whosoever receive the mark of his name.
