[.style-blurb, short="A Call to the Scattered Sheep"]
== A Call in the Love of God, to All the Scattered Sheep.

Hearken and give ear, you scattered ones, upon the barren mountains of profession,
who having lost the living sense that was on many of your spirits years ago,
are now seeking the living among the dead professions,
and your bread in desolate places: Remember the years past;
call to mind the days of your tenderness,
when the light of God so shined on your tabernacle,
that by it you saw yourselves in darkness,
and in separation from the enjoyment of your Creator;
which sense brought a day of mourning and bitter lamentation on you,
and was the cause of your fasting, praying, and earnest seeking after the Lord,
with sighs and tears.
This caused you to set many times to meet together to
pour forth your souls in seeking the living God,
for his breaking forth by his eternal power,
and for the revealing of his arm of salvation.
In that day how did many of you retire into your closets and secret places,
to mourn be fore the Lord? How did your cries and pantings after the Lord,
prevent the morning watches? And in that day,
was it not the substance itself that you sought after,
even the revealing of the Son of God`'s love in your souls? Let
me expostulate with you in the name of the mighty God,
even with you, among all professions,
that have any tenderness or breathings after the Lord remaining in you.
What was it that stirred up your hearts, many years since,
thus to seek after the Lord? that gave you the sense of your own inward
conditions? and that made sin appear exceeding sinful? What was it you felt
in your minds that warred against the law of sin and death in your members?
that in some measure opened the eye of your understanding to see idolatry
and superstition? that drew your hearts out of the world,
and made those things of light esteem,
in comparison of that which your awakened souls sought after? What was it
that inwardly upheld you in sufferings? that your minds retired unto,
when the wicked raged as the waves of the sea,
when you were mocked for the plainness of your apparel,
and for your strictness in your families? Remember your many signal deliverances.
How did the Lord answer you in the day of your
tenderness? What was it that exercised you,
moving on your spirits for a reformation? Was it not the free grace of God? Was it
not that light which shined on your tabernacle? Did not this shine in your hearts,
and move your spirits Godwards,
and began the work of the Lord in you? Why did you start aside
from following on to know the Lord in the way of his judgments,
when a little prosperity attended you? Why did you seek to get from under the judgment,
before it was brought forth into victory? Be awakened, and come back,
you that have thus turned aside for a thing of nought,
and wandered from one mountain of profession and of imagination to another,
until you have spent all your portion, and are in nature returned to Babylon,
the city of confusion, out of which the Lord thus calls you; "`Hasten,
hasten to come forth, and partake no longer with her in her sins,
lest you partake with her in her plagues, which are hastening to come upon her,
and upon all that shall be found within her borders.`"
Open your eyes, and behold where you turned aside,
through which your foolish hearts are darkened.
For the enemy that "`goes about as a roaring lion,
seeking whom he may devour,`" wrought in you to
turn you from this Divine Seed that awakened you,
and began to work the work of God in you,
into a profession of the words and conditions whereof the saints wrote,
who attained thereto, through passing from death to life,
in obedience to the grace of God, that is given to every man to profit withal,
who knew the holy, war, and fought the good fight, and so obtained the victory.
Through its effectual workings they obtained it, and not through mere notions,
upon the words of their brethren the prophets; of which victory,
through faith and obedience unto, and in, the eternal spirit of holiness,
they were made partakers.

Thus it was they came to put off the old man, which is indeed a work,
and to put on the new man, which is a real change and translation out of Satan`'s kingdom,
and from under his power, into the kingdom of the dear Son of the living God,
and so to be under his power.
But the enemy of your souls turned you from this free grace of God,
which wrought in you in your day of tenderness.
by drawing your minds into an airy notional profession of this grace,
and that by it you were saved;
not considering that the immortal souls of such lie in bondage,
whose faith stands in notions, and not in the power of God;
or whose faith is no other than a belief of what is done for them without,
not coming experimentally to know the work of God in themselves,
and the obedience of faith which purifies the conscience, and makes alive unto God.
And such was the soaring into imagination, of some called gifted men for the ministry,
that they presumed to teach and hold forth the free grace of God after such a manner,
that the understandings of many were confounded, and thereby defiled and corrupted,
by admitting a liberty to the fleshly nature, and avoiding the cross of Christ,
contrary to that holy liberty, which through the operation of the grace of God is known.
For though it is true, as the apostle says,
"`By grace we are saved;`" yet whosoever holds forth this grace,
so as to raise a belief in any, that they are thereby saved from condemnation,
while they are found transgressors against the righteous law of God; such, I say,
divide not the word of God aright, but teach for doctrine,
the conceptions of their own brain.
For it is not a bare belief or assent of the mind, to the power of the grace,
that can give satisfaction to the immortal soul,
or true assurance of eternal peace with God;
but there must be also a conformity in the inward man, to the power thereof;
and so man comes to be created in Christ Jesus unto good works,
to be sanctified throughout, both in body, soul and spirit.
And I have found, that instead of preaching up conformity to the power of the grace,
they have not only preached up free grace, which indeed is an expression in itself,
proper enough to be held forth, for the grace of God is freely extended unto all,
but also therewith they have preached up a
justification of sinful and unsanctified persons,
by imputed righteousness; even in such a manner, as many have, from there,
concluded themselves in a state of salvation,
while sin has had its reign in their mortal bodies; which I cannot but testify,
is as great an error, and as contrary to the Gospel ministration,
and the end for which Christ was manifest in the flesh, which was,
to save people from their sins so as to live no longer therein,
as the error of the scribes and pharisees was,
when they were seeking and believing justification by the works of the law,
without the righteousness of faith.

And thus has it been, that many have turned the grace of God into wantonness,
or turned from the grace of God, into wantonness; so that in a little time,
many professors grew light and vain,
and ran with the very profane into the same excess of riot,
and being lifted up in the flesh, came to be much in show,
but little and light in the balance!
And here, you professors of all sorts,
that have gone from the spiritual appearance of Christ Jesus within,
into a profession of the saints`' conditions and performances,
without the leadings of the same Spirit and power, have lost your way,
and gone out from your guide, which would have led you up to the substance, Christ Jesus.
Thousands of ignorant people have been led, through the cunning slights of men,
into an empty profession; and when the manifestation of the Spirit of God,
which is given to every man to profit withal,
has stirred in the heart to draw the mind out of the ways,
spirit and nature of the world,
then the transforming enemy has lain near to deceive and betray,
directing people into this profession or the other,
or to take up this outward performance, or the other shadow,
under the specious pretense of the ordinances of God and Christ.
Hereby the subtle enemy,
that will admit of people being in the practice of outward things,
while he can have his throne in the heart,
has led thousands aside out of the straight way of salvation,
by drawing them from the true inward guide, "`the grace of God that brings salvation,
that has appeared unto all men,`" into outward observations.
And here the fear of thousands towards God, is taught by the precepts of men,
who know not the leadings of the Spirit and power of God;
and so have healed the hurt of the daughter of Zion deceitfully,
and have daubed with the untempered mortar.

And now, all you scattered ones upon the barren mountains,
hear the counsel and call of the Lord: turn, you prodigals,
who have spent your portions and lost much of your sincerity and tenderness,
and that secret enjoyment you had of the Lord inwardly, years ago,
and who for a long season have endeavored to fill yourselves with husks,
and the profession of the saints`' enjoyments, my heart yearns towards you,
and my soul is often bowed down in the sense of your states;
my heart is often pained within me, when I behold you wandering up and down,
seeking rest and finding none, but what is polluted,
and your souls are lean for lack of the fatness of God`'s house, and the enjoyment of it.
My soul cries unto him night and day, to visit you with an outstretched arm: Return,
return, unto that which will show you all that ever you have done,
and will hasten you to the Father`'s house, where the bread of life is;
and no longer spend your money, precious time and labour,
for that which is not the bread of life, but a profession, a talk of bread,
and which cannot truly satisfy your souls.

And now behold!
I sound the trumpet of the Lord in your ears; prepare, prepare,
to meet the Lord Jehovah in the valley of decision;
and all you who have any tenderness in your hearts, and breathings after the Lord,
among all professions.
Come out, come out of Babylon, and be separate; touch not any longer the unclean,
that the Lord may receive you,
who stands ready to receive all that come in Truth and righteousness unto him;
who will mark all that mourn because of the sins of the people, which are great,
and the measure thereof filling up; and the time is hastening,
of the pouring out of the fury and indignation of God, who lives forever and ever.
Therefore flee for your lives, out of Sodom`'s nature,
and stick not in the mere profession,
the ground of which does not spring from the immediate work of God,
and daily operation of his eternal power in your heart;
but come down into obedience to the pure still voice of the Spirit,
and gift of God in your own heart, which will, as your inward ear is attentive,
direct you in the narrow way of life eternal, in which you should walk.
Here you come to that which moved in the hearts of many, years since, Godwards,
which wrought many into the tenderness before spoken of; herein walk and be faithful,
and it will lead to the Fountain of blessedness, from which it came,
and unto the horn of God`'s anointed;
and to Shiloh shall be the gathering of thousands through the nations,
tongues and people; and the mountain of the Lord`'s house shall be exalted,
through this great day of trial, tribulation and anguish,
upon the top of all the mountains.

The Lord God Almighty reach all hearts that have any breathing desires after him,
among all professions, and pull many as brands out of the fire.
So breathes my soul,
who am a travailer for the universal visitation and deliverance of the seed of Jacob.

[.signed-section-signature]
Charles Marshall
