[quote.epigraph, , 1 John 2:6]
____
Let that therefore abide in you, which you have heard from the beginning.
If that which you have heard from the beginning shall remain in you,
you also shall continue in the Son, and in the Father.
____

== Advertisement.

The present volume contains the writings of Charles Marshall,
as published in the year 1704, (under the title of [.book-title]#Zion`'s Travellers Comforted,
and the Disobedient Warned,#) with the exception of a very few pieces,
which either apply particularly to the circumstances
of the times in which the author lived,
or are of similar import to other parts of the work.
Various slight verbal alterations, not affecting the sense of the author, have also,
for the sake of perspicuity, been made.
In this republication the work is divided into chapters:
such of the Epistles and other Pieces as have dates affixed to them,
are placed in order of time, next following the Journal; and after them,
those without dates, according to the order in which they stand in the first edition.

As the honourable character of Charles Marshall,
and the instructive tendency of his writings,
are fully set forth in the Preface and the Testimonies which follow this Advertisement,
the editor does not consider it needful for him to offer much by way of introduction.
He would therefore only add,
that he has been induced to undertake the reprint of this work, from the conviction,
that it is well calculated to afford comfort and
encouragement to the sincere traveller towards Zion,
in this _our day;_
and to "`stir up the pure mind,`" by exhibiting in the life and labours of the author,
the genuine fruits of christian zeal, charity, and self-denial;
also under the influence of an affectionate desire,
that the impressive cautions herein contained, against false liberty,
the love of the world, and other snares, (whereby some,
even of the early professors of our principles,
lost their standing in the truth,) may promote among us,
a diligent observance of the injunction given forth by the great Head of the Church,
"`Watch therefore, and pray always,
that you may be accounted worthy to escape all these things,
and to stand before the Son of man.`"

[.signed-section-signature]
Thomas Chalk

[.signed-section-context-close]
Kingston-on-Thames, Fourth Month, 1844.
