== The Preface

[.blurb]
=== By William Penn

I must needs say,
it is with some sadness that I remember the departure of so many of the Lord`'s worthies,
as a little time has deprived us of; but I have sometimes comforted myself in this,
that the Lord intends to take his Church more immediately
under the care and ministry of his own blessed Spirit,
whereby that loss would be more than repaired;
and also yet raise up more of his servants,
and bestow upon them such measures of the Holy Spirit and power from on high,
as to be thereby amply qualified to gather home the residue of the dispersed of Judah,
and scattered of Israel, to the hill and city of God:
and though they should not attain to the first rank of the Lord`'s worthies,
yet that they may deservedly be reckoned among the rest that served God,
and David their King, valiantly.

The person, whose least part of his works and labours follow,
having abounded much more in a fervent ministry than
writing--was brought up in the nurture of religion,
among the most seeking and enlightened people of his time, in the city of Bristol;
and was therefore a prepared vessel to receive with joy,
the glad tidings brought out of the north by those eminent servants of the Lord,
John Audland and John Camm, at their first visits to the aforesaid city,
with the testimony of light and salvation,
and of the coming of the power and kingdom of Christ,
to the inhabitants of this age of the world;
where his zeal and godly conduct greatly recommended him to God`'s people.
But in some time after, not contented to eat his bread alone,
being filled with love and a religious concern for the good of others,
he found himself engaged in the name and power of God to
visit the meetings of His people throughout this nation,
the land of his nativity;
and he continued a faithful labourer and minister in the vineyard of Christ to his end.
By his travels and labours, as many were turned to righteousness,
so others were quickened in their gifts to the ministry;
for he was not one that affected words or laboured an elegancy of speech,
or leaned upon memory or former openings;
but one that waited for the feeling of God`'s living and heavenly power,
to carry him forth in his ministerial exercises, whereby, like a right gospel minister,
he often refreshed the family and heritage of God.
As for what regarded himself in a more particular manner, I can indeed say,
he was a great composition of love and zeal, of meekness and affability,
singular uprightness and simplicity; very compassionate and helpful;
serious in his converse, and inoffensive in his freedoms;
fervent against the troublers of Zion`'s peace,
yet tender to the mistaking and relenting.
He was naturally of a lively, but kind and friendly temper,
and where he professed a friendship, very faithful as well as affectionate:
and as the Lord had been with him from the beginning,
and gave him an honourable place in the hearts of his people that are Israelites indeed,
so did he continue his strengthening and comforting presence with him to his end.
For visiting him with several Friends but a day or two before his departure,
as one filled with the love, life and power of Christ,
he prayed after a very earnest manner, "`that the Lord would preserve his people,
and carry on his work among them,
and exalt his Truth;`" and even as in an agony of spirit said,
"`The eternal and everlasting God bless and prosper you and all his people,
and stand by you and carry you through all opposition;
the eternal God and Majesty on high`" with much more in the same fervent manner;
remembering his love to all his dear friends as opportunity offered.

Thus the Lord carried him through the labours of his life,
as well as weakness of his body, till he took leave of us and it,
to receive a more during and eternal mansion in the kingdom of glory.
And reader, in this I write my knowledge of the author of the following book,
upon an ancient, as well as very intimate acquaintance; for I must say,
his friendship and society were always grateful to me, for the sake of that love,
peace and piety that did adorn his conduct: and I beseech Almighty God,
his following labours may be a seasonable and an effectual
memorial of those many former personal ones,
that were so beneficial and acceptable among the Lord`'s people.
Indeed his writings that were made public, are not many;
however they are too many and sensible to be lost;
and if the reader peruse them in seriousness,
they will demonstrate from what fountain they sprang,
even that of heavenly love and zeal, for the stirring up of those that read them,
to the fear, love and service of the everlasting God, and that truth, unity,
peace and concord may increase and be multiplied
among the Lord`'s people where they come.

And I would add what I earnestly desire, namely:
That Friends would be diligent in stirring up their children
and families frequently to read the Holy Scriptures;
also the writings of our ancient departed Friends,
which are an eminent vindication of the divine authority of that blessed book,
upon the experience of those faithful ministers and servants of Christ;
and that all who make profession of the holy and blessed Truth in the inward parts,
would make the lives and labours of those worthies
of the Lord their lively and constant examples,
in their known seriousness, retirement, silence, self-denial, temperance, humility,
meekness, tenderness, brotherly kindness and sincerity to God and his people;
that so there may be a succession in sobriety, righteousness, and godliness,
which is the very sum and substance of religion;
and that one generation may become heirs in holiness to another, till days be no more,
and time be swallowed up in eternity.

[.signed-section-signature]
William Penn.
