== Chapter I.

Charles Marshalls Birth--His early religious impressions--He associates with
some who devoted one day in the week to fasting and prayer--John Audland and
John Camms visit to Bristol--The effect of their ministry on Charles Marshall--Various
exercises--The importance of humility and retiredess of spirit.

I was born in the city of Bristol, in the Fourth Month, 1637.
My education and bringing up was after the strictest manner of religion,
my parents being such as feared the Lord.
I was kept much from the company of other children,
and attained about the fifth and sixth years of my life to read the Scriptures of Truth,
in which, in a little time, I took delight.
In my very tender years I had an abhorrence of swearing and lying, and such like sins;
and not only so, but many times I had inward desires and breathings to know God;
so that about the eleventh and twelfth years of my life,
I not only longed to know the true and living God, but also sought after him,
and loved and esteemed sober, honest people, who feared the Lord.

I went with my mother to the Independents meetings,
in the days of that peoples tenderness and sincerity;
and sometimes I went to the Baptists meeting, and in public,
to hear those men who were esteemed most zealous in their day.
Among those people, and in those assemblies, there were awakenings inwardly,
through the stirrings and strivings of the gift of God, under the sense of which,
living pantings and breathings were in many of their souls, after the true,
spiritual knowledge of God who is a Spirit.
But they went out from that +++[+++state,]
into a profession of the saints words, works and enjoyments,
and left this pure principle of light, life and truth behind.
Now, as I advanced in years, I grew more and more dissatisfied with lifeless,
empty professions and professors, feeling the burden of the nature of sin,
which lay on my spirit; in the sense whereof, I became like the solitary desert,
and mourned like a dove without a mate.
And seeing I could not find the living among the dead professions,
I spent much time in retirements alone, in the fields and woods, and by springs of water,
which I delighted to lie by and drink of.
And in those days of retirement, strong, great, and many were my cries unto the Lord;
and sometimes being retired into places free from passengers, to ease my heart,
I did cry aloud, because of disquietness of spirit.
And I had openings of the miserable fall and inexpressible degeneration of mankind,
and the captivity and bondage which my soul lay in;
in the sense of which state of bondage and thraldom, I cried out, Oh,
that my soul might be eased from these heavy burdens and loads of death and darkness!
that out of this state of gross Egyptian darkness I might be saved,
and from the land of drought, a land of anguish, a land of horrible darkness!
Oh, undeclarable fall! said my soul; oh, inexpressible wall of partition and separation!
Oh, gulf unutterable!
For the fallen and undone state of the sons and daughters of men was opened unto me,
beyond all words to demonstrate.
And in those days, as I walked and beheld the creation of God Almighty,
everything testified against me, heaven and earth, the day and the night, the sun, moon,
and stars, yes, the watercourses and springs of the great deep,
keeping in their respective places; the grass and flowers of the field,
the fish of the sea and fowls of the air, keeping their order; but man alone,
the chief of the work of Gods hand, +++[+++I saw was]
degenerated.
Then cried I out bitterly, Mans state in the fall is worse than +++[+++that of]
the beast that perishes; for the ox knows his owner, and the ass his masters crib,
but man, in this state, is ignorant of God his maker, and is become a stranger unto him,
walking in enmity and disobedience, serving and obeying the devil,
who neither created anything, nor can preserve any living thing; and from the beginning,
his appearance against God has been mere enmity, altogether evil;
a destroyer and a murderer.
And such is the inexpressibly thick darkness that over mankind is come and spread,
that they give up themselves in body, soul and spirit, to be led by him.
Oh, thick darkness! that thus is come over the families of the earth!
Here could I set my seal to the truth of that scripture, darkness covers the earth,
and gross darkness the people.

So in a deep sense of mans miserable state,
and particularly the sense of my own captivity,
and share in this inexpressible state of darkness, death, bondage, misery,
sorrow and amazement, I fell to the ground,
and cried unto God for deliverance and redemption out of this state; and,
although the witness of God thus stirred, and was the discoverer of this miserable state,
yet I saw not, neither had a clear knowledge of that which thus discovered.

And in those times, about the year 1654, there were many +++[+++in these parts]
who were seeking after the Lord;
and there were a few of us who kept one day in the week in fasting and prayer;
so that when this day came, we met together early in the morning,
and did not taste anything.
We sat down sometimes in silence; and as any found a concern on their spirits,
and inclination in their hearts, they kneeled down and sought the Lord;
so that sometimes, before the day ended, there might be twenty of us praying,
men and women; on some of these occasions children spoke a few words in prayer;
and we were sometimes greatly bowed and broken before the Lord,
in humility and tenderness.

Unto one of these our meetings, in the year 1654,
came dearly beloved John Audland and John Camm, messengers of the everliving God;
of whom a testimony is recorded in an Epistle written by a servant of the Lord,
Alexander Parker, concerning dear Josiah Coale,
and prefixed to the said Josiah Coale`'s works, after his death.

By this John Audland`'s powerful ministry, given and committed to him by the Lord,
was I reached and turned unto the Spirit of God, which had discovered my state unto me,
as before-mentioned;
and presently the testimony that was borne by the aforesaid messengers,
was readily received; and as I kept unto this light, whereunto I was turned,
I saw a separation made between light and darkness, the day and the night,
the precious and the vile; and as my mind loved the light,
judgment was set up in my heart, even laid unto the line,
and righteousness to the plummet.
So was I brought into great dread, fear and awe of God eternal, and had great esteem of,
and regard to Gods messengers, who brought the acceptable tidings of life and salvation.
Through them doctrine dropped as the dew, and was received;
and as their words were gracious words,
so was there a great estimation in my soul of every word,
and a fear of rebelling against any part of that counsel I received from them,
either by word or writing.
A long travail I saw, through the ministration of condemnation,
which indeed was glorious in its time:
and as I kept down to the judgment of the Lord in my heart,
the operation whereof was as a sword, fire, and hammer, and the evil nature,
in some measure, came to be overcome, then something of divine refreshing streamed in,
and love flowed, which refreshed me in my travails.

But now began the old subtle enemy to lay snares, and hunt after my soul,
which was in some measure rescued out of the jaws of death; so that when I had precious,
refreshing openings of the way of truth, through which a secret hope and joy sprang,
the enemy led me out from sinking down into a sweet enjoyment and treasuring up,
to spend my own bread in disputes for truth, against opposers;
and to declare of it unto those who had some love for it.
But so it was, that after I had given and spent my own bread,
which was given me only to strengthen my own soul,
that when I came home and communed with my own heart, and came to stillness,
then I saw myself quite empty,
having leaked out that which was given for my refreshment and consolation.
My beloved was withdrawn; then distress took hold on me beyond all expression,
and I was greatly bowed down; and having an understanding of the cause,
I was ready to promise and covenant,
that if I came to my former peace and refreshment and feeding again,
I would not run out prodigally again, nor spend my portion,
through which that inward trouble and barrenness came over my spirit.
And here the enemy, that in his transforming workings had thus led me out,
would work subtly also in the day of my trouble,
to bring great discouragements over my spirit, and unbelief.
Here my soul has in remembrance the great anxiety of spirit,
and sense of the withdrawings and hidings of +++[+++the Lords]
face, and the veil that came over.
I was thus led out in a zeal not according to that knowledge
which the power gives in its leadings and guidings;
and when I promised and covenanted, and then broke covenant,
I was pursued for a covenant-breaker.
But in time the Lord helped me through and over this exercise,
and I came rather to stand as a fool,
and to sit in silence before the Lord among his people,
than to wrong my condition and grieve the Spirit of God.
And when I thus kept obedient to Wisdoms directings, a secret joy would spring,
and pure peace and inward ease; yet when I came to inward peace, and felt life and joy,
for that the light of the Lord shined on my tabernacle,
for lack of keeping low in humility, where the growth in the truth is,
the enemy wrought subtly again,
to persuade that there was not that need of such a severe watch and inward exercise,
as formerly; through which he sometimes prevailed, to lead into a liberty,
inward and outward, that had a tendency to lead again into inward bondage: and I,
through often refreshings, openings, prophecies and promises,
was ready to conclude my mountain was immovable.

But soon I found a withdrawing again of the Lord; then I knew a winter again,
and the storms of the enemy;
and not having yet learned the state of being contented in want,
as well as in aboundings, I not only fell into a poor, impoverished, murmuring state,
but also into great trouble, in a sense of this change,
and fears and doubts were ready to enter: I toiled in this night,
but could catch nothing which administered any comfort that was lasting.
Here I was willing and running and striving, being in great fear and sorrow;
and the more I toiled and laboured, kindling sparks of my own,
the more my sorrow was increased; for as yet I had not learned the state of resignation.
And now, I was brought very low; and having mourned many days,
in the sense of the withdrawings of the presence, love and power of my God,
being in deep distress and amazement,
Israels travels in the wilderness were opened unto me;
how the Lord tried them with lack of bread and water,
and that their happiness stood in their being content and resigned up to the will of God,
and in the belief of the Lords faithfulness, to have endured the trial.
But they murmured and repined, and thereby grieved the Spirit of God; so did I:
yet through the lovingkindness of God, the state of resignation was opened unto me,
in which man stood before he fell through transgression,
into his own workings and willings.
Now, when my understanding was thus opened, my soul cried unto the Lord my God,
Oh! preserve me in pure patience and passiveness, and in living, acceptable obedience,
and I will trust in you.

And as I believed in the light of the Lord,
and thereby and therein was comprehended and resigned, his pure power,
love and life broke in as formerly, which greatly refreshed;
then the sun shined upon my tabernacle, and I bowed before the Lord,
blessing and praising his holy, glorious name; then he instructed me,
and his pure Spirit and power opened in me the way of preservation, and that was,
to centre down in true humility.
So then my soul began to be as the dove that found a place for the soles of her feet.
Yet did the enemy continue to tempt by his allurements, and so laid his baits and snares,
that if at any time I was drawn to look abroad, and went out to view, as Dinah did,
I was in great danger of being defiled: for I found,
if at any time I went out from this pure, preserving power of God,
that had wrought in my soul through inexpressible travail,
and let in the spirit of the world and reasoned,
and thereby beheld a beauty in any fruit but what was brought forth by the Tree of Life,
then came over me a wound, a stain and defilement.
And if at any time the enemy prevailed in the inward ground,
to cause any cleaving to his temptations, through the lusts of the flesh,
or the lusts of the eye, then was I afraid, because of horror and inward wrath;
and then the power of the Lord, in love to my soul, wrought mightily,
to sanctify and cleanse it again.
This inward exercise I passed through,
when no friend nor intimate acquaintance knew thereof.
Oh!
I remember the nights of bitter sorrow that I passed through,
when no defilement could be discerned by any, I walking blamelessly among men.
For such was the great love of God to my soul all along,
in those days of inward travail and exercise,
that judgment followed presently upon the outgoing of my mind:
and as I kept single to the Lord, and upright in heart, not joining unto any iniquity,
I found the Lord near at hand in many exercises that happened in our city and elsewhere.
Also +++[+++during]
the working of the power of darkness in James Nayler,
and the runnings forth of John Perrot and others, God let me, a young lad,
see through all those subtle workings and transformings,
and by a secret hand preserved me.
Of those things and trying times I have not much upon me to leave in writing at present;
known unto the Lord they are, the ends, the causes, and permission,
and letting loose of the enemy; and what therein has been in secret opened by the Lord,
the Opener and Revealer, is left.
God has willed the keeping low of his people in every generation; and he has,
by his power secretly struck at every things that has a tendency to rob him of his honour.
He delights in the humble, and dwells with the brokenhearted and contrite in spirit;
and in this state is safety and preservation to us in this age,
and will be the safety +++[+++of all]
in succeeding ages.
And now, through these exercises at which I have hinted, in short,
I have learned from the beginning of the work of restoration and redemption,
that every ones preservation is in pure inward retiredness unto the Lord;
and in his pure fear, awe and dread to keep low; feeling after his soul-redeeming,
soul-preserving, holy power, which quickens and enlivens; and as it is abode with and in,
keeps alive in its own pure nature and quality, over the world,
its spirit and defilement.

And further, I have a sense upon my spirit, beyond utterance,
of the potent workings of the enemy, in and through the generations of mankind,
to accomplish his end, namely, that after the Lord God Almighty has appeared in any age,
in the free dispensings of his love unto mankind, and the breakings forth of his power,
and the making bare of his arm, in order to restore man into covenant with Himself; then,
I say, has the enemy appeared with all his power, mightily, subtly, gradually,
and hiddenly, to undermine and anticipate the work of God; and his great end has been,
by different and manifold snares, to draw first into a lessening of the estimation,
in the visited people, of the power and appearance of God, in this day, age,
and generations in which it is manifested; and subtly to +++[+++lead]
the mind, by his transformings, into an estimation of the manifestation that has been,
or into a strange affectation of what may or is to appear;
drawing the mind out of a due regard unto that manifestation
which alone works the eternal welfare of the creature.
This was the case +++[+++with Jerusalem of old]
to whom it was said, if you had known, even you, at least, in this your day,
the things which belong unto your peace.

So this I have learned of the Lord, and therefore leave it,
both to friends unto whom it may come in this age and generation,
and unto Gods people in the following generations of the world:
more fully hereof +++[+++may be seen]
in my general and particular Epistles to Friends,
and in the book called The Way of Life Revealed, etc.
