== Chapter VI.

An Epistle to the Flock of Christ Jesus, and professors of Truth in general among us:
being to them a tender visitation from the True and Living God.
+++[+++Reminding them of his gracious dealings with them,
and containing sundry exhortations and warnings.]

Dearly Beloved Friends,

When we sat in darkness, and in the region of the shadow of death,
when darkness had covered the earth, and gross darkness the people,
as well in this professing nation, as in others;
in this long and tedious night of apostasy,
wherein we were seeking the living among the dead; seeking our bread in desolate places;
were cast out into the open field, and lay polluted in our blood;
wounded by sin and iniquity,
and greatly distressed for lack of the knowledge
of Zion`'s way to be cast up in this our day;
even then, in the dispensation of love, did the holy God of heaven and earth visit us,
a people in this northern island, with his everlasting day springing from on high.
This day was a day of love beyond all expression,
and I am from day to day moved of the Lord to call
it to remembrance in the ears of his people;
it is a day never to be forgotten: for if the day of outward Israels visitation,
in outward Egypt, was to be kept in a continued remembrance;
how much more ought the day of the visitation of spiritual Israel, in spiritual Egypt,
in thraldom under spiritual task-masters, to be kept in a perpetual remembrance?

And, dear Friends, you know what manner of entrance Truth made in its first appearance,
in the day of our first tender visitation;
how it regarded not the empty profession of any, but broke in upon us,
pricking us to the heart,
bringing us to a true sense of our inward states and conditions before the Lord; where,
notwithstanding all the fair shows of professions, we saw our immortal souls in death,
and buried in the grave of sin,
and the nature of transgression exalted above all that was called God in us.
Then we had not only a sight of this our deplorable state,
but also a sight of him whom we had pierced,
and whose countenance we saw marred more than any
mans and his visage more than the sons of men;
and here many knew a day of mourning, of passing through a vale of tears,
and a drinking of a cup of trembling from the hand of the Lord:
for our awakened souls cried unto the Lord,
to be eased from under the burden and load of iniquity;
and the living Lord God bowed down his ear to the cry of his Israel,
and manifested his mighty, out-stretched arm of power, which wrought in us mightily,
for the killing and making alive, for the casting down and raising up.
And because of the working and operating of the glorious power of the immortal God,
our very bodies trembled, so that we became as signs and wonders to people; yes,
to our very acquaintance and relations:
for we were as a people separated from all comforts and delights.
And, my dear Friends, although it was thus with many, yet it was a good day;
for the judgments of the Lord being in the earth, many learned righteousness.
And as this immortal power was bowed unto, and lived in,
it brought forth the soul out of the horrible pit,
which was an answer to the cries of the panting, distressed heart and soul.

Dear Friends, as the Lord God began an effectual work, by his immortal, living,
glorious power, so has he, by the same, been carrying it on these many years among us;
notwithstanding the great oppositions it has met with every way,
by the power of darkness, in them that went out from us, and from men without.

Ah! how has Leviathan, that crooked serpent, wrought!
Under how many disguises has he appeared, to rend and devour!
How many false spirits has he appeared in!
And what endeavour has the old serpent made, to bring the heritage of God into sufferings!
But blessed forever be the name of the mighty God,
he is laying waste that serpentine spirits working, and will lay it waste,
and tread it down forever under the feet of his anointed;
and will make all their skirts bare, who have called themselves Jews and were not,
but were and are of the synagogue of Satan;
who would have perverted the right way of the Lord,
and would have risen up in the enmity of the old crooked serpent,
against the servants and messengers of the everlasting God,
whom they have caused to go with bowed souls before the Lord.
Friends, against that spirit, in its root and branches,
I have a certain testimony from the Eternal God to bear; and woe from God,
to the vessels that are still polluted with that spirit.

And, dear Friends, not only this mercy have we received from the hand of the Lord,
namely; the treading down of the serpentine spirit, which indeed I cannot but say,
is not one of the least of the mercies and kindnesses of our God;
but as the Lord has appeared wonderful in power for our inward deliverances,
so has he appeared wonderful in power for our outward deliverances,
and preservations from time to time: he has bound the seas with swaddling-bands,
and has said to the proud waves, "`hitherto shall you come, and no further.`"
Magnified be the name of the Lord God forever.

And so, my dear Friends, on every hand we are an engaged, obliged people unto the Lord,
who has been digging, dressing, pruning and watering us, his vineyard, from day to day,
from week to week, from assembly to assembly; and his living power,
that began this good work among us, in the day of our first tender visitation,
has been carrying the same on to this day.

And now, dearly beloved Friends, in every place,
this to you is the message of the Lord of hosts, that I have received from his mouth,
and am necessitated, both by word and writing, to sound in the ears of his people,
in this nation peculiarly,
which was the first of the nations that was visited with this his everlasting,
glorious day in our age;
that the Lord our righteousness does require his people in every place,
to keep stayed in that immortal light of life,
unto which they were directed in the day of their first tender visitation;
in that to feel the virtue, power, and efficacy of the girdle of truth,
to gird up the loins of their minds in the light of righteousness;
daily there to wait to feel the everlasting power, and right arm of Gods salvation,
its manifestation, operation and effectual working; so that thereby,
that good and holy work, which the Lord God began among us,
in the day of our first tender visitation, and has been carrying on to this very day,
may now be finished and perfected; and the residue of that nature,
against which the sword of the Lord has been furbished, might utterly be destroyed.

And, dear Friends, in the name of the everlasting God +++[+++I declare it,]
this is the very work of this day, in and among the people of the Lord;
and for this end does the Lord spare many,
and lengthen out the day of the tranquillity of this nation,
with which he had a sore controversy,
and which he will assuredly visit for its iniquities.
Therefore, Friends, let all prize their time,
and the lovingkindness of the Lord God that is now
extending itself unto his people in this day,
wherein he is laying his hand of love upon those called to be the lot of his inheritance,
to pull them out of spiritual Sodom fully.
And this is the voice that is to go forth unto the unfaithful and disobedient among us,
(as it was of old,--come out of Babylon,
come out of Babylon my people,--so now,)--come out of all Babylons abominations,
touch no unclean thing; and be not partakers with her in her sin,
that none may partake with her of her plagues.

Dear Friends, nothing will now please the Lord but a thorough work;
a real cleansing and sanctification throughout, in soul, body and spirit; +++[+++a being]
really translated out of the kingdom of Satan, into the kingdom of the dear Son of God.

Now, dear Friends, this perfect salvation is no way attained,
but as there is an abiding in the way of it,
closing with the being comprehended into that light of righteousness,
given to us to profit withal; for, in it is the power received,
in it is the virtue of life known, which no mind is made worthy of the enjoyment of,
but that which can sit at Jesus feet,
which can stoop to the lowest appearance of Christ Jesus,
where the mind is made low and little.
Here is the entrance into the power of life that gives dominion; and many miss here;
they come not down,
so as to be nothing in the love of this world nor in any created object;
to be nothing in thoughts or imaginations that are evil; to have no Dalilah,
no beloved lust to be as the right hand, or as the right eye:
for where the mind is in these things entangled, it finds not perfectly the way of Life,
the place of power and ability to stand over every defilement and temptation,
of what nature and kind soever.
The door of hope is found in the valley, where, in mind, heart and thoughts,
we come to be as nothing in our own eyes before the Lord; here the power has its passage,
and here the Spirit of Life has its free and perfect operation,
to work the work of God effectually,
until man throughout be leavened into the lump of Life, brought up into the image of God.
So then, every one must come to be as a child, yes, and as a weaned child too;
and here the work of the Lord in the heart and soul goes forward daily:
for the Lord is weary of the out-side professions;
and they are before him as the fig-tree, that was covered with leaves, but had no fruit;
concerning which Christ Jesus said, never man gather fruit of you, and it withered;
so will it be with the false and hypocritical professors:
for none shall be able to stand in the day of the Lord that hastens,
but such as come to stand in the possession of Life itself.

Dear Friends, may every one know the blood of sprinkling,
that sprinkles the conscience from dead works to serve the living God in newness of life;
for where the blood of Jesus is despised and trodden under foot,
there will the destroying angel enter, in the day of his passing through;
the whirlwind of his wrath will be revealed, to sweep away the wicked,
and the sword of the Lord is bathed in heaven against the ungodly.
Therefore, Friends, prize your time, prize your time; waiting daily on the Lord God;
that so the nature of transgression may be wholly taken away in us,
for which the mighty God has a controversy with the nations:
for there sill be no hiding-place for any but the clean in heart, in the day at hand,
of the dreadful pleadings and rebukes of the Lord God of heaven and earth.

And, dear Friends, it is upon me to leave this, as the counsel of the Lord,
unto all the families of the Lords people through this nation, who may be concerned;
that all heads of families, and those that have the tuition of youth,
may always in their families feel the daily arising of Gods immortal power,
and in that labour according to their power,
to keep down all sin and iniquity in their families;
and in that feel ability to reach the witness of God in their children,
servants and families;
that so no sin nor iniquity may be in the families of the Lords people,
but that all be kept sweet and clean, pure and savoury before the Lord; all in is fear,
dread and awe, out of all needless discourses, vain words and foolish jestings.
Let your words be fore, administering grace to the hearers;
that so when the people of the world come to your houses,
to have converse or commerce with you, all being in the dread,
fear and awe of the Lord God, in the sweet, savoury, chaste life,
the witness of God may arise, and make them acknowledge you are the people of the Lord,
and that he is with you:
here all in their respective places will be preachers of righteousness; and here,
in this pure harmless life, we must overcome.
And this does the Lord God, in whose hand is the breath of all living,
require of all the families of his people.
And those who do, or shall walk in a contrary life,
the Lord God of eternal might and strength will visit with the rod of affliction.

And, dear Friends, it is likewise upon me to warn all, in all places,
to be careful that neither you nor your families run into superfluities in food,
or in drinks, or in apparel, into the +++[+++use of]
proud, offensive garbs of the world;
but in all these things let us all keep in our first fear, dread and awe;
that in none of these things, provision may be made for the flesh,
to fulfill the lusts thereof.

It is also upon me to warn all to beware of trusting,
or having a life in uncertain riches, or in any external thing; and at all times,
and in all places, to keep out of the many and needless words.
Both in dealing and in all your converse and commerce with the world,
let your words be few; for Friends,
there is a great hurt sustained in a multitude of words; by it is the mind drawn forth,
and the spirit of the world let in;
through which the continued sense of the presence of the Lord is lost,
and our testimony weakened against the world therein;
also thereby the opportunity is lost of reaching
the witness of God in the hearts +++[+++of others,]
on occasions of having to do with them.

And therefore, dearly beloved Friends, I beseech all in the bowels of the love of God,
in the moving of his Eternal Spirit and power,
that in your dealings you use but few words; be equal, just and upright;
and do not be drawn forth into many words,
to answer that mind that is out of the dread and fear of the Lord;
but after you have put a price on your commodities, which is equal,
and as you can sell them, then if the persons you are dealing with, multiply words,
stand you silent in the fear, dread and awe of God;
and this will answer the witness of God in them you are dealing with;
and if this should not please people at first, yet you will see it will quickly overcome;
therefore in your dealings, keep out of the spirit of the world, out of all covetousness,
over-reaching and craftiness, in the harmless life; seeking the kingdom daily;
and let other things come as additions.
So all being diligent in the pure fear of the Lord,
out of the love of these worldly things, abiding in the love of God,
and seeking the kingdom that is not of this world,
you will see great opportunity in your dealings, of reaching unto people;
and thereby thousands may be reached, convinced, and brought to the Truth.

And, all Friends, be watchful over your own hearts, in the fear and dread of the Lord,
in the first moving cause of marriage;
that none who profess to walk in the undefiled way of the Lord,
may run into the lusts of the flesh and of the eye,
in which ground stands all the polluted marriages of the world;
but let all try the very ground of their love and affection,
whether it stands in the covenant of God, in the clean life of righteousness;
for although it is the very truth, that marriage is honourable,
yet the bed must be undefiled; which is a near word,
and judges the polluted marriages in the world, that are begun, carried on, and finished,
out of the fear and dread of the living God.

And, Friends, I am moved of the Lord God to warn all,
to try the first moving cause of their desire and
willingness to marry this or the other person,
and that when it first springs in their hearts, and is in the bud; for then,
if by bringing it to the light, it be found not wrought in God,
but in the spirit of this world, it is easy cut off and broken; but if it still continue,
and way is given to it, then it becomes a mountain;
and the persevering therein draws the mind so far out into the affectionate part,
as that it veils and darkens the heart; and the thing seems right in the consideration,
although altogether the working of the destroying enemy.
And here stands the ground of the running out of the affections of Friends,
(or such as profess the truth,) to marry men and women of the world;
for lack of the keeping out the first motion +++[+++thereto,]
they lose the sense of the truth, and so persevere therein, to the ruining

their condition in the truth and to the displeasing of the holy Lord God.
Of this practice I warn all, in the fear and dread,
and by the power and spirit of the Lord God, to beware;
and all such things will be avoided, as heed is taken, in the first thought +++[+++thereto.]

And, dear Friends, if any see that a single condition is not best for them,
then let them wait to be guided in the truth, in the changing their condition;
and not run as the worlds people do many times, from place to place,
and from person to person, having their affections one while on one object,
and another time on another, and it may be so on to many; which is a wrong thing,
and destruction every way attends it; but let all in the pure fear of the Lord,
(that keeps the heart clean) proceed,
seeing their way clear and plain in the sense of truth,
out of all the worlds bargainings and folly, that attend the management of such things.

And let all masters and mistresses, and heads of families, stand in their places,
in the exercise of a pure, meek spirit, to their servants and children;
not in the merciless spirit of the world,
which would require of servants more than they have ability to perform comfortably;
but out of that let all keep, in the love of God, waiting on him for wisdom,
that every one may know their places.

And let all servants stand in the subject, diligent state, in meekness.
I warn all servants, professing truth, to keep low in the fear and dread of the Lord,
out of high-mindedness and pride, and out of all eye-service,
waiting on the Lord to know your places in all things;
and herein you will adorn the profession of truth.

And also it is upon me, in the fear, dread and counsel of the Lord,
to warn all in all places, of that thing +++[+++concerning which]
Joseph warned his brethren, namely, of falling out by the way;
that there be no way given to the least appearance of that which would make any rent,
schism or division;
for the hand of God Almighty is against every person
that shall set up that spirit that thirsts to envy;
that spirit that hurries into passions;
that spirit that will backbite and whisper in secret, through which breaches come.
The dread of the Lord of hosts, as a consuming fire,
will break out against all who shall continue in any such spirit;
for the nature of the spirit of Truth is to bring forth the very contrary fruits in all,
where it lives, reigns and rules.
The life of such is peace, and they are peace-makers:
such cannot rest nor be contented while there stands
anything between them and a brother or sister,
if they be concerned therein.
If one of these see any iniquity in his brother or sister, he will,
in the bowels of tender love, go to his brother or his sister, and say, my brother,
or my sister, do not offend or grieve our tender Father,
who has dealt so tenderly with us; so in the heart-breaking love,
he will labour with his brother or with his sister; and if not received,
will let no prejudice nor anger arise, nor shut out his brother;
but if there should be no reception,
there will be a single standing in the love and simplicity of truth;
and they who shall not so receive, shut themselves out.

And if there be a controversy between any, where the life of Truth is known,
and there be but the least sliding, the most innocent will be ready to acknowledge first,
that with the love of God he may break down and overcome the mountain in his brother;
and this spirit ruling, which is the spirit of the Savior of the world, no rent,
schism or division can live, or have an existence among the people of the Lord:
for against this spirit that causes division, the hand of the Lord is; and woe from God,
to all whose hearts and spirits do not subject to that which seeks peace,
and delights in no other thing.
The living God requires this of all his people;
and if there be the least of the contrary in the hearts of any, I beseech all such,
in the bowels of love, that they would presently put it away, and flee from it,
as from the devourer of Gods heritage.
So, dear Friends,
may all dwell together in the unity of the one Eternal Spirit of life and peace,
and therein feel your hearts united; for he and she that loves not their brother,
how dwells the love of God in them?
And so, as the apostle well said, mark them that cause divisions;
and out of their divisions keep forever.
And, dear Friends, wherever anything of division or distance remains in any heart,
I earnestly beseech you, seek speedily an end to it;
for Gods controversy is against all things of this nature,
and the wrath of the Lord is and will be revealed against all such things.
Therefore, O Israel! put away this accursed thing wherever it is found;
and let every soul desire and press into the lively
state of brethren dwelling together in unity:
for here the blessing of the life and virtue of the
endless fountain of goodness will flow over all,
and here all will be knot together as by joints and bands; all holding the head,
and knowing their places in the body: here one member will not say to another,
I have no need of you; but all will seen need of another:
here no stop will be put to the current of life, but through all it will run,
even from vessel to vessel; in which state God Almighty preserve us all forever and ever.

And, all Friends everywhere, quench not the spirit of the Lord in yourselves,
nor in one another; nor let any resist or judge the power of the Lord God,
although in a tender babe, that cannot yet speak plain.
For where any do thus hurt the tender lambs of Christs fold,
and stop the bubblings up of life, they bring a barrenness over their own souls,
and over the assemblies they belong unto.

And so, dear Friends, as there may be, and has been, a false forward birth,
that has or may run before, to the burdening and grieving Gods heritage,
which birth the Lord destroys; so there has been a stopping,
a quenching and resisting the requirings of the power, to the hurt of many,
and to the hindering of the growth of many,
and of the prosperity of Truth in the general: for some being in the sight,
and under the grief of the false, untimely birth in +++[+++others,]
have resisted the motion of Gods Holy Spirit in themselves,
whereby two evils have proceeded at once, namely, the exaltation of the false,
and the suppressing of the true birth.
Some men, unto whom God has given gifts,
and upon whose spirits the requirings of Gods power have been felt,
through their reasonings and looking out, have even hurt the birth of Gods begetting,
to the bringing darkness and heaviness over themselves,
and to the hindering of their growth.
And therefore, as on the one hand the false, forward birth is to be kept down forever,
whose end is always something, either to be great, or looked at,
or to have ease or prosperity in the flesh; and also,
that it may have its way in the lusts thereof;
(for all such births centre in those things,
notwithstanding all fair and fine appearances at times and seasons,
or for a time or season;) so, on the other hand, the true birth is to come up.
And therefore, in the name, strength and power of the God of heaven, arise, arise,
you child of the covenant, and come forth, and show yourself,
and work in your Fathers vineyard; break through, ah! you breathing, panting birth,
and in your Fathers strength break every bond and chain, that has held you under: Arise,
Zion, and shine, for your light is come, and the glory of the Lord is risen upon you.

Arise, Zion, and thresh the mountains, and beat the lofty hills to dust;
for into your hand has and will the mighty God, the great Jehovah,
put a sharp threshing instrument.
And so, dear Friends, in this thing,
let every one be careful to walk in the even path of life eternal;
in which path every eye will be single, and the whole body will be full of light;
here every one will see and know the time when to speak, and when to be silent:
for the true births life is in the will and power of the Lord,
and at his time and requirings +++[+++those who cherish it]
bring forth sacrifice, not to their own nets,
nor will every seek an interest of their own among any, but honour God alone,
and be as worms before the Lord.
But it is not so with the false birth; its life is not in meekness, but in the contrary:
so here all may know the motions of the one from the other:
where the true motion of life is, the mind is brought into stillness,
to wait on the Lord, and there the will of God comes to be sealed to the understanding.

And, all Friends everywhere, keep diligently your meetings;
for our meetings were set up by the Lord God of Abraham, Isaac and Jacob,
and in his counsel they now stand; and the Lord requires us now to meet as boldly,
as constantly and as diligently as ever, without any regard to what man can do unto us;
because we know we meet not in refractoriness to any man on earth,
but purely in obedience to the living God, who does require it of his people;
and whatever draws from meetings, in part or wholly, draws from God,
and is an antichristian spirit, let it appear when, and where, and in what vessel soever;
and Gods infinite power and dread will tread that spirit down forever.
Therefore, dear Friends, let none forsake the assembling of themselves together,
as the manner of some was in the apostles days, and also is in our days;
and if any do thus for fear, or for saving their estates or worldly goods,
and so fear to come forth to confess the name of the Lord before men,
that will prove an evil snare to as many as go into, and keep in it;
for this is a way to bring a curse upon themselves and all they have.
And where any depart from meetings to save an outward estate,
and do not give up to the power of the immortal God,
to divide them from that spirit +++[+++of fear,]
the outward, for which they have left the Lord, may be rent from them, or they from it;
and then, when such shall lose that, and their peace with God also, what a miserable,
horrid state will that be!
This will be the state of all them that sell their birth-right for a mess of pottage.
And, Friends, this I know, and therefore in the name of the Lord declare it,
God does and will appear mightily in the assemblies of his people, and arise in them,
in the magnificence of his Eternal Power,
to the astonishment of the heathen that knows not God,
and to the gathering many lost sheep.

And Friends, these are the ends of our meetings, namely; our daily edification,
through the manifestation and workings of his Eternal Power in our hearts,
in our assemblies:
and therein and thereby for God we give a testimony against all the false professions,
and false worships in the whole world; and stand as a city set upon a hill,
to gather to the Lord the outcasts of Israel, and the dispersed of Jacob:
and at the report of the Holy Spirit descending in our assemblies, as in ages past,
shall many gather to them, and be pricked to the heart,
and be turned from the evil of their ways,
and be brought to the mountain of Gods holiness,
now to be exalted in and over the tops of all mountains.

And Friends,
where any have been visited with Gods everlasting day springing from on high,
and +++[+++after having]
made open profession and confession of Gods everlasting truth,
have erred from the holy commandment,
have made shipwreck of faith and of a good conscience,
and thereby have gone into the evil spirit,
or into any iniquity in their dealings and commerce with the sons and daughters of men,
or into any evil whatsoever;
that have or do cast a stumbling-block in the way of the weak, or have cause the dear,
and precious, and honourable name of the Lord to be blasphemed among the heathen,
and his truth and people to be reflected upon; to all such I say,
in the name of the Lord,
return unto the holy light of righteousness from which you have erred,
there to wait for the arising of the power of the living God, to heal your backslidings;
that you may know the free love of God to come over all again,
and feel a testimony arise in you against anything you have committed,
that has caused his dear name to be blasphemed,
and his truth and people to be reproached, and the hearts of any to be hardened;
which testimony you are to bear us publicly as the transgression has been:
according to the nature of the offence against God, his truth and people,
even so must the testimony go out against it, in the fear and dread of the Lord God,
and in brokenness of heart and spirit before him:
and where the backsliders in heart and conduct do not thus return,
in the name of the Lord I declare, that the day hastens,
wherein the hand of the Lord God will find all such out,
and they shall be made an astonishment to themselves and to others;
for the living God has determined to clear up the innocency of his truth and people.
And where any such do not return into a sense of what they have done,
in their backslidings from the Lord, and declare against themselves,
to the clearing of truth, then is it the duty of the people of the Lord,
who keep their garments unspotted, after they have dealt with such tenderly,
according to the order of the gospel of peace,
to give a testimony against all such persons and practices, that are out of,
and against the truth:
and this testimony is to go forth according to the nature of the offence,
that the house may be cleansed, and all kept pure and sweet;
and that all may be clear of the iniquity, and of the blood of all men.
And so, dear Friends, in the light of righteousness let us all keep our habitations,
in a continual watchful state; then we shall grow, as the willows by the water-courses,
and be preserved out of all the snares and wiles of the enemy,
in the light of righteousness;
in which the arm of the Lord God preserve us all to the end of our days;
that every day we may perfect holiness in his fear, to the glory of the Most High God,
and comfort of every faithful follower of the Lord.

Given forth in obedience to the requirings of the Lord,
through one who is a travailler for Zion`'s redemption.

Charles Marshall.

1672.
