== Chapter VII The Way of Life Revealed / And The Way of Death Discovered.

[.centered]
_Wherein Is Declared Man`'s Happy State Before the Fall,
His Miserable State in the Fall, and the Way of Restoration Out of the Fall,
Into the Image of God Again, In Which Man Was Before the Fall._

[.small-break]
'''

[.centered]
_Also The By-Paths, Crooked Ways, Wiles, Snares and Temptations
of the Enemy of Man`'s Soul Discovered,
Who Goes About As a Roaring Lion,
Seeking How He May Ensnare and Devour
Those Who Are In Any Measure Escaping Out of His Ways Of Death And Destruction._

[.blurb]
=== To The Reader.

Be serious when you take in hand to read this following treatise,
and have a single regard unto the inward state of your immortal soul;
and let your spirit bow down to the measure of the
Spirit of God given you to profit withal,
that by it the eye of your understanding may be opened;
so will you see the things herein contained, which concern your own eternal welfare:
and let not your own thoughts and imaginations, in the wisdom from below,
which is sensual and earthly, be judge therein; but stand still,
out of your own comprehendings, ascendings and descendings;
and let a true and diligent regard be had to the word in your heart and mouth,
there placed, that you may obey it and do it;
so will your heart be truly opened to read with delight
the things herein opened by the Spirit of Truth,
which searches all things, yes, the deep things of God; and the travail in Spirit,
which is for opening the eyes of the blind, and unstopping of the ears of the deaf,
will be answered,
and the Lord God Almighty will have his honour from his own workmanship,
and you the benefit; which is the desire, travail and breathings of him,
who is a traveller for Zion`'s perfect deliverance.

[.signed-section-signature]
C+++.+++ M.

[.signed-section-context-close]
Bristol, the 2nd of the Seventh Month, in the year 1673.

[.old-style]
=== Section 1. / Man`'s Happy State Before the Fall

In the beginning God created the heaven and the earth;
and after he had made all things on the earth, he made man in his own image,
formed him of the dust of the ground, and breathed into him the breath of life,
and man became a living soul.
And the Lord planted a garden in Eden, and there he placed the man whom he had formed;
and out of the ground the Lord God made every tree
pleasant to the sight and good for food,
to grow; the tree of life also in the midst of the garden,
and the tree of knowledge of good and evil.
And He that made man in this state, gave him a law to preserve him therein,
as the scripture of truth witnesses, saying, and the Lord God commanded the man, saying,
of every tree in the garden you may freely eat;
but of the tree of the knowledge of good and evil, you shall not eat of it;
for in the day that you eat thereof, you shall surely die.
Now God saw everything that he had made, and behold it was very good;
the tree of knowledge of good and evil was good, but not for food.
And man was endued with that divine wisdom,
that when the Lord God brought of every beast of the field, and fowl of the air, to Adam,
he gave names unto them; and whatsoever Adam called every living creature,
that was the name thereof.
So here was man`'s station in the image of God, a living soul, a noble plant,
wholly a right seed, filled with divine wisdom and virtue, clothed with innocency,
covered with glory, adorned with celestial beauty,
in the continual enjoyment of the love and favour of the Eternal Being of all beings,
having his daily communion with Him that made him; no death, no darkness, no sorrow,
no occasion of tears, no transgression, no knowledge of evil;
dwelling in the innocent life itself; placed in the garden,
into which came the river out of Eden that watered it.
O blessed state!
O happy condition!
O inexpressible enjoyment! undeclarable beauty and glory!
It is beyond the tongue of man to declare fully, that blessed, happy state of joy, peace,
virtue, purity, holiness, righteousness, and fruition of life,
which man was in before he transgressed the royal law of God.

[.old-style]
=== Section 2. / Man`'s Miserable State In the Fall.

But now he, who kept not his first habitation, neither abode in the truth,
envied man`'s happiness in the truth, and therefore, as a serpent,
more subtle than any beast of the field, which the Lord God had made, came to the woman,
who out of the man was made, and said, "`Yes, has God said,
you shall not eat of every tree of the garden?`"
The woman said, "`We may eat of the fruit of the trees of the garden;
but of the fruit of the tree which is in the midst of the garden, God has said,
you shall not eat of it, neither shall you touch it, lest you die.`"
And the serpent said unto the woman, "`You shall not surely die; for God does know,
that in the day you eat thereof, then your eyes shall be opened,
and you shall be as gods, knowing good and evil.`"
And here the serpent got an entrance.
And when the woman, (mark) saw that the tree was good for food,
and that it was pleasant to the eyes, and a tree to be desired to make one wise,
she took of the fruit, and did eat, and gave also to her husband with her,
and he did eat, and the eyes, (mark) of them both were opened:
here the god of the world prevailed, so as to open an eye that saw evil pleasant,
and to blind the eye in these children of disobedience,
that they should no longer behold the glory of God, etc.
And here they became naked,
having lost the robe of righteousness and garment of innocency,
and then made aprons of fig-leaves to cover their nakedness;
and they heard the voice of the Lord God walking in the cool of the day,
and Adam and his wife hid themselves from the presence of the Lord God;
and the Lord God called unto Adam, saying, "`Where are you?`"
And he said, "`I heard your voice in the garden, and I was afraid, because I was naked;
and I hid myself: and he said, who told you that you were naked?
Have you eaten of the tree whereof I commanded you that you should not eat?`"
Then Adam began to excuse himself, saying, "`The woman whom you gave to be with me,
she gave me of the tree, and I did eat.`"
And the Lord God said unto the woman, "`What is this that you have done?`"
And the woman said, "`The serpent beguiled me, and I did eat.`"
And the Lord God said unto the serpent, "`Because you have done this,
you are cursed above all cattle, and above every beast of the field;
upon your belly shall you go, and dust shall you eat, etc.
And I will put enmity between you and the woman, and between your seed and her seed;
it shall bruise your head, and you shall bruise his heel.`"
So the Lord sent Adam forth from the garden to till the ground, etc.,
and placed at the east of the garden of Eden cherubims,
and a flaming sword which turned every way, to keep the way of the tree of life.

O miserable change!
O deplorable alteration!
O lamentable state! Undeclarable, undone condition! Inexpressible fall!
What!
He that was in the image of the incorruptible Being,
a living soul inhabiting in the garden of the Lord, where the tree of life was,
and the splendour of the glory of the Divine Being was known and enjoyed,
driven from all into the earth; and not only so,
but the cherubims and flaming sword that turns every way,
placed to keep the way of the tree of life!
Be astonished, O heavens! at this, and be horribly afraid, O earth!
The Lord God brought up children, and they rebelled against him.

Now what was the cause and ground,
O sons and daughters of Adam! that brought this wonderful change,
that brought man into this deplorable state and condition?
Was it not disobedience to the righteous law of God?
Did not sin enter into the world through disobedience, and death by sin?
And is not sin continued in the world through disobedience?
Is there any other way by which sin enters now, than it did then, and death by sin,
which has reigned over all, and reigns over all who are in the fallen state from God,
even over them that have not sinned according to the similitude of Adam`'s transgression?
For all have not sinned according to his similitude,
who was deceived with an expectation of a higher state than
that in which the Lord God had placed him.
But all iniquity, of what similitude soever, is one in the ground,
and becomes a separator of man from his God.
So the ground of all iniquity and transgression that ever was, is, or shall be,
is man`'s disobeying the righteous law of God, disobedience whereunto brings death.

But what was that which in Adam died?
And what was the death?
Seeing that the Lord said, In the day you eat of the tree, before mentioned,
you shall surely die; and yet, though he did eat thereof, he lived outwardly,
and had children.

It was the inward man that died, which was so made by the living breath of the Almighty;
for man going out of the counsel of the Lord,
by his disobedience came to be alienated from the life of God,
and so became insensible of that primary life in which he was wholly a right seed,
and a noble plant.
In his degeneration he became inwardly dead;
the inward senses of the inward man were lost; the inward ear was stopped;
the inward eye was blinded; the inward sense of tasting how good the Lord is,
the inward feeling after the divine virtue, which is all power, life, love, and joy,
the inward sense of smelling his garments,
that smell of myrrh and of the spikenard spiritually, were all lost; and instead thereof,
an ear opened, that hearkened to the voice of the stranger; and an eye opened,
that saw the forbidden fruit pleasant and desirable; the heavenly clothing of innocency,
meekness, and resignation lost; and thus he came to be without God in the world;
and here, in this state, man was altogether out of a capacity of abiding in the garden,
or partaking of the heavenly tree of life that was in the midst thereof;
and in this state are all the unconverted sons and daughters of men,
notwithstanding all fig-leaf coverings of professions.

But as the law of the spirit of life breaks forth in its manifestation,
and the sons and daughters of men come with it to be awakened,
they will have the sight and true sense of their inward state and condition,
which will indeed cause a cry to arise in the soul, O wretched state!
O miserable condition!
And here the entrance of sin come to be seen, which has brought death;
for the wages of sin is death, which was the death that came over Adam,
and over all since, that have disobeyed the righteous spiritual law of God,
which is just, holy, and good, and was before transgression; which law brings to Christ,
the promised seed, the gift of God, which is eternal life.

Now, man being thus departed out of that nature, image and seed,
in which man had his being before transgression,
is become the degenerate plant of a strange vine before the Lord God that made him.
And from the sons and daughters of men,
as they stand joined to this nature and seed of the serpent,
which has defiled man in soul, body, and spirit,
proceed these branches and fruits of iniquity, namely; pride, envy, emulation, strife,
variance, debate, hatred, wrath, anger, murder, inordinate affection, concupiscence,
lasciviousness, wantonness, vanity, uncleanness, fornication, adulteries,
love to this world, drunkenness, revelling, idleness, swearing, cursings, cheating,
defrauding, double-dealing, evil-speaking, back-biting, covetousness, idolatry,
witchcraft.

Man being thus fallen from God into this miserable, deplorable state, the Divine Being,
in his endless, boundless, fathomless lovingkindness,
has opened a way by which mankind might be restored up to himself again;
which way is the promised seed, concerning whom he said to the serpent,
I will put enmity between you and the woman, and between your seed and her seed;
it shall bruise your head, and you shall bruise his heel.
So herein was the tender mercy of the everlasting God extended unto mankind,
in giving the seed, namely, Christ Jesus; else all would have been as Sodom,
and like unto Gomorrah, which God destroyed with fire in his wrath:
so this is that one seed, on which he has laid help, who is mighty to save,
who is the image of the invisible God, the first-born of every creature;
in which image man was before the transgression,
who was glorified with the Father before the world began.
This is He, of whom in the name of the great Jehovah, I give testimony,
that He is the way of life and salvation;
and that there is no other name by which any man can be saved, than by Him who was,
and is, and is to come; who was from everlasting to everlasting, the Rock of Ages,
which followed Israel, and was in the church in the wilderness,
as Stephen testified before he was stoned to death.
This is He, who is without beginning of days, or end of life;
who in the fulness of time was manifest, taking on Him not the nature of angels,
but the seed of Abraham, for whom there was a body prepared,
in which to do the will of his Father; who, after He had accomplished it,
ascended where He was before, far above all heavens, that He might fill all.
This is the Emmanuel, God with us; Jesus, the Savior; Christ, the Anointed;
who has been called by several names,
and spoken of under several denominations and appellations,
through the mouths of his servants,
the prophets and apostles in ages and generations by-past.
This is the only Beloved of the ransomed, and this is our Friend.

And now He is arisen and arising, who is the Ancient of days, in the might of his power;
and is revealing himself the good old way, and path of life,
whose out-goings have been from everlasting; in which way Abel, Seth, Enoch, Noah,
Abraham, Isaac, Jacob, and all the servants, prophets, apostles,
and saints of the Most High God walked, through all ages and generations;
which way was before all the invented ways and worships were,
which have been set up in the will and time of man; for all the holy men of God,
and saints of the most high, worshipped God in the spirit of holiness,
in which they were accepted of Him, who is the God of the spirits of all flesh.
And no outward performance whatever, performed by any, through ages and generations,
was any farther acceptable unto the Lord, but as performed in this spirit.

[.old-style]
=== Section 3. / The Way of Restoration Out of the Fall, Into the Image of God Again, In Which Man Was Before the Fall, etc.

But how salvation comes to be wrought by Him,
and how mankind may be brought again into Him, who is the way, the truth, and the life;
and brought from under the power and dominion of the seed of the serpent,
in which by nature all have been the children of wrath,
is indeed the thing that lies on my spirit weightily to demonstrate,
having obtained mercy to see this way of life and salvation revealed and opened;
and not only so,
but a necessity has been and is upon me to preach the gospel of Christ Jesus,
and declare the way of life and salvation to my countrymen,
through this island of England; and now a necessity is also upon my spirit,
to leave a testimony of the same on record.

This is generally confessed, that in the first Adam all die, and in the second man Adam,
Christ the Lord, all shall be made alive.
But how mankind comes out of this state of death, in the first man Adam,
into this state of life in the second Adam,
is that which the wisdom of this world never knew, never saw, never understood,
nor comprehended truly or rightly.
Man, by that wisdom,
has only imagined and conceived something in the carnal mind concerning this great mystery,
and therein has set up many inventions of the way of life and salvation.
And into these many ways of man`'s inventions and imaginations,
set up in the fallen wisdom of man, there have been the several calls, lo here, lo there;
but the day is dawned, and appearing, and now breaking forth more and more,
(magnified and praised be the name of the infinite,
almighty God,) wherein all invented ways, set up in the will and wisdom of man,
that is earthly, sensual and devilish, shall come to an end.

And now, in the name of the mighty God, all the graven images, the work of men`'s hands,
and earthly wisdoms shall be broken to pieces and ground to powder;
the mouth of the Lord of Hosts has spoken it,
who will perform it by the might of his arm, and by the strength of his power.

And therefore, tremble, tremble, all you image-makers of all sorts,
who have been making and framing likenesses of the way of life and salvation,
in your fallen wisdoms and corrupt wills, and have made gods thereof, and have fallen,
bowed down to, and worshipped them; so that it may be said of christendom, so called,
as it was once said of Judah, according to the number of your cities are your gods,
O Judah.

But now is the fulness of time come and coming, wherein the ancient way of holiness,
in which the righteous walked through all ages and generations, is cast up,
manifest and manifesting; which way is Christ Jesus,
the gift of the Father`'s love unto the sons and daughters of men,
who has as before-mentioned, been preached up and declared of by his servants,
messengers, prophets and apostles, under several denominations and appellations,
according as he was pleased to manifest himself in and to them,
and as his Spirit gave them utterance.
Among many other appellations, he has been declared a Priest forever,
after the order of Melchizedec; the Rock that followed Israel,
who was in the church in the wilderness; a King; a Law-giver; Wonderful; Counsellor;
Prince of peace; a Branch; a Light to lighten the Gentiles; the Arm of God`'s salvation;
a Covenant; Messiah; a Leader; a Commander; a Captain; the Horn of Gods Anointed;
a Stone of stumbling; a Foundation laid in Zion; the Corner-stone; the Word of God;
the Word that was in the beginning; the True Light,
that enlightens every man that comes into the world; the Truth, the Way, and the Life;
King of kings; Lord of lords; Christ; Emmanuel; Jesus;
the Beginning of the creation of God; the First-born of every creature;
the First-begotten from the dead; the Faithful Witness; Alpha and Omega;
Bright and Morning star; the Image of the invisible God; the Offspring of David.
Under these, I say, and other names and denominations,
has he been spoken and declared of, and by;
who still has a name that no man knows but himself,
who is that one Eternal Fountain of blessedness, and the one previous Savior;
and there is no other besides him, although diversely denominated,
according as his Spirit gave utterance,
to demonstrate him to those unto whom his servants spoke, prophesied, and wrote.

And now, by the ancient power of the holy everlasting God, is he preached up,
under the denomination of LIGHT, in this island of the Gentiles,
according as was prophesied of old, by Isaiah, chap.
xlix.
6, who said, "`It is a light thing that you should be my servant,
to raise up the tribes of Jacob, and to restore the preserved of Israel;
I will also give you for a light to the Gentiles,
that you may be my salvation unto the end of the earth;`"
which is one with the testimony of John chapter 1, saying,
"`In the beginning was the Word, and the Word was with God; and the Word was God.
The same was in the beginning with God.
All things were made by him, and without him was not anything made that was made.
In him was life, and the life was the light of men.
And the light shines in darkness, and the darkness comprehends it not.
There was a man sent from God, whose name was John.
The same came for a witness to bear witness of the Light,
that all men through him might believe.
He was not that Light, but was sent to bear witness of that Light.
That was the true Light, which enlightens every man that comes into the world, etc.`"
And to this agrees the testimony of just Simeon, who came by the Spirit into the temple,
and took the child Jesus into his arms, and said, "`Lord,
now let your servant depart in peace, according to your word;
for my eyes have seen your salvation,
which you have prepared before the face of all people, a light to lighten the Gentiles,
and the glory of your people Israel.`"
This is he of whom we testify, whose light is the way of life:
And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
For everyone (mark) that does evil hates the light, neither comes to the light,
lest his deeds should be reproved.
But he that does truth comes to the light, that his deeds may be made manifest,
that they are wrought in God.

Now this Light, which the servants of the Most High testified of,
is that which has been spoken of and denominated under several names:
for this manifestation of God in man, is sometimes called the Word, the Spirit, the Law,
the Grace of God; now the Word, Light, Grace, Law, Spirit, are all one in nature,
although diversely named: Moses called it the Word,
and directed to this Word in the heart and in the mouth; which Paul,
that illuminated man, rehearsing, says,
"`Say not in your heart (mark) who shall ascend into heaven?
(that is, to bring Christ down from above:) or, who shall descend into the deep?
(that is, to bring up Christ again from the dead.) But what says it?
The word is nigh you, even in your mouth and in your heart; that is,
the word of faith which we preach.`"
This is the sure word of prophecy, unto which Peter directs to take heed,
as unto a light that shines in a dark place,
until the day dawn and the day-star arise in the heart.

This Light is the law of the spirit of life, wherewith Paul was acquainted,
that warred in his mind against the law of sin and death, which was in his members:
this Light is the law in the heart and the spirit in the inward parts,
the new covenant of God Almighty; this is that which converts the soul;
which law Paul delighted in according to the inward man: this law is light,
of which the scriptures of truth plentifully testify:
this is that grace that Paul declared, brings salvation, which has appeared to all men;
which Law, Light, Spirit, Grace, Gift, has in measures, as God`'s talent,
appeared to all men, which teaches all that are led, taught and guided by it,
to deny all ungodliness and worldly lust; and not only so, but also to live soberly,
righteously and godly in this present world.
This is that grace which the Lord, the giver thereof,
said to Paul was sufficient for him, to deliver him from the temptation,
the thorn in the flesh; of which the same apostle said unto the Ephesians,
"`By grace you are saved, etc.`"
And this is the manifestation of the Spirit spoken of by Paul,
which is given to every man to profit withal.
And this is that good Spirit of the Lord given to Israel, who rebelled against it,
as the old world did, unto whom the Lord said,
"`My Spirit shall not always strive with man;`" of which Word, Law, Light, Grace and Spirit,
given to be the Leader and Guide of mankind out of sin, and death, and darkness,
into which man fell through disobeying the righteous law of God, as is afore declared,
the Holy Scriptures give clear and full testimony, as has been demonstrated.
But now, that which is ready to arise, is an objection in some,
(whose understandings are not opened, whose searchings to comprehend,
and inquiries after the way of man`'s salvation, stand in that wisdom that is from below,
and in the will and reason of man degenerated from
the life of God,) whether the preaching up this Word,
Light, Law, Spirit and Grace of God manifest within,
has not a tendency to make Christ Jesus`' appearance in the flesh, his sufferings, death,
resurrection and ascension to be invalid?
Unto which I answer, no; forasmuch as no persons ever did, do, or shall truly see,
discern, know,
understand or enjoy the benefit of Christ Jesus`' manifestation in the flesh,
but as their hearts were, are or shall be opened,
and understanding illuminated by the light;
which is a measure of the Divine fulness that dwelt in him, and is communicated to,
and placed in all immortal souls, as the universal love of God;
extended in the Son of his love to all the families of the earth,
as the revealer and discoverer of the will of Him from whose divine fulness it comes,
and issues forth itself universally: for the Scripture thus witnesses,
that no man knows the things of a man, save the spirit of man which is in him;
even so the things of God knows no man, but the Spirit of God.

The hearts of the Jews not being seasoned with this grace of God,
and ignorant of the gift of God, which is eternal life, they neither discerned,
loved nor received Christ Jesus, when manifested in that outward bodily appearance,
but rejected him; notwithstanding they professed love, honour and regard to the prophets,
and were in expectation of the fulfilling their prophecies of the coming of the Messiah,
who in due time came, and yet they did not receive him; but instead thereof,
set themselves against him, taking counsel from time to time how they might slay him,
though in words they professed an earnest waiting for him: so in this day,
age and generation, there are many,
who by their words do profess they believe his coming in the flesh, and his sufferings,
death, resurrection and ascension;
but yet having their faith consisting in outward notions,
and having no inward experience of the end of his coming,
nor of the virtue of his sufferings, death, resurrection, etc.,
they are enemies in their minds to his second appearance,
and coming without sin unto salvation.
So there is a necessity for all the sons and daughters of men to come to,
and obey this divine, spiritual principle,
which is placed in their consciences by the living eternal God,
that thereby the eye which has been blinded through disobedience,
by the god of the world, may be opened; for, until this in some measure be effected,
the mystery of godliness, which is great, can neither be seen nor understood;
and therefore Christ said, finding the woman of Samaria ignorant of himself,
who was and is that great mystery, and the gift of the Father`'s love,
"`If you knew the gift of God, and who it is that says to you, give me to drink,
you would have asked of him, and he would have given you living water.`"

The travail in spirit of the messengers and servants of the Most High in ages past,
was the same as now it is, namely, to turn people from darkness into light,
and from the power of Satan to the power of the living God;
thereby in no way invalidating Christ Jesus manifestation in that bodily appearance,
neither his sufferings, death, resurrection or ascension;
but bringing all people guided thereby,
unto that which will open the eyes of their understandings,
whereby they all come unto such a condition and spiritual understanding,
as to see and know their benefit by that appearance of the Savior of the world;
for this we testify, all are perfected by that one offering, that are sanctified.
But here arises another objection by some, who may come so far as to own and confess,
that there is a principle or light in man, that discovers sin,
and teaches man to do justly and equally, which some call morality;
but that this light or principle in man, is of a saving property,
and of the nature and quality of the Divine Being,
many for lack of understanding do deny; and so are found opposers of Truth itself,
and stumble at the cornerstone; which indeed in all generations,
has been to many men a stone of stumbling and rock of offence; which thousands,
giving themselves up to be guided by their own wisdom and prudence, reject; yes,
those accounted the wise master-builders, professors of God and Christ,
being ignorant of the root and offspring of David,
have and yet do reject this corner-stone.

Now, for the sake of all who do or may desire after the
true and saving knowledge of Christ Jesus,
it is on my spirit yet further to open and manifest
the nature and property of this principle and light;
whose fountain is the Eternal Being, and everlasting ocean of Divine fulness,
and its nature and quality is one with this fountain from which it comes.
John testified, In the beginning was the Word, and the Word was with God,
and the Word was God.
In him was life, and the life was the Light of men.
He also testified, that he was not that Light, but came for a witness, to bear witness,
that that was the true Light, which enlightens every man that comes into the world:
so the original of this light is Christ Jesus, the Word.

But some may query thus, is Christ the Light in every man?

To which I answer; Christ does appear by his light in every man; and the light,
which comes from Christ, is in every man;
as is clearly demonstrated in the Scriptures of truth: and,
though I account it unnecessary to answer the curious inquiries of such,
who seeking to know much, do not walk answerable to what they know;
yet for the sake of such whose understandings are not opened,
and yet are inquiring the way to Zion, I add this similitude:
the natural sun is placed by the Creator to lighten the outward world,
and does extend from its body a measure of its light and natural property,
shining on the just and the unjust,
and so does daily give forth of that virtue which is inherent in itself.
When the sun shines on any object whatsoever, we sometimes say, the sun there appears;
and other times we say,
There is the sun; the propriety of either of which manner of expression, I suppose,
none will question; for light in that appearance is seen, and virtue is felt,
penetrating to the refreshment of our natural bodies;
and this light and heat is inseparable from the fulness:
and notwithstanding it daily shines,
and displays its virtuous life into and over all the earth and its inhabitants;
yet its body is not any way exhausted or altered through ages and generations.
And so I say, that Christ, the universal fountain of Life, the Sun of Righteousness,
the ocean and fulness of spiritual light, life and virtue,
from which is communicated a measure of his nature, property and quality,
is given of the Father to enlighten all the sons and daughters of men;
who accordingly are all enlightened with his spiritual appearance;
and though this appearance cannot be called the fulness,
yet being a measure of that fulness, it is one in nature and property with,
and inseparable from the fulness; and though through its virtue,
life is daily communicated unto the sons of men, who waiting for the appearance thereof,
as for the morning light, cannot live unto God without it,
yet does he admit of no diminution, alteration or change;
but all fulness of Divine light, life and glory, does and shall,
through every age and generation, remain with him:
and albeit the veil of darkness has over-shadowed the hearts of some,
so as when we give testimony unto the universal appearance of the Sun
of Righteousness in the hearts of all the sons and daughters of men,
they are ready to say,
such a testimony leads to the diminishing of that
glory and honour which belongs unto Him,
as He is the fulness, and sitting at the right hand of the Father;
inferring from such our testimony, as if,
while we testify to his appearance in our hearts, we exclude his presence elsewhere:
which inference, I say, is as irrational as it would be for any to conclude,
that because we say of the shining and appearance of the sun, there is the sun,
or the sun there appears, therefore we exclude the being of the sun elsewhere:
for its virtue is communicated to our natural bodies,
every one having in measure some enjoyment of the virtue or light of the natural sun;
which is light to the eye, even as the outward eye is light to, or of the natural body;
and whosoever they are,
whose invisible sense are quickened by the influencing
virtue which proceeds from the Eternal Sun of Righteousness,
do thereby see and discern,
that these things are according to the clear manifestation
of Truth in their inward parts;
and from a true sense thereof, can of a truth give this certain testimony,
that Christ the Lord, by his holy quickening Spirit, has appeared in them,
to the quickening of their immortal souls;
and that through believing in the Light and obedience to his appearance,
being come out of that state which is reprobated by the Lord,
can of certain experimental knowledge say, Christ is in us the hope of glory.

And so, when we direct people to this Word, Light, Law, Grace and Spirit,
we do not thereby intend that Christ Jesus, the Light of the world, and gift of God,
is not the true Savior, Redeemer, and Reconciler of mankind unto God.

Now this Word, Light, Law, Grace and Spirit, which is one in nature,
does lead and guide the souls and spirits of all such as obey it, up to God,
the fountain from whom it comes; and no man comes to see its nature,
but such who are led by it; for in the light of the Lord alone, man comes to see light,
and to have an understanding from which it springs.
Before this be fully seen or understood, the mind of man must be brought down,
out of all its own willings and runnings, comprehendings and searchings,
into the principle of light, therein to see a death to his own will,
and be comprehended into this light;
and so man comes to have an understanding to know Him that is true,
and to be in Him that is true.

Now, as any are convinced of, and converted by this heavenly principle,
(which is placed in the conscience,
there given to be a guide and leader unto mankind,) they are led thereby out of darkness,
wherein they have been, while yet the light shone in darkness;
in which darkness no man ever comprehended this light or heavenly grace,
which sometimes moves through the darkness, on the depth of man`'s understanding,
reproving and discovering darkness, causing man to hear its small still voice,
moving in man Godwards; and so daily continues without change,
reproving man while he remains in rebellion and disobedience,
all the time of his visitation,
and approving and giving peace unto man when he is obedient.

This principle of light remains entire in its own purity;
and although man may change and alter, and go from it, and rebel against it;
and thereby become one of them of whom Job speaks, that rebel against the light,
and thereby know not the way of it; but give way to the working of the god of the world,
to be drawn out into the fading perishing things;
yet this principle remains immutable in itself, being of and from the immutable,
unchangeable Being, and remains with man, until it be taken from him,
and he be cast into utter darkness.

The first operation of this heavenly Light, among those who are convinced by,
and turned to it, the gift of the Father (which Christ Jesus, in his parable to the Jews,
compared to a grain of mustard seed; and to a little leaven,
which a woman took and hid in three measures of meal,
until the whole came to be leavened,) is, to show man his inward state and condition;
and the first step in the way of life, is, to be turned to this holy principle,
that teaches the obedient to know God savingly;
and when by this principle man comes to have a true sight and sense of his fallen state,
and sees how he has transgressed against that Eternal Being that gave him life and breath,
who notwithstanding in his long-suffering, waits still to be gracious,
and knocks at the door of the heart, and has striven by his Divine light,
the true sight and sense hereof will break the heart,
and tender the spirit before the Lord;
and under the weighty sense of the great burden of sin and iniquity,
there will be a crying out, my sins they are too heavy for me to bear,
and my iniquities are gone over mine head; as Paul did, saying,
"`O wretched man that I am! Who shall deliver me from the body of this death?`"
And here comes the eye to be opened that sees Him, whom man, in his disobedience,
has pierced afresh and put to open shame;
and then there will be days of mourning and wailing, because of Him;
and this is truly the day of Jacob`'s trouble.
And in the sense of this deplorable, fallen state, and the long-suffering of the Lord,
and the long-striving of his Spirit, you will see, that in the justice of God,
eternal death might be your portion; but that which brings into this sense,
begets a secret cry in the immortal soul, after a deliverer and Savior;
and will also give a true sense and sight,
that there is no way for your soul to be ransomed,
but in and through the tender mercies of God through Jesus Christ;
which you will see can no other way be effectually begun in you,
but in the way of the judgments of the Lord; for Zion shall be redeemed with judgment,
and her converts with righteousness.
And here also you will see that the measure of the sufferings of Christ yet behind,
must be filled up in you; for no other way can any man pass unto life,
peace and joy with the Father of spirits, but the way the Captain of Salvation passed,
which was through death; and here you will begin to arm yourself with the same mind:
for none ceases any further from sin,
but as they suffer in the flesh the crucifying of the affections and lusts thereof;
and here the end of the gospels preaching comes to be known and witnessed,
which was and is, that they might be judged according to men in the flesh,
but live according to God in the Spirit.
And in this spiritual inward sense and exercise,
the Lord God Almighty will bow down his ear, and answer the cries of your awakened soul,
and manifest his word of power;
which all in this state and passage will know to be sharper than any two-edged sword,
piercing,
to the dividing asunder of your immortal soul from the spirit and nature of transgression,
and its working daily, as subjection and obedience is yielded unto it;
dividing and making a separation between joints and marrow,
giving you daily a discerning of the thoughts and intents of your heart.

And as the soul, mind, and heart, gives up in love to God,
freely to follow him in the way of his judgments,
and gives up to the sword of the Lord that which is for the sword;
and that which is for destruction to be destroyed;
thus will the precious work of the Lord prosper.
And although this be a time of sorrow, and a time of trouble, travail and anguish; yet,
notwithstanding, it is a good day: therefore, strive not to get from under it,
neither to make haste; for the true godly sorrow works the true repentance,
which is never to be repented of.
And after the true repentance, follows the true knowledge of remission and forgiveness;
and so your iniquities, by the judgments of the Lord God Almighty,
come to be blotted out;
and then the times of refreshment come from the presence of the Lord,
and from the glory of his power.

And as there is a faithful abiding in inward watchfulness,
and continual obedience to this heavenly light,
in which the beginning of the work of God was known,
there will be a going on from step to step in the footsteps of the flock of Christ Jesus,
and a growing from strength to strength over sin and the nature thereof,
and from one degree of grace to another;
and as there is a faithful perseverance in this divine principle,
the eye of the understanding will be single; and here everything which has or does let,
will be seen, and the soul never start aside from an inward travail,
until that which hinders be taken out of the way,
and until you see all the rule and authority of the enemy
to be subdued under the feet of the Lords anointed,
and the government in the soul upon his shoulders, whose right it is to reign over all.

And here salvation, redemption, and restoration is effectually enjoyed through faith,
and the effectual working and operating of the almighty power and arm of God Almighty,
unto whom be the glory of his own work forever;
and so here will be a growing and increasing,
until there is a coming into that precious state and image,
in which man was before he fell.

[.old-style]
=== Section 4. / The By-paths, Crooked-ways, Wiles, and Snares of the Enemy Discovered.

Now when the mind is turned to this divine heavenly principle,
and that therein the work of the Lord is begun, which before is said,
is the bringing man into a real, sensible knowledge of his state and condition,
then will the same destroyer, that brought man into bondage at first,
and has kept him in bondage, begin to work cunningly,
and every way endeavour to destroy the work of God begun in the soul;
and that he may accomplish his end, he will go about every way, seeking an entrance,
and will lay his temptations suitable to the propensity or inclinations of the creature.

If the heart and mind be bowed down under the weighty sense of iniquity,
the sins committed coming in order, and the many transgressions in sight,
through which the sorrow and bitterness is great,
here the enemy will work in his transformings, and although in appearance like the light,
yet in nature contrary thereto: for,
albeit the light and appearance of God gives the
certain understanding of the inward state,
and brings sorrow because of sin,
and shows the mountain of iniquity and the exalted hills of transgression,
yet its workings inwardly beget a secret hope of overcoming by the Lord`'s strength;
but then the enemy, when he sees the soul bowed down, as aforesaid,
oftentimes afflicts and brings down the mind into unbelief of ever overcoming,
thereby endeavouring to sink the soul down into despair; knowing, if he overcomes,
he still keeps under his power, although in another appearance;
but to all that are exercised in this kind, waiting on the Lord singly,
with the mind stayed in the light, this snare will be discovered; for, as I said,
although the true appearance of God`'s heavenly light and grace brings a day of trouble,
sorrow and anguish; yet that sorrow is not a sorrow without hope;
but the enemy`'s working is, to bring into a sorrow, trouble and anguish without hope,
and to draw down the spirit into the chambers of darkness, where there is no order.

But now, when the enemy of the soul`'s peace is discovered in this his working,
and the heart and soul, through the love and power of God, is comforted,
encouraged and refreshed, and raised up into a measure of the living hope,
satisfaction and content; then the old, crooked, subtle serpent,
endeavours to lead from off the inward, daily travail,
(that so judgment may not be brought forth unto victory;) and to
draw up the mind into a false persuasion of obedience and diligence,
when as there is not an abiding in that which gives
a true sight and sense of the state and condition.
And as before, he would have destroyed the hope that is an anchor sure and stedfast,
so now on the other hand, he would beget a false hope and confidence,
and so bring out of the daily cross,
through which the nature which has alienated from God, should be destroyed.

And if the workings of the enemy be seen and overcome in both these wiles and snares,
on the right hand and on the left,
and that the work prospers even until much be subjected; and that,
through the daily obedience to the heavenly power, much is slain;
and that the heart and mind comes in a good measure to be cleansed;
and that in pure obedience and constant faithfulness, in this light of righteousness,
a good progress is made through the administration of condemnation,
that is glorious in its time;
and that something of pure peace and heavenly joy
springs and arises in the heart and soul;
here again the enemy will be subtly at work, to betray and lead aside,
in persuading to sit down now, as if all were done;
and so lead out from the feeding on the tree of life,
to feed on the tree of knowledge of good and evil,
and into a liberty to break the commandment of the Lord;
and here at first subtly and cunningly draws the
mind out so far as to take a little liberty,
and draws the mind somewhat from that diligent watchfulness, dread,
fear and awe it was in before, in the inward travail of spirit.
And here, if the destroying subtle enemy can but prevail a little,
he will lead out of the innocent harmless life, and so gradually lead a little forth,
and by degrees open an eye that may see something in the outward visible things,
that may somewhat affect the mind; and as here he prevails,
and causes his work to prosper, which he does subtly, gradually and hiddenly,
the eye that was opened comes again, through disobedience, to be in some measure blinded;
and here loss is sustained, even before the unwatchful is aware.
And so the working of the enemy first is,
to cause such to make shipwreck of faith in a little measure; that is,
not to have the daily belief stand in the power; the daily enjoyment of which,
coming to be left by degrees, there will then be a turning from the power of godliness,
into the form thereof.
And although at sometimes the eternal power of the Lord God may be felt in this state,
yet there being not a daily feeling after it, the enjoyment thereof,
as to true refreshment and consolidation, comes to be lost,
and an image comes up in its place;
and the enemy provides and presents some object or objects so to take up the mind,
as that by degrees he may enter in, and defile the mind,
and draw it out from its true guide, so as also to make shipwreck of a good conscience.

And now, if the enemy be discovered in these his workings,
before he can so effect his work, as to bring death and darkness over again;
and that the power of the Lord breaks his snares, and gives a true weighty sense thereof,
through which trouble and anguish of spirit comes; here he will again transform,
and begin to work, as in the beginning of the work,
like the condemning power of the Lord;
endeavouring to lead the mind down into despair of
ever recovering again into the former condition;
and hereby endeavour to draw the mind to look at him that has stung, that so the remedy,
the soul-ransoming power of the Lord, may not be felt after, nor looked at.
But here, as there is a true regard to the Lord,
and a waiting upon him in the way of his judgments,
having the faith and confidence to stand in his power, the backsliding will be healed;
and returning and diligently keeping in the light,
the power of the Lord God Almighty will work over that which has hurt,
and endeavoured like a roaring lion to destroy, etc., and so lead on the way again.

But when deliverance is known again from this deadly snare,
and the work again goes on prosperously until the house be swept and garnished,
and there is a passage known and witnessed from death unto life,
and the administration of condemnation being passed through,
and the spirit that ruled in the disobedient state cast out,
and the openings of that which does exceed in glory, the administration of the Spirit,
being known, here the enemy will again transform,
and with all his power and strength in the transformation, as an angel of light,
work by his temptation on the right hand and on the left.
For when there are openings to the understanding and prophecies,
and through the working of the Eternal Power, joy springs in the heart,
then will the enemy work secretly and cunningly; and if he prevails here,
to draw out of this habitation of safety,
then he will transform to lead the mind out through
the motions of his transforming spirit and power,
into extremes, thereby endeavouring to destroy the true birth, which is bringing forth;
and so bewilder the mind and hurry it forth, through imaginary notions,
to dishonour the name of the living Eternal God, and to destroy his work,
which through sorrow and travail has been brought forth.

And if he cannot prevail here, but the light of the Lord discovers him,
and the power of the Lord works over his appearance herein,
then will he be at work to draw the mind out of the watchfulness,
out of the daily awe and fear, and out of the liberty of the sons of God;
which liberty is, only to serve the Lord: for dominion being felt in some measure,
the morning of comfort and consolation enjoyed,
and praises springing in the heart of Him that visited and redeemed,
the enemy will be ready here also to draw the mind out of the valley of humility,
out of the stayed state of meek and constant watchfulness in the light;
thereby causing the creature prodigally to spend the portion and to lavish out the enjoyment,
by running and climbing up to sacrifice upon the mountains,
and to run before the leadings, guidings and movings of the power of the Lord,
into the speaking forth of the enjoyment, the prophesyings and openings;
not being led thereunto by that Eternal Power that first opened the heart:
and here is the ground of the untimely birth that has been brought forth,
that +++[+++has withered; and such]
will wither and come to nothing.

But now, where the enemy is seen and discovered in all the aforesaid workings,
and cannot prevail by these snares, traps, gins and temptations aforesaid,
he will not cease, who goes about as a roaring lion, seeking whom he may devour,
and how he may again get entrance;
so that he lays his temptations according to the spirit, growth,
capacities and inclinations of every one.
Now after the good work of God has been begun prosperously,
and that the right arm of God`'s salvation has been wonderfully revealed,
and signally manifest to bring out of Egypt`'s land of darkness spiritually;
and that the Lord has magnified his arm spiritually,
in giving many signal deliverances from the destroying enemy;
and has often fed with the heavenly food,
and caused the rock to yield water for the thirsty;
and that the many turnings aside in the passage through the wilderness have been seen,
and the backslidings and going out from a sense of the Eternal Power,
have been discovered; and that there is a coming through the river of judgment;
and the mighty power and arm of the everlasting God drives out the enemy that has inhabited,
where only Abraham`'s seed is to inhabit; and that the war in great measure ceases,
and part of the good land is possessed and enjoyed,
even the land that flows with spiritual milk and honey,
and the fruit of the vine drunk of; here also, as in the travails afore-mentioned,
will the old crooked, subtle enemy be working, as he did with outward Israel,
causing Jesurun to wax fat, and then kick against the ancient Power;
leading the mind out, through the enjoyment of that which in its place is good,
into ease; and so to forget the Lord that made and formed man,
and brought him into the land of rest, and lightly to esteem the very rock of salvation;
and so leads into an easeful state, in a profession;
and draws away the mind from the inward enjoyment of virtue,
to set up idols in the heart, and to serve other gods, even gods of silver and gold,
and an idol, a profession without life and possession:
and into this state and condition did the old enemy prevail to lead a people,
who in many ages had seen the great and mighty works of the Lord,
who saw from time to time the arm of God Almighty out-stretched
and magnified in the sight of their enemies for them;
howbeit they departed from the Lord, and from the inward sense of his Eternal Power.
Now here the spirit that was cast out, and wandered in dry places,
takes to it seven worse spirits, and returns, tempts, prevails and enters;
and here indeed the latter end is worse than the beginning; for in the beginning,
although the enemy had his power and rule, yet there was a sense thereof,
and the heart and mind was humbled, tender, and brought into the true poverty;
and there was a mourning before the Lord for lack of the dominion;
_and this state of humiliation, brokenness of heart, and tenderness of spirit, +++[+++is that]
in which the Lord took and takes delight; and therefore in his endless,
boundless lovingkindness +++[+++has]
visited and caused his redeeming saving power and arm to be revealed:
but now in this other state, the mind is high, the heart fat and full, and at ease,
and gotten forth into the love of the world, and the things thereof,
through which there is an unmindfulness of the Lord,
who in the beginning was every day sought after, and diligently waited for;
and here the Rock, the Power, is lightly esteemed of;
for the estimation is of another thing:
and here two great evils are committed even at once,
namely, the fountain of the former living mercies forsaken,
and a hewing out broken cisterns, a profession, that will hold no water,
no durable refreshment, no durable joy, no durable peace nor consolation.
And the enemy has thus prevailed through many ages,
to bring thousands from their enjoyment of God, in the pure, tender, broken, contrite,
upright-spirited state, which he does effect through his workings and subtlety,
and that gradually: his first footsteps hereunto is, to bring out of the constant, daily,
sure watchfulness,
and causing a little liberty to be taken to the carnal
mind and to the flesh and that gradually,
and, as it were unperceivably; causing such to take, as it were, a taste,
a certain enjoyment of sweetness therein, and thereby a little darkening the sight,
and so alluring into a little more liberty:
sometimes his beginnings are to draw out of obedience in
those things that were required in the day of small things;
sometimes into many words, out of watchfulness,
no more to be as a door-keeper in the house of the Lord,
and so the enemy works to cause such-like things to seem small and indifferent things,
thereby to cause the offence of the cross in those things to cease;
and then the heart and mind runs forth to make provision
for the flesh to fulfill the lust thereof,
either in food, drinks, apparel, or such-like,
which the truth in times past has discovered and made manifest, and the power of God,
the cross of Christ, has crossed, and in measure led out of, into watchfulness,
in pure fear and holy awe, not making provision for the flesh, in any respect,
to fulfill the lusts thereof; but drawing the creature in practice,
as well as in principle, into plainness, and out of all superfluities,
admitting of the creature to refresh nature, and not feed the lusts._

But yet the enemy works by degrees, subtly and covertly,
to lead out of the liberty of the cross of Christ Jesus, the power of God unto salvation,
into the liberty of the flesh again, and hereby gets a little further entrance;
and though the enemy be working to draw forth the mind into a wrong liberty,
as into many words in dealings, in commerce, or converse,
and into the love of the world and the things thereof again,
and yet the profession may remain, and the enemy may be contented therewith; yes,
and many times the power of God may be felt in some measure,
which indeed works not in the approvement, but to draw out of the snare;
but the god of the world having by this time much blinded the eye,
and darkened the heart, and deceived the understanding,
there is not a sense nor knowledge of the mind of the power of the Lord in its workings,
nor a real sense of the decay, and gradual, subtle workings of the enemy;
for the outward profession and conformity may be in a great measure kept to,
which is a cover, under which the enemy may work undiscovered by the unwatchful.
And so the enemy many times leads cunningly step by step,
until he has led out of the power of godliness, and slain the tender birth,
which in the first days of tender visitations was begotten;
and so here will be a growing high, fat and thick; and such +++[+++as are in this state]
will call the operation of Gods dividing power, extremes and imaginations;
and Jesurun-like, will kick and turn against the dividing power of the mighty God;
for all such are best contented with a likeness and image:
for they love the smooth things in the wisdom of the gifted man, that has lost his way,
through erring from the power,
not waiting continually on all occasions to be guided thereby.
So here is the itching ear, and heaping up teachers to please self,
to please that and uphold that; and here Jezebel is permitted and upheld,
which error crept into the church of Thyatira;
and in all ages they that went from the broken, tender state,
into the conditions before +++[+++described]
did and do both allow and nurture this Jezebel, who must be cast on the bed of torments,
and all her children must be killed with death; and all the workings of the enemy,
under every disguise, is to slay that which was quickened,
and to bring in a contentedness with an outside profession of the way of Truth,
Light and Life of Christ Jesus, the power of God unto salvation,
while the heart is adulterated and gone from the Lord, and has embraced other lovers;
and so in process of time, where the enemy thus prevails, he leads again into the world,
from which the arm of the Lord gathered;
and the latter end of such is indeed worse than the beginning:
for the enemy having led to make shipwreck of faith and of a good conscience,
the second death comes over, and such become twice dead,
and become as salt which has lost its savour, and are good for nothing,
but to be cast forth and trodden under foot of men.

_The preservation out of these by-paths, crooked ways, wiles,
snares and temptations of the enemy,
is only in the true waiting and sincere abiding in the light, gift and grace of God,
in which the daily revelations and manifestations of God`'s Eternal Power,
and right arm of salvation and preservation is known,
in the daily acquaintance and experience thereof; which keeps all minds truly low,
and hearts sincerely tender; wherein arises an inward travail, longing,
breathing and panting after the daily and continual enjoyment of the life, power,
and blessed refreshing,
the heavenly virtue which alone renews and increases the strength of the inward man;
in which God Almighty preserve all the travellers towards Zion to the end._

[.old-style]
=== Section 5. / The Utter End and Final Destruction Prophesied, of All False Professions, Which Have Had Their Rise in the Night of Apostasy

After the glorious breakings forth of the day of God among the apostles, etc.,
the enemy wrought mightily against that appearance, both in his instruments,
by and through which he raised up persecution,
and also in those apostates in whom he got an entrance among the churches,
and has so prevailed, that great has been that horrible night of darkness and apostasy,
that has been many centuries in and over the nations of the earth;
in which times the old subtle serpent, in his many transformings and appearances,
has mightily wrought, to alienate man from his God.
O the ways and inventions that have been by him set up,
through his workings in the wisdom which is from below, which is earthly,
sensual and devilish, under pretence of religion, obedience, and worship of God!
What rending, tearing, devouring, murdering and destroying,
has there been for these many hundreds of years about religion?
First, the great red dragon of persecution appeared,
to devour the man-child and destroy the woman, but both were preserved;
then he made war with the remnant of her seed; and after came in another appearance,
which John saw rise as a beast out of the sea, having seven heads and ten horns;
and on his horns, crowns, and upon his heads the name of blasphemy;
and one of his heads had a deadly wound by the sword;
but this deadly wound was again healed; and all the world wondered after the beast,
saying, "`Who is like the beast?
And who is able to make war with him?`"
And all on the earth do and shall worship the beast,
whose names are not written in the book of life of
the Lamb slain from the foundation of the world.
And after this, a second beast appeared, that came out of the earth;
and this beast had two horns like a lamb, but spoke like a dragon;
and John saw he exercised all the power of the first beast,
who received his power and authority from the dragon,
like unto which this second beast spoke; and this beast that had horns like a lamb,
caused the earth and them that dwelt therein,
to worship the first beast whose deadly wound was healed; and he caused all,
both small and great, rich and poor, free and bond,
to receive a mark in their right hand or in their foreheads.
And here has been the universal working of the power and spirit of darkness,
that has exalted himself, sitting in the temple of God as god and ruler.
But, blessed forever be the name of the Almighty God, the great red dragon,
and the beast that arose out of the sea, and the beast that arose out of the earth,
and mystery Babylon, are and shall be manifest.
The wisdom that is pure and peaceable, numbers these appearances.
And the judgment of the great whore is come and coming, who rides upon the first beast;
for now the angel of God`'s presence is come down from heaven, having great power,
who lightens the earth with his glory, and the mighty cry is now going over the earth,
uttered with a strong voice, saying, Babylon the great is fallen, is fallen,
and is become the habitation of devils, etc.
All nations have drunk of the wine of the wrath of her fornication,
and the kings of the earth have committed fornication with her,
and the merchants of the earth are waxed rich, through the abundance of her delicacies;
and the voice is now uttering from heaven, "`Come out of her, my people,
that you be not partakers of her sins, and that you receive not of her plagues;
for her sins have reached unto heaven, and God has remembered her iniquities:
and now is the one day dawning over the earth, wherein her plagues, mourning,
and famine come, and she shall be utterly burned with the fire of God`'s jealousy;
for strong is the Lord God who judges her.`"
And now, in the name of the eternal, ever-living, blessed God, the Creator of all things,
I prophesy of the perpetual destruction and utter desolation of the religions,
inventions, ways, worships, prescriptions, orders, decrees and imitations,
that have been setting up these many hundreds of years, and not by the eternal,
living Power of the living God, nor by the directions,
leadings and guidings of his quickening Spirit of life,
that led and guided the Apostles in their day, age and generation: root and branch,
head and tail, and the whole fabric of the Babylonish building shall be utterly consumed,
razed down and confounded forever;
and all the worshippers of the beast and his image
shall drink of the wine of the wrath of God,
which is poured forth, without mixture, into the cup of his indignation;
and these worshippers shall be tormented, and have no rest night nor day,
who worship the beast and his image, and whosoever receive the mark of his name, etc.

[.old-style]
=== Section 6. / A Call, In the Tender Bowels of the Love of God, Shed Abroad in this Day, Age and Generation, Unto All the Scattered Sheep, etc.

Hearken and give ear, you scattered ones, upon the barren mountains of profession,
who having lost the living sense that was on many of your spirits years ago,
and are now seeking the living among the dead professions,
and your bread in desolate places.
Remember the days, months and years past; call to mind the days of your tenderness,
when the Light of God so shined on your tabernacle,
that by it you saw yourselves in darkness,
and in separation from the enjoyment of your Creator;
which sense brought a day of mourning and bitter lamentation on you,
which was the cause of your fasting, praying, and earnest seeking after the Lord,
with multitude of sighs, groans and tears;
which caused you to put many days and times apart,
to meet together to pour forth your souls in seeking the living God,
for his appearance and breaking forth by his Eternal Power,
and for the revealings of his ancient arm and horn of salvation:
and in that day how did many of you retire yourselves into your closets and secret places,
to mourn before the Lord! and how did your cries, breathings and pantings after the Lord,
prevent the morning-watches!
And in that day was it not substance itself that you sought after,
even the revealings of the Son of God`'s love in your souls?
Let me now come near, and expostulate with you in the name of the mighty God;
even with you, among all professions,
that have any tenderness or breathings after the Lord remaining in you.
_What was it that stirred up your hearts, many years since, thus to seek after the Lord?
What was it that gave you the sense of your own inward conditions?
What was it that made sin appear exceeding sinful?
What was it that you felt in your minds that warred
against the law of sin and death in your members?
What was it that in some measure opened the eye of
your understanding to see idolatry and superstition?
What was it that was drawing your hearts out of the world,
that even made those things of light esteem,
in comparison of that which your awakened souls sought after?
What was it that inwardly upheld you in sufferings?
What was it that you retired your minds unto,
when the wicked raged as the waves of the sea;
when you were mocked for the plainness of your apparel
and for your strictness in your families?
Remember your many signal deliverances:
how did the Lord answer you in the day of your tenderness?
What was it that exercised you inwardly,
moving on every one of your particular souls and spirits for a reformation?
Was it not the free grace of God?
Was it not that Light which shined on your tabernacle?_
Did not this shine in your hearts, and move on your spirits godwards,
and began the inward work of the Lord in you?
Why did you start aside from following on toward the Lord in the way of his judgments,
when a little prosperity attended you?
Why did you seek to get from under the judgment, before it was brought forth unto victory?
Be awakened and come back, you professors of all sorts,
that have thus turned aside for a thing of nought,
which has caused you to wander from one mountain of profession to another,
and from one exalted hill of imaginations and conceivings to another,
until you have spent all your portion, and are in nature returned to Babylon,
the city of confusion, out of which the Lord God Almighty thus calls you, hasten,
hasten to come forth, and partake no longer with her in her sins,
lest you partake with her of her plagues, which are now hastening to come upon her,
and upon all that shall be found within her borders.

Open now your eyes, and behold where you missed and turned aside,
through which your foolish hearts have been and are darkened;
for the enemy that goes about as a roaring lion, seeking whom he may devour,
wrought in you to turn you from this pure, immortal principle of the Divine Being,
(that in the days, months, and years by past, awakened you,
and began to work the work of God in you,) whereof
the saints wrote and left on record behind them;
who attained thereunto, through passing from death to life,
in obedience to the grace of God that is given to every man to profit withal;
who knew the holy war, and fought the good fight, and so obtained the victory;
through the effectual workings of God they obtained it,
and not through mere notions upon the words of their brethren the prophets;
of which victory through faith and obedience unto, and in the Eternal Spirit of holiness,
they were made partakers.
And thus was it that they came to put off the old man, which indeed is a great work;
and to put on the new man, which is a real change and translation out of Satan`'s kingdom,
and from under his power, into the kingdom of the dear Son of the living God,
and so to be under his power.
But the enemy of your souls turned you from this free grace of God,
(which was that which stirred in you,
and wrought in you in your day of tenderness,) by drawing
your minds up into an airy notional profession of this grace,
and +++[+++into the belief]
that by it you were saved;
not considering that the immortal souls of such lie in bondage,
whose faith stands in notions, and not in the power of God;
or whose faith is no other than a belief of what is done for them without,
not coming experimentally to know the work of God in themselves,
and the obedience of faith which purifies the conscience, and makes alive unto God.
And such was the soaring up into imaginations,
of some called gifted men for the ministry,
that they presumed to teach and hold forth the free grace of God after such a manner,
as that the understandings of many were confounded,
and thereby many were defiled and corrupted,
by admitting a liberty unto the fleshly nature, and avoiding the cross of Christ,
contrary to that holy liberty, which through the operation of the grace of God is known.
For though it is true, that, as the Apostle says, by grace we are saved;
yet whosoever holds forth this grace, so as to raise a belief in any,
that they are thereby saved from condemnation,
while they are found transgressors against the righteous law of God; such, I say,
divide not the word of God aright,
but teach for doctrine the conceptions of their own brains.
For it is not a bare belief or assent of the mind, to the power of the grace,
which can give satisfaction to the immortal soul,
or true assurance of eternal peace with God;
but there must be also a conformity in the inward man, unto the power thereof;
and so man comes to be created in Christ Jesus unto good works,
to be sanctified throughout, both in body, soul and spirit.
And indeed, I have found,
that instead of preaching up conformity to the power of the grace,
they have not only preached up free grace, (which indeed is an expression, in itself,
proper enough to be held forth,
for that the grace of God is freely extended unto all,) but also therewith they have
preached up a justification of sinful and unsanctified persons by imputed righteousness;
even in such a manner,
as many have from there concluded themselves in a state of salvation,
while sin has had its reign in their mortal bodies; which I cannot but testify,
is as great an error,
and as contrary to the gospel-ministration and the
end for which Christ was manifest in the flesh,
(which was, to save people from their sins,
so as to live no longer therein,) as the error of the Scribes and Pharisees was,
when they were seeking and believing justification by the works of the law,
without the righteousness of faith.

And thus has it been, that many have turned the grace of God into wantonness,
or turned from the grace of God into wantonness; so that in a little time,
how did many professors grow light and vain,
and run with the very profane into the same excess of riot;
and were lifted up in the flesh, and so came to be much in show,
but little and light in the balance?
And here, you professors of all sorts,
that have gone from the spiritual appearance of Christ Jesus within,
into a profession of the saints conditions and performances,
without the leadings and guidings of the same Spirit and Power, lost your way,
and went out from your Guide, which would have led you up to the substance, Christ Jesus:
and thousands of ignorant people have been led here, through the cunning sleights of men,
into an empty profession; and when the manifestation of the Spirit of God,
which is given unto every man to profit withal,
has stirred in the heart and soul to draw the mind out of the ways,
spirit and nature of the world,
then the transforming enemy of mankind has lain near to betray and deceive,
by pointing and directing people to run into this profession or the other,
or take up this outward performance or the other shadow,
under the specious pretence of the ordinances of God and Christ:
and hereby the subtle enemy,
that will admit of the peoples being in the outward practice of outward things,
while that he can have his place, seat and throne in the heart of mankind,
has led thousands aside out of the strait way of salvation,
through his drawing them from the true inward Guide,
the grace of God that brings salvation, that has appeared unto all men,
into the outward observations: and here the fear of thousands, towards God,
is taught by the precepts of men,
who know not the leadings and guidings of the Spirit and power of God;
and so have healed the hurt of the daughter of Zion deceitfully,
and have daubed with the untempered mortar.

And now, all you scattered ones upon the barren mountains of professions, give ear,
hear the counsel and call of the Lord: turn, prodigals, who have spent your portions,
and lost much of your sincerity and tenderness,
and that secret enjoyment you had of the Lord inwardly, years ago,
and who for a long season have endeavoured to fill your bellies with husks,
and the profession of the saints enjoyments.
My heart yearns on you, and for you are my bowels turned:
my soul is often bowed down in the sense of your states; yes,
often my heart is pained within me,
when I behold your wanderings up and down from mountain to mountain,
seeking rest and finding none but what is polluted;
and your souls are lean for lack of the fatness of God`'s house,
and you have not the enjoyment of it.
My soul is even many times distressed for you, God that made heaven and earth,
bears me record, whom my soul cries unto, even night and day,
to visit you with an out-stretched arm.
Return, return, unto that which will show you all that ever you have done,
and that will hasten you to the Father`'s house, where the bread of life is;
and no longer spend your money, precious time, and labour,
for that which is not the bread of life, but a profession, a talk of bread,
which cannot truly satisfy your souls.

And now, in the name and authority, and by the motion of the Spirit of the Eternal God,
behold, I sound the trumpet of the Lord God Almighty in your ears; prepare, prepare,
to meet the Lord Jehovah in the valley of decision;
and all you who have any tenderness in your hearts,
and breathings inwardly after the Lord, among all professions,
of what name or denomination soever, come out, come out of Babylon, and be separate;
touch not any longer the unclean thing, that the Lord may receive you,
who stands ready to receive all that come in truth and righteousness unto him;
who now will mark all that mourn because of the sins of the people, which are great,
and the measure thereof filling up quickly; and the day and time is hastening,
of the pouring out of the vials of the unmixed fury and indignation of God,
who lives forever and ever.
And therefore flee, flee for your lives, out of Sodom`'s nature,
and _stick not in the profession of things, neither the one nor the other,
while the ground of your profession did not,
or does not spring from the immediate work of God,
and daily operation of his Eternal Power in your heart;
but come down into pure obedience to the pure still voice of the Spirit,
and gift of God in your own heart and soul, which will,
as your inward ears are attentive, direct you in the narrow way of life eternal,
in which you should walk;_ so coming here,
you come to that which moved in the hearts of many, years since, godwards,
which was that which wrought many into the tenderness before spoken of: herein walk,
and be faithful, and it will lead to the fountain of blessedness, from which it came,
and unto the horn of God`'s Anointed:
and to Shiloh shall be the gathering of thousands through the nations, tongues,
languages and people; and the mountain of the Lord`'s house shall be exalted,
through this great day of trial, tribulation and anguish,
upon the top of all the mountains.

So the Lord God Almighty, by the arm of strength,
reach all hearts that have any breathing, panting desires after Him,
among all professions, and pull many as brands out of the fire.
So breathes my soul,
who am a travailer for the universal visitation and deliverance of the seed of Jacob,
and raised up to prophesy of the things which shall come to pass,
and be fulfilled in their time and season.

[.signed-section-signature]
Charles Marshall.
