== Chapter VIII

A Warning Unto the Rulers and People of England, in the Tender Love of God

Give ear and hear, all you rulers and inhabitants of these northern islands:
God Almighty, even the God of Abraham, Isaac and Jacob, in this latter age of the world,
is risen and arising, and causing his ancient Horn of salvation to be revealed;
of whom all the holy men, prophets, and servants of God gave testimony,
through ages and generations, to be that Holy One on whom he has laid help,
who is mighty to save, Christ Jesus the Lord; of whose spiritual appearance and coming,
we are witnesses this day;
and by the arm of his Eternal Power are raised up to declare
him unto these northern islands of the Gentiles,
as their light to lighten them, according to the prophets, the testimony of John,
old Simeon, Christ Jesus, and the apostles and messengers of God Almighty,
through many ages and generations; of which many demonstrative testimonies,
in the evidence and demonstration of the spirit and power of Christ Jesus, have been,
and are daily borne, both by word and writing; which holy, certain testimonies,
men of the spirit of Jannes and Jambres, men of corrupt minds,
have risen up to withstand, and by lies, slanders, misrepresentings, etc.,
have endeavoured their utmost to veil and cloud; which work and way of theirs,
God has beheld, and has determined to blast,
because in their right hand has been found a lie,
and the poison of asps is under their tongues, to reproach, vilify,
and misrepresent the servants and people of God, under hideous and odious disguises;
that they might thereby, as much as in them lies,
effect such a work as the old heathens did on the Christians; namely,
by putting lions skins and bears skins on them,
that thereby they might cause the dogs to take hold on them:
so has there been an endeavour in our day,
to misrepresent the servants and people of the Lord,
as deniers of salvation by Jesus Christ; as +++[+++those who make]
his birth in Bethlehem of Judea, his travails, sufferings, blood, death,
resurrection and ascension of no value; as deniers of the Scriptures of Truth;
and instead thereof, preaching up salvation by meritorious works of our own;
and in short, representing us as enemies to Christianity: concerning which charges,
and every particular of them, full, clear,
and demonstrative answers have been and are given,
unto which I refer all unsatisfied persons.
That which lies on my spirit at this time is, to declare in the presence,
name and power of the everlasting God, that these things spoken and written of us,
are as false as the accusations of the Pharisees concerning Christ Jesus,
and as false as the accusations of the Jews concerning the apostles.

1+++.+++ For, first, we declare to all nations, tongues and languages,
that we believe in the One, Holy, Everlasting God.

2+++.+++ We believe concerning him, that he is a Spirit; and concerning his worship,
that it is in spirit and spiritual.

3+++.+++ We believe, preach, and publish salvation in, or by no other name, but in, by,
and through him, of whom all the prophets gave testimony, the apostles preached,
the primitive saints believed and received, namely, Jesus Christ.

4+++.+++ We declare we are so far from denying or having any light esteem of that holy,
honourable record, the Scriptures of Truth,
that we are often greatly bowed and tendered in spirit,
in the sense of the great mercy and love of our God;
that although the wicked have been allowed to persecute, revile,
and evilly to represent the way of life and salvation believed and preached by them,
and also have proceeded to kill the bodies of the prophets of God,
of Christ Jesus our Lord, his apostles and faithful servants;
yet that his great and inexpressible love has been such as to preserve
their precious testimonies unto our age and generation.

And now, you rulers and people of these northern islands,
in the universal love of the God of the spirits of all flesh, I warn you,
that as anything comes unto your ears of us,
contrary to this our faith and belief in God, that you be so noble,
as to do that which is but just and equal for you to do, namely,
to keep one ear for the accused, to hear with diligence and without partiality:
and let none be like those ignoble people of Thessalonica, who being moved with envy,
refused to hear the apostles doctrine; but be like those worthy Bereans,
whose nobility is recorded, because they received the word with all readiness of mind,
and searched the Scriptures daily, to see whether those things were so.

So this is that,
O you rules and people! that may and will hinder you from
having groundless prejudices against an innocent people,
and from running on to persecute them, having not heard nor known their principles,
but from the misrepresentation of others.
This thing has brought an insupportable burden on some:
and I am glad that the unfruitfulness of coercion is in any measure seen;
but sorry that some men should make so ill an use of their liberty,
as to improve it to calumniate those who in spirit are travailing after the Lord.

And this know, O England! and let your rulers, for their good and benefit, understand;
there are thousands in this land of our nativity, and within these dominions,
that are the visited of the Lord: for God Almighty,
has bowed down his ear to the cries of spiritual oppressed Israel,
and seen the oppressions thereof under the thraldom of sin and iniquity;
and their groanings and cryings for deliverance from
out of the house of bondage and darkness,
are come up before him; and for the sake of the poor, and cry of the needy,
that have no helper on the earth, has God Almighty risen and is arising,
and making bare his arm in the sight of the nations,
to carry on his great work of destroying sin and finishing transgression,
and bringing in everlasting righteousness.

And therefore, as you desire to prosper,
let none endeavour to hinder this work of the Lord; for all that shall presume so to do,
Gods heavy hand will be upon them, and their plagues shall be wonderful and astonishing:
and so let all the prejudices and ill resentments
that have been received into the minds of any people,
through the enmity and ignorance of men, be dispossessed;
and hear for yourselves and try all things, and hold fast that which is good;
for sorrow comes on many daily, who have received false reports of an innocent people,
and thereby have been prejudiced,
so as to speak evil of that way they have not known nor proved;
for as the apostle said in that age, so can we say,
in the way accounted heresy by some in our age, as in the ages by-past, we worship God,
believing what is written in the law and the prophets, and of Christ Jesus,
by the apostles.

So the Lord God Almighty in his infinite love,
open the understandings of all that have breathing desires
in their souls after the knowledge of the Lord,
rightly to discern the stumbling blocks, and to see them removed,
that the subtle enemy of mankind, through his instruments, has laid in the way:
and God Almighty reach with his hand of love,
to gather those who have some desires after the Lord,
and yet are led by the craftiness of men, to seek the living among the dead,
and to wander on the barren mountains of professions:
the Lord open their understandings everywhere,
and bring them to the blessed sheepfold of Christ Jesus, is the desire of him,
who is a travailer in body and spirit for the outcasts of Israel, and scattered of Jacob,
that they may be gathered.

Charles Marshall.

An Epistle to Friends +++[+++Under Sufferings.]

Dear Friends and Brethren,

That are suffering for your meeting together,
in answer to the requirings of the power and spirit of Jesus;
my love in the fellowship of the sufferings of Christ salutes you,
breathing to the God of the spirits of all flesh for you;
that the grace that brings salvation, the mercy that comforts,
the peace that is as a refreshing river, may be multiplied in you and among you,
to your great satisfaction, joy and rejoicing in the Lord.
Lift up your heads in the light of the Lord; behold, and livingly remember what the Lord,
the jealous God, has done for you these many years; who has, in unutterable kindness,
visited you with his day-spring from on high, and with his excellent, honourable,
powerful arm, has saved, delivered and wrought for us, time after time;
and beyond all expression has wonderfully turned
back the enterprise of the enemy of our souls.
He has indeed bound the seas as with swaddling bands,
and said to the proud waves of execution, hitherto shall you come and no further;
his arm has brought out of bonds and set at liberty, and has rebuked,
as in the midst of a storm, and has brought many a sweet calm; we have seen what his arm,
power and wisdom has done, and have been deeply engaged unto him,
and bowed tender and broken, in the sense of his unspeakable love.

And now dear friends and brethren, I am moved of the Lord thus to write:
keep your meetings in the name, power and authority of the living God,
and therein let all be gathered into the name of Jesus, the immaculate Lamb of God,
who will then be known to be in the midst of you;
and wait diligently with the loins of your minds
girded with the efficacious girdle of Truth,
in the fear, dread and awe of the mighty Jehovah.
His dread and fear will keep out the fear of man, whose breath is in his nostrils,
and whose life is at the dispose, every moment, of the great Creator.
Let none reason with flesh and blood,
but overcome all reasonings and counsellings of the earthly, sensual wisdom,
and walk in the seed immortal; +++[+++then will his]
springing life make all your meetings sweet, refreshing, and desirable,
but dreadful and terrible to the workers of iniquity.
So dear Friends, in the weighty sense of the honour and dignity of the precious Truth,
which you are concerned in, before the eyes of many that are upon you, manage yourselves,
and let the increase of it bear weight with you over all your interests;
and eye the Lord, who can give and take away,
and whose are the cattle on a thousand hills.
Look not at the things that are seen, which are carnal;
but at those which are not seen with the visible eye, which are eternal;
and no more sufferings shall come on you that keep resigned up the Lord,
and in his counsel, than shall be to his honour; and in the end over all,
you shall be comforted and be filled with joy,
when your enemies shall feel the tribulation and anguish
which the Lord is rendering to the workers of iniquity.
So, into the arms of the living God do I commit you,
and unto the word of his patience that keeps in the hour of temptation;
and the Lord arise among you in the glory of his own power,
and in the excellency of his own brightness, to the astonishment of the wicked,
and to the refreshing and comforting of you all;
in whose name I send this his counsel among you,
who am your brother in labour and travail of the gospel of life and salvation.

Charles Marshall.

Tetherton, the 20th of the Second Month, 1677.
