== Chapter IX.

An Epistle to Friends coming forth in the beginning of a testimony:
and of the snares of the enemy therein.

Dearly Beloved Friends,

Who in your meetings and assemblies sometimes feel something of a testimony for the Lord,
spring and move in your hearts; keep your watch in the Light, that so none stay behind,
neither run before;
but let all who open their mouths in the assemblies of the Lords people,
do it ( as the oracles of God,) in the arising of the Eternal pure Power;
for nothing can beget to god, but what comes from the immortal Word of Life,
that lives and abides forever; and nothing can refresh,
strengthen or comfort that which is begotten by the immortal Word of Life,
but what springs from the same.
And therefore dear Friends, whom this concerns, wait diligently,
not only to know and savour every motion,
but also to know the appointed time and season when
the same motion shall be brought forth;
so shall what is ministered, if it be but few words, reach to the witness,
and do its service.
For this I have learned, that though there may be a true motion of the power of the Lord,
and a true operation thereof,
yet where there is not a true waiting for the perfecting of what is to be brought forth,
but instead thereof, a coming forth before the time,
then that which is brought forth seems an untimely birth;
which is a hurt to the vessel through which it comes, the hearers thereof are burdened,
and the life which first moved, comes to be oppressed;
and here is the ground of that untimely birth that never saw the sun, that has,
does or shall come forth: and as long as any are found walking in this by-path,
although they may find the true power of God moving in them,
yet they never come to be skilful, nor to divide the word of God aright;
and such do not truly grow, but sometimes bring forth a mixture,
sowing the field with two sorts of grain, and wearing a linen and woolen garment.

So, Friends,
this lies upon my spirit to all who feel the beginning
of a testimony spring in their hearts;
wait diligently in the Light, low, in the pure stillness and passiveness of your spirits:
and as you here wait,
you will come to feel the counsel of the Lord sealed unto your understandings,
and see the time when to speak, and when to be silent;
and here will be a right and true increase of your testimonies.
And when that which is thus sealed to the understanding is offered, retire inward,
sink down into the pure stillness, and keep in the valley: and let all know,
that no ministration, save that which comes from life itself,
from the fresh arisings of the pure power of the Lord, avails anything;
and all ministerings out of this, will come to an end, and fade,
and vanish in the approaching day of trial.

And, dear Friends, as the mind and will of the Lord is made manifest,
yield sincere obedience thereunto, if the requiring be but a few words;
for I have seen it a dangerous
thing to resist and rebel against the motions of Gods power,
and have known many hours of sorrow for so rebelling.
And in the day of a beginning of a testimony for the Lord, even in the upright heart,
great will be the opposition of the enemy every way; where he cannot lead out before,
to brig forth an untimely birth,
there he will endeavour to shut up the heart in disobedience or rebellion,
or raise up so many fears, doubts and amazements, as, if possible, to bewilder the soul;
and here I had perished,
if it had not been for the dear love and tender mercy of the Lord.
And so, dear Friends, for whose sake I am moved thus to write, when a motion is felt,
and openings are in the heart, and the power of the Lord is prevailing,
then sink down in that in which no vain thought can be hid, and stand single and passive;
the more still, humble and passive you are, who are thus exercised,
the motion of life will the more live and show itself,
and the power will arise and clear your understanding; and then,
in the power which warms your heart and moves on your spirit, enter into your service.
When that is done, and nothing else, but sit in the still habitation,
and in that humility and passiveness you were in before;
and then the reward of obedience you will feel, and grow in experience and knowledge,
and be more and more furnished to every good word and work.

And in this even path,
in which all will feel a being strengthened with might in the inward man,
and furnished to serve the Lord, God Almighty preserve all that are thus exercised.

And, Friends, when any through lack of experience err, in running before the power,
be very tender; and although there may be a savour and judgment in yourselves,
and you may be burdened, yet beware how you speak to ease yourselves,
but wait on the Lord therein, to be guided by his counsel; for some having such a sense,
as aforesaid, and not having a discerning wherein the miscarriage lay,
have run forth in judgment, and so have sometimes hurt,
and even destroyed +++[+++the true birth,]
or at least have become a stumbling-block to such an exercised Friend,
and have also much hurt themselves; so that they, not having a true discerning,
between the first moving cause, which is the power,
and that which led forth before the power, have judged both,
and so have brought a hurt over their own souls, through judging the power of the Lord;
and this sometimes may extend to hurt others;
out of which snare God Almighty preserve all; that so one may be a strength to another,
taking one another by the hand, and saying one to another,
let us go up to the mountain of the Lord, to the house of the God of Jacob;
who will teach us more and more of his ways; and here, in all Gods holy mountain,
is neither hurting nor destroying.

Given forth in the moving of Gods eternal Spirit, through your dear brother,

Charles Marshall.

1677+++.+++
