== Chapter X.

[.blurb]
=== An Epistle to the Women`'s Half-Yearly Meeting, 1677.

[.salutation]
Dear Friends,

Keep your meetings in the name of the Lord Jesus Christ,
and wait for the arising of his power among you, your hearts to open;
so will wisdom spring in, to instruct you;
and here none will be without their ornament and adorning, namely,
a meek and quiet spirit; which is of that value that it is of great price with the Lord:
and all keep to the teaching of the grace which comes by Christ Jesus,
in which male and female are one, being members of one holy body,
of which Christ Jesus is the head; from whom virtue flows, life streams,
and love abounds, which will season all your words and deportment,
and make them savoury.

And, dear Friends, be swift to hear the heavenly oracle, but slow to speak, +++[+++waiting for]
its teaching, leading and helping; so shall order, in the sweet harmonious love and life,
be among you.
And let no discouragement be upon any of your spirits;
for the Lord has owned your meetings with a testimony from heaven;
and I am now constrained to remind you how the Lord broke in upon you,
in your last meeting together on this occasion;
wherein you were refreshed and stirred up to your
several services in your respective meetings,
habitations, and families.
So be faithful, according to the stirrings of his Spirit and Power,
that no guilt may be on any, when they come on their dying beds: but all in the strength,
leadings and guidings of the Lord`'s power, live and walk,
and serve up your generation according to the will of God,
in whose love I send this among you.
And my soul desires and breaths,
that his love and life may plentifully spring among you.
The salutation of my wife`'s dear love in the Lord is to you,
with breathings to the Lord, that his power,
life and glory may spread itself over your meetings: she has lain under some exercise,
because prevented by some service at Bristol, of being with you.
Farewell in the Lord.

I am your tender friend, in the labour of the Gospel of Peace,

[.signed-section-signature]
Charles Marshall.

[.blurb]
=== An Epistle to Friends in and about Bristol.

Friends and professors of the truth, in and about Bristol, this to you is my message,
in the name of the King of kings, and Lord of lords.

Let all flesh be silent before the Lord, among you; cease from a multitude of words,
that is not from the guidance of the Word, which was in the beginning;
and cease from those discourses that draw the mind out from an inward,
deep sense of the invisible, immutable power of the Lord God Almighty,
that is at work to sweep the house, and cast forth the defiler of the temple of the Lord.

Friends, I say again, in the name and authority of the King of heaven and of earth,
whose embassage this unto you is;
let an outward and inward silence come over all your
families and assemblies before the Lord;
and let the Lord arise in all your hearts, families, and assemblies;
and wait upon him in his great dread, to feel more and more of the word of his holiness.
And tremble, tremble, tremble at it; I warn all in his power,
that is upon me at this time, thus to write.

And let all pride, superfluity, and all loftiness in the enjoyment of perishing things,
be searched out in all families; even every hidden thing of Esau`'s mountain.

And in the dread of Israel`'s God, let all mind their latter end; lest the grave-clothes,
and winding-sheet, become your swaddling-bands, and you not in a prepared state for it.
My soul is filled with the love of my God,
and my spirit is overcome with the dread of the Lord`'s power,
who will hasten his great work among you,
which will affect the hearts of thousands with fear, and dread, and love to God.

And O flock of God in Bristol! You shall be as a garden of roses and lilies,
your scent and savour shall refresh many thousands:
your beloved shall be to you as a fountain of gardens, and as an endless,
over-flowing spring of living water;
the destroyer shall be destroyed out of your habitations,
and the waster from your dwellings.
The Lord Almighty will touch the mountains and they shall melt,
and the hills shall dissolve like snow; and a low, brokenhearted people shall you be:
then shall the travails and deep exercises, which are before the Lord this day,
be remembered with great breakings of heart.

So dear Friends, that are tender in spirit, keep inward with the Lord,
and move not out of his power, I beseech you;
but let the fear of his great name be upon you night and day;
and be not drawn forth by any occasion, out of the habitation of light,
in which is the armour of righteousness; keep to the oracle;
live in the covenant of God Almighty; go not before, nor stay behind,
and the Lord will be with you, (you shall see it), in whose name I send this among you,

Who am your friend and brother in the labour, tribulation,
and patience of the gospel of peace, and a servant of the living God.

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
Written in the year 1677.

[.blurb]
=== Another Epistle to the flock of Christ Jesus: +++[+++exhorting to self-denial, stillness,watchfulness, and earnest prayer for the establishment of universal peace.]

All tender Friends, whose faces are turned from the world Zionward,
love the dawning of the day of light in your souls, and take heed to the sure word;
let it be as a lamp to your feet; then will it guide you,
and translate you out of the nature of sin and darkness, into the divine nature,
which is light, and +++[+++enable you]
so to dwell in it, as to go no more forth,
but to be as pillars in the house of the Lord forever.
Now this work is carried on and accomplished no other way,
but through a daily persevering, and obeying the light in all its leadings.

And you that are not only turned Zionwards, but have been and are travellers in the way,
who have ardent desires after that one thing David so much desired, namely,
to dwell in the house of the Lord, that he might see his celestial glory,
who has immortality and dwells in the light;
I have this message of glad tidings to sound in your ears;
the Lord God of strength and might has heard your cries,
and your breathings and pantings are come up before him.
Give up out of the self-hood; deny your wills;
take up the daily precious cross of Christ Jesus; come out of your own thoughts,
willings and runnings, and close in with the heavenly light of the Lamb.
Give that nature that has slain the Lamb, to be slain by the Lamb;
so shall your salvation be wrought and accomplished by him,
and you forever united unto him, bearing his image,
who is the express image of his Father; and here all souls can again without rebuke,
approach to the Father by him, who is the celestial fountain of light:
and all profession of the Father and the Son, of light and truth, and kingdom of it,
without the knowledge of this work,
(began and carried on by the Alpha and Omega,) will wither and be blasted;
and God Almighty accounts it as stubble for his fire of vengeance.
Under the conduct of this light and truth,
you will bring forth the fruits of it in all your conduct;
and this brings a care one over another,
and a universal care in all your assemblies of sons and daughters,
to labour that all may be kept sweet, and that nothing may be lacking,
but all may be as one family.
And this universal light in its increasing manifestation, has drawn,
and does draw many in this nation and others,
to meet together to serve the Lord and one another; to counsel and strengthen;
to relieve the poor, impotent and needy;
to see that all things which we have to act as a people in this world,
may be as becomes the gospel.

Now, unto all those that discourage this work, and lift up the heel against it,
I have this to say in the certain counsel of the Lord;
the Lord will debase them and pour contempt upon them,
and confound their tower and rend their double wall;
and the righteous generation shall see it,
and shall see the more cause to dread the Almighty, because of his signal judgments;
and shall fear to rebel against him, and rise against his peace, and the work of it:
and the Judas in spirit is discovered, and will be more and more,
that with a kiss does betray; that with and under the profession of the light,
draws from it; and under the profession of the truth,
endeavours to destroy the work of it; which the inward,
tender waiter in the light shall see,
beholding and feeling the wolf under the sheep`'s clothing, and be preserved.

And now, all you families of the earth that call on the name of the Lord,
and profess the light of Israel, that shall be as a flame among the stubble:
give ear to the counsel of the mighty God, the Lord of heaven and earth; love, esteem,
and in fear and dread give up to his ancient, honourable, renowned, saving arm;
that by it you may be gathered that are not gathered, into the universal,
divine light of the morning of the celestial day:
and this is the counsel of the Lord God eternal,
let it be your habitation and dwelling-place; for this is his requiring,
that as you have professed the evangelical light
of the morning of this eternal day before the nations,
you may all, in every place, dwell and walk in it before the nations;
and therein shall you know his being with you, making his abode with you,
who has immortality and dwells in the light: and then,
to you that dwell in this habitation, will the Lord God gather the nations,
and sweetly assemble the people,
from the rising of the sun to the going down of the same,
among whom the name of the Lord shall become great.

But woe! woe! woe!
From the tabernacle of the glory of the infinite God,
unto all that have long made and +++[+++still]
make a profession of the holy,
spiritual light of the Lamb of God while in the darkness they are;
the dreadful day of God Almighty`'s pleading with all such, greatly hastens.
And therefore you, everywhere, that hold the truth in unrighteousness,
be warned in the name and authority of the God of the whole earth,
that none offend nor displease the Lord any longer in this thing, namely,
of professing his pure immortal light, and walking in darkness;
lest his anger break forth like devouring fire,
and he consume you thereby from under the heavens,
and appoint you your portion among the hypocrites,
who are gone into everlasting burning, under the vengeance of eternal fire.

Therefore, let a search pass through all families:
and where any have continued unto this day, thus displeasing the Lord Almighty,
and working the destruction of their own souls, I say unto all such,
in the name of the Lord, haste, haste, haste out of the darkness; give ear;
the trumpet of the Lord gives a certain sound; therefore obey from the heart,
that you may yet, before your day go over, be translated out of the kingdom of Satan,
which is darkness, into the kingdom of light of the dear Son of God,
Christ Jesus the Lord.

And all Friends everywhere, that have the sealing of Gods Eternal Spirit,
that you have obeyed from the heart,
and to this habitation and dwelling-place of light are come;
in the sense of the unutterable lovingkindness of the Lord Almighty,
and the work of his glorious gathering arm, continue, and keep your habitations;
for the angels that kept not their habitations are
reserved under the very chainings of darkness,
to the judgment of the great day.

And Friends, in all the hurryings of men and nations, look not out,
but dwell in the habitation aforesaid; and in times of distresses and amazements,
in the fulfilling of the word of the Lord,
this to you all is a universal word of counsel from the Lord, be still, be still,
be still, and know that I am God, says the Lord;
and stir not out of my counsel in anything, nor take counsel of your own heart:
keep the eye of your minds to the heavenly, spiritual oracle of wisdom,
and you shall have counsel from the Lord to your satisfaction; but if you look out,
you will be darkened, and may fall with them that fall.

And all assemblies and families of the Lord`'s people everywhere, watch unto prayer,
that you may feel the spirit of prayer and supplication poured forth upon you:
and as drawn thereunto,
sit before the Lord in the deep sense of the great work of the destroyer,
who is stirring up the nations to destroy and devour one another;
and is seeking an entrance, as a roaring lion, to destroy some of the Lord`'s people,
called in the morning of the day of his love.
Oh! cry, cry, cry mightily unto the Lord, for yourselves, your friends, and your enemies,
and for the poor land of our nativity,
which is heavy laden with the iniquities of the inhabitants thereof;
over whom the piercing eye of the Almighty looks in great displeasure.
Oh! let your supplications be, that the Lord Almighty would arise in his great strength,
and so judge among the nations, that their swords may be beaten into ploughshares,
and their spears into pruning-hooks;
that the nations may learn war no more one with another:
and that this expedient for universal peace may be upon the hearts of princes and people,
namely, that all people might leave off warring with, and destroying one another;
and all come into the spiritual warfare in their own hearts, with the spiritual weapons,
against the common enemy of mankind, the devil;
that so they all might experience the end of the coming of Christ Jesus, namely,
to destroy the works in every man, of the great Abaddon, Apollyon, the destroyer.
And may the living God be pleased to hasten his great work,
of putting to an end the sin of this age, and iniquity of this generation;
and so bring in everlasting righteousness, +++[+++and cause it]
to flow as a mighty river of sweet refreshment;
that this poor land with others might enjoy its sabbaths; that He who is King of Salem,
Prince of Peace, may rule in the hearts and souls of princes and people;
so that the great, universal, omnipotent God may have his honour,
and the princes and people of all lands their comfort, in the sweet,
inexpressible enjoyment of his omnipresence,
and blessing of sitting under their own vine and fig-tree.
So shall all fear be removed out of the nations, but the fear of the Lord God Almighty;
which would make all rulers and people happy, both in this world,
and that which is to come.
Amen, Amen, Amen, says the tribulated, travailing soul of your friend and brother,

[.signed-section-signature]
C+++.+++ M.

[.signed-section-context-close]
Tetherton, Twelfth Month 13th, 1678.
