== Chapter XIII.

[.blurb]
=== A few words or call, in the universal love, to all the scattered sheep, who in the sense of their captivity in Babylon, feel some drawings, longings, and breathings in their souls, towards the Lord and his holy hill, which he is now exalting on the top of all hills.

The everlasting God has beheld you and your suffering state; and your cries,
your sighs and your groans, are come up before the Lord God of Sabaoth;
he has looked down upon desolate Zion, from his honourable dwelling-place;
his bowels are moved to return the captivity and bondage of worm Jacob,
who is small and as one helpless among the people:
God has beheld your wounds and taken notice of your bruisings,
and he is waxed angry with the people, because of your oppression, O worm Jacob!
Your captivity has continued for many ages, your oppressions for many generations;
your cry is great through all lands, and your sighings,
O virgin daughter of Zion! is come up before your Deliverer;
the violence that is done to you in the midst of the earth, the Almighty God has seen;
and he has taken notice of the dominion, or reign, that mystery Babylon,
the mother of harlots, has had over the nations, tongues and people;
whereby you are become as a desolate widow that sits mourning on the ground,
with your mourning apparel on, and as one covered with ashes:
you are as a speckled bird in all lands, and as a turtle dove forsaken of her mate.
How is my soul often bowed down, my heart oppressed, and my spirit filled with sorrow,
in the consideration of your mournful, sorrowful cries and sighings, misery, trouble,
servitude, bondage, wounds and bruisings;
but I am comforted through beholding the Almighty
Gods being arisen and arising in his glory,
might, majesty, and heavenly, everlasting power, to work your deliverance.

And therefore come forth every one of you,
who have any desires to be brought into the image of God again, wherein man,
before transgression was; come out of Babylon, come out of all the false ways, worships,
professions, practices and ordinances,
to the standard which the Almighty God has set up in the view of all people; namely,
his holy Light, saving Power, and quickening Spirit,
which is revealed in the inward parts, for the saving the soul,
and bringing of it from under the shadow of death, into the land of the living.
Remain no longer in the outward court,
for that is given to the Gentiles to be trodden under foot; but come to within the veil,
and to the holiest of all, where the mercy-seat is to be found of every one of you.
Remain no longer in the images, shadows, likenesses and figures,
but come to the thing typified of, to the thing itself;
to the circumcision that is without hands,
of which the circumcision with hands was a figure;
to the baptism with fire and the Holy Spirit, typified forth by the baptism with water;
to the unspotted Lamb of God, the Savior, held forth by the paschal Lamb;
to the true sabbath of the Lord, signified by the outward sabbath;
to the worship in the inward temple,
of which the worship in the outward temple was a figure;
to offer up the bestial lusts to be slain, instead of the offering up of beasts;
and come to the spiritual worship, to the worship of the new covenant, namely,
the worship in spirit and in truth, that Christ spoke of at Jacobs well;
for this worship the mighty God is now exalting and setting up,
that all people may bow unto it, and all nations may tremble before the glorious,
infinite power of the everlasting God,
who is bringing to pass and prospering his glorious work in the earth;
and by his Almighty arm of power is gathering the dispersed of Jacob,
and scattered of Israel; and shall return, and is returning their captivity,
as the streams in the south.

And therefore, awake, awake; the spiritual trumpet of the Lord is sounded,
to proclaim the year of Jubilee, after the long night of apostasy,
wherein antichrist has reigned.
Tarry not, delay not, go not about to reason with flesh and blood;
but come to the obedience of the Light and Spirit of God,
which gives a true sight and sense of sin and unrighteousness, and the nature of it:
and being come to this true feeling and sight, you will come to the true sorrow,
and the forsaking that accompanies it: and so,
through the judgment of the Lord upon the transgressing nature,
you will find mercy for your souls; for Zion is redeemed through judgment.
Here then the blotting out of sin,
and the times of refreshment from the presence of the Lord will be witnessed;
and by the truth in the inward parts, that makes free indeed,
and is beyond all outward profession, an inward, spiritual work will come be wrought.

To this are you now called, through the sound of his powerful voice from his holy place,
all of you who have any desires towards the Lord; and be assured that all that come here,
shall find a sure hiding place in the day of the fiery indignation of the Lord,
that is ready to break forth upon all the inhabitants of the earth.

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
Written from Harwich, the 1st of the Fifth Month, 1687.

[.letter-heading]
An Epistle to Friends.

[.blurb]
=== An Epistle to Friends, +++[+++exhorting them to self-examination, and warning against false liberty.]

[.salutation]
Dear Friends,

And all professing the precious truth of our God,
unto whom the redeeming arm of the Lord has reached, to redeem out of the nature of sin,
into the Divine nature; your mercies herein have been inexpressible.

Friends, it has pressed on my spirit day and night, for some time,
to visit you with a few lines in tender bowels of love; to call unto you,
in the name of the Lord, to come into a spiritual communing with your own hearts,
in openness of soul, as before the Lord; with his heavenly light,
inquiring how far you have answered his heavenly call;
whether you have made your calling sure,
by persevering in an inward hearkening thereunto;
and whether you have made your election sure, by coming out of the reprobating nature,
and obeying and closing in spirit with that heavenly power,
that translates out of the kingdom of Satan, into the kingdom of the dear Son of God.

Now, dear Friends, the Lord God Almighty is drawing near to judgment,
and will judge in righteousness, according to the root in which every one grows,
and the fruit they bring forth;
for all the worshippers in the outward court will be trodden
down under the swift judgments of the eternal God,
and made desolate.
Therefore, in his name that lives forever, I say unto you everywhere, be inward, inward,
inward; haste inward into the Divine nature, which alone will be a safe abiding place,
in the dreadful pleading-day of Almighty God, that comes on quickly.
And in his name I warn all who are gone from the
obedience to the daily cross of Christ Jesus,
and abide not in the daily, holy watch, and thereby have got into a false liberty,
in their ways, words, conduct, food, drink and apparel, to return speedily inward,
under the operation of the spiritual circumcising-knife; that all which offends the Lord,
and grieves his good Spirit, given to profit withal,
may be effectually cut off and removed, and you may be brought back into your first fear,
dread and awe, and holy watchfulness in the light of the Lamb.
So will the Lord be with you in the day of the dreadful overthrow,
when both the sandy foundations, and the buildings thereon, will fall together.
Therefore, in the name, strength, and power of Almighty God,
and in the sense of the majesty of his divine, glorious presence, I cry to you,
To the Rock, to the Rock, to the Rock; so will the Lord favour you, and encompass you,
and make you sing of his praise; here is safety, food and water,
heavenly and never-failing.

And unto you, young men and women, and children of the people of the Lord, I say,
fear and dread the living God of truth and love;
bear the yoke of the Lord Jesus in your youth, and love his heavenly cross,
that crosses all your inclinations to vanity and vain pleasures;
abstain from all hurtful company, beware of your desires, that go out to pleasures, food,
drinks and apparel, out of the fear of God; let your words be few and savoury,
and your conduct in all places be in solidity and gravity,
in the heavenly awe of the omnipresent God,
feeling after the enjoyment of his heavenly joys and divine consolations.
Read the Scriptures of truth in seriousness, as often as you can,
with your minds turned to that heavenly wisdom that will open them unto you;
so will your youth preach forth the honour of truth, will be blessed of God,
and be a joy and comfort to your tender parents: but, if you grow up in another nature,
namely, that will is evil, and leads into vanity and evil,
God Almighty will cut off many of you from the land of the living:
for he can raise up seed to Abraham even of the stones.
Hear, fear and tremble before the Most High God,
who has beheld you with an eye of jealousy; bow before him,
and let none of your enjoyments puff you up into pride and stout-heartedness,
vanity and a loose life.
God Almighty incline your hearts, and put his fear in your inward parts,
that you may see beyond all terrestrial riches, glories, pleasures and vanities;
and be taken up with fervent love +++[+++to God,]
and delight in the heavenly treasures and enjoyments that never fade away.
Amen, Amen.

And all you tender-hearted babes that love the sincere milk of the word of life,
keep you near the sincere milk of the word of life,
keep you near the breast of consolation, and suck daily thereat;
letting nothing come between it and you;
so will your growth be daily from one degree of strength and stature to another;
in the light, beholding the snares and temptations of the enemy,
and abiding in a living inward diligence, out of the foolish virgins state,
where through spiritual idleness, comes spiritual slumber, to the losing the oil,
and so the lamp goes out: but abiding in a daily subjection to the heavenly cross,
in the holy watch, +++[+++you will]
grow up to the young man`'s state, wherein you become strong,
and the word of God abides in you; and you abiding in it, will overcome the wicked one,
and escape the high-way, stony and thorny ground: and so the increase of riches,
or any terrestrial enjoyment, will not harm you; for you will feed on another life,
and behold clearly another glory, even that which is eternal and celestial;
and so grow up into the state of fathers, eating of the tree of life:
for you will see Him that was from the beginning,
in whose Almighty power is preservation out of Jesuruns state: you will walk in wisdom,
and in the valley of humility, where Shilohs brook runs and flows,
by whose water you will be washed;
and by the holy blood and life of the Lamb sprinkled inwardly,
and with his holy oil anointed; and so come within the veil, into the holy of the holies,
where the glory of the Ancient of Days is beheld on the mercy-seat of infinite lovingkindness:
and in the enjoyment of his sweet smiles and divine favours,
being overcome with the majesty of his presence, +++[+++you will ascribe],
in the strength of his love, might, majesty and dominion, to the Lord God and the Lamb;
and heavenly praises will ascend to his throne, who is over all, in heaven and earth,
God blessed forever and ever.
Amen, Amen.

From your tender Friend and Brother in the labour and travail of the gospel,

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
The Fifth Month, 1689.

[.letter-heading]
An Epistle to the Women`'s Meetings.

[.salutation]
My Dear Friends,

Whose souls love Mount Zion and Jerusalem that is from above,
the beautiful dwelling-place of the redeemed, where the glory of the Lord shines,
the tree of life grows, and the river of life runs:
meet you together in the adorning of the ancient, virtuous, holy women;
and wait to feel +++[+++your]
spirits gathered down into the deep, where the wonders of God are seen,
and where life and power, and wisdom from above, spring into the immortal soul;
by which you will be opened to the Lord, and one unto another.
And dear friends, you here sitting in great humility before the Lord, his precious,
living power, will spring among you; which when you feel warming your hearts,
and in it any of you open your mouths, keep within the compass of the motion thereof;
so shall you minister refreshment, and come to no loss nor hurt in yourselves.
And dear friends, stay not behind the motion of the power, nor go beyond it; begin,
continue, and end, in that in which the kingdom of God stands.

And now, forasmuch as there is a spirit of contention risen,
that would divide from the precious shepherd of Israel, and scatter lambs from lambs,
and sheep from sheep, and all from the fold of everlasting rest and safety;
in the life of righteousness live it down;
and let none have an occasion to say that any of you do
exercise yourselves in pulling the mote out of others eyes,
and do not see a beam at home in your own and families.
Therefore in the name of the Lord Jesus Christ, be careful,
watchful and circumspect at home, to keep down evil in your children and families;
that under the conduct of the sweet, saving wisdom of God Almighty you may be managed;
that so you may live down all evils and opposition,
and stop the mouths of all gainsayers with your upright walking.

And dear friends and handmaids of the Lord Jesus, let the remissness,
carelessness and opposition of them that give up to the enemy`'s leadings,
and thereby neglect to serve up their generation, according to the will of God,
be examples unto you to beware of unwatchfulness:
that you that stand may take diligent care, and walk in the Lambs innocency;
that day after day, more and more of the nature of meekness, patience and temperance,
and the fear of the Lord may appear in you; that your just, careful, watchful, awful,
tender, living, pure and unrebukable walking, in all your respective places,
may preach forth the life of Jesus.
And then the Lord will bless you with dominion over his and your enemies.

And dear friends, endeavour not to reason down; but as I said,
in the name of the Lord Jesus Christ, live down all opposition and contention.

The Lord will hasten his work,
to put an end to that which in this day dishonours his worthy, glorious, renowned,
dear name.
So keep your meetings in the name of the Lord Jesus, our Leader, Commander, Savior,
Shepherd, and Bishop of our souls; who will supply all your needs,
and bow down his ear to your cries, in the sense of your wants,
and answer your supplications, tears, sighs and groans.
God Almighty be with you, and fill you with the fillings of his life and heavenly wisdom,
is the breathing and travail of the soul of your bowed-spirited friend and brother,

[.signed-section-signature]
Charles Marshall.

[.postscript]
Postscript.

And the Lord Almighty cause a plenteous, pleasant, heavenly,
refreshing shower to descend among you;
that thereby you may be as a well-watered garden;
that all may be melted and dissolved down into that heavenly frame of spirit,
that would make you shine in all your respective places and dwellings.

And dear friends, manage those affairs of truth presented before you, in the grave,
heavenly wisdom; and be swift to hear, and slow to speak;
that in the comely ordering of the heavenly wisdom, you may be ordered,
and weigh things ponderously before you speak; wait, to see things first clearly,
and how you may be co-workers together and helpers, and then speak one by one:
so will you go through things in a short time,
and come to comfortable satisfactory conclusions; and in the end,
part in heavenly contentedness of mind,
in the sense of the Lords helping you along in his work and service.
God Almighty be with you, and bless you with his heavenly presence, power, light,
life and glory.
Amen, Amen.

Let this be read in the assemblies of women,
in the fear and feeling of the power of the Lord of glory; and copied carefully,
and sent abroad.

[.signed-section-signature]
C+++.+++ M.

[.signed-section-context-close]
Tetherton, the 23rd of Second Month, 1697.
