== Chapter XIV.

[.blurb]
=== A General Epistle to Friends, +++[+++cautioning against the spirit of the world, and recommending watchfulness, unity, humility and stillness.]

[.salutation]
Dear Friends and Brethren,

Who with a high and heavenly calling have been called out of darkness,
and all the ways and works thereof,
to walk in the marvelous light of the glorious day of God Almighty,
that has preciously dawned in this our day; grace, mercy, and peace from God,
with the virtues of his Eternal Spirit, be multiplied in and among you.

Friends, the great Husbandman of the whole earth, having in the riches of his love,
planted a vineyard with the choicest vine, in a fruitful hill, in this age of the world,
which he has pruned, dressed and plentifully watered, is coming to take a view thereof,
to see what fruit it brings forth;
and therefore it weightily concerns you to see with the light of the Lord,
how you have answered his great and inexpressible love,
which for many years has been abundantly extended unto you;
and to prize your time while you have it, and it is called a day of mercy.
O! have a care that you give no room to the spirit of the world,
that blinds the eye of the mind, and subjects the affections to things below,
and raises up the old love to the world again:
beware of the going out of the simplicity of the gospel; and let there be a tender,
inward care to watch against all thoughts that darken you,
and grieve the Spirit of the Lord.
Let your words be few, and seasoned with heavenly grace:
go not out of the exercise of the precious cross of Christ Jesus,
into any excess in food, drinks, or apparel;
and make no provision for the flesh to fulfill the lusts thereof;
let not your gold and silver, lands and livings, furniture or apparel,
any way ensnare you, or entangle, surfeit, or overcharge you.

O Friends! the enemy of Zion`'s prosperity has laid deep
snares in the spirit of the world in those things,
to draw out the mind from the pure, innocent life,
obtained and enjoyed through the spiritual exercise of the cross of Christ Jesus,
which crucifies us to the world, and the world unto us;
for it the mind goes out of the awe, and dread, and fear of the Lord,
and holy cross and heavenly watch, into a false liberty,
then you will live to the world and the world to you;
and here is the way that death comes over again.

Therefore dear Friends,
this is the word of truth to all the professors thereof everywhere, home, home, inward,
inward; and in the spiritual watch-tower stand and abide,
where you will receive manifold spiritual advantages,
and will see the approaches of your souls enemy, when, where, how, and in what he works;
and here you will see clearly how sin is conceived in the thoughts, which,
when it is finished, brings forth death;
and so you will receive an understanding how sin is strengthened, and how overcome;
how it is finished and brought to an end,
and the everlasting righteousness of Jesus Christ brought in;
and how the knowledge of God increases,
and comes to cover the earth as the waters cover the sea;
and so shall your peace flow as a river.

And dear Friends, keep the unity of the Spirit in the bond of peace, and grow up in it:
for while the churches kept in the purity, they were in the greatest unity;
here they were with one accord, and great grace was upon them,
under the dominion and beauty of the glorious power of the Lord:
for Zion is a city at unity with itself, and the body edifies itself with love;
but when the enemy prevailed to draw out the love of Christ Jesus,
(where all the numbers that hold the Head,
are knot together as with joints and bands,) then other fruits did appear.
Now dear Friends, the pure, glorious, sweet unity of the churches is in the spirit,
where all have unity with God who is a Spirit, and with one another in his Spirit:
this is increased as all grow up in the nature of Christ Jesus, which is meek and lowly;
here all are preserved in the dominion of the sweet, edifying love of God,
and in unity one with another, let there be ever so many tens of thousands:
but when the enemy prevailed to draw out of the quickening Spirit of the second Adam,
and out of his nature,
and led into another spirit and into the wisdom which is from beneath,
therein arose those bitter fruits mentioned in the Scriptures of truth.

Therefore, dear Friends, everywhere, in the name, and pure,
weighty dread of the Most High keep;
and grow up in the sweet nature and wisdom of the Ancient of Days,
and watch against the least appearance of that which would break your unity;
and if anything of this nature has broken in anywhere,
in the name of the Lord God everlasting, let it be driven out of his camp,
it being one of the greatest enemies of Zion`'s peace, comfort, growth, and beauty:
for unity is our strength; and keeping our ranks here,
all the enemy`'s endeavours without, will not be able to prevail.
So Friends, in the spirit of meekness,
which keeps in a sound judgment and spiritual discerning, dwell; where no wrath,
fleshly passion, envyings or emulation can have any place:
for no strife and division can have room, as all grow up in the divine nature,
in the faith of Abraham, who said to Lot let there be no strife between us,
for we are brethren; if you will take the right hand, I will take the left;
and if you will go to the left, I will go to the right:
here all controversies are ended and shut out.
Dear Friends, with the light of God`'s holy day search, see and discern how it is with you;
that so if the enemy of Zion`'s prosperity has gotten any entrance,
to hinder the precious work of the Lord, from prospering in your souls,
by +++[+++prevailing on you to]
turn aside into any by-path, or to sit down by the way, or take up a false rest,
with the glorious light of the Lamb you may see and discern it;
and speedily retire inward to hear the voice of the good Shepherd,
that by him you may be led out of all the enemy`'s snares.

And now, O tender Friends! make use of your time and day:
and all to your spiritual tents everywhere, in the sweet valley of humility;
where you will not only see all the devices and snares
of the unwearied enemy of your souls,
but will also see, feel, and enjoy the descendings of the glory of the God of Israel,
in the daily openings of his divine hand, which is full of blessings.
And here you will be tenderly concerned in Spirit,
to cry fervently to God for yourselves and families,
and for a people that have not hearts to seek and cry to God for themselves,
that the tender compassionate God would open their hearts,
that they might see and be sensible of the mercies
of a long-suffering and long-provoked God,
who has often shaken his hand, and threatened his terrible judgments;
and on the other hand, has largely and wonderfully extended his mercies.
And in this tender exercise of spirit,
you will approve yourselves the true friends of your neighbours,
and you will have a hiding-place in the day of his dreadful, consuming judgments,
which he will assuredly bring to pass upon all the professors of Christianity,
that are out of the nature thereof, unless they repent.

And now, O Friends! let a true silence and sweet stillness come on all your spirits;
so shall your inward ear be opened to his heavenly counsel; and you will be ready,
in true bowedness of spirit to say, what the Lord has commanded and required,
that will we do, through his divine strength:
and here you will be preserved in all the various exercises of the day,
out of the hurries of the people,
in this season of the fulfilling what was said in many of our ears, many years ago;
disappointment upon disappointment, sorrow upon sorrow, exercise upon exercise,
and distress upon distress: and as you are inwardly stayed upon the Lord,
in his eternal light, you will feel help from him in all your straits.
Therefore gather to the munition of rocks, where your bread shall be sure,
and waters never fail: be faithful in the Lords work, and keep your meetings,
as the Lord God has required, and that diligently, on week-days as well as First days;
and the Lord will appear in the brightness of his power,
and the glory of the Majesty of his presence you shall enjoy more and more.
And dear Friends, you that God has blessed with outward substance,
feel the love of Christ Jesus, who offered himself up for us, to open your hearts,
and give you wisdom to take effectual care of the poor and needy,
according to your ability.
So to the glorious arm of God`'s Almighty power I commit you; and having done his will,
I rest in my Fathers love, your tender friend and brother,
in the labour and travail of the gospel,

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
London, the 25th of the Second Month, 1697.
