== Chapter XVI.

[.letter-heading]
An Epistle to Friends in Pennsylvania.

[.salutation]
Dear Friends,

In the heavenly covenant of Eternal Life, is the salutation of my love in the Lord Jesus,
unto all that love and fear him in +++[+++your]
country.
I am sensible that God has sown a good seed among you;
therefore be careful to receive it rightly and deeply, that the fruit may appear:
for though the testimony is true,
of the rich and plentiful visitation of the heavenly power among you, +++[+++yet]
if there be not a true and right receiving the seed,
and a tender waiting for the watering rain and dew of life,
and its taking root in the honest heart, the good ground,
thorns may grow up instead thereof.
Therefore, in the fear and dread of the great God, keep low;
and out of the snares of the enemy,
in the cares of this life and the deceitfulness of riches;
and I warn you in the name of Him who is the dread of nations,
let none defile that land in which you are strangers.
But walk in the way of Abraham, Isaac and Jacob, etc.,
and the Lord God will pour out wonderful blessings upon you.
But if you will not cleave unto him with your whole heart,
and serve him in fear and trembling, that a good savour may go forth from you,
then will he bring his righteous judgments over you,
according to the swiftness of his goings in his sanctuary.
Therefore sanctify the dreadful God of the whole earth before the heathen;
so shall you prosper.
In his love and fear, I send these few lines unto you;
hoping you may be watchful and diligent in all things to glorify his name,
who is over all, God blessed forever.

[.signed-section-closing]
Your tender friend,

[.signed-section-signature]
Charles Marshall.

[.letter-heading]
A Salutation to the Men`'s and Women`'s Meetings about the City of Bristol.

[.salutation]
Dear Friends,

In the ever-blessed truth of our God, which endures forever,
I tenderly salute you at this time; desiring greatly your prosperity and growth therein,
+++[+++and that you may]
serve up your generation according to the will of God;
in which you will have peace forever.
Now the God of heaven has not only called you to
watch and take care of your own hearts and families,
but also the flock and family of God where you live;
therefore be careful and diligent in your meeting together, and in a faithful discharge,
as before the Lord, to answer the service of your meetings effectually:
and to that end I exhort you, in the dread of Israel`'s God,
to wait diligently upon the Lord, to feel his sweet,
opening power and spring of divine wisdom,
that you may see your several places in the body,
and service in that place faithfully performed.

And dear Friends, for some time it has lain before me, in the name of the Lord,
to stir you up to an increase of love: and you that have families, sons and daughters,
stir them up often to come to meetings, and into the service with you,
answering the Lord`'s requiring; that they may remain with you, serving the Lord: then,
when you are taken away, they may be ready to serve the Lord,
being thus trained up in his way, in a holy freedom.
And therefore I charge all young men and women,
in the sight of Him who shall judge righteously, who has put you, in some measure,
in a capacity to serve the Lord in the men`'s and women`'s meetings,
that you neglect not your care herein;
lest the Lord God exercise you with various trials, unthought of by the careless mind.
For if you do love, and give up to serve the Lord,
and bring of your substance to serve the poor, as the Lord has commanded,
you will find a reward in your bosom, and satisfaction by being in your duty and service.

And, dear Friends, lift up your heads in the light of the Lord;
feel his eternal arm to gather you into a growing state, in the holy root of life;
that therein you may be able to stand in the dreadful day of his vengeance,
fury and fire, that breaks over a sinful people,
for the humbling of thousands to the dust.
Arise, shake yourselves in the strength of the Lord, from the dust of the earth;
put on strength and heavenly zeal for his name, and his sweet counsel;
with your minds gathered to stand and see the fulfilling
of his words that have dropped over this land.

The God of our tender mercies incline you all his counsel to take,
that so you may serve him in all faithfulness; that now, as living travellers,
you may journey on, and come to Zion, the city of the heavenly King;
where his glory shines, his love flows, his mercy extends,
and the joy of the Lord springs up,
to furnish man with living high praises to him that sits upon the throne,
and to the Lamb forevermore.
That you may have your lot and portion in that city,
has been the travail of soul and ardent desire of your tender friend and brother,

[.signed-section-signature]
C+++.+++ M.

[.letter-heading]
An Epistle to the Captives.

[.salutation]
Dear Friends,

In the everlasting, living, sweet Truth of our God, I dearly salute you;
bowing in spirit to our God and Father, in supplication,
that he would remember you in the greatness of his love and heavenly providences;
making your captivity the more easy through his divine
and glorious shinings in your souls;
making you to sit together in heavenly places in the Son of his love;
and in his own time make way for your redemption,
to see your dear relations and families.

We often yearn over you, and remember you; and our eye is to the Holy God,
that his right arm of salvation you may find underneath;
that his Divine counsel may guide you,
and that your time may be improved to a spiritual advantage;
that out of the inward captivity you being redeemed and ransomed, may joy in the Lord,
and magnify his great and glorious name.

Your letter was read in our meeting, and the spirits of Friends sympathised with you;
and I believe they will let no time or opportunity
slip wherein they might hasten your redemption.
The salutation of their dear and tender love is unto you; so is mine;
and I rest your tender friend,

[.signed-section-signature]
Charles Marshall.

+++[+++It is probable, the Captives to whom this Epistle was addressed,
were those mentioned in Sewel`'s History of Friends,
as some seamen of the people called Quakers, who were in slavery at Algiers,
and concerning whom he states it was a pretty long
time before opportunity was found to redeem them;
but in the meanwhile they so faithfully served their masters,
that they were permitted to go loose through the town, without being chained or fettered;
and liberty was also allowed them to meet at set times for religious worship;
and their patrons themselves would sometimes come and see what they did there;
and finding no images or prints,
as papist slaves in the exercise of their worship made use of,
but hearing from their slaves, that they reverently adored and worshipped the living God,
Creator of heaven and earth, they commended them for it, and said it was very good,
and that they might freely do so.
And since one of them was raised to speak by way of edification to his friends,
some other English slaves frequenting that meeting, came to be united with them.
In the meanwhile the Quaker`'s name came to be known at Algiers,
as a people that might be trusted beyond others.--Editor.]

[.letter-heading]
An Epistle to Friends of Charlecot, in Wilts.

[.salutation]
Dear Friends,

All keep on the watch-tower,
wherein alone you are in a capacity to hear what the Lord says,
and in which you will find peace spoken unto you, that none may go back into folly,
into earthliness, carelessness, or double-mindedness again.
And tender Friends, keep your meetings diligently,
and therein wait with an earnest expectation of Christ Jesus
coming in among you and breathing on you invisibly;
through which breath of life, your senses can alone be made living;
and so being daily watered and refreshed,
you will go away inwardly strengthened and increased.
So dear friends, be faithful in watering and diligent in watching,
and then you will find and feel the breakings in of the pure,
heavenly power of the everlasting, true God upon your spirits,
through which your meetings will be kept living and fresh;
so will the great travail that has been for you be answered.
And this I say unto you in the name of the Lord, if after such dressing, pruning,
and watering that has been among you, you keep not in the Son of the endless,
boundless love of God, but allow your minds to go into the earth,
the Lord shall bow you down dreadfully, and render unto you the reward of forgetfulness,
carelessness and earthly-mindedness; out of which, dear friends, in the love of God,
I earnestly desire you all may keep, a sweet savour unto the Lord;
that so the servants of God coming among you, may be refreshed,
your souls therein abundantly comforted, and the worthy name of the Lord God magnified:
this is the breathing of your travailing friend and brother,

[.signed-section-signature]
Charles Marshall.

[.postscript]
====

Friends, be diligent in keeping your week-day meetings;
it lies on my spirit to lay it on you at this time.

====

[.letter-heading]
A Letter to Friends of Falmouth.

[.salutation]
Dear Friends of Falmouth,

My love in the living, quickening truth of God,
salutes you all that are faithful to the Lord,
in the manifestation of his light of righteousness revealed in your inward parts,
wherein is Zion`'s way cast up before your understanding; in which pure path of life,
which the vulturous eye never saw, nor ravenous beast ever trod in,
my soul breathes to the God of Heaven you may be preserved.

And, dear Friends, many know the truth,
but it is obedience to it that gives the entrance into the purchased possession;
purchased by the Captain of our salvation,
who through suffering and doing the will of his Father, is entered within the veil.
So dear Friends, we must follow him in the daily dying and baptism:
for here lies the mystery of the entrance into the kingdom, even in the daily dying;
and being, through a daily dying, at last baptized into his death,
then there is a rising in his life.
Dear Friends, here it is, that many missing that, have, or may have some sight of truth,
and enjoyment thereof; yet not keeping down to the daily cross, thereby to die daily,
that lives which is for death; and such will hold the truth in the unrighteous ground:
and here lies the very ground why many, being convinced and knowing the truth,
do not grow and thrive in the innocent, virtuous life of righteousness;
not giving up all to be slain by the daily appearances
of the working of the power of God Almighty.
So Friends, God Eternal has determined to put an end to all professions,
where possession of life is not the ground thereof,
by bringing forth the substance of all profession, even the perfect work of holiness,
in the hearts of thousands of his subjected, obedient people; and by his eternal power,
and by his dreadful arm of strength,
will he dash in pieces everything that is not weighty and real:
and that day will certainly come, and hastens,
that will deeply try all that are not born of God; and in this day the chaff, the dross,
the tin, yes, and reprobate silver +++[+++will be rejected.]

So dear and tender Friends, wait diligently in the invisible power,
to be born into the nature of Him that is the first-born of every creature;
and here will be your inexpressible comfort forevermore.
God Almighty preserve you diligent,
with the loins of your minds girt up unto him from the morning to the evening;
that the travail you may know in the power, and the bringing forth,
in which is the lasting and true joy that will stand forever.

I received your tender lines, and often before have you lain in my remembrance,
in dearness: and +++[+++I have]
tendered the living breathings and springing desires Godward,
that I saw and felt among you, which often have refreshed me.
God enlarge the borders of his sanctuary thereaway,
and preserve you as a city set on a hill, to be a good savour in the righteous,
holy life before the world.

My dear love salutes dear Friends about you: so in the yearning bowels of true love,
after your prosperity and growth, I rest your travailing friend and brother,

[.signed-section-signature]
Charles Marshall.

[.postscript]
====

Dear Friends, as to my coming into your parts, I know nothing of it at the present;
in God`'s counsel and name I visited you, +++[+++and may again]
if he require it of me; in his will I desire to live to the end of my day.

====
