== Chapter II

[.chapter-synopsis]
* His call to the work of the ministry
* Exercises consequent thereon
* His concern to visit Friends throughout England
* Names of the places visited
* Remarks relative to this engagement
* Providential escape from drowning

After many years travail of spirit, as before in short is hinted, in the year 1670,
and the thirty-third year of my age, God Almighty raised me up by his power,
which had been working in my heart many years,
to preach the everlasting gospel of life and salvation; and then a fresh exercise began:
for the enemy tempted me to withstand the Lord,
to look to my own weakness of body and spirit, and insufficiency for such a great work.
And such was the prevalency of the enemy of my soul, that had not the Lord God,
in his inexpressible love, stood my me, borne with me, and helped me, I had perished,
after all, through disobedience.
For when the power of God fell upon me,
and a few words were required of me to speak in the
assemblies of the Lords people in Bristol,
I reasoned they were a wise people, and how could it be I should add to them; also,
that I might hurt myself; that imagination might be the ground of such requirings,
and that many wise men therein might look upon me as forward, and so judge me;
and I thus reasoned through some meetings, until I was in sore distress.
When those meetings were over, wherein I had been disobedient, then great was my burden.
Oh, then I was ready to engage and covenant with the Lord,
that if I felt the requirings of his power again.
I would faithfully give up in obedience unto him.
Yet when I was tried again,
the same rebellious mind would be stirred by the power of the enemy:
then hath the Lord withdrawn the motions and the feeling of his power,
and all refreshment with it, and hid his face.

Then was I in great sorrow,
having a sense of others feeding on the bread of life in our meetings,
and drawing the water of life, but my soul was without +++[+++refreshment:]
great bars +++[+++were]
over +++[+++me,]
and as it were, a sealing down under darkness; I beheld the displeasure of the Lord,
and was bowed down and in great affliction;
my soul cried to the Lord to try me again with the breakings in of his power,
and to give me a clear demonstrative knowledge of his requirings, and I would obey him.
Then the Lord God of life heard my cry again, and opened my heart that had been fast shut.
And when I began to feel the warming power of God stirring in my inward man,
I was glad on one hand, but very sorrowful on the other hand,
fearing lest I should be rebellious again:
and so hard was it for me to open my mouth in those meetings at Bristol,
that had not the Lord caused his power so to be manifest in my heart,
as new wine in a vessel that wanted vent, I might have perished.
But the Lord had regard to my state, and knew the peoples state,
among whom I was gathered, and also first brought forth among: and when,
through the great and wonderful love and power of my God, I had broken through,
the enemy`'s snares were manifest; for which my soul praised the Lord God of my life;
and I have been, and often am broken in the sense of his goodness to me when a child,
nay, as a worm.
And in the sense thereof, at this time, even in the fresh remembrance of thy love,
I bless, magnify and extol thy name, O Lord, who art good, and doest good,
and art worthy of all fear, obedience, reverence, and honour, forever and ever.

After I had, through the goodness, love, and power of God, gotten dominion in a measure,
over that which did let, I faithfully gave up liberty, estate, relations and all,
to my God, and was drawn forth in his power,
in the assemblies of his people in the city of Bristol and places adjacent.
And as I gave up in obedience, I found my way made easier and easier,
and the enemy that would have hindered me, more and more conquered; so in the year 1670,
I received this commission from God, Run through the nation, and visit my breathing,
bruised birth, which I begat among my people,
in the day of their first tender visitation; proclaim my acceptable year,
and day of perfect deliverance to my breathing, tender birth,
and my day of vengeance to come upon all that have bruised it,
either among my people or in the world.
Then cried I unto the Lord, How shall I visit thy people in these times,
when the rod of the wicked is upon their backs;
and almost everywhere endeavours +++[+++are used,]
through violence, to scatter the assemblies of thy people!
How shall I meet with them!
And the Lord said Go, I will prosper thy way;
and this present exercise which is over my people, shall be as a morning cloud;
and I will be to them as the tender dew, through the land of thy nativity.
Then bowed I before the Lord, and travelled in obedience to his command;
and from the latter end of the Tenth Month, 1670, to the 20th of the Twelfth Month, 1672,
I was at about 400 meetings.^
footnote:[The particulars whereof follow: About the latter end of the Tenth Month, 1670,
I visited the meetings in and near the city of Bristol.
On the 12th of the Eleventh Month,
I went forth of Bristol.
{footnote-paragraph-split}
1670 11th Mo. 13th,
I had a meeting at Calne, and one at Marlborough.
14, at Chippen-ham.
15, Uridge Farm and Corsham Ridge.
16, Shaw Hill.
17, Camberwell.
18, Sutton.
19, Charlecot.
21, Nailsworth.
22, Cirencester.
Then I came to Bristol, out of Wiltshire, went out again on the 5th of 12th Month,
13 1670, +++[+++and was&#93;
at the General Meeting at Nailsworth.
12th Mo. 9th, Oldstone.
12, Pucklechurch.
14, Abington.
15, Ross.
16, Gloucester and Cheltenham.
17, Tewksbury.
18, Evesham.
19, Campden.
20, Warwick and Dordon.
12th Mo. 23rd, Wishaw and Birmingham.
24, Lin.
26, Trole.
28, Lancaster.
1671+++.+++ 1st Mo. 2nd, Kendal.
5, Swarthmore, 8, Franly.
9, Congleton, 12, Bradley.
13, Stourbridge.
14, Dudley and Stourbridge.
15, Chadwick.
16, Worcester.
17, Pershore.
19, Evesham, two meetings.
20, Tewksbury and Gloucester.
Then to Bristol.
I went again from Bristol the 30th of the 1st Month, called March, +++[+++O.S.&#93;
31, at Cannings, (a General Meeting.) 2nd Mo. 1st, Calne.
2+++.+++ Foxham.
3, Cheverell.
4, Bugly.
7, Wallop.
9, Southampton.
11, Alton.
2nd Mo. 12th, Hedley.
14, near Guildford.
16, Gracechurch Street.
18,Devonshire-house.
21, Horsleydown.
22, Westminster.
23, Wheeler Street.
25,Devonshire-house and Peel.
28, Ratcliff.
3rd Mo. 2nd, Bristol, Mens Meeting.
3, 5, 7, Bristol.
I went from Bristol on the 9th of the 3rd Month, 1671, to visit the West of England.
10, Hollowtrow.
11, Shepton Mallet.
12, Street and Ilchester.
14, Membury and Honiton.
15, Absom.
16, near Norton and Launceston.
18, Falmouth and near it.
22, Truro.
23, Thos.
Lowers.
24, Trigen Jervis.
25, Thos.
Mounts.
26, Menhinuick.
28, 29, Plymouth.
4th Mo. 1st, Coliton.
2, Ashton.
3, Thorncombe.
4th Mo. 4th, Bridport.
5, Weymouth, and at a village by.
6, Poole.
7, Ringwood and Southampton.
8, Portsmouth.
9, Porchester 10, Petersfield.
11, Guildford.
12, London.
13, A General Meeting.
14, Another.
16, Peel.
17, Westminster.
19, Colchester.
15 22, Coggeshall.
23, Ibid, Quarterly Meeting.
25, Hemmington and Halstead.
29, Haverill and Brick-house.
30, Felsted.
31, Colchester.
5th Mo. 2nd, Overburyhall.
4, Woodbury.
5, Bucklesham.
6, Ipswich.
10, Mendlesham.
12, 13, Ibid, Quarterly Meet-ing.
14, Two Meeting +++[+++Meetings&#93;
at Bury.
15, Snarehill.
16, Ramplingham.
17, Tivetsall.
18, John Barbers.
5th Mo. 19th, Norwich.
20, Stoke.
21, Whittlesfen, in the Isle of Ely.
24, Long Sutton, Lincolnshire 25, Wingolf.
26, West Wellowby, at William Moinces.
27, Lincoln.
28, The Isle of Axholm.
30, Garshop.
31, Sike.
6th Mo. 1st, Selby.
2, York, two meetings.
3+++.+++ Malton.
4, Scarborough.
5, Whitby.
6, Hinderwell, in the Bishopric of Durham.
7, Stockton.
8, Shotton.
10, Near Auckland.
11, Bowden.
12, Newcastle.
13, Darmon-water.
14, Arlington.
16, Matson.
17, Carlisle.
18, Scotby and Morehouse.
Thomas Stordys, within two miles of Scotland.
6th Mo. 20th, George Bulies, Cumberland.
27, Preston in Westmoreland, Morland.
30, Swarthmore.
31, Lancaster.
7th Mo. Warwick.
2, Barmel.
4, Franly.
6, Near Stafford.
8, Coventry.
9, Warwick.
10, Lament-house, and Cirencester.
11, Bristol.
13, Winterborn.
20, Week.
21, Calne.
23, 24, Andover.
Then I went to London, and through the Meetings +++[+++of that city,&#93;
from the 26th of the 7th Month to the 8th of the 8th Month, and from thence into Essex,
where I had three Meetings, and so into Suffolk;
from thence I returned to London in about five days, and had two meetings more.
After these two meetings, I came from London to Bristol,
which was about the 20th of the 8th Month, 1671.
Then I spent some time in visiting the meetings in and about Bristol,
and almost all the meetings in Wiltshire, and part of those in Gloucestershire.
I went again from Bristol on the 2nd of the 11th Month, 1671,
+++[+++and attended meetings as follows.&#93;
11th Mo. 4th, at Cirencester.
5, Gloucester.
7, Nailsworth.
9, Sutton-under-Braylis.
11, Siddington, Cirencester.
12, Cricklade, and a village a mile from Cricklade.
14, Sutton-under-Braylis.
16, Warwick.
17, Coventry.
18, Hinckley.
19, I went to see G. F.`'s mother in Leicestershire.
21, Badgley.
22, Swanington, Castle Dunnington.
23, Nottingham.
24, Seatly.
26, Little Norman-ton, at Thos.
Brokeshaws.
28, near Derbyshire.
11th Mo. 29th, near Derby.
30, Sileby.
31, Kirby, (Leicestershire Quarterly Meeting.) 12th Mo. 1st, Leicester, at Samuel Wilsons.
2, Black Ashley, Hartshill, at Nathaniel Nuttons.
4, near Leicester, at Wm. Wells.
5, Long Clanson, in the Vale of Bevor, at Ed. Halums.
Ibid, had a great Meeting at night.
6, Oakham, Rutlandshire.
7, Farndon, near Market-Harborough.
8, Northampton.
9, Wellingborough.
11, Kings-Rippen.
13, Earith, which took in friends of Cambridgeshire and the Isle of Ely.
14, Ashwell.
15, Hitchin and Baldock.
12th Mo. 16th, Hertford.
18, London, Gracechurch Street, and Peel.
19, The Mens Meeting.
26, I set forward towards Kent.
27, Frinsbury.
28, Canterbury.
29, Dover. 1672. 1st Mo. 1st, Deal.
2, Sandwich.
3, Wamsted.
4, Swingfield.
5, Masom.
6, Tenterden.
7, near Cranbrook.
8, Staplehurst.
9, Frinsbury and Gravesend.
10, London, Bull and Mouth.
11, Sarah Sawyers.
13, Peel, and so from meeting to meeting in that city.
21, Albans.
22, Kensworth.
24, General Meeting for Buck-inghamshire.
26, Marlborough, and the next day home, where I remained four days,
and had a meeting at Charlecot, another at Gotaker, and four meetings at Bristol.
2nd Mo. 4th, at Chippenham.
5, Marlborough.
6, Sutton.
29, Gloucester.
30, Ross.
3rd Mo. 2nd, Ross.
3, Hereford.
4, Leominster.
6, Almesly.
7, Shrewsbury.
8, Edgmond.
9, Shrewsbury.
10, Bradley in Staffordshire.
12, Lin.
19 13, Birmingham.
14, near Dudley.
15, Birmingham, Warwick.
16, Banbury.
17, Hooknorton.
18, Nornewton.
20, Bugbrook 21, Northampton.
22, Welling-borough.
23, Sherrington.
24, Kensworth.
25, Albans.
26, Winchmore-hill.
27, The General Meeting in London.
28, I went out of London.
29, Colchester.
30, Coggeshall.
3rd Mo. 31st, Overbury-hall in Suffolk, at Ann Doylys.
4th Mo. 3rd, Mendlesham.
4, Ann Doylys uncles.
6, Witham.
7, Manningtree.
9, Colchester.
10, Hingingham.
14, 16, Plaistow, near London.
18, Croydon.
19, Burmeg.
20, near Reigate.
21, near Grinstead.
24, Warbleton.
26, Lewes.
28, The great house in Saine, and so through Surrey and Hampshire, home,
where I remained ill about two months, and was, in appearance, at the brink of the grave;
but was raised by the power of God.
After my recovery, I visited Friends about Wiltshire.
On the 4th of the 8th Month, 1672, I took my journey for London,
having a particular requiring to visit that city.
8th Mo. 4th, +++[+++I attended&#93;
Devizes Quarterly Meeting.
8th Mo. 5th, Marlborough.
6, Reading.
8, Reading, 9, Henley-upon-Thames, and had a dispute with the Baptists.
10, Windsor.
11, London.
13, Gracechurch Street, and Sarah Sawyers.
15, Peel.
16, The new meeting-house, viz. Savoy.
17, Westminster.
18, Peel, 20, Bull and Mouth and Horsley-down.
22, Witham, in Essex.
23, Colchester.
24, Halstead.
25, Manly.
26, Overbury Hall in Suffolk.
27, Colchester.
28, Coggeshall, Ibid, night.
29, came into London.
31, Devonshire-house.
9th Mo. 1st, Ratcliff.
3, Peel, 9th Mo.4th, Gracechurch Street.
5, Devonshire-house.
6, Wheeler Street.
8, Sarah Sawyers.
Then I was sick a week.
15, Gracechurch Street and Devonshirehouse.
Then I was moved to visit the city of Bristol; came out of London on the 16th. 17,
Reading and Newbury.
19, I came home, and stayed until the exercise of parting with my child was over:
I had three meetings, and then went to Bristol.
11th Mo. 13th, Tethbury.
14, Badmington.
15, Nailsworth.
16, Painswick.
18, Cirencester, two meetings.
21 20, Cricklade.
21, Gloucester.
11th Mo. 22nd, Ross.
23, Leominster.
25, Almley.
26, Year Island.
28, near Leominster.
29, Hereford and Ross.
30, Gloucester.
12th Mo. 1st, Gloucester.
4, Cirencester.
5, Shipston.
6, Sutton-under-Braylis and Tadmerton.
10, Banbury.
11, Adderbury.
12, Banbury.
14, Charlbury.
16, Two at Oxford.
20, Calne.
And on the 21st of the 12th Month, 1672, I came home again,
where I was ill about thirteen days; and after visiting a few meetings in Wiltshire,
I went to Bristol, was at several meetings there, and in the country adjacent.]

Now in my foregoing travels many were convinced, and the mouths of gainsayers stopped:
the Spirit of God fell on divers that have now a testimony to bear for his name.
I was many times brought very low in my body, even to the brink of the grave;
yet God Almighty, in lovingkindness, raised me up again, particularly twice,
in a marvellous manner.
Great were the trials, sorrows, difficulties and jeopardies, inwardly and outwardly,
that I went through in this travel, which God Almighty only knows;
and great were his deliverances many ways;
one particular instance of which here followeth, to wit; in going over the sands,
near Margaret Fox`'s, in Lancashire, I was wonderfully preserved with four more:
for being come down to the sea-shore, in order to cross the sands,
two persons that lived on the other side informed us, we might go over safely;
and nothing appeared to the contrary: but when I attempted to go,
I was stopped in my mind; and waiting a season on the Lord, I was forbid to go;
and it was showed me, that if any attempted to go at that time, they would perish;
which caused me to hinder passengers from going: and in about an hour the sea overflowed;
so that if we had gone, in all likelihood we had perished;
which when some that were there saw, they were greatly tendered,
and magnified the name of the Lord.
