== Chapter III.

[.chapter-synopsis]
* A warning to the cities of London and Bristol
* Remarkable protection from persecution during his travels through the nation
* His sufferings at some other times
* Great convincements which resulted from his Gospel labours
* Notice of the apostasy of John Wilkinson, and John Story, and exercises occasioned thereby
* The designs of the separatists defeated
* Charles Marshall is imprisoned in London
* Remarks on his Gospel labours and other service
* His last illness and decease

When visiting the city of London, I left a paper, a copy whereof here followeth:

[.embedded-content-document.paper]
--

A warning to the people that have lent their ear to the declaration of the truth,
and have not received it in the love of it.

A warning to those convinced of the truth, who have not subjected themselves thereto,
in pure, living obedience.

A warning to all who have begun in the Spirit, and set their faces Zionward,
that they neither return into Egypt, (spiritually so called,) nor sit down by the way.

The dreadful day of Gods vengeance proclaimed,
in which all professors and professions shall be tried, the floor thoroughly purged,
the wheat fanned, and the gold tried; and the day of God +++[+++shall come]
upon all images and likenesses.

A treading down of all that which is risen through a loss of the ancient, eternal power.

A day of calamity, misery, amazement and distress,
to come upon the inhabitants of the city of London,
and the begirdings of sorrow upon the nation of England; and after this day,
the day of gathering through nations,
of the dispersed of Israel and the scattered of Jacob.

--

In the name and authority of God Almighty,
I also cleared my conscience of the city of Bristol,
and have not kept back his counsel from them;
but in the power and demonstration of his Eternal Spirit, and in all manner of plainness,
I have declared the truth as it is in Jesus,
manifesting the many snares of the enemy that do attend Friends of that city;
and I am clear of the blood of the inhabitants thereof,
and of all professing truth therein;
and am assured that a day of deep trial will come upon many of its inhabitants; for,
as was my testimony to the city of London, so was it to the city of Bristol.

Now, in this day of my travel through the land,
there were many attempts made for my imprisonment; but the Lord was with me,
as often it was his word, I am with thee;
and the word of the Lord was as a fire in my bones, +++[+++constraining me]
to run through the land:
and he helped me often in the spiritual battle with the
enemy of the souls of the sons and daughters of men.
And so it was, that although the laws were then put in execution against dissenters,
which empowered the magistrate to fine twenty pounds for the house wherein was a meeting,
five shillings for every person present, and twenty pounds for the preacher;
and those that were accounted able, were to pay the fines of the poor;
and the informer to have a third part thereof; yet in this time of sore persecution,
in all my passage through cities, towns, and all the counties in England,
no man was suffered to lay hands on me to stop my way; neither did any man,
that I know of, lose five pounds on my account, throughout the nation.
This short account I leave to posterity, not out of any glory to self,
but to magnify and exalt the holy power and arm of the Lord;
and that many travellers yet to be raised up, may be refreshed,
and trust in the Lord Jehovah, in whom is everlasting strength.
For although He call to hard things, yet is he not a hard Master,
but giveth power unto all that believe in his Arm and trust in Him;
his glorious power and right arm of salvation hath done glorious things in our day:
unto Him, through generations, be given and rendered everlasting praises, honour,
holy thanksgiving and renown, +++[+++even]
unto Him who liveth forever and ever.

[.small-break]
'''

+++[+++Although Charles Marshall was,
as he observes whilst engaged in the above-mentioned extensive service,
preserved in a remarkable manner, from imprisonment and personal abuse,
yet it appears that at some other times he shared with his
fellow-professors in sufferings for conscience sake.
In the year 1664, a law was passed,
bearing the title of An Act to prevent and suppress seditious conventicles,
which forbade the assembling together of five or more persons
under color or pretence of any exercise of religion,
in other manner than is allowed by the liturgy or practice of the Church of England,
on pain of imprisonment or fine for the first and second offences,
and transportation beyond the seas for the third offence.
Among the names of 219 persons, convicted under this Act, of the first offence,
are those of Charles and Hannah Marshall.
Charles Marshall was also, in the year 1670, taken up by a priest, on a writ,
issued by virtue of a law passed in the 23rd year of Queen Elizabeth,
which enacted that every person not repairing to their parish church,
shall forfeit twenty pounds for every month they so make default.
See Besses Collections of the Sufferings of the people called Quakers.

Another instance of suffering which befell Charles Marshall, is related by John Whiting,
a friend who resided in Somersetshire, as follows:
It was in great dread and power he came among us, and had great meetings in our county,
as at Portishead, Nailsea, Backwell and Claverham; at which last place he was,
in the Tenth Month, 1674, pulled down as he was at prayer, by some justices of the peace,
so called, (but some of them, in those days,
were the greatest disturbers of it;) particularly Francis Pawlet, of Wells,
who laid violent hands on him, to pull him through the rail where Friends used to stand,
griping him so, by the side, as caused him to spit blood;
and haled him out of the meeting;
which hurt he felt and complained of long after.--Editor]

[.small-break]
'''

+++[+++The Editor is unwilling to pass from the subject of sufferings,
without inserting an extract from a letter written to Charles Marshall,
wherein is exhibited the efficacy of that divine support,
through which our early Friends were enabled, even when under bonds and afflictions,
to rejoice, and give thanks.

[.embedded-content-document.letter]
--

Through the mercy of the Lord and his goodness towards me and my fellow-prisoners,
we have no cause to complain in our sufferings;
for the Lord is pleased to afford his powerful presence to attend us,
which refreshes our souls and rejoices our hearts.
For these his mercies, let my soul bless his holy name, and that forever more,
who makes hard things easy and heavy burdens light, through his goodness and mercy.

[.signed-section-signature]
John Harris.

--

The said John Harris was committed to prison at Fisherton-Anger in the Eighth Month,
1683, at the suit of Daniel Salloway, priest of Hilmarton.
When in prison, the priest his prosecutor,
endeavoured to persuade the jailer to keep him close,
and not allow him the benefit of the air.--Besse.]

[.small-break]
'''

After this, I did not travel so constantly or swiftly, nor +++[+++have I]
kept any account of many remarkable things,
signal deliverances and preservations that I met with in my travels;
but this I can say in truth, and in the presence of my God,
who opened the door of peoples hearts so effectually,
that I believe thousands received the word of life:
many were added to the church in divers places,
and meetings were settled in some places where there was never a Friend before.
In one place a whole meeting was convinced at one time;
and I never heard that any of them turned back, +++[+++or]
but +++[+++that they continued]
faithful unto the Lord.
Oh! the tenderness that mine eye has seen in many places through the land:
the watering showers that descended on the Lords plantation, is beyond expression.
Many that had apostatized and backslidden,
were effectually reached and brought back again; so that I may say,
the Lord was with me and made way for me, according to his word,
before I went forth to travel through the land.

I continued labouring until the time that John Story and John Wilkinson,
with their adherents,
set themselves up to oppose the order and discipline
that were then set up in the churches of Christ.

This opposition was carried on eagerly,
under a specious pretence of standing up against imposition;
but it took its origin from the minds of some, +++[+++who]
going into a singular spirit and getting into an undue liberty,
endeavoured to lead others into the same; a fearful, slothful spirit,
that left and turned from the pure power of the Lord,
and a daily dependence on its fresh arisings and quickenings;
retaining a ministry of the doctrinal part of truth, in a dry and dead spirit;
endeavouring to lay waste the Quarterly Monthly, Yearly, and Women`'s Meetings,
by opposing the settled methods thereof; calling them forms and an idol;
when indeed it was the same divine power and wisdom that gathered us to be a people,
that caused the setting up and settling good order and discipline amongst us;
for taking care of the poor, the widows and fatherless;
for care as to due proceeding in that great concern of marriage,
and other things relating to the service of Truth and the welfare of the church.

Great was the travail of our ancient, honourable friend George Fox,
in this weighty concern, in the first breaking forth of Truth in this age of the world;
and several other brethren were also deeply concerned in
the settling of many meetings in the said good order;
and we found the Lord with us in our work and service.

Now the power of the Lord wrought thus, to settle us a people in a good order,
that we might appear to the world to be guided by his wisdom,
and be found in the form of godliness,
as it arose from the power of it inwardly in the soul.
But the enemy, that would have had us a people in confusion, a Babel instead of a Zion,
wrought designedly, in the earthly, sensual wisdom of some loose-spirited men,
who had lost their divine sight and sense of the goings and leadings of the Almighty,
and brought them into a false imagination,
that we were going from the inward guidance of Gods Spirit,
to set up forms like other professions,
and thereby were leaving the light of Christ Jesus,
which was to be every mans guide in faith and practice.
Hereupon they endeavoured, with all their strength,
to break down and lay waste the meetings before mentioned, crying,
imposition on conscience was the cause of their separation;
when in truth it was an opposition by the power of darkness working in themselves,
whereby they were quickly benighted; and many ran into their errors.

Now this spirit brought great affliction and travail upon some particulars,
in the beginning of its workings in Westmoreland and other parts of the north;
and in Bristol, Wiltshire, Gloucestershire and some other places.
Great was the hurt and disorder it made in Bristol and Wiltshire;
because of which the Lord concerned me, with other faithful brethren,
in his name and power to make war, in great travail, sorrow,
tears and distress of spirit, for several years together;
to run in between the living and the dead.
I travelled +++[+++on this account]
in Gloucestershire, Somersetshire, Berkshire, and to London, for several years;
and can say, the Lord God,
who guided me to travel in his name and dread through the land,
was with me in this day of deep exercise; and I have cause, in great bowings of spirit,
to magnify his glorious name, who preserved me faithful over all discouragement.
My bow he made strong, and my quiver he daily replenished with arrows;
my soul he caused to be, as it were, baptized for the dead,
as one eating the bread of adversity, and drinking the water of affliction;
and I spared neither strength nor substance.

And indeed,
to a great height of opposition did this spirit of division rise in divers instruments:
the clouds were so thick, and the mist of darkness so great,
that many poor sheep were in danger of becoming a prey to the wolf and devourer.
The honest-hearted were grieved and bowed down,
and the rich in imagination exalted in rage and fury;
so that this separation came quickly to be spread in the sight of the world;
and in several places we were shut out of our meeting-houses,
and exposed in the streets to the view of the world.

I very well remember the day that I received instructions of the Lord in a vision,
concerning that people, wherein their work, end and downfall were shown unto me;
so that a concern came on my soul to invite faithful Friends of
Wiltshire to have a meeting on purpose to wait upon the Lord,
in a deep concern of soul; and to cry to him to appear for his names sake and his people.
And friends did readily answer my desire, and we agreed upon such a meeting;
and the first was in the town and place where +++[+++the opposers]
designed to have laid waste the Quarterly Meeting of that county.
When we were waiting upon the Lord,
this was the cry of my soul amongst friends and brethren:
O Lord! what wilt thou do for thy great name, that is dishonoured;
thy heritage whom the enemy and destroyer would now scatter?
+++[+++he would]
devour thy lambs, spoil and trample down thy vineyard, etc.
Thus we cried, in bowedness of spirit before the Lord, who heard from heaven,
his holy habitation; and his power broke forth in a wonderful manner,
tendering his people before Him: the Majesty of his presence,
and glory of his power and heavenly wisdom,
comforted and confirmed his servants that day;
and Friends were opened to speak well of the name of the Lord,
and greatness of his power and appearance.
This meeting was then concluded to be continued, and it was so for many years;
our wrestling therein prevailed with the Lord,
who attended us with his heavenly power and presence; and we saw from that day,
the blasting of that spirit in all its undertakings, and the confirming of +++[+++the Lords]
heritage and people.

And the same power of God wrought a great, inexpressible travail in the city of Bristol;
there the Lord God of Power many times signally caused a decision,
(and that in great assemblies, as at their fair-time,
when many of those preachers up of separation flocked together,)
and disappointed the design of their great appearances:
Davids sling and stone smote their Goliath, that rose up against the armies of Israel;
and +++[+++the Lords]
glory has shined over all.
I cannot forget the many days, nights and years of sorrow I went through in that city,
wherein I laboured, in the power of the Most High, for the settling in some measure,
the churches of Christ, in the city and adjacent counties, in peace and good order.

After this time did the enemy fill the heart of the priest of the parish where I dwelt;
and he laboured many months to get me into prison, and take away my substance;
sparing no cost until he got me into the Fleet-prison in London, where I was both before,
and at the time of the great frost,^
footnote:[According to a respectable publication of [.book-title]#Remarkable Occurrences,#
this frost commenced in the Tenth Month, 1683, and continued 13 weeks.]
and thus came to be separated from my dear wife and children:
in about a years time after, my family removed up to London.
During this imprisonment I suffered much in body, spirit and substance,
known to the Lord, who was with me, as his word was often to me in my travails.

About the space of two years after, the priest came to the prison,
caused the doors to be opened, and brought me out; and some time after he died.

[.small-break]
'''

+++[+++Our historian John Gough, in his account of Charles Marshall,
states the following particulars respecting this imprisonment: In the year 1682,
whilst resident at Tetherington in Wiltshire, he was prosecuted for tithes,
by John Townsend, priest of that parish;
in consequence whereof he was arrested and brought before
the Barons of the Exchequer and committed to the Fleet-prison,
where he was confined for the space of two years.
The priest growing uneasy in his mind about this time, came in person to the prison,
released him, and soon after died.--Ed.]

[.small-break]
'''

I then settled, with my family near London,
and for many years laboured in the gospel in that city;
and was greatly concerned for the sick,
and in several services for Gods church and people:
I was frequently concerned with some in the government,
in behalf of his suffering people and the good of my native country;
which I shall pass by, as to particulars, desiring to be as concise as may be,
in this account of my labour, travels and exercises.
But before I conclude, I must say, for my last three years,
I was several times concerned to visit the city of Bristol and adjacent counties.
And God Almighty concerned me in a great travail, in those several visit,
which he gave me power and strength to go through; where his glory did shine over all,
his river ran, his latter rain descended; the springs of the sheep have been broken up,
and the mysteries of the kingdom,
and travels of spiritual Israel have been abundantly opened and answered.
Oh, that they may be a worthy people,
to the praise and renown of the name of the Lord! is my souls cry to the God of my life,
on their behalf.

[.signed-section-signature]
Charles Marshall.

[.small-break]
'''

+++[+++The account which follows,
of the peaceful close of this diligent labourer in the Lords vineyard,
is extracted from Gough`'s History of Friends, and Piety Promoted: and as it is,
for the most part,
additional to that contained in the Testimonies which precede the Journal,
the Editor trusts it will not be considered unsuitably appended in this place.]

[.asterism]
'''

His last journey was to Bristol and the western counties; after his return from which,
he was visited with a lingering indisposition, which proved mortal,
contrary to the opinion of his physicians, but not to his own;
for he seemed fixed in his opinion that it would terminate his existence in this world.

And even before his illness he seemed to have a presage of his approaching end; for,
some little time before,
he pressingly requested an intimate friend to take a ride with him,
having something of moment to impart; and when they were gone a few miles out of London,
he told him, he was satisfied the time of his departure drew near,
and therefore he was desirous of an opportunity to discourse with him,
between themselves, about some particulars, before he died.

And when, soon after this, he was seized with indisposition,
though he remained settled in opinion that he should not recover,
yet this fixed persuasion of his mind was attended with
no fearful apprehensions of his future well-being:
having passed a life of faithfulness,
integrity and extensive benevolence in the service of God and man,
he felt in the assured prospect of his approaching change,
that the work of righteousness was peace,
and the effect thereof quietness and assurance forever.

Being advised to go into the country for the benefit of the air,
he rather chose to be removed to John Padleys, near the river-side, +++[+++Southwark]
a friend for whom he had an affectionate esteem.
He lay ill about four months, in great weakness, frequently attended with great pain:
but borne up superior to his affliction, by the serenity of his conscience,
he was strengthened to bear his painful sensations with much patience,
and calm resignation to Divine disposal;
and his senses and understanding were preserved to him clear and sound to the last,
under the pure influence of heavenly support,
and the consolatory enjoyments of Divine life.

During his illness, several friends came to see him,
and he would be frequently giving them seasonable counsel and advice,
in many heavenly expressions; and would often exhort them to keep in love and unity,
and to the living, divine power of Truth,
that thereby they might be kept a people fresh and green, and living to God;
that so formality might not prevail over them.
And he pressed, that a great regard might be had of the poor,
and that some way might be found out for their employment; often saying to this effect,
that in an inexpressible manner he felt their sufferings, by reason of their poverty.
Indeed he was a man that greatly sympathised with those who were afflicted,
either in body or mind, being of a very tender spirit.

A little before his departure, he sent for John Padley and his wife into his chamber,
and said to him, Dear John, do what thou canst for the honour of Truth,
and the Lord bless thee and thine for generations to come.
And to his wife he said,
that he desired the Lord might be with her when she
came to such a time as that he was then in,
and make her passage easy; and his desire was granted,
for she died in less than a year after, and said on her dying bed,
that the Lord had answered dear Charles Marshalls request, for she lay very easy,
and freely given up.

When our friend George Whitehead came to see him, with much tenderness of spirit,
he signified his great peace and satisfaction, and that he always, from the first,
had an honourable esteem of the unity of his brethren.
And a little before his departure,
when our friend William Penn and divers others visited him,
he lay as a man gathered up in his spirit unto God; and though he was almost spent,
his voice being very low, hardly to be heard, yet by what was understood,
it might be perceived that he had in possession the earnest of that blessed peace,
which he was going to receive the fulness of:
the observation of his peace and happy condition, much affected those present.
And so he departed like a child, in a quiet frame of spirit, the 15th of the Ninth Month,
in the year, 1698, aged 61 years, and was buried from Gracechurch-street Meeting-house,
in Friends burial ground, near Bunhill-fields, London.
