== Chapter IV

[.blurb]
=== A Testimony to the glorious morning of the day of visitation of the love of God, (in particular to the city of Bristol, and adjacent parts;) and to the great and mighty power of the Lord, which appeared in and with his two precious servants John Camm and John Audland, who came to that city in the year 1654.

After the long and tedious night of apostacy spread over nations,
and dismal darkness over people,
it pleased the Lord God of heaven and earth to visit
with the morning of his ever-blessed day,
this northern island, and first the northern part thereof;
from whence came the aforesaid blessed servants of the Lord Jesus;
having received the everlasting gospel from the angel of Gods presence,
to preach in the demonstration of his mighty power; with which, indeed,
they were filled.

John Camm was a man full of zeal and fervency in the gospel,
endued with the precious gift of discerning and sound judgment;
terrible to the man of sin, and full of tenderness to travailing souls;
sharp and terrible to the evil,
but sweet and friendly to the tender and well-inclined unto the way of righteousness.
He spared not his weak body, but offered it up even unto death, to serve the Lord God,
in his blessed work of gathering, which he saw in a plentiful manner,
to his great satisfaction.
A further testimony of him, as to his country, life, travels and death,
is given by his dear wife, and his son Thomas Camm and his wife, to which I refer.
His memory is blessed, and his place is among the living ancients in Jerusalem.

John Audland was a younger man, of a ruddy, sweet and amiable countenance,
and of a cheerful spirit; one of the wise in heart, filled with the excellent, bright,
glorious power of the Lord God.
His voice was as thunder, dreadful in the strength of the Lord of Hosts,
against the man of sin, and those in covenant therewith; terrible in the dread of God,
against the workers of iniquity;
but livingly tender to the sensible travailers and poor in spirit.
Ah! my soul hath a sensible remembrance how the doctrine given him of Jesus Christ,
dropt as dew and descended as the refreshing rain.
He was a labourer indeed, night and day, in the work of the gospel,
and therein he extremely spent himself;
and his frequent and inexpressible travails in and about Bristol, I am well satisfied,
laid the foundation for the wasting of his natural life,
which was spent and offered up for the Truth, and in the work of it.
And indeed he, with dear, honourable John Camm,
were instrumental in the hand of Almighty God to our gathering;
and the spending their lives and strength was most
in their labours and travails amongst us in the city,
and adjacent parts, of which I was an eye-witness, being frequently with them.

These two ministers of Christ Jesus came to the city of Bristol, in the Fifth Month, 1654.
And first they came amongst a seeking people,
who kept one day in the week in fasting and praying;
waiting for and breathing in spirit after the morning and visitation of God,
and day of redemption.
Amongst us they spake the powerful word of life,
in the dread of his name who lives forever;
and we were seized on and smitten even to the heart; and that day,
and the visitation of it, overtook us, which we had longed and waited for;
and from darkness to the marvellous light of the Lord we were turned.
Some meetings we had, before the more general gathering in and about the city,
which began on this wise.
On a First day in the morning, I went with these two servants of God,
about a mile and half from the city, to a little spring of water,
where I often had spent many solitary hours in my tender years, seeking the Lord.
Here we sat some time, and drank of the spring.
After some hours of the morning were spent, I saw in them a great travail of spirit.
J+++.+++ Audland trembling, said, Let us be going into the city.

So we came to the street called Broadmead,
to a house where several people were met together, inquiring after these two men of God.
John Audland was under a great exercise of spirit, and said:
Is here any one that has an interest in any field?
An ancient man said, I have, in a field pretty near.
Notice being given to the people in the house, they came forth; and as we went along,
people in the streets went also to the field,
(called Earls-mead;) so that we came a pretty number, and some scats were brought.
Dear John Camm began to speak tenderly, and in great zeal,
directing to the heavenly grace of God,
and testifying fervently against sin and iniquity: to +++[+++his testimony]
some were attentive in this season.
I perceived a great exercise on my dear friend and father in Christ Jesus, John Audland,
who trembled very much.
After dear John Camm stood down, he stood up, and full of dread,
and with brightness on his countenance, lifted up his voice as a trumpet, and said,
I proclaim spiritual war with the inhabitants of the earth,
who are in the fall and separation from God, and prophesy to the four winds of heaven;
and so went on in the mighty power of God Almighty, opening the way of life.
But ah! the seizings of soul, and prickings at heart, which attended that season.
Some fell on the ground, others cried out, under a sense of the opening of their states,
which indeed gave experimental knowledge of that which is
recorded Acts 2:37. Indeed it was a notable day,
worthy to be left on record, that our children may read, and tell to their children,
and theirs to another generation; that the worthy,
noble acts of the arm of Gods salvation may be remembered.
At this meeting many were effectually convinced, and from darkness to light turned;
and afterwards our meetings grew larger and larger.
They visited the meetings of those called Independents and Baptists,
testifying amongst them, in great power, the things given them of God;
directing the poor and needy in spirit, who saw their want of the Lord Jesus Christ,
no longer to seek the living among the dead; but to look from the mountains and hills,
dead ways and worships, unto Christ Jesus, the Fountain of life and salvation.
There was added unto the gathering daily;
and great dread was round about and in our meetings,
under the seasonings of the Holy Ghost.
Oh! the tears, sighs and groans, tremblings and mournings,
in the sight of the middle wall of partition, that we saw then, in our awakened state,
stood between us and the Lord,
and in the sight and sense of our spirited wants and necessities!
Oh! the hungerings and thirstings of soul that attended daily,
and great travails of spirit, to obtain, through the working of the mighty power of God,
dominion and spiritual victory over the enemy of our souls,
who had led us in the paths of death and darkness!

And indeed, as the visitation of Gods holy and ever blessed day,
was signal and inexpressible; so I testify,
in the fear and dread and awe of God Almighty, we received the gospel with a ready mind,
with broken hearts and affected spirits; and gave up to follow the Lord fully;
casting off the weights and burdens, and the sin that easily beset,
and from the evil ways and vanities of the world departed.
Oh! the strippings of all needless apparel,
and the forsaking of superfluities in meats and drinks! in the plain,
self-denying path we walked, having the fear and dread of God so on our souls,
that we were afraid of offending in word or deed.
Our words were few and savoury, our apparel and houses plain,
being stripped of superfluities; our countenances grave, and deportment weighty,
among those we had to do with.
Indeed we were a plain, brokenhearted, contrite-spirited people;
our souls being in an inexpressible travail to do
all things well-pleasing in the sight of God:
for our great concern night and day was, to obtain through Jesus Christ,
the great work of salvation,
and thereby an assurance of the everlasting rest and Sabbath of our God.

And in those days, Oh! the inexpressible labour, travails,
and spending of the strength of these servants of the Most High,
in great assemblies in that city, and countries round about!
Our meetings were so large that we were forced to meet without doors,
and that in frost and snow.
In which meetings, Oh! the extending of the voices of these servants of God,
to reach over the great multitudes, when several thousands have been assembled together!
And as the work of the Lord increased,
so the enemy wrought in priests and people in those days,
who stirred up the youth of the city, into a tumult, like the +++[+++shrine-maker]
of Ephesus; and once we had a very great tumult: the streets were crowded,
and these two servants of the Lord were seized by the multitude,
and were in great hazard.

But the Lord signally delivered them,
(as in days past he did his servants on such occasions,) and all came to be quieted,
and our meetings peaceable: many grew in grace,
and in the knowledge of God and Christ Jesus, which is eternal life.
Much more of particulars I might write, but I affect brevity for several reasons.
I say in short, such was the effectual working of the mighty power of God,
and making bare of his arm of salvation, that attended those servants of the Most High,
and the great work of our gospel Meetings,
with the various trials and exercises that attended them,
and us who were the fruits of their labours in the Lord,
that my tongue cannot express +++[+++all]
that I was an eye and ear witness of, and soul-sharer in.
Therefore to the God of this bright morning of our day of visitation, ariseth,
springeth up, as +++[+++from one]
in covenant with Himself through Christ Jesus, holy, heavenly high praises; and might,
majesty and dominion are ascribed to the Lord God and the Lamb: so let it be,
saith my spirit, in fear and trembling, through ages and generations,
forever and evermore.
Amen.

And now, dear Friends everywhere, but more particularly in and about the city of Bristol,
who have seen the morning of the day of God break forth in our age, as aforesaid;
and by the Divine light thereof,
have seen the darkness that has covered the people dispelled; (in which darkness,
people have been ignorant of the true and living God, and his precious work of salvation,
and in this ignorance have performed their worship,
even in the same nature in which they are sinning, and rebelling,
and grieving the good Spirit of God, which all ought to be subject to:) +++[+++Remember how]
it pleased the Divine Being, in his infinite love, and tender pity and compassion,
to look down upon us, whilst in the land of Egypt, and house of bondage spiritually:
and to send forth his light and truth,
to give us a sense inwardly of the deplorable state of our souls, in the separation from,
and deprivation of, the enjoyments of the Lord.
This sense and sight begat in us living breathings,
and a holy cry after the knowledge of Him we saw ourselves ignorant of; and He,
in the fulness of the dispensation of time visited us, as afore-mentioned; of which,
dear Friends, we were right glad; although when the Lord discovered our states,
he laid judgment to the line, and righteousness to the plummet,
and gave to us the cup of trembling, wherein was the wine of astonishment.
+++[+++Yet this]
was in mercy to our poor souls,
that could not be redeemed but by judgment poured
on the nature that had separated us from God,
and on us as joined thereunto; and here, although sin revived, we began to die to it.
Oh, good day, and precious season! worthy, worthy, to be remembered both by us,
and our offspring,
through generations! for although it was the season of the administration of condemnation,
yet was it glorious; and in this season the Almighty God, by his spiritual trumpet,
sounded to us, that the end of this his spiritual appearance was to root out, lay waste,
and utterly destroy the nature of sin and iniquity,
that had divided and separated us from God,
and hindered the good things from us of his heavenly power and kingdom.
We were persuaded the set time was coming for cleansing and sanctifying the temple,
and fitting it for the pure immortal God; and did not we begin inward,
as in the day of Hezekiah, that the temple might be cleansed thoroughly in every part?
For in the outward temple they cleansed first the inward part of the house of the Lord,
and so came along to the porch, until the temple was thoroughly cleansed.
Indeed in the morning of our precious day of visitation,
the axe was laid to the root of the corrupt tree, and the hammer to the hard,
rocky heart, and the spiritual fire was kindled in the stubble.

Now, dear Friends, in the word of Truth I say unto you,
search with the holy light of Christ Jesus, how this work has prospered in your souls;
see whether you that knew a right beginning first in the inward part,
have come along faithfully in the work of sanctifying the heart and the temple,
from the inward part to the outside; see whether the root has not escaped the axe,
the rocky heart the hammer, and the chaff the fire; for if it has,
the cause is not in the Lord, nor in his power, but in your disobedience and negligence,
going from the axe, hammer and fire, and so sparing the best,
as disobedient Saul and Israel did;
so the root of bitterness springs up against the work of God,
and bringings forth of his heavenly wisdom.
To the holy, plain speaking witness of God I appeal,
earnestly desiring and entreating all to have a single regard
to that which will duly and rightly apply these things;
and let all see whether that nature be alive,
that the holy power of the Lord did work against in the beginning; and if so,
see the cause, which being seen,
will deeply humble and seize on the spirits of all concerned.
Oh! what a day have we had!
How has the good Husbandman been at work in his vineyard!
How did He plant in a fruitful hill, with the choicest vine!
He digged, pruned, and gathered out the stones, and hedged and walled about; and,
after all, He looked for good fruit;
but where the unspeakable mercy and long-kindness of the Lord has not been answered,
behold wild fruit and sour grapes were brought forth.
And what was the consequence of it?
Was it not the taking away the hedge, through which it was eaten up;
and breaking down the wall thereof, and it was trodden down?
Read, see, feel and consider;
and the Lord God Almighty visit you in your habitations and secret chambers,
with his holy dread, and with his searching life and piercing word of power,
who in his tender infinite love and mercy, long-sufferings,
great bowels to his seed and offspring, visited us in his pure morning aforementioned,
to give all the sense of their inward states, as they are in his sight,
from whom nothing can be hid.

And now, dear Friends, the hindrance of the prosperity of the work of the Lord,
in the souls of any, hath not been from any cause in God, or deficiency in his light,
power and wisdom,
but from the creatures going out of a capacity of
receiving and enjoying the working power of God,
in which salvation is worked out, by all that wait for it, join with it,
and cleave to it, and do not forsake it, for I have learned of the Lord,
through many exercises inexpressible,
that after the visitation of the Almighty to any soul,
He requires an inward worthy receiving his love,
and the spiritual watch to be kept in his holy light,
in which all the workings and approaches of the destroying
adversary of the soul is discerned,
and the enlightened and obedient mind is preserved.
And through the spiritual sense,
given in a tender waiting on the Lord in the inward part,
supplicating breathings arise to the living Eternal God of love and compassion,
who beholding the want of the soul, descends in his love,
and reaches forth his helping hand to the broken and contrite-hearted,
and lifts up the bowed down spirit, with the liftings up of his holy spiritual standard.
So the temptations and assaults of the enemy are vanquished and overcome,
and the power of God is felt in those that descend with it in humility,
to be working on the root as an axe, on the rocky as a hammer,
and on the chaffy as a fire.
Now, Friends, when there is an abatement of the inward and spiritual care,
and a gradual lessening of the inward watchfulness,
the mind becomes both unworthy and incapable of the enjoyments of the power of the Lord,
that begun and carrieth on the work of the Lord: then the enemy comes as not seen,
through the minds being out of the holy watch in the light,
the nature that was wounded comes to be healed again,
and ease given to that which should be destroyed: and the enemy,
perceiving where the weakness is, and how,
and by what means he has got a little entrance,
endeavours with all subtlety and vigilance, by presenting matters and subjects,
to lead by degrees out of a watchful state; and according to every degree of digression,
he brings over the once enlightened mind a proportion
of darkness and deceivableness of understanding,
and insensibility of spirit.
The enemy of the soul thus works,
that with the declining there may be a proportion of benumbing the inward sense of seeing,
hearing and feeling; and then again he has mankind in a state fit to work upon,
by drawing them out by his power,
to act and bring forth that which he sees them most capable of,
and which there is the greatest inclination in their natures to go into:
hence schisms arise in judgment, which the wrathful part in man getting into,
he works by the way of a fierce management, with a sort of zeal,
but not according to knowledge.

The enemy is never wanting to present matters to the mind, as just,
for the creature to be blown up with,
which end in dishonouring the Lord and his precious truth, and in hurting others.
When the enemy has worked his end +++[+++on any]
by such instruments, he brings them into an alienation from the life of God,
into a worse state than the tender day of Gods visitation found them in; and so,
if not humbled under the mighty hand of God, and returning, they are exposed to shame,
and so die away under the wrath of God.

Now, dear Friends, the enemy of Zions prosperity works variously,
according as he sees where he may get an entrance,
proportioning his snares to the inclinations of every one, as before is hinted.
Where he sees an inclination in any to be taken with earthly things,
there he works subtly to captivate the mind, and draw it out of the watchful, tender,
spiritual state, into a false liberty, both to the affections,
to the things acting and possessed, and in the conversation amongst men;
others +++[+++he draws]
into superfluities in meat, drink and apparel, on themselves and houses; and such,
their comforts stand most in outward things,
and by degrees they are swallowed up of them, and the pleasures, lust and delights below;
and so they die to an inward life of watchfulness and freshness,
which is preserved in fear and dread, in keeping the holy watch,
and in the spiritual cross, which crucifies to the world, and the world to it.
Now, dear Friends, here is our spiritual encouragement, viz.,
the same that through death to sin made us alive to God,
as we abide under the leadings and teachings of it, keeps us alive to Him, in a growing,
increasing, fresh flourishing state; for as we delight in his eternal law of life,
we grow as willows by the water-courses of immortal refreshings,
and travel faithfully on in our spiritual journey, until we come to Zion,
the city of God, and then are enjoyers of the end of all our trials and tribulations;
having overcome, we see an entrance administered, and that abundantly,
into the eternal rest and sabbath of our God.

The Lord Almighty give all to enjoy this blessed portion and goodly inheritance;
and let all see in this age, and the ages to come,
all that which lets and hinders them taken out of the way,
that the God of all our mercies, in whom are all our fresh springs,
may have his honour and glory,
and his church and people through ages the comfort and consolation.
Amen.
Amen.

[.signed-section-signature]
Charles Marshall.
