== Chapter V.

[.blurb]
=== An Exhortation to the Quarterly, Monthly, and all other Meetings set apart for the transacting the affairs of Truth.

[.salutation]
Dearly Beloved Friends,

This exhortation ariseth in my heart, in the motion of Gods immortal Power and Spirit,
unto all concerned in the meetings above mentioned,
that before you begin to speak to the matters that
shall lie before you in all such meetings,
you take a little time to wait on the Lord,
to feel your minds gathered and inwardly retired into the heavenly light of righteousness,
and there wait to feel the pure spring of wisdom, which is from above,
and is pure and peaceable, in which every one may see and know his place in the body.
And as every one is here centred, all waiting,
in brokenness of heart and contriteness of spirit, upon the Lord,
the sensual wisdom being under foot, and self made of no reputation,
but humbled to the very death of the cross;
all seeking the prosperity and welfare of the body,
in the one universal spirit of life and love; then when a matter is spoken of,
all will ponderously weigh the thing, in the heavenly peaceable wisdom of God;
and as any things therein are opened in the understanding,
there will be a pertinent speaking to the matter; and such speaking will be savoury,
and one by one, as anything opens in the understanding that may be helpful.
And here, in the unity of the one Eternal Spirit of life and peace,
things will be soon dispatched; for things will be seen through,
as the inward eye and sense is opened and attentive to the heavenly oracle.

And, dear Friends,
as your concerns in all such meetings are managed in the meek spirit of Christ Jesus,
the Savior of the world, you will all be refreshed, and go away from them comforted,
being leavened and seasoned by the grace of God amongst you;
and as you thus return to your respective places again,
amongst your brethren and sisters, the savour that you come from the meetings in,
will refresh, strengthen,
comfort and encourage your brethren and sisters of the meetings you belong unto.

But where there is not a waiting thus to be led and guided,
so as for all to know their places in the body, (for every member is not an eye, a hand,
or a foot,) there will be confusion: and if the earthly, sensual wisdom,
in which are the rents, the contentious passions, haste and heat,
if this gets up to order there, the fruit will follow;
and then the heritage of the Lord will be grieved, burdened and bowed down,
and this leaven will work to leaven others; and so, dear Friends,
as the right and well-managed of these meetings would
be inexpressibly profitable to the body in general,
so the wrong management cannot but cause great hurt to the body.
The Lord God of power, wisdom and strength,
cause this matter ponderously to weigh on all hearts concerned herein,
that so He may have his honour, and we all the comfort thereof.

And, dear Friends, God is and will be jealous for his name, glory and honour,
and will not give it to another; and nothing must rule in and amongst the Lords people,
but the Spirit of God, and those who are guided by that Spirit.

And so, Friends, having in some measure cleared myself, in the counsel of the Lord,
in this matter; and desiring that eye may be opened in all, and kept open,
that will see much weight in it, beyond what is here expressed, I remain,
in a travail to see Zion delivered,
and brought up into the very perfection of the beauty of holiness,
which was the righteous end of the Lords visiting us with
his holy glorious day-spring from on high.

Your dear brother, in the measure of the grace of God received,

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
Sutton-under-Brailes, 14th of the Eleventh Month, 1671.
