== Chapter XI.

[.blurb]
=== A Tender Visitation of Love, to the called of God everywhere; being a testimony to the precious, ancient, sweet, living power of the everlasting God.

[.salutation]
Dear Friends,

Gather you everywhere inward, into a feeling of, and continuing with,
and subjecting unto, the glorious, precious, ancient, living and mighty power of God;
and let all diligently attend its teachings, leadings, openings and operation;
that by it a search may go through all hearts, all families and assemblies;
that all that grieves his Holy Spirit, and is offensive in the pure eye of the Lord,
may be sought up; and every garden viewed to see what grows there,
that every plant that is not of the Lord`'s right hand planting,
may be discovered and pulled up.
For, Friends,
under the weighty dread of the Lord God Almighty
is my soul exercised at this time to say unto you,
the Lord is arising to prove, to try, to fan, to purge and refine; for the day grows on,
that will burn as an oven: but what shall abide?
and who may abide?
let this be the examination: for the lead, the tin, yea, also the reprobate silver,
will pass away in this refining fire.
And that which may have the likeness of gold, and is not of a pure, enduring nature,
will vanish, and leave all poor that possess not the gold.

So dear Friends, everywhere, I say unto you, in the dread, awe, fear,
and name of the Lord, _haste, haste out of all that is not weighty,
out of the nature that keeps the soul in any bondage and distance from the Lord._ Yea,
hasten out of the state of professing the truth, in a nature and spirit contrary unto it,
which grieves the Spirit of the Lord God.
Dear Friends, the pure eye of the Lord that runs to and fro,
beholding the evil and the good, sees all states and conditions,
all false ways and false births; all that run from the daily cross,
all that lose the sweet lovely image of God,
and are growing up in another image in the house of imagery,
and walk in the land of graven images; and all that depart out of the sweet, tendering,
heavenly wisdom, into that which is earthly and sensual,
wherein there is a priding in the openings opened in the day of tenderness,
and an increasing in that knowledge which will bring increase of sorrow,
a growing into the state of being fat and strong, that must be fed with judgment;
and sees all that know the truth, its way and work, and come not into obedience unto it:
I say, the pure, immortal eye of the eternal, ever-living God,
sees all these states and conditions,
and all the by-paths and crooked ways the souls enemy leads into;
and his holy power is arisen to bring them all to judgment.
Therefore hasten, hasten, +++[+++ye]
who are concerned herein, to meet the Lord God Almighty in the way of his judgments.
Bow, bow unto the pure power of the Lord; feel it in its burning and consuming,
where there is matter that hurts the soul, that bondageth the soul,
and darkeneth the understanding;
that so all may be comprehended down under the dominion and reign of this glorious power,
through its consumings,
utter destroyings and burnings up all that is contrary unto the divine nature thereof.
In this power immortal, peace is known with the Lord,
through his blessed work of spiritually slaying the enemy;
and thereby is the reconciling to God through Christ Jesus our Lord.
And all dear and tender friends, who are lovers of this sweet, ancient power of the Lord,
and have heavenly tastes thereof, and sweet, precious openings thereby;
Oh dear friends! dwell with it and in it, and it will give you your souls desire,
crowning you with dominion over the man of sin, his root and fruit;
and in it will your inward man, in spirit, walk with God who is a Spirit,
and obtain that which Enoch obtained, even that consolidating testimony,
that you please God.
And therefore all friends everywhere,
wait for the fresh springing and glorious arising of this Almighty power of the Lord;
that it may shew itself signally everywhere, rending all veils, breaking all bonds,
opening all graves, raising up all souls into life itself:
that in all your assemblies and meetings everywhere, this testimony you may have,
that life and immortality are brought to light;
and in it may rejoice with joy unspeakable and full of glory,
because this immortal power reigns over all, glows over all, waters all, melts down all,
fills all, sweetens all: that in the enjoyment of its spiritual fillings,
holy high praises, thanksgivings, in the sweet, spiritual melody of eternal life,
may rise, spring, and be offered up in the sweet overcoming of his love,
who is the mighty power of God unto salvation; that so all that is false and wrong,
that grieves the good Spirit of the Lord,
may be driven and carried away before the mighty stream, and strong flowing,
of this immortal power of the Being of beings.

And now, all you lambs and babes and weak ones; and all you suffering, sincere ones,
under the buffetings and temptations of your soul`'s enemies;
and all you prisoners everywhere for the testimony of Jesus,
in all your various exercises, trials, straits, necessities and temptations;
and you mourning, tribulated servants of God for Zions sake,
whose souls have been oppressed, grieved and bruised, under the sense of the crushing,
bruising, and treacherous work of Zions enemies;
look up to the Lord God of tender compassion, who is bowing his ear to the cries, groans,
and supplications of his oppressed in every state, whose souls love the Lord,
and have chosen his strait way, and pure path of self-denial.
Feel, feel the arising of this immortal power of the Lord,
which will help over all weakness and insufficiency, over all straits,
sorrows and temptations.
Arise, arise, in the arising and immortal power; for the Lord is arising in the land,
and his work shall prosper,
and his determined counsel which he hath caused to be proclaimed therein,
he is bringing to pass.
Woe, woe to the wicked! let their profession be what it will, it shall go ill with them:
but with the righteous, saith the Lord, it shall go well.
Be therefore encouraged, for the Lord strong and mighty is on his way:
ye tender people of the Lord everywhere,
that diligently wait upon him with brokenness of heart and contriteness of spirit,
heaven`'s windows over you shall be opened,
and showers of plentiful blessings shall come down on your souls.
You hungry ones, you shall be fed with the bread of God; and ye panting ones,
you shall be nourished with the virtue of immortal life; and ye thirsty ones,
ye shall be abundantly refreshed with the new wine of the kingdom of God,
handed to you by the hand of power, in the cup of his salvation.
But the high, the haughty and the rebellious, the stiff-necked, shall mourn;
and the tongues that have been lifted up against the work
of the Lord and the bringing forth of his power,
shall be gnawed for pain:
and the Lord will smite the proud and confound the enterprizes of the sensual:
and his power shall go over all, and tread down all thine enemies, O Zion,
that hast gathered to this immortal power, and with it continuest, and to it subjectest;
its brightness and glory shall be thy covering.
This is the testimony for the glorious Lord Omnipotent and Omnipresent.

Of your dear, travailing friend and brother,
in the labours and travail of the gospel of peace,

[.signed-section-signature]
Charles Marshall,

[.signed-section-context-close]
Tetherton, the 16th of the Eighth Month, 1679.

[.letter-heading]
An Epistle sent to Oxford.

[.salutation]
Dear Friends and Brethren,

In the love of my Father is this salutation unto you,
greatly desiring the powerful presence of the mighty, everlasting God,
may be signally with you in this your meeting, and in all your meetings;
that wisdom from on high may descend amongst you;
and that the river of that love wherein Zion is a city at unity with itself,
may plentifully and livingly flow among you,
even that love in which the body edifies itself:
that so being sweetly opened and furnished thereby to every good word and work,
ye may serve the Lord faithfully.
And as you have been a good savour to adjacent counties,
because of your zeal and faithfulness, love and unity one with another, so continue,
increase and abound therein, I exhort you in the presence, power and counsel of my God;
that so nothing but a good savour of you, through Jesus Christ, may be in every place.
In order to which, grow in that which unites and cements;
and live and walk in that which makes for peace, and in the noble seed of life,
in which the Father is honoured.
And as you live, walk and persevere herein, you will see the evil seeds-man,
and in every concern, keep in dominion over his sowings, through any occasion whatsoever,
which is the thought and counsel of Israel`'s God unto you.
That in and through the brightness of the everlasting, glorious Truth,
you may shine in all your several places and services, and be good examples in love,
fear and unity, and all sweetness of life to the adjacent country;
that the rain of God`'s heavenly love in showers may come
down daily upon and amongst you in every meeting and family;
that you may grow like a well-watered garden, full of trees and plants of righteousness,
and full of the divine virtue of the holy Vine of life.
God Almighty be with you in all your meetings and families,
causing it thus to be with you,
is the breathing of your travailing-spirited friend and brother,

[.signed-section-signature]
Charles Marshall.

[.signed-section-context-close]
For the Quarterly Meeting in Oxford, and from thence +++[+++to be]
sent to Friends other meetings.

[.signed-section-context-close]
Cono-Alline, the 28th of Tenth Month, 1679.

[.letter-heading]
A General Epistle to Friends and professors of the truth,
+++[+++on the necessity of the new birth.]

[.salutation]
Dear Friends,

Who with the morning light of the eternal day have been visited,
and by the heavenly power of Christ Jesus called out of the world;
I am to say to you through my Father`'s counsel, +++[+++let]
all your minds be gathered down unto the feeling of, and cleaving unto that immortal,
incorruptible seed which bruiseth the serpent`'s head: of which seed all must be born,
or they cannot see the kingdom of God,
which is excellent in celestial brightness and sweetness, full of glory, immortality,
peace and joy.

O Friends! everywhere, in the bowels of Christ Jesus,
even in the yearnings of the Father`'s love, I beseech you, feel and read in the deep,
what you know of this blessed work,
in which the happiness of the immortal soul consisteth:
for there may be a coming out of Egypt, and to the law,
which was added because of transgression, until the seed should come; yea,
to the prophets, who saw and prophesied of his coming;
and in these states there may be openings and heavenly tastes;
but the eternal welfare of the soul is,
inwardly to experience the working of the divine hand of Him who is the good Husbandman;
a cutting off from the wild olive and planting into the Vine of life;
a translating out of the evil nature and kingdom, into the divine nature and kingdom.
All come here to know a being born of the quickening Spirit, the second Adam,
the Lord from heaven; here is the state +++[+++which]
truly avails, even the new creature, which, in Christ Jesus,
hath a right to enjoy the favour and presence of God the Father,
forever and forevermore.
A profession of religion, under what name or denomination soever,
without this work experienced in some measure, doth the souls of men and women no good.

Therefore Friends and professors of the truth everywhere, in the fear,
dread and awe of the most high God, live low before him;
that so where this inexpressibly precious work is not experienced,
there may be a true waiting and travailing in Spirit,
in which a living cry and supplication will arise to the living God to accomplish it.

And now, unto all who feel true longings, living breathings,
and ardent desires in their souls, this blessed work to know,
I say in the name and power of the Lord, and in rolling bowels of love,
bow down in tenderness of spirit and sincerity of heart to this seed of the kingdom,
if but as a grain of mustard seed.
Be low within, and love that which doth discover the seed of the serpent;
love its workings and bringings forth in the heart; suffer with it,
sorrow and mourn with it; give up not only to the discoveries of the seed of the kingdom,
but also to its judgment,
that the nature and works of the seed of the serpent may be destroyed.
For the soul can never come to be one with the seed incorruptible, nor be born of it,
in which the promises are all yea and amen, but through the wasting, working under,
and destroying of this nature and work of the seed of the serpent,
which hath been as a separating or partition-wall between the soul and Christ Jesus.
So through becoming passive and subject to the power,
and the working of this incorruptible seed, in the least and lowest appearance,
it will bring every one that is acquainted therewith, very low and tender in spirit;
and possess the heart and soul with the fear and dread, and awe of the Most High;
and +++[+++will make such]
truly careful; diligent to attend to, and tender of neglecting, its secret motions,
and sweet, powerful workings in the soul.
Now tender people, that come here,
diligently and constantly cleave with your souls unto it; and you shall feel and see,
as your faith stands in it, the working of it as leaven,
to leaven you into the divine nature.
So be not weary of bearing the cross of Christ,
nor of mourning here in these deep exercises of spirit;
but persevere daily in the love of this immortal seed; for then,
coming to be born again and brought forth by the power of its workings in the soul,
ye shall be tenderly nursed up by that of the same nature, namely,
the sincere milk of the word, which lives and abides forever,
of which you were begotten;
and so grow thereby up to the day of espousal in
the marriage-chamber of divine love and life,
where the soul is safe in the enjoyment of the unutterable
joy of the Lord God and the Lamb forever.

That God Almighty may arise in his great power and bright glory everywhere,
for the bringing down and laying waste of every false birth, and the works of it;
and bringing forth the birth of the morning of his sweet day, through this and +++[+++other]
nations, to the magnifying, renowning and exalting his blessed name forever,
is the breathing and travail of your tribulated brother

[.postscript]
====

Postscript.--Dear Friends everywhere,
feel that divine Hand and mighty Arm that gathered you out
of the rollings and tossings of the nations and people,
into the sweet, safe habitation of Israel,
where you may dwell alone out of the defilements of the nations;
where the hiding place will be known, until the word of the Lord be fulfilled,
and his indignation pass over, to accomplish his own determination in the earth.

====

[.signed-section-signature]
C+++.+++ M.

[.signed-section-context-close]
1680

[.letter-heading]
An Epistle to Friends, chiefly at Bristol.

[.salutation]
Dear Friends,

Who are called of God, by the heavenly voice of his Spirit, out of the world,
its evil ways, evil works, vain worships, and corrupt nature,
to walk in the way of the Lord, and take up the daily cross,
which crucifies you to the world, and the world to you, and brings you to the divine,
sweet nature of God, in which is life, virtue and peace: dear Friends,
travail on in the faith of God`'s elect; be not discouraged at the mountains and hills,
the sea nor the Egyptians; but look to the fiery pillar of God,
the preservation of his called and chosen:
stand still in the light of the glorious gospel,
and see the salvation which the mighty God will bring this day,
unto all that endure in well-doing; not looking out nor wavering in your minds;
for to all that so do, darkness, weakness and offences come in,
and they start aside like a broken bow, fall short through unbelief,
die in the wilderness, and obtain not the promise; but all that keep in the loveliness,
amiableness and divine brightness of the truth, they look over all here below,
of the fading, uncertain, corrupting treasures and pleasures

of the world, which perish in the using.
Therefore gird up in the power of the Lord; arise, shake yourselves from the dust,
the serpents food, and go on in the name of the Lord:
run in the heavenly chariot of life,
the heavenly race and do not look upon the present mess of pottage,
the enjoyments of this life,
and lose both birth-right and blessings from the immortal Fountain of eternal delight.
Ah dear Friends! consider how good the Lord hath been to us;
how he hath made bare his holy arm these many years;
how he hath risen early in excellent power, and sent forth his labourers,
who have neither spared their lives nor substance in their travails,
to bring to you the message of eternal life.
Ah, the plowing, digging, dressing, pruning and watering,
that there hath been for many years!
The fitting and preparing, nursing and feeding, strengthening, encouraging,
that you might come into that frame of spirit,
able to endure the day of proving and trying the
many professions and professors of God and Christ!
How hath the power of the Lord God Almighty wrought to settle you, in every place,
that profess the light of his holy morning, on the Rock;
that you may stand in the tempestuous day,
and seasons of proving foundations and buildings,
which were declared and sounded in your years,
in the power and demonstration of the Spirit!
Blessed are all they that are not offended in him,
nor with anything that he worketh or permitteth to come to try and prove,
to winnow and to sift;
he hath a care of you that have a care to walk sincerely before him,
and live to him in the spirit of the gospel;
the Angel of his presence is with you everywhere, in all your sufferings, imprisonments,
strippings, and impoverishings: he remembers you in all straits,
and is near to you when fainting would overtake.

Ah poor oppressed Zion!
Thy God beholds all, and looks in the morning-watches upon thy oppressors;
therefore let us live in His nature who brings peace on earth and goodwill to men.
Let us meet the furious, angry man in His lamb-like nature,
whose meekness shall out-live all malice; resolving, if we live, to live with and in Him,
and if we die under our sufferings, to die in Him.
The God of glory is with us, his fountain is unsealed, his river Shiloh flows;
the windows of heaven are opened, his showers descend;
visits from the throne of his eternal glory are experienced,
which comfort our souls in the midst of many tribulations,
and bring forth an offering of thanksgiving and sacrifices of high
praises to Him that rides upon the wings of the wind,
and spans the heavens as with a span, binds the sea as with swaddling bands,
and commands the proud waves: this is our God, we will trust him.
Finally, dear Friends, live in that love, everywhere, that gives dominion over enmity,
and over every thought, word and action that rises from that root:
grow to God in the root of life; so shall you be preserved alive, fresh, green,
and in sweetness of spirit before the Lord.

God Almighty visit you all everywhere, in the glorious descendings of his immortal power,
and shine amongst you all in his Divine brightness;
in whose love I am your friend and brother,
in the tribulation and patience of Christ our Lord.

[.signed-section-signature]
C+++.+++ M.

[.signed-section-context-close]
The Ninth Month, 1683.
