== Chapter XII.

A Tender Visitation in the love of God, unto all people everywhere;
particularly unto the inhabitants of Wiltshire, Gloucestershire, and Bristol,
and to my neighbours in and about Tetherton, Calloways,
and the adjacent towns and villages.

"`And unto this people thou shalt say; thus saith the Lord,
behold I set before you the way of life, and the way of death.`" Jer. 21:8.

For the commandment is a lamp, and law is light,
and reproofs of instruction are the way of life. Prov. 6:23.

"`Take fast hold of instruction, let her not go: keep her; for she is thy life. Prov. 4:13.

"`For we must all appear before the judgment seat of Christ;
that every one may receive the things done in his body, according to that he hath done,
whether it be good or bad.
Knowing therefore the terrors of the Lord, we persuade men.`" 2 Cor. 5:10-11.

"`Tribulation and anguish upon every soul of man that doeth evil, of the Jew first,
and also of the Gentile; but glory, honour, and peace to every man that worketh good,
to the Jew first, and also to the Gentile:
for there is no respect of persons with God.`" Rom. 2:10-9.

Friends, Neighbours, and Countrymen,

Amongst whom I have had my conversation in times past,
in the fear of the Lord God of heaven and earth; and now being a sufferer in this prison,
for Jesus Christs sake, I am constrained in his tender love, to visit you by these lines,
+++[+++in order to]
to stir you up to a serious and tender examination and consideration,
what way you are walking in; seeing there are but two ways, as Christ Jesus saith, Matt. 7:13-14.
Enter ye in at the strait gate: for wide is the gate,
and broad is the way that leadeth to destruction, and many there be that go in thereat;
because strait is the gate, and narrow is the way which leadeth unto life,
and few there be that find it.
Now commune with your own hearts, and be truly still in your minds,
and say unto your own souls, what way are we walking in?
For Christ Jesus here took no notice of the many ways and
professions of religion among Jews and Gentiles,
but plainly concluded all people walking in one of these ways, namely,
by the wide gate in the broad way, or through the strait gate in the narrow way.
It is true, there are now many ways and professions of religion in this age of the world;
but now, as then, they are all concluded under these two, the way of life,
and the way of sin and death.
And as these two ways are contrary one to another, so are the fruits different,
that are brought forth by men and women walking in these ways.
All that are walking in the broad way, are bringing forth the fruits of the broad way,
which are evil thoughts, murders, adulteries, fornications, thefts, false witness,
blasphemies, Matt. 15:19; which the apostle also, summing up together, saith,
are these, adultery, fornication, uncleanness, lasciviousness, idolatry, witchcraft,
hatred, variance, emulations, wrath, strife, seditions, heresies, envyings, murders,
drunkenness, revellings, and like;
and saith that they which do such things shall not inherit the kingdom of God. Gal. 5:19-21.
Now these are the fruits of the broad way,
and of those who walk therein: and this way is called broad,
because here men may walk in their sins and iniquities,
in the pleasure and vanities of their minds; and the gate is wide,
to receive all that spend their precious time, the morning and evening of their day,
out of the fear, awe and dread of the holy God.
The multitude walk in this way; for the enemy of mankind, the devil,
cares not what men may profess in words, of God, of Christ, the kingdom of heaven,
religion and worship, while they continue walking in the broad way,
which leads to his kingdom of darkness.

The great God, by his servants the prophets and apostles,
testified against the worships and performances +++[+++of some formerly,]
and that of several things which were once commanded.
And why?
Ye may see it was +++[+++because]
they had forsaken the right way of the Lord,
and were performing their worship in the same nature,
spirit and way they were sinning in against God;
their hearts were corrupt and consciences defiled.
And he complains by Isaiah, chap.
lxv. 2. I have spent out my hands all the day unto a rebellious people,
which walketh in a way that was not good, after their own thoughts.
This way that was not good, was the broad way, in which they were,
as now many are walking in, notwithstanding all their outside profession of religion.
And as saith the Lord, by his prophet Isaiah, chap. i. 11-17.
To what purpose is the multitude of your sacrifices unto me?
saith the Lord; I am full of the burnt-offerings of rams, and the fat of fed beasts;
and I delight not in the blood of bullocks, or of lambs, or of he-goats.
When ye come to appear before me, who hath required this at your hand, to tread my courts?
Bring no more vain oblations; incense is an abomination unto me;
the new moons and sabbaths, the calling of assemblies, I cannot away with;
it is iniquity, even the solemn meeting.
Your new moons and your appointed feasts my soul hateth: they are a trouble unto me;
I am weary to bear them.
And when ye spread forth your hands, I will hide mine eyes from you: yea,
when ye make many prayers, I will not hear: your hands are full of blood.
Wash you, make you clean; put away the evil of your doings from before mine eyes;
cease to do evil; learn to do well; seek judgment, relieve the oppressed,
judge the fatherless, plead for the widow.

So you may see, that no performance of worship or service,
were acceptable in the sight of God,
but those that were performed by men and women +++[+++who were]
walking in the way of the Lord, denying themselves,
and cleaving to the good Spirit of God, which the prophet said,
God gave to instruct and guide +++[+++his people Israel,]
but they rebelled against it.
This is the broad way, Adam and Eve, through degeneration, went into,
when they disobeyed God, and transgressed his righteous law and commandment:
this is the broad way that Cain walked in, when he slew his innocent brother Abel:
this is the way that the old world walked in, when they had, through disobedience,
turned aside, so as that the Lord said, my Spirit shall not always strive with man;
and it repented the Lord that he had made man on the earth,
and it grieved him at his heart.
This is the broad way in which Israel walked when they had forsaken the Lord,
the fountain of their living mercies, and provoked him to anger, both in the wilderness,
and through several generations; as you may read in the prophets,
whom the Lord sent to testify against them.
This is the broad way the scribes and Pharisees were walking in,
notwithstanding all their great professions of religion,
who killed the Lord of life and glory, Christ Jesus.
This broad way is that in which the apostatizing Christians walked,
whom Jude pronounced woe against, because they walked in the way of Cain.
It was going out of the narrow way of obedience,
and walking in the broad way of disobedience, that brought the judgments,
plagues and calamities, miseries and depopulation of nations and kingdoms,
from Adams day to this day.
It was going out of the narrow way of obedience into the broad way of disobedience,
that brought misery on Adam, the curse on Cain, destruction by a flood on the old world,
judgments on the children of Israel in the wilderness,
and sore plagues and calamities through several generations,
as you may read even all along in the prophets;
and then what befel Jerusalem and that people, and +++[+++the disobedient]
since, through ages and generations to this day.

Now having said something of the broad way and wide gate, and of the walkers therein,
I am to say something of the narrow way and strait gate, which Christ Jesus saith,
few find.
This is the way called in Scripture, the way of holiness, and is called the narrow way,
because no double-minded man can walk therein.
For all mankind, that come to walk in this way, must leave their iniquities behind:
for there is no coming out of the broad, into the narrow +++[+++way],
but by putting off (as the apostle saith,) the old man with his deeds;
and this is effected by adhering, joining to,
and obeying the grace that came by Jesus Christ, which the apostle saith,
bringeth salvation, teaching to deny ungodliness and worldly lusts; and not only so,
but leads into a living godly, righteously and soberly, in this present world.
This makes manifest the broad way, gives a sense of the destruction it leads to,
and leads out of it into the narrow way.
And albeit this way is narrow, and the gate strait,
to mankind in the fall and alienation from God, walking in the broad way,
laden with sins; yet as men and women come out of the broad way,
and from delighting in unrighteousness, and come to delight in following the Lamb of God,
Christ Jesus, by his Spirit,
who leads the obedient on in the blessed work of regeneration,
they will see that the way of the Lord is a pleasant way,
and the just mans path a shining light, that shineth more and more unto the perfect day;
and so shall drink of the brook of comfort and consolation by the way,
and say with Solomon, in the way of righteousness is life,
and in the pathway thereof there is no death.
(Mark,) life to the soul is death to sin:
here the ransomed by the precious blood of Christ Jesus,
return to Zion with everlasting joy upon their heads.

But now, all that come to walk in the narrow way, and enter in at the strait gate,
must take up the cross of Christ Jesus daily, and deny themselves;
and in the strength received by the heavenly grace of God,
resist and withstand all the temptations of the devil,
who tempts most to that sin and iniquity which he knows man is most prone to.
But when he comes to tempt, and thy mind is exercised in the light of Christ Jesus,
thou seest his temptations;
and thy souls desires and breathing supplications ascend to the Lord God of strength,
for the lifting up of his spiritual standard in thy soul,
against the temptations and power of the enemy, in every evil thought and inclination,
in which the enemy worketh first.
And therefore in Matt. 15:18, thou mayst read, Christ Jesus put evil thoughts first,
before murders, adulteries, etc.:
for there is a time of sins conceiving in the inward parts,
before bringing forth and finishing; which the Iapostle observing, saith,
when it is finished it bringeth forth death; for the wages of sin is death;
but the gift of God is eternal life through Jesus Christ our Lord.

Now the holy light and saving grace of God, gives the sight,
and makes a discovery of sin in its first arising,
even when the power of the enemy worketh to tempt and allure man, and draw him aside:
while man in the spirit of his mind is not joined to the temptation,
it is not charged as sin; but when man gives up and closes with the temptation,
so as to obey it, then is sin finished, and bringeth forth death.
For his servants ye are, saith the apostle, to whom ye obey; whether of sin unto death,
or of obedience unto righteousness.

Now read here a little, neighbours and countrymen,
how far reacheth your experience in this narrow way,
where men and women with their sins cannot walk.
For this is the holy way and divine path, which man finds on his coming out of sin,
and departing from all iniquity.
But some will be ready to say, if we should hearken to this counsel,
and obey the grace of God thou art directing to, (which brings salvation,
which the apostle says, teacheth to deny ungodliness and worldly lusts; and not only so,
but it brings to live soberly, godly and righteously in this present world;
and so teacheth to forsake the devil and all his works,
the pomps and vanities of this evil world, and all the sinful lusts of the flesh,
which many have promised in their baptism;) and so have our whole conversation changed,
and become other men, not walking in the way most of our country,
town or village walk in,
we fear we shall become a by-word and scorn to our neighbours and acquaintance; nay,
we doubt our kindred and near relations would forsake us,
and we should become as strangers unto them, and lose their respect;
and it may be lose our employ and trade,
and endanger a disappointment on ourselves of the expectation we had from some relations:
and should be go to markets and fairs, and use but few and savoury words in our dealing,
as the fear of the Lord teacheth; and refuse to drink to excess,
or beyond what nature requires for its nourishment and refreshment,
and not be vainly merry, as in times past we were, we should be a derision and a by-word,
and scorned by such as have been our companions in those things in times past:
and this might be very hard to bear, not only to us, but also to some nearest relations.

To which I answer; if any should meet with such exercises as these,
for turning from sin and evil, and ceasing to walk in the broad way, which many walk in,
as aforesaid, there is no cause to be discouraged; for the scripture saith,
he that departeth from evil maketh himself a prey;
and the servants of the Lord were the song of the drunkards; and the apostle saith,
wherein they think it strange that ye run not with them to the same excess of riot,
speaking evil of you:
who shall give account to Him that is ready to judge the quick and the dead.
So look over all the reproaches you meet with for righteousness sake:
for ye may remember how Christ Jesus the Lord was reproached,
for following whom ye may be reproached.
But after ye are exercised in the narrow way, taking up the cross of Christ Jesus,
despising the shame, you will feel that soul-satisfaction,
inward peace and divine consolation, that heavenly content,
which will out-balance all exercises and trials of this nature;
so that you will often have cause to magnify the Lord, and to say, he is good,
and abounding in his love and tender mercies over the workmanship of his own hand;
who hath visited our souls when we were posting on in the broad way of destruction,
and had only a profession, by the hearing of the ear, of God, Christ and his kingdom,
the scriptures, religion, and once a week confessing, we were miserable sinners,
erring and straying from the right way of the Lord;
and knew not the true repentance which is always
accompanied with a true forsaking of sin and iniquity.
But the God of the Hebrews hath met with us,
who beheld us as bond-slaves in spiritual Egypt;
and he hath visited our souls with his heavenly morning of light,
by which we have seen our sinful ways and life in iniquity; also our vain worship,
which was so far from being performed in the Spirit,
that we were some of that number in our parish who despised the Spirit,
and mocked them that worshipped in it;
this is the ancient worship set up by Christ above sixteen hundred years ago,
when Jesus said unto the woman of Samaria, the hour cometh and now is,
when the true worshippers shall worship the Father in Spirit and in truth;
for the Father seeketh such to worship him.
God is a Spirit; and they that worship him, must worship him in spirit and in truth.
So we see that now, all worship not performed in the spirit and in truth,
hath no acceptance with the holy,
righteous and equal God of tender mercies and compassions;
through whose favour we contemn and despise all reproaches for his names sake;
rather chosing suffer reproaches with a people truly fearing God and eschewing evil,
than live in the pleasures of sin, which are but for a season, and then end in torments,
pains, miseries and astonishment, beyond all expression of words.

Now where any poor travailing souls are thus exercised in coming
out of the broad way into the narrow way of life eternal,
and are inwardly waiting on the Lord, receiving the instruction of his heavenly gift,
such will see and understand more and more of the heavenly, strait gate and narrow way,
and it will be daily more and more easy and delightful to the obedient:
so that such will experience what Christ Jesus saith,
take my yoke upon you and learn of me; for I am meek and lowly in heart;
and ye shall find rest unto your souls.
For my yoke is easy, and my burden is light.
The yoke of Christ is indeed easy,
when thy mind is subjected unto the saving grace of God, which teacheth,
as I mentioned before, what to deny and how to walk,
so as thou mayst have an answer of peace,
in pleasing God the Fountain of all our mercies.
And then when any mock or scoff,
thou wilt remember thou wast walking once in Ishmaels way of scoffing, as they are;
and thou wilt pity them; and thy soul will be concerned for thy neighbours,
relations and acquaintances; crying to the Lord,
that as he has visited thy soul through his grace that brings salvation,
and shewed thee kindness, so he would do for thy neighbours.
For this +++[+++grace]
leads into the christian nature and spirit, not to render evil for evil, anger for anger,
scoffing and reproaching for the same; but good for evil, love for hatred;
praying for +++[+++persecutors]
as Christ Jesus did, Father, forgive them, for they know not what they do.

So following this meek Lamb of God,
the Savior of mankind thou wilt have an increased sight of the
difference between a Christian in name and a Christian in nature.
A Christian in name, is one that has only an outside profession of Christianity, God,
Christ, the Scriptures and religion;
drawing near to the Lord with the lips and honouring him with the mouth,
whilst the heart is going after sin and vanity, and is far from righteousness.
A Christian in name and profession only, is a talker of the narrow way and strait gate,
but is a walker in the broad way; having a name to live,
but is dead in sins and trespasses.
But a true Christian in the divine nature is circumcised inwardly, and is a Jew inward;
one that is born again, without which Christ saith,
there cannot be an entering into the kingdom of heaven; so is really changed in nature,
and cut off from the wild olive, and planted into the true Vine, the divine nature,
from whence fruits of Christianity are brought forth.
Here the circumcision is not that of the flesh, but that of the Spirit:
a Christian in the divine nature, is one that hath followed the Lamb in the regeneration,
hath put off the evil, corrupt nature, and appears amongst men in simplicity,
bringing forth the fruits of the Spirit, love, joy, peace, long-suffering, gentleness,
goodness, faith, meekness, temperance, mercy and goodwill to mankind.
And +++[+++as thou who hast begun to walk]
in the way of the Lord, perseverest therein,
thy experience will increase in the knowledge of
the footsteps of the flock of Christ Jesus;
seeing first how thou wast turned from darkness unto
the marvellous light of Gods holy day,
with which thy heart was searched,
and sin became exceedingly sinful and inexpressibly burdensome.
Then thy soul cried out in distress unto the Lord God for deliverance;
who hath heard the cry of the poor in spirit, and the sighing of the needy;
and hath made bare his delivering arm,
and in due time gave remission of sin and a blotting out of transgression.
And then times of refreshment came from the presence
of the Lord and from the glory of his divine power,
that hath wrought effectually for the cutting off from the wild olive,
brought thee out of the broad way, and planted thee into the heavenly Vine of life,
that is the way, and made thee a branch of the heavenly Vine,
daily receiving sap and divine virtue from this heavenly, holy Root:
and then lets thee see thy daily, spiritual, incumbent duty, which is,
to abide in the Vine, Christ Jesus.
For as the natural branch cannot bring forth fruit, except it abide in the natural vine,
no more can any bring forth fruit acceptable to God,
except they abide in the heavenly Vine, Christ Jesus.

So neighbours and countrymen, thus coming out of the broad way of sin and iniquity,
and walking in the narrow way of righteousness and holiness, following the Lamb of God,
Christ Jesus, in the regeneration, ye are fitted for his glorious kingdom.
And they are indeed blessed that are come to that state; who can in truth say,
for me to live is Christ, and to die is gain:
surely these have put off the sins of the flesh, the old man with his deeds,
and have put on the new man,
which after God is created in righteousness and true holiness.

For our life here is very uncertain and momentary;
so that when we lie down in the evening, we are uncertain of rising in the morning;
and when we rise in the morning, we are uncertain we shall live until the evening.
Our life is like water spilt on the ground, which cannot be gathered up again;
it is like unto a weavers shuttle, quickly displayed and cut off;
and like the trace of a bird through the air.

Well, therefore, since our life is so uncertain and death so certain,
dear countrymen and neighbours, in the tender bowels of Christ Jesus, I beseech you,
for your own poor souls sake, whilst you have time, a very little time,
so to number your days, and remember your latter end,
as to apply your hearts to that heavenly wisdom,
which teacheth and instructeth to walk in the narrow way of self-denial,
which leads to life eternal: that when the messenger of death comes,
the king of terrors to all evil-doers, it may meet with you walking in the way of life:
which will be the comfort,
joy and satisfaction of all men and women who have prized their precious time,
that God Almighty hath given them in the riches of his infinite love,
to obtain the heavenly translation out of the kingdom of darkness,
into the kingdom of his dear Son, Christ Jesus, and are thereby fitted for that hour.
When nothing but death is expected every moment,
thy breath in thy nostrils is withdrawing, and thy dear relations,
friends and acquaintance are about thy deathbed, mourning and lamenting,
thou who art +++[+++thus]
passed from death unto life spiritually,
canst comfort them with telling thy spiritual experience; that thou art assured,
when this earthly tabernacle is dissolved, thou hast a house not made with hands,
eternal in the heavens, an eternal mansion of joy and blessedness;
that having fought the good fight, thou hast overcome sin, death, hell, and the grave,
through Him that hath loved thee, and redeemed thee with his precious blood,
Christ Jesus, the King of eternal glory;
and that the seal of Gods favour is upon thy soul,
and the joy of his salvation on thy spirit.
And +++[+++thou canst say to]
thy neighbours who are ignorant of this precious work;
O neighbours! do not content yourselves with he pleasures
of sin which are but for a season,
(O, a little season indeed!) and lose your own souls,
and be shut out of the paradise of God.
O! but redeem your time; spend no more of it in sin and iniquity,
in vain and foolish discourses; but prize every hour: enter in at the strait gate,
walk in the narrow way, that ye may enter into the kingdom of joy and immortal glory;
where the redeemed enjoy endless blessings of peace, and unspeakable consolations,
and behold the amiable, celestial beauty of Him who sits at the table of divine love,
saying, eat, O friends! of the bread of life, and drink,
and let your souls be satisfied with the fatness of the house of God.
O! here, in this kingdom, is an end of all pains, sorrows, burdens, tears, conflicts,
cruelties of wicked men; an end of inhuman, ungodly imprisonments;
here the redeemed of the Lord are out of the reach of all cruel, hard-hearted men; yea,
here the weary are at rest in an eternal Sabbath,
beholding Him who is a fountain of gardens, a well of living waters and divine streams.
And here the new song is sung before the throne of God, in the springing up of endless,
increasing joy and divine refreshments, in which ariseth blessing and glory,
wisdom and thanksgiving: honour, power and might be unto our God forever and evermore.
Amen.

Friends, neighbours and countrymen, who may have any doubt, which are true prophets,
ministers and teachers of Christ Jesus, and which are false prophets,
ministers and teachers of antichrist,
(since there have been both through many ages of
the world;) unto all such I make this friendly,
reasonable, and Christian proposition, namely, to do like the noble Bereans,
who were desirous of truth, search the Scriptures from Genesis the first,
to Revelations the last, and mark in what way they walked,
and what fruits they brought forth, who were true prophets, ministers or teachers,
both under the law and the prophets; and on the other hand, what way they walked in,
and what fruits they brought forth, who were declared to be the false prophets,
ministers and teachers, by the true prophets, Christ Jesus and his apostles;
so may ye safely conclude, those that walk in the way,
and bring forth the fruits of the true ministers of Christ, to be now true;
and those false now,
that walk in the way and footsteps of the false prophets and ministers of antichrist.
So, search the Scriptures in the spirit of truth, that leads into all truth,
and receive Christs precept, about the strait gate and narrow way, Matt. 7:13-14,
of which I have, in his love, before treated; and in verses 15 and 16, he saith,
beware of false prophets, etc.
Ye shall know them by their fruits, etc.

TRUE MINISTERS

Christ sent them forth to preach the kingdom of God; saying, the harvest truly is great,
but the labourers are few; pray ye therefore the Lord of the harvest,
that he would send forth labourers into his harvest.
Go your ways: behold I send you forth as lambs among wolves.
Carry neither purse, nor scrip, nor shoes: and into whatsoever house ye enter, first say,
Peace be to this house.
And if the Son of Peace be there your peace shall rest upon it: if not,
it shall turn to you again. Luke 10:2-6.

The elders which are among you I exhort to feed the flock of God, which is among you,
taking the oversight thereof, not by constraint, but willingly; not for filthy lucre,
but of a ready mind; neither as being lords over Gods heritage,
but being ensamples to the flock. 1 Pet. 5:1-3.

FALSE MINISTERS.

Thus saith the Lord concerning the prophets that make my people err,
that bite with their teeth, and cry, Peace; and he that putteth not into their mouths,
they even prepare war against him.
The heads thereof judge for reward, and the priests thereof teach for hire,
and the prophets thereof divine for money. Micah 3:11-5.

Woe be to the shepherds of Israel that do feed themselves!
should not the shepherds feed the flocks?
Ye eat the fat, and ye clothe you with the wool, ye kill them that are fed:
but ye feed not the flock, etc., Ezek. 34:2-5.

C+++.+++ M.

Fleet Prison, The 9th Month, 1683.

O! thou holy, most high God of mercy and tender compassion,
look down with an eye of pity on the inhabitants of the earth;
and send forth thy light and truth more and more,
to guide the people out of the broad way of destruction into thy narrow way of life,
which leads to thy holy mountain, where there is no hurting nor destroying.
O! that through the glorious, outstretched arm of thy salvation,
sin may be finished and iniquity brought to an end;
that the righteousness of Christ Jesus, the dear Son of thy love,
may cover the earth as the waters cover the sea.
Ah! for thy names sake, hear the cry of the poor and sighing of the needy;
and stretch forth thy arm and deliver thy oppressed out of their distresses;
that thy creation, O Lord, may be eased,
and thy great name and the noble acts of thy Almighty arm and Divine
power may be renowned gloriously through all lands.
Amen, Amen.
