== Chapter XV.

Concerning the precious Unity of the Spirit in Christ Jesus.

The unity of the Spirit is so precious a virtue,
and glorious a qualification in all the churches of Christ Jesus,
that whilst the people of the Lord did abide therein, in every age,
they were in a thriving, flourishing, sweet and glorious station.
For as long as they truly held the head Christ Jesus, and kept in unity with him,
unity and amity were preserved amongst them in their several stations and services,
as members of one body.

Of this unity, David speaketh preciously and comprehensively, saying,
behold how good and how pleasant it is for brethren to dwell together in unity!
It is like the precious ointment upon the head that ran down upon the beard,
even Aarons beard: that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion:
for there the Lord commanded the blessing, even life forevermore.
This was the state the holy power of the great God gathered a people into,
+++[+++in the apostles days:]
for concerning them, it is left upon record, they continued steadfastly in fellowship,
and were daily with one accord in the temple.

Now dear Friends, we clearly saw, felt and understood,
in the precious morning of our tender visitation,
that the same ancient power of the Lord wrought powerfully,
first to disunite us from the nature which separated us from God,
and then to bring us up into unity and fellowship with himself, in his dear love,
and therein, one with another.

For here ever was, and is the foundation of the true unity, even that of the Spirit;
in which love the body edifies itself,
and is increasing and building up a holy habitation for God, through the Spirit.
So then, all abiding and growing up in the love of God,
and walking with him in the divine nature,
unity increaseth amongst all the members and branches taken out of the wild olive;
and +++[+++they are]
planted and abide in the Vine of life, Christ Jesus, our Head and Lawgiver:
here the church of Christ grew up, into a state of being clothed with the sun,
having the moon under her feet.
Ah! precious, blessed, sweet and glorious station.
But did it always thus continue, even in the apostles days?
Ah! no.
The old serpent, the enemy of mans welfare, wrought powerfully and cunningly,
to draw forth from the root of life, and out of the holy love of,
and spiritual subjection to, this glorious power which had gathered them to a daily,
inward walking with God;
and out of the spiritual exercise of the spiritual cross and holy watch:
and then fruit from another root was brought forth,
as the reader may note in several of the Epistles +++[+++addressed to the primitive believers,]
and in John+++[+++s testimony to the seven churches of Asia.
Then the power of the Lord that had gathered them,
moved to exhort to put away bitterness, wrath, anger and clamour,
evil-speaking and malice.
Ephes.
iv.

And now, dear Friends, with your lamps trimmed and burning, look inward;
search every corner of your hearts,
that clear unto your own understandings every one of your states may appear,
as they are in the sight of the pure, all-seeing God;
that so all the enemy`'s darkenings and veilings and turnings aside,
by what way or means soever, may be clearly, with the light of the Lamb,
seen and discovered.

And, tender Friends, +++[+++remember]
the sweet, lovely, precious state of unity and concord,
that the excellent power of the Lord God Almighty gathered into, and was gathering into,
in the blessed morning of our day; and the spiritual advantages, comforts, joys,
refreshments and divine satisfaction that attended the church of
Christ in this true and spiritual unity with our Lord Jesus Christ,
and one with another: and on the other hand, heed the anxious,
exercising consequences of the enemy`'s prevailing to break unity:
all the true-hearted and sincere-spirited to God, cannot but, on the one hand, admire,
prize and inexpressibly esteem this precious unity; and on the other hand,
greatly dread the turnings aside, and going out of it.
For those who have kept their habitation, and lived to God,
as they have tasted and enjoyed the sweetness,
and beheld the amiableness of this unity and amity,
so they have felt the sorrows and anguish of the effects of the contrary;
which have caused them to go many days and months with mournful souls,
crying to the Almighty God of tender compassion night and day,
under the inexpressible weight thereof.
And the God of love has bowed down his ear to the cry of the poor,
and sighing of the needy: he has arisen in the might of his power,
and the majesty of his glorious presence hath relieved: his holy arm hath been made bare,
through which he hath redeemed his darling from the dog,
and his dear ones from the devourer;
and still continues working to bring into this precious unity, in the holy light of life,
with God in Christ Jesus, and one with another.
And now, dear Friends, everywhere, unto you and to the generation coming after,
I have this warning and tender advice to leave behind me, in the name of my God,
who hath been with me by his power, in my travails,
work and labour in the gospel of life and salvation:
keep the unity of the Spirit in the bond of peace;
and let none give way to a prejudicing spirit, which leads into secret whisperings,
backbitings, and such-like evil and pernicious fruits;
the working of which spirit is like a moth in a garment, dividing, destroying,
spoiling and eating up.
For indeed, as Zion is a city at unity with itself,
under the seamless garment of Christ Jesus, and there all are well and safe, growing,
increasing and flourishing; so when the spirit aforesaid prevails,
to draw out of Zions gates, and from within her walls of salvation,
O! what deplorable work and havock will it make in its growth and progress; working,
as I said before, +++[+++like]
the moth, gradually and secretly first;
but as it prevaileth and increaseth in its growth and strength,
it will appear as a roaring, devouring lion, seeking whom it may devour and swallow up.
Here comes in pride and haughtiness,
a spirit puffed up with the abundance of enjoyment of outward things.
Emulations, heart-risings, evil jealousies, bitter speakings, detractings,
and abundance of evil fruit, arise from this root of bitterness;
which root and fruit are to be brought under,
and sunk down under the eternal judgment of the holy, glorious, sweet power of the Lord.
And therefore Friends, I say unto you, in the name of the Lord God eternal,
let none give strength,
or any encouragement or nourishment to this spirit
in any of its murdering workings in the heart;
but let it be looked upon as a vagabond and fugitive on the earth: and so,
as it is kept out of the camp of God, and from Israels dwellings, by the sweet, living,
bright power of the great God of heaven and earth,
it will perish under Truths judgment set up in every soul; and the nature thereof,
as well as its evil, rending and dividing fruits will be worn out and destroyed forever.
And then, all keeping in the first love, pure fear, living awe, and holy dread,
fearing to offend our God and tender Father,
persevering in an inward keeping the holy watch,
and abiding in subjection and obedience to the spiritual cross, in staidness of mind,
soundness of judgment and clearness in understanding, you +++[+++will]
see, comprehend, and fathom all the enemy`'s devices, temptations and snares:
and the Lord God beholding you in a stedfast habitation
of obedience and spiritual tenderness before him,
his power will descend wonderfully in an increasing manner, his glory will shine,
and his river of life flow; yea the spring of the great deep will be broken up,
and the windows of heaven will be opened, that you may be abundantly filled with joy,
thanksgivings, and songs of deliverance;
and spiritual high praises will ascend to his throne, as sweet incense,
and a sacrifice acceptable to our God.
And here you shall spend the residue of your days in dominion over
the snares of the enemy which attend both prosperity and liberty,
and adversity and persecution;
seeing over all things that have their rise in mortality and time;
feeling mortality swallowed up of life immortal;
and so be gathered to the general assembly, to the church of the first-born,
to the spirits of just men made perfect; yea, to the First and Last,
to God the Judge of all; to whom be immortal high praises and holy renown,
forever and forevermore.

But if the wonderful blessings, tender mercies,
and loving-kindnesses that the Lord Almighty every way extends to us in this age,
be not duly, reverently and obediently taken notice of; and instead thereof,
any shall forsake and be unmindful of the Lords tender mercies,
and embrace lying vanities;
going out of the spiritual diligence into a spiritual idleness,
through which a spiritual slumber overtakes, and the lamp thereby be inwardly neglected,
the spiritual watch and cross slighted, and not duly regarded,
but the earth and earthly things take up the exercise of the mind and affections; then,
I say, instead of enjoying what is above expressed,
tribulation and anguish will seize upon all such;
and the dreadful judgment of the eternal God who lives forever and ever,
will overtake all such unfaithfulness: a dreadful cup ye +++[+++unfaithful ones]
shall drink of, from the hand of God,
and the rebukes of the Lords countenance shall distress you;
and you shall be numbered amongst the people of his indignation,
in his dreadful approaching day of signal pleading with
all flesh that have corrupted their way before him.
Therefore hear, fear and dread the holy name of the Lord: and whilst it is called today,
bow before him, and speedily return unto him, lest your day pass over,
and ye sleep the sleep of eternal death and destruction,
and be separated forever from his refreshing presence, in which is life,
and from the glory of his divine power.

Therefore, all dear Friends everywhere, retire inward; see,
feel and understand the counsel of the Lord which unto you springs; all retire inward,
in great humility before the Lord, that you may grow in the root of life,
and feel his blessed work perfecting your inward man:
that as you have professed the knowledge of a spiritual oracle before the nations,
you may approve yourselves in the sight of God, following its instructions in all things.
Go not without it; lean upon the Lord, and cry to him to guide you with his eye,
and lead you by his arm in the way everlasting.
And this is his promise, whilst you keep with him, he will be with you,
and will never leave nor forsake you if you do not leave nor forsake him;
his presence and glorious arm of salvation shall surround you, to the renown of his name,
and consolation of his people.
Amen, Amen.

Charles Marshall.
1697.
