== Chapter XVII.

[.letter-heading]
An Epistle to Friends, exhorting them to wait on the Lord.

[.salutation]
Friends,

In the fear and dread of the Almighty it is upon me to say unto you,
wait upon the Lord in the gift of his own Spirit, made manifest in us,
for the revelation of his eternal, unlimited power;
that by the powerful operation thereof, all may be cut off, rooted out, and burned up,
that hath hindered or broken our unity with the Lord, or one with another;
that so by its working we may all come into the unity of the one eternal Spirit,
where the everlasting, unchangeable love of God will be shed abroad in our hearts;
in which being all united as one body, and the government being on His shoulders,
who was a man of sorrow and acquainted with grief, we shall with one consent,
put our hearts and hands to the work of reformation.

And Friends, I cannot but say in the name and power of the Lord God,
this ought to be the first thing desirable amongst us:
and it is upon me to remind you of the tender visitation
that reached unto us some months since,
which was in order to what I have afore spoken; _for as we all come,
through the operation of this immortal power of God,
into the unity of the one eternal Spirit of life,
all those outward exercises +++[+++which have been]
run into, as the customs, fashions, ways and words of the world that are evil,
will be cast off: yea,
there will be a great tenderness in the very use of needful things,
that the heart may be kept out of them._
And Friends, it is on me to say unto you,
let none of us quench the Spirit nor despise prophecy in ourselves,
or in any of our brethren or sisters; for if we do, we hurt our own souls,
and bring a famine thereon: but where the Lord God requires any,
in the motion of his eternal power, to bear a testimony for his name,
be faithful unto it: and on the other hand,
let us all be careful not to spend our own bread,
for that will burden others instead of refreshing them;
for the heart may be refreshed and the power felt,
and may be lost again through going forth.
But this is certain,
the motion of God`'s power liveth and abideth in the stillness of all flesh; and +++[+++the more]
the mind is retired into the true, inward silence,
the motion of life doth the more shew itself,
and the heart and mind come to be satisfied of God`'s requirings;
and these in due time and season being brought forth,
are a savour of life unto the living; but it is not so with the false birth,
nor with the abortive.

And dearly beloved Friends, it is furthermore on my spirit to say unto you,
it was the immortal power of the Lord God that first touched
and pricked us at the heart in the day of our first visitation;
which immortal power of God brought down many lofty cedars,
and cut down many sturdy oaks in that day.
It brought many of us into deep humility of spirit, and into great tenderness of heart;
it made the earthly tabernacles to tremble and shake, and wrought through the members,
where the law of sin and death had ruled:
in that day it ploughed up the fallow ground of our hearts,
and discovered the root of iniquity;
and the axe was laid to the root of the corrupt tree.
And that immortal power and arm of strength must finish that good and
holy work that it began in us in the day of our first tender visitation.
Therefore Friends wait diligently,
being inwardly turned to feel the arising and effectual operation of this living,
eternal power and arm of the Lord God;
that the old heaven and old earth may both pass away,
and that all may know the new heavens and the new earth wherein dwells righteousness.
As this immortal power of the Lord God ariseth, it will break every bond of iniquity,
and snap in pieces every chain of darkness; it will rend the rocks,
and break in pieces the mountains; it will burn up the stubble and drive away the chaff:
and here we shall know the fan in the hand of his
power that thoroughly purgeth his floor,
and that truly makes the separation, gathering the wheat,
and burning up the catch with unquenchable fire; which is the power of the Lord.
And Friends, I am pressed in spirit to entreat all, in the pure bowels of tender love,
to make a true and a thorough search with the light of the Lord,
that nothing of the accursed thing may be in any of the tents of Israel,
which should cause them to fall before their enemies:
and therefore this runs through me in much fear and trembling; sanctify yourselves,
and be ye holy;
that in the day at hand of the breaking forth of
the glory of the Lord as a devouring fire,
all of us being sanctified and thoroughly cleansed, we may be able to abide and to stand.
For a day of calamity, even a day of distress, is at hand;
and the Lord in his everlasting lovingkindness, which is unspeakable,
is laying his hand on many, to draw them out of Sodom and Gomorrah spiritually.
Oh! that all hearts might be broken, and all spirits tendered,
and all dissolved down into a tender, broken frame of spirit before the Lord;
that all may tremble at the word of his holiness, and dread and fear his holy,
glorious name,
who is coming out of his place to visit the earth in his everlasting dread:
and all the earth shall be filled with his glory,
because of the work which he will work amongst his people,
and also among the heathen that know him not.
And Friends, as all are brought down here into this melted, dissolved frame of spirit,
supplication will ascend from prevailing Jacob to the Lord God;
and he will bow down his ear to the cry of his distressed,
and deliver them with a great deliverance, and save them with a mighty salvation:
and his Jerusalem shall be made the praise of the whole earth.
The Lord God of heaven and earth bring all his people
into this city and into this frame of spirit;
so shall Friends be as the garden of the Lord, which shall give a pleasant smell;
and you may be raised up to stand in the gap in the
day of the fierce anger of the Lord God,
that comes on this nation, the land of our nativity.

And Friends that are masters and mistresses of families,
and have the tuition of children and servants,
this to you is the counsel of the Lord God of heaven and earth:
wait daily on the Lord for the arisings of his holy power,
that therein you may keep down all evil in your families.
In the everlasting power you will have ability to reach
to the consciences of your children and servants,
that all the families of the people of the Lord may be sweet and clean before him.
For the Lord will pass through his whole camp; and where sin,
iniquity and uncleanness are cleaved to and lived in,
there will he break forth as a consuming fire: and Friends,
where any have been visited with the day of God springing from on high,
have professed the truth, and made confession and profession of the pure way of the Lord,
and have erred from the pure path,
through the receiving and bowing down to the Spirit of this world,
by which they order not their conversations aright;
but through careless walking in their dealing and in their converse with the world,
cause the truth to be evil spoken of, and the name of the Lord to be blasphemed;
I declare in the counsel, fear and dread of the Almighty Lord God of heaven and earth,
if such do not speedily return to that pure principle,
unto which they were directed in the day of their first tender visitation,
in that to wait to know God`'s immortal power to heal their backslidings,
and his free love to come over all again,
in which a testimony may arise in them against all that
ever they have acted in their dealings or otherwise,
that hath caused the worthy, dear name of the Lord to be evil spoken of:
I say that if such do not thus return, the day hastens, +++[+++in which]
God will make them an astonishment to themselves and to all round about them;
and will honour his great name over them in their destruction.
_Dear Friends, it was the arm of the Lord that gathered us to be a people; and it was,
and is in obedience to him that we met and do meet together;
our meetings did not rise by the will of men,
neither will they go down by the will of men;_
for God Almighty will fill the assemblies of his people, through this nation,
with his dread; and no power, strength, nor arm shall break them,
so as the people of the Lord shall not meet together to wait upon him and to worship him;
but all that riseth up against them shall fall and come to nothing:
and therefore doth the Lord require his people to meet together, as boldly,
as diligently, as faithfully as ever, without fear of men;
and whatever makes careless in coming to meetings or draws from meetings,
is the antichristian spirit, in what vessel soever it shall appear.
But to all that meet faithfully, and gather into the name of the Lord in their meetings,
and wait diligently on him, the Lord God, in his everlasting power, will appear,
to their inexpressible comfort and to the honour of his great name,
which shall over all be renowned in this nation.

And so I have cleared my conscience in the sight of my God;
and if any shall rebel and not walk in his counsel, nor be faithful unto him,
I am clear of their blood;
and O! that every one of us may know the things that concern our peace.
I am your friend and brother in the tender bowels of love,

[.signed-section-signature]
Charles Marshall.
