== Chapter XVIII.

[.letter-heading]
An Epistle to the Men`'s and Women`'s Meetings, in and about the City of London.

[.salutation]
Dear Friends, Brethren and Sisters,

Partakers of the heavenly calling of God, through Jesus Christ,
in the riches of his love, in this his gospel-day, wherein he hath made bare his holy,
outstretched arm of eternal salvation, for the gathering, and saving,
and thereby bringing many sons and daughters to glory:

Grace, mercy, and peace, with all the fruits of the eternal Spirit,
from the fountains of mercies and blessings, be multiplied in and amongst you,
and all the flock and family of Christ Jesus everywhere.
Dear Friends, being led in spirit,
into a deep sense the tender mercies of the Lord extended unto you,
in inexpressible visits in his power; the living waterings, holy dewings,
daily instructings, and wonderful preservations that you have enjoyed,
and what God hath wrought and would work amongst you, and to what you are called; I say,
in the inexpressible sense and sight hereof,
my soul is deeply affected and bowed before the Lord our God;
and my spirit is stirred in the love of Christ Jesus,
to exhort all to stand fast in that liberty unto which you are called,
which is the liberty of the sons and daughters of God Almighty;
a glorious liberty from the embondaging power of hell and death,
under which we were captives.
Now, unto all you that are witnesses of this liberty, I say, in my Fathers love,
good will and counsel,
watch diligently in living subjection to the holy power of an endless life;
that in nothing ye may be entangled again with any part of the yoke of bondage,
under which we could not serve, please, nor worship God aright.

The Lord God hath called and gathered you from off
the barren mountains and desolate hills,
to his holy mountain; so that you may walk where there is no hurting nor destroying,
no rending nor dividing.
Here you are preserved, and see every barren mountain and hill, where the hurting,
dividing rents and schisms are; against which the judgment of truth is set,
and unto which they go, that go from the holy mountain of God.

Dear Friends, brethren and sisters,
who appertain unto the flock and fold of our blessed Shepherd, walk ye, as he walked,
in the harmless life of innocency.
O! let none cast off his heavenly yoke, nor cast away his spiritual burden,
nor get above his crucifying cross, into any fleshly liberty, or self-exaltation;
but let the dread of Israel`'s God be on your spirits,
eying your excellent and high calling; +++[+++for ye are called,]
not only out of the world, its ways, impure religions and fallen worships,
into a testimony against such; but further into the spiritual worship,
therein to be exercised night and day in the temple of the Lord;
and also into an inexpressible care and concern for others.
O! let the deep sense of this heavenly call and requiring of our Heavenly Father,
weigh upon all your spirits, according to the inexpressible weightiness of it.
And I am to put you in mind, that you are, above many of the called of God,
set as a city upon a hill, in the view not only of your friends but enemies.
Therefore as you tender the honour of God, your own souls welfare, and Zions prosperity,
walk in the self-denying path:
and you whom God hath any way honoured with a service in his church,
and amongst his people, this counsel is given me to send unto you,
in the name of Almighty God; seek the honour that comes from God only,
and walk before his people, his tender lambs, and babes, and little ones,
in the self-abasement.
O! humble self to the death, even to the death of the cross of Christ Jesus;
for if any get out from this path, they will hurt instead of heal,
starve instead of feed, make naked instead of clothe.
O! the blessed words and practice of Christ Jesus, who knew what there was,
even in his disciples, that would seek who should be greatest.
He taught them, by setting a child amongst them: he girded himself with a towel,
he washed their feet; shewing thereby, not only that if he washed them not,
they could not be clean; but also shewed them,
how they should walk and do for one another.
He also said to Peter, lovest thou me more than these?
feed my lambs; and this, in universal care and inexpressible bowels for his little ones,
he repeated again and again, that he might perform his duty well.
Friends, let us all walk as we have Him for an example and a Captain:
and this opens in my soul, that the greater the growth is in the seed immortal,
the more self will be abased and denied,
and the more will the interest and weighty concern of truth be in every ones eye;
seeing the glory of God, the good of souls,
and the welfare of his people are concerned in the care and diligence,
and in the performing that service in the church of Christ,
which every one is called unto.

And Friends, be very diligent in +++[+++attending]
all those your meetings, and all other meetings; and when met,
be as diligent to wait upon the Lord with tender breathings,
in the girding up with the girdle of truth, the loins of your minds:
wait in every occasion, for the fresh descendings,
fittings and capacitatings of heavenly wisdom, which is pure and peaceable.
And set not about the affairs of truth without some feeling and helping of it;
for this I have seen, no parts nor acquirements whatever, without this guiding,
counselling, instructing wisdom of the Lord, will carry on truly,
or affect rightly the affairs of Truth, although it be in outward things.
And my heavenly Father whom I have loved and feared from very tender years,
hath shewn me that in the sensual wisdom stands the strife,
and out of that ground arise the exaltedness, haste, rashness, schisms, rents, sects,
etc.

Therefore in the meekness and gentleness of Jesus, treat one another;
and if any feel their spirits warmed, and not with the heavenly power of God`'s love,
(that guides to speak tenderly and respectfully one unto another,) let such an one,
saith the Spirit of Truth, sit silent until that is brought under,
and the nature of the Lambs wisdom and meekness comes up,
to leaven and rule the heart and guide the tongue.

And you that are rich and full in the outward,
you are charged of the Lord not to trust nor have confidence in uncertain riches,
nor to be puffed up out of your places in the body by reason thereof;
but rather be the more humble, in the sense of the mercy and bounty of the Lord;
and supplicate the Giver to give you wisdom to be stewards well pleasing in his sight;
so shall a blessing be in your basket and store.

And Friends, live in self-denial and self-abasement in meats, drinks and apparel;
let nothing of fulness lead you beyond self-denial,
and so to forget the afflictions of Joseph, many distressed, straitened, imprisoned,
impoverished members of the same body.

And +++[+++let]
those that are ancient and much in Truths service, in all humility,
labour and delight to bring up the young therein; and when any son or daughter,
in simplicity, and as enjoyers of the new wine in some little measure, speak as children,
help them, strengthen them, taking them by the hand, and bowing to their state,
in honouring the lowest members; so shall not the tender bubblings up of life be stifled,
nor the tender grapes bruised; but all preserved, and the Lord thereby honoured.
For I testify, in the power of the Most High, as it is given me,
he will abase all that exalt themselves, and they shall be brought low;
and all that seek themselves, and their own honour, the Lord will discover.

And dear Friends, brethren and sisters, watch over the flock of God,
over which he hath made you overseers, that the rending,
dividing spirit of opposition may not enter secretly.
Visit, exhort, seek, warn, reprove, and set judgment in the Lords power and counsel,
over all that which would hurt the tender flock of God;
the way and works of which destroying the spirit the Lord God will blast,
and the bringings forth and product of it consume,
with the brightness of his arising and coming,
and blow away with the breath of his mouth.

Finally, Friends, brethren and sisters, be of one mind, and dwell low;
live with and in life itself; deny yourselves;
be in the daily bearing of the cross of Christ Jesus, that crucifies you to the world,
and the world to yo; live above the worlds heights and depths, joys and sorrows:
for a sore and dreadful day will the Almighty God
bring upon the world that lies in wickedness;
and a bitter cup must many of the inhabitants of this nation and that city drink off.

But if ye walk with God, and grow to him, you shall know the hiding-place of his love,
wherein safety is, and bread and water shall be sure and certain to your souls.
And the Lord Almighty cause his power in great glory and brightness,
more and more to arise amongst you; and send plentiful showers of divine rain,
and cause his sweet evangelical dews to descend morning after morning, on your souls,
in your meetings and families; through which ye may be kept green and fresh,
like the growing innocent lilies, and lovely as the rose of Sharon.
The Lord God of our life warm all your hearts and souls, with his beams of glory,
and cause you, in the inward man, to partake of the blessings of the second covenant.

So, having done the will of my God, and eased my spirit before him,
I commit you to the word of God`'s grace,
that is able to build you up in his most holy faith,
and give you an eternal inheritance with his saints in light:
+++[+++that this may be your portion]
is the earnest breathing of your travailing brother, in the labour,
tribulation and faith of the gospel,

[.signed-section-signature]
Charles Marshall.

[.postscript]
====

Glory and honour, might, majesty, with holy renown, and immortal dominion, be ascribed,
with living high praises, to the Lord God, and the Lamb, who reigns in Zion,
and before his brokenhearted, bowed-spirited ones, gloriously.

====
