== Chapter XIX.

[.blurb]
=== An Epistle in the Love of God, to Friends everywhere, +++[+++exhorting them to perseverance.]

[.salutation]
Dear Friends,

Who have been visited with the morning of the heavenly day of God`'s everlasting love,
and have seen the clear inshining of the celestial light thereof,
through which the ancient,
precious way of eternal life is cast up in the view of your understanding;
in the sense of which mercy, and inexpressible kindness of the Lord,
which unto you hath been largely extended, your hearts have been tendered before him:
dear lambs and babes of my Father`'s fold,
in the bowels of inexpressible dearness is the salutation of my love and life unto you;
and in the pure stream of love and life, and precious power of the Lord, I say unto you,
walk on in the heavenly path of life, and way of peace; the mark is before,
the glorious prize, that all shall obtain that run well.
Therefore in the name and power of the everlasting God,
cast off every weight and burden that hath hindered or would hinder you,
and now walk on towards Zions city, the palace of the Great King,
where he reigns before his ancients gloriously:
shut out all weakening and discouraging thoughts and reasonings,
and come away in this the day of the arisings of the glorious,
powerful God of heaven and earth,
who in this his day is freshly visiting his inheritance, causing his latter, plenteous,
sweet rain of love, life and heavenly virtue, to descend abundantly thereon.
And therefore, all everywhere, who are convinced of the heavenly, truth, in the dread,
fear, and pure awe of the Almighty,
wait to be capacitated to enjoy what the Lord is now plentifully dispensing,
of the increase of his goodness and blessings.
And the way to be so capacitated for this precious, spiritual enjoyment, is,
diligently to wait upon the Lord, in the inward, sweet,
retiredness of the mind and spirit; in the feeling of,
and subjecting to that heavenly leaven that leavens the whole three measures;
so shall every one come to receive the holy divine dispensings of love,
life and nourishing virtue, whereby the inward man grows up in strength and stature,
and so comes to have an heavenly place of joy in the mansion-house of the Lord.

So to the heavenly, sweet Comforter, to his teachings,
leadings and feedings I commit you all everywhere;
and rest in the satisfactory knowledge of the prosperity of the Lord`'s work,
your brother in the labour tribulation and hope of the gospel of peace,

[.signed-section-signature]
Charles Marshall.

[.postscript]
====

[.salutation]
_Postscript._--And Dear Friends and Brethren,

The lord hath suffered several trials to arise, since we have been a people,
through which there hath been, and is, a sifting and winnowing:
but as you grow in the knowledge of Him that is true, and abide in Him that is true,
you shall receive a certain understanding to know him that is false;
and so be preserved in the word of his patience,
from entering into the hour of temptation, that all those fall into that,
go from the heavenly into the earthly; in which grows the heady, stubborn,
and murmuring birth of sensuality, which is born after the fleshly wisdom,
and therein makes war with the birth that is after the Spirit;
which the Lord Almighty will debase and consume by the brightness of his appearing,
arising and coming, and by the breath of his mouth.
And many hearts shall be broken with the joy of the Lord,
and overcome in the power of his love, who is arising, ah! mournful Zion,
to comfort thee through accomplishing thy spiritual warfare,
and laying low the enemies of thy prosperity; causing more and more thy light to come,
and break forth as brightness, and the glory of the Lord to arise on thee.
Amen, Amen, saith my soul and spirit.

====

[.signed-section-signature]
C+++.+++ M.

[.blurb]
=== An Epistle to Friends, +++[+++recommending them to wait for, and live under the power of the Lord.)

[.salutation]
Dear Friends, Brethren and Sisters,

Who have been visited with the morning of the eternal day,
and by the arm of the mighty God,
gathered from the barren mountains of lifeless professions;
and called to come to the mountain of the Lord`'s house; grace, mercy, and peace,
life and divine virtue, God Almighty multiply and increase in and among you all; Amen,
Amen.

Dear Friends,
a necessity is upon my travailing soul this to say in the name of the Most High:
your growth, increase, and preservation is alone in that which first reached unto you,
and gathered you, namely, the mighty power of the living God; and therefore,
dear Friends, wait diligently in that lowliness of mind,
and contrition of heart and soul, wherein you may have an increased knowledge thereof,
and of its bright, powerful arisings and appearing amongst you;
without which you cannot be safe,
nor bring forth anything that is truly acceptable in his sight; for without this,
all testimonies and performances are lifeless and senseless,
and such as the Lord hath no delight in.
Therefore, in the sense of the heartbreaking love of my God,
this counsel ariseth unto all Friends, in all your assemblies, and families:
wait diligently to feel this living power of the Lord to
spring in strength and might in all your souls;
and when felt, bow with all your hearts unto it,
so shall you know that the mind thereof is purely to purge away all the dross, the lead,
the tin, and the reprobate silver,
and to make a clean habitation for him to appear and dwell in.
And as the pure power of the Lord is +++[+++submitted to]
in its arisings, it will search thoroughly, and find out all that nature, that is not,
nor can be at unity with it, nor with his works;
the burning up of which nature will be known, and so the power of the Lord will appear,
and make chosen vessels to bear his name, and to honour him in your respective places.

And dear Friends, in this is the living cross of Christ Jesus known,
which crucifies to the world, (mark), and the world to you,
in which all will be preserved in the pure awe, dread and fear of the Almighty God:
and all that are here truly preserved grow to God, and come up in his service;
serving him in their generation, according to his will;
knowing their places in that body which edifieth itself in love.
Here all are led up in the pure, sweet unity, none moving out of their proper places;
he that speaketh in this, speaketh as the oracle of God; and they that hear in this,
hear so also: and a few words heard in the motion of the glorious power,
are of more service than thousands spoken out of it;
for these burden and grieve the Spirit of the Lord,
and them that are in the tender sense thereof.

And here tender Friends, brethren and sisters, wisdom from above +++[+++will]
descend into your souls; and as in it, and with it, and under the conduct thereof,
in the dread of the Lord God Omnipresent,
you manage the affairs of Truth in all your meetings,
heavenly blessings and prosperity will attend you, strengthening and encouraging you,
and the whole flock and family of God.

My dear Friends, this further lies upon me to say to parents, masters,
and mistresses of families, in the fear and counsel of the Lord:
watch over your children and servants diligently,
and let your souls be lifted up with strong cries and supplications to the mighty God,
that your families may be brought under the government and seasoning of this sweet,
precious power of the Lord, +++[+++and]
that in this you might rule well.
And to young men and young women, and children, I say,
let the dread of this power be over you, keeping you in that blessed,
sole state of fearing God Almighty, and trembling at his word.
And here it will be the delight of children, to love honour, and obey their parents;
and of servants, to perform their services truly and faithfully, as in the sight of God,
in their respective places.
Finally, dear Friends, nothing but the bright shinings and pure operation of this power,
and living obedience thereunto, can keep and preserve you a savoury people.
And therefore, once more I say, in the name of the God of truth, wait for the increasing,
feeling knowledge of it, and cleave fully to it;
so shall you be defended and fenced about.
And as the mountains were round about Jerusalem, so shall a wall be round about you,
even the compassing, ancient, honourable and renowned arm of God Almighty;
which alone can fence out the wild boar of the forest, and the roaring lion,
that now goes about seeking for an entrance to destroy
and lay waste the heritage of the Lord.

God Almighty be with you in your meetings and assemblies;
and O! that his heavenly blessings, rain, and pure refreshings, as sweet dews,
may plentifully descend among you to your great joy and inexpressible consolation;
that high praises may be in your souls to the Lord God that ruleth and reigneth,
and to the immaculate Lamb that sits with him upon his throne of celestial glory;
to whom my soul +++[+++ascribes]
might, majesty and dominion, for his daily arisings,
and the bright goings forth of his mighty power;
for he is worthy to receive all honour and glory, with heavenly renown,
forever and ever.
Amen, Amen.

Your tender, travailing brother, in the fellowship of the gospel of life and salvation.

[.signed-section-signature]
Charles Marshall.

[.postscript]
====

[.salutation]
_Postscript._--Dear Friends,

The Lord`'s living call and counsel unto you all everywhere, is,
that you diligently feel after, and wait for the living operations of that power of love,
which brings to true contrition of spirit; that under the mighty hand of the Lord,
+++[+++and his]
dissolving life and power,
all the families of Friends may be humbled before
the day of the Lord`'s humbling the people in judgment;
that in that day you may be favoured of the Lord,
as those were that sighed for the great iniquity of Jerusalem:
so you being made sensible of the grievous oppressions
of the iniquity of the land of our nativity,
may with strong cries and groans, night and day,
cry mightily unto the Lord God of Sabaoth, for the finishing of the sins thereof,
and bringing to an end its transgression; that so it may enjoy deliverance,
and thereby a Sabbath.

====

[.signed-section-signature]
C+++.+++ M.

[.blurb]
=== An Epistle to Friends, +++[+++exhorting them to walk in the light, warning the disobedient, and recommending inwardness of spirit, humility and diligence.]

[.salutation]
Dear Friends,

The High and Holy One, that inhabiteth eternity,
condescends in his love to dwell with those that
are of a broken heart and contrite spirit,
and tremble at his word; these are the qualifications of the people he will uphold,
refresh, and be with, in the dreadful, astonishing day of his fierce anger, and terrible,
consuming indignation.

Therefore, home, home, to live and walk in that ye have made profession of,
in the sight of the nations, namely, the holy light of the Lamb,
in which ye will see all your states and conditions,
how you stand before the Lord this day;
for the Lord God Almighty will extend his wonderful lovingkindness unto all the obedient,
that walk uprightly before him, in his pure fear, awe and dread;
sanctifying his great and glorious name before the people, in a Christian conversation,
as becomes the gospel of Christ Jesus: and +++[+++as you]
inwardly in spirit walk with God,
he will appear more and more for your safety in a dreadful, stormy day,
and give you the desire of your souls, in perfecting his work begun in you,
to the honour of his own name, and consolation of your own souls;
your habitation shall be sure and pleasant in the munition of rocks,
where bread shall be given you, and your waters shall not fail;
the everlasting arm of Jacobs God will surround you,
where ye may behold the magnifyings thereof before the nations.

But to all the disobedient, unfaithful, earthly-minded,
that grieve and vex the Spirit of the Lord, dishonour his name,
and harden the hearts of the people, causing them to speak evil of the way of Truth;
I have sad tidings to send unto all such, in the sound of the trumpet of the Lord;
and to tell them I have seen a dreadful day hastening apace over them,
wherein that which they have been delighted in,
in their departing out of the pure fear and awe of the Almighty, will be removed;
and a fire not to be quenched will be kindled in their bosoms,
consuming dreadfully and astonishingly.
Therefore awake, awake; arise, trim your lamps; see to your oil,
before the lamp goes out never to be lighted any more,
and the day of shutting out forever, overtakes.

So dear Friends everywhere, be inward, inward;
in great bowings down of spirit and humility of soul,
wait to feel the invisible power of the mighty God to sanctify,
that ye may be able to stand in the day of his fanning the nations,
and treading the winepress of his indignation amongst the people: and as ye stand here,
divine rain and heavenly dew will descend upon you,
causing you to grow as a well-watered garden, even like Eden, before the Lord;
in which he may take great delight.

_So dear Friends everywhere, double your diligence; redeem your time;
feel and love the girdle of Truth to gird up the loins of your minds;
and where any have been unwatchful, careless, or earthly-minded,
let the time past be sufficient, I entreat you; and now in pure fear,
living obedience and spiritual watchfulness, wait to feel the mighty power of the Lord,
in that to increase in the increasing of God;
in the power of whose love this comes unto you, through a servant of the Lord,
and travailer for Zions welfare._

[.signed-section-signature]
Charles Marshall.
