== Testimonies of Charles Marshall

[.blurb]
=== George Whitehead`'s Testimony Concerning Charles Marshall, Deceased.

What the Lord our God promised by holy prophets,
of the pouring out of his Spirit upon all flesh,
and that his sons and daughters should prophesy, and declare his name in the earth;
and that when he gives his word,
many become the publishers thereof;--this truth the Lord hath renewed, and is fulfilling,
even in our day; so that a great cloud of witnesses,
he hath been pleased to raise up even in these latter days;
and they have truly concurred in their blessed testimony, for the convincing,
converting and confirming many in the faith of the
everlasting gospel of our Lord Jesus Christ;
wherein this our well beloved brother, Charles Marshall,
had a share and effectual service in his day and time, through great labour,
travels and exercises.
To whose memory,
with that of many other faithful servants of Christ Jesus who are at rest in Him,
we owe such tender respect, as truly to commemorate them, their service,
and testimony for the name and power of the Lord our God, and his dear Son Jesus Christ,
and to recommend the same to posterity;
for that "`the righteous shall be in everlasting remembrance.`"
I knew this our deceased brother, in his young years; wherein,
as the Lord was pleased religiously to incline his heart and mind to virtue,
and to the knowledge and love of the blessed Truth, as it is in Christ Jesus, in spirit,
life, and power, he received and retained the love of the same when discovered unto him;
and accordingly his love was sincere to Christ`'s ministers and servants,
who were instrumental for his and many others`' information,
and the good of their immortal souls.
And his sincere love and regard to Christ`'s ministers and messengers,
appeared to be a good and necessary preparation,
for him to be a witness and partaker of the same ministry and testimony of Christ Jesus,
and to have a share in the work of the same blessed,
spiritual ministry of the gospel of the grace of God,
which wrought in his heart for the same end;
and which accordingly the Lord was pleased to make him instrumental in,
as a minister of the spirit, and not of the letter,
to turn people from the flesh to the spirit, and from darkness, sin and Satan,
to Christ the true light; and from the barren and empty forms of religion,
to the power of godliness.
And as he was a loving and tender-hearted man,
he was truly tender and zealous for the glory of God,
and the honour of his holy name and Truth;
and retained unfeigned love to his brethren in Christ,
and regard to the lively and comfortable fellowship of the Holy Spirit,
wherein we were often comforted together.
He was not one of them that would turn aside from the flocks of the Lord`'s companions,
whom Christ esteems as his own brethren.
He often zealously testified against the spirit of division and separation,
and against treacherous apostates and sowers of discord;
and often endeavoured to alarm and awaken the careless people, out of the sleep of sin,
carnal security, fleshly liberty and ease therein; for which end he laboured hard,
and took great pains,
as one given up to spend and be spent in the Lord`'s work and service.
I truly loved him for love`'s sake,
(for none was lost between us,) and as one who kept the faith,
and retained the unfeigned love of the brethren,
and true love to all the faithful in Christ, even to his whole heritage.
And the Lord did not only make him truly compassionate and helpful by
his spiritual ministry to poor souls under affliction and distress;
but also because of his tender-heartedness to such as were afflicted in body,
or any ways indisposed as to their health, and his readiness to sympathize with them,
and to help them in his physical practice, I believe,
the Lord did the more bless the same for the help,
ease and relief of many who had laboured under bodily weakness and distempers,
as they have confessed.

And as an ancient Friend, in great tenderness, true love and affection,
declared at his funeral his being then in paradise,
I really believe he is written in heaven, and recorded in the Lamb`'s book of life,
with all the faithful in Christ, the redeemed from the earth,
who keep their integrity in the truth to God, and their faith in Christ,
and love to all his saints; even those who are faithful unto death,
for whom the crown of righteousness,
the crown of life and glory is prepared and reserved in heaven.

And though I have not had the opportunity to peruse all the writings, books,
and papers relating to our holy profession of this good man, our deceased brother,
I hope nothing will be found in them offensive, to the unprejudiced readers,
or inquirers after the way to life eternal;
considering the validity and weight of his known evangelical ministry,
and spiritual testimony.

[.signed-section-signature]
George Whitehead

[.signed-section-context-close]
London, the 15th of the Ninth Month, 1703.

[.postscript]
====

Postscript.--+++[+++With]
the foregoing testimony concerning our dear brother Charles Marshall deceased,
his great labours and service in the gospel of Christ, and his zeal for God,
and the spreading of the truth; his unfeigned love to his brethren,
and his great regard for the preservation of God`'s people in the
unity of the spirit and bond of peace--we have true unity.

And having known him many years, and been witnesses of his labours,
and having laboured with him in the same work; in christian respect to his memory,
and in real esteem and value for his faithful testimony, +++[+++we]
do testify, he was an evangelical minister, and faithful servant of Christ,
and hath left many seals of his ministry; for the Lord greatly blessed his labours,
and filled him with his divine power, and attended him with his glorious presence,
even unto the end; for he enabled him through all his exercises,
to finish his course in peace: and we are fully satisfied,
the Lord hath given him the crown of righteousness.

And we doubt not but all who shall read impartially his following writings,
will find that he was what we testify concerning him, viz. a sincere man,
of a tender spirit, full of love and zeal for God and his truth; +++[+++one who]
laboured in his day and time for the good of souls,
in the gospel of our Lord Jesus Christ; to whom be glory and dominion forever.

====

[.signed-section-context-close]
Signed at our Second day`'s Morning Meeting, the 22nd of the Ninth Month, 1703.

[.signed-section-signature]
Ambrose Rigge.
John Bowater.
John Field.
John Kent.
John Waughton.
Theodore Ecclestone.
John Butcher.
William Robinson.
Thomas Pitstow.
John Tomkins.
Edward Bourne.
George Bowles.
John Padley.
Samuel Waldenfield.
William Hornoull.
William Warren.
Joseph Baines.

[.blurb]
=== John Freame`'s Testimony Concerning Charles Marshall.

Although the several testimonies, relating to our deceased friend Charles Marshall,
may sufficiently testify concerning him,
yet I having had the benefit of his conversation for many years,
think myself engaged to say something of him, in +++[+++that]
true love and respect which I bear to his memory;
he having entertained a particular kindness to me from a child,
and continued his friendship stedfastly to the end;
affording me much of his company for the last ten years of his time,
whereby I came to have a particular knowledge of him.

And I can truly say, that he was a faithful and true Friend; having often observed,
where he professed friendship +++[+++to any, it was so in reality, and not in show only;
being ready to serve such to the utmost of his power,
not forsaking them in a time of adversity.

He was a faithful labourer, and true minister of the gospel,
and had an eminent service in that respect,
having been made a happy instrument for the convincement of many.

He was a zealous reprover of such as made profession of the Truth,
and walked contrary thereto in life and conversation;
but very tender to those under exercise of spirit.
His ministry was such as effectually reached the divers states and conditions of people,
+++[+++he]
being skilful in dividing the word aright; so that he was both a planter,
as well as a waterer in God`'s vineyard:
and there are many can say they have sat under his doctrine with great delight;
having been thereby comforted and greatly refreshed.
He was also eminent for an innocent life and exemplary conversation;
which being attended with good nature and a kind disposition,
rendered his acquaintance and conversation both edifying and acceptable.

He was of a peaceable spirit, making it his concern to keep up love, unity and concord;
and, as occasion offered, frequently exhorting thereto: his demeanour was such,
both in this and other respects, as made him an elder in the church,
that deserved double honour; and it may be truly said of him, that he was a peace-maker,
he being often +++[+++engaged in]
performing that office of true friendship,
by endeavouring to reconcile those that were at difference;
and as he was no favourer of that spirit that endeavoured to sow discord amongst brethren,
so he was no encourager of such as would be secretly lessening the esteem one of another;
always looking upon such things to be of pernicious consequence.

He was a real sympathizer with those in exercise or affliction,
often visiting them in the time of their greatest need.

And thus he continued until the time of his +++[+++last]
sickness, which he had a sense of before it came upon him;
for a little before he was taken ill, he signified to me, that his departure was at hand;
and desired, amongst other things, that his Journal, Epistles, and other writings,
might be collected, in order to be printed after his decease;
and earnestly pressed me to take some care therein.

I was frequently with him in his sickness, and observed him attended with great patience,
and in a sweet composed frame of spirit, resigned up to the will of God:
and although towards his latter end he grew very weak,
yet he had still a care for the welfare of the church, and good of the poor,
as appears by the following expressions,
spoken to some ministering Friends that came to visit him; and I being present,
and perceiving an earnest desire in him that the same should be communicated to Friends,
committed them to writing presently after; which were to this effect, viz.:

[quote]
____
I have loved the brotherhood;
I have sought the unity and peace of the church for these forty years;
and to my great comfort, never did anything tending to the breach thereof.

I have two things that lie upon me to Friends,
which I desire may be communicated to them: the first is,
that they gather down into the immortal Seed and Word of Life in themselves,
and be exercised in it before the Lord; and duly prize,
and set a right value upon the many outward and inward mercies, blessings,
and heavenly visitations, that the Lord has eminently bestowed upon them,
since the morning of the day of his blessed visitation; then shall they grow,
and be preserved in a living freshness to him;
and the Lord will continue his mercies to them, and they shall not want his divine,
refreshing presence in their meetings together before him.

The second thing is, that those Friends that the Lord hath given great estates unto,
ought to cast their bread upon the waters, and do good therewith in their life-time;
for those that are enjoyers of such things should see that they are good stewards thereof.
O! the many poor families that such persons might be a help to;
how easily might they with a little, assist many a family to live in the world;
and what a comfort would it be for such to see the
fruits of their charity in their life-time.
____

After which he grew daily weaker and weaker,
and departed in great stillness and quietness of mind,
being taken away from divers troubles and exercises to possess
and enjoy an incorruptible inheritance that will never fade away.

[.signed-section-signature]
John Freame.

[.signed-section-context-close]
London, the 25th of the Eighth Month, 1703

[.blurb]
=== A Testimony concerning Charles Marshall.

We understand that the memory of our ancient and faithful friend and brother,
Charles Marshall, is likely to be revived by the publishing a collection of his writings.
As to his conversation and character, this testimony lives in our hearts for him, viz.,
that he was known to be a lover of the Holy Scriptures,
and early sought after the knowledge of God,
by whom he was prepared to receive the testimony of Truth,
which he soon received in the love of it,
and became an able minister for the turning many from darkness to light.

And as he was a true believer in Christ, so he was a sufferer for his name and testimony;
and he underwent +++[+++sufferings]
with patience and cheerfulness.

His endeavours were, where he came,
not only to keep the unity of the spirit in the bond of peace,
but also to press to the same; well knowing,
that as the character of a disciple of Jesus was love, so by it unity and peace here,
and happiness hereafter, would be secured to us.

He was indefatigable in his labours for promoting universal charity,
but especially on behalf of the poor, for whom he was a constant advocate;
charging the rich not to put trust in their riches,
nor shut their ears against the complaints of the necessitous.

In short, he was a loving husband, a tender father, a good neighbour, a true friend,
and a zealous and faithful minister.

He was for following after those things that make for peace,
as well in his natural temper, as by a divine qualification:
he had a very great sweetness in his conversation,
which had a general tendency to the promoting of love and good works;
in which we believe he continued stedfast to the very last:
and having left this troublesome world, is translated to a better place,
where he is at rest with the Lord.

[.signed-section-signature]
Thomas Callowhill, Richard Snead, William Smith, Charles Harford, Benjamin Coole,
Charles Jones.

[.signed-section-context-close]
Bristol, 22nd of the Tenth Month, 1703.

[.blurb]
=== Hannah Marshall`'s Testimony Concerning Her Husband Charles Marshall.

[.salutation]
Dear Friends,

It is a Christian obligation, as well as a commendable practice,
for survivors to transmit to posterity something concerning the deceased,
especially of such as have been exemplary in their lives,
and whose death proves the church`'s loss, though their own eternal gain.
Such are of that righteous generation, whose memorial is never to be forgotten.

Amongst these,
my dear deceased husband was one who yielded early
obedience to the visitation and call of God,
persevered in his fear, and finished in his love.
The testimony he bore for the Lord and his blessed Truth,
was in the authority of divine life;
and it often reached the witness of God in many hearts.
He was zealous for God, tender of the good in all;
terrible against the works and workers of iniquity.
In the exercise of his gift, he was grave and reverent;
his testimony was full of reproof and conviction,
but in that meekness which made the same truly edifying: his doctrine was sound,
and sufficient to stop the mouths of gainsayers,
flowing from that living fountain and divine spring of light, life and heavenly wisdom,
which the wisdom of this world could never comprehend.

He was often drawn forth in prophecy,
which was attended with a suitable concern in himself,
and which also affected those that heard him;
nor did the concern terminate when he had declared what was upon his mind,
but in long and deep travail of soul would he plead with the Lord to hasten the good,
and avert the evil;
often with great brokenness of spirit beseeching God to
bring over this land of his nativity a Nineveh-repentance,
that thereby his judgments might be averted.
In such travails as these did he spend the days of his strength, and prime of his years,
whereby his outward man has often been weakened and made feeble;
such was his zeal for God, and his love to mankind;
and the Lord was pleased many times to answer the desire of his travailing soul,
which he always thought a good recompense for all the labours
and sufferings he went through on that account.

O! dear Friends, let none quench the Spirit in themselves nor others;
nor despise prophesying,
where the Lord by his Spirit raises up servant or hand-maid in it; such that do,
are slighters of their own mercies.

My dear husband was a great sympathizer with the afflicted in soul,
and with the mourners in spirit: he was a great lover of the brethren,
and peace of the church, whose tranquillity he sought;
and knew right well the body could be edified in nothing but love;
often pressing the professors of Truth to keep to the precious unity of the Spirit,
as the only bond of their peace.
Nor did this tenderness with which he was wont to treat the weak,
lead him into foolish pity to the wilful; for no man was more zealously concerned,
when any went about to rend or divide; nor few men more willing to sling a stone at them;
which he often did with great success,
it being done in the authority given him of God over such spirits;
always continuing in that Christian frame of spirit,
that could forgive upon their repentance and return, which he often prayed for.

Nor did the heat of persecution hinder him from making
a general visit to the churches through the nation,
which he began in the year 1670, and which was richly blest: the Lord so ordered it,
that scarcely any Friend suffered loss of goods upon that account;
and the meetings were generally quiet where he came,
as may be more particularly seen in his following Journal.
As his work was great, so was his faith; and the power of God in which it stood,
was greater than the power of the enemies of Truth.
He was freely given up to the expense of substance, time, and strength,
in that journey and service; as indeed he was at many other times,
when concerned to visit the churches of Christ, and heritage of God,
especially for twenty years; in which time, though I enjoyed but little of his company,
the Lord bears me record, I never dared to murmur,
but was kept in resignation to the will of God, in which I found peace.

Thus was the Lord pleased in the riches of his love,
to make known his ancient way of Truth unto him; and he with many brethren,
were made able ministers of the gospel of salvation, and willing to run to and fro,
that knowledge should be increased amongst the people,
after a long night of error and apostacy,
where in the ancient path of Truth and Life had been departed from,
the world had become as a wilderness, and the glory of the church obscured and eclipsed:
many ran from one barren mountain of profession to another,
seeking the living amongst the dead, and their bread in desolate places: I say,
then did the Lord appear,
and concern a remnant whom he had chosen and made vessels fit for his own use,
to testify in his name, that the teachers of the people had caused them to err;
and that the true primitive and apostolical religion and ministry they were strangers to;
feeding themselves, not the flock, and seeking their gain from their quarter,
instead of seeking the lost sheep.
Nor could these for conscience`' sake comply to pay for the support of such a ministry.
For this testimony my husband suffered with cheerfulness,
and valiantly bore the imprisonment of his body, the loss and spoil of goods,
standing over the power of the oppressor, in the authority of Christ,
whereby others were affected and strengthened to be faithful,
in keeping up their testimony against tithes.
I pray God his example in that, and all other branches of his testimony,
wherein he was kept faithful unto death, may be a motive to all to follow the Lord fully;
then will God have his honour, and our souls the everlasting comfort.

And as he was thus given up for the spiritual welfare of all,
so was he made instrumental of much temporal good to many.
He was a lover of the poor, and a friend to the rich; often putting the latter,
at their well-furnished tables, in mind of the former;
recommending self-denial and hospitality, instead of high living.
Nor was he wanting in example, any more than in advice;
often visiting and inspecting poor families;
always sympathizing with them in tender compassion, and true Christian charity,
which were inseparable companions in him; supplying the sick with advice and physic;
the hungry with bread, and the naked with clothes, according to his ability;
so that with Luke, who was both evangelist and physician,
he was made serviceable in his generation, in both respects,
to the relief and comfort of the souls and bodies of many.

He was a man of a self-denying life:
he would not be moved by abuses or injuries when offered,
imputing them to ill nature or ignorance,
which he did not think worthy of possessing the mind.
He approved himself a long-suffering, patient, meek and humble man,
as became a minister of Christ; always trusting in the goodness of God,
to whom he delighted to pour out his supplications, in full assurance of faith,
that he would have regard to the oppressed,
to the afflicted and bowed in soul and spirit;
and that he would bring them into the divine bosom,
where their souls should be filled with heavenly joy, +++[+++and enabled]
to praise, magnify and bless his holy name.

What shall I say?
He was a loving husband to me, and a tender father to his children,
for whose welfare he travailed in spirit night and day,
in a great sense of the design of the enemy upon them and the offspring of Friends,
to obstruct the prosperity of Truth; often being drawn forth, with the apostle Paul,
in great concern for his kinsfolks after the flesh,
that they might be made partakers of the goodness and mercy of God.
He was a kind master to his servants, an affectionate friend,
well respected and of good report in his neighbourhood.

It pleased the Lord,
after his return from visiting Friends of Bristol and the western parts,
to afflict him with a long sickness;
and notwithstanding his physicians had hopes of his recovery,
yet he often declared his distemper would prove mortal; which indeed ended in his death.

Thus was his life finished,
(after about four months`' sickness,) in sweetness and the enjoyment of divine life.
In this long sickness, although attended with extreme pain,
he had his senses continued to the last; in which time I accompanied him night and day,
hardly allowing time for necessary refreshment,
and heard the weighty expressions that fell from
him upon the visits of Friends and otherwise;
some of which I shall here add, they being some of his last words,
viz. that he had not handled the word of the Lord deceitfully,
nor done his work negligently; earnestly desiring, that Friends might live in love,
and keep in the unity of the Spirit, as the only bond of their peace; and signified,
that though some might put the trying day he had seen and declared of, afar off;
yet it would come, and on such as a thief in the night.

As his last moments drew near, he closed his eyes with his own hand,
and with cheerfulness and composure of mind,
as one that had the sting of death taken away, resigned his soul to God,
the 15th of the Ninth Month, 1698, in the sixty-second year of his age.
Well! he is gone to his rest, which he often desired he might, before me; and I may say,
he was taken from the evil that was to come.
However it will be but a little +++[+++time,+++]+++ if we continue faithful in our measures,
ere we shall arrive at the same haven of rest, and port of joy, where all sorrow,
sighing, and tears will be done away;
which is the travail and desire of my soul for all the visited of God,
Who am your ancient and deeply afflicted Friend,

[.signed-section-signature]
Hannah Marshall.

[.signed-section-context-close]
London, the 1st of the Ninth Month, 1703.
